#!/bin/sh

built_sources=""

headers=`find .. -name "*.h" -a -not -name libmesh_config.h -type f | LC_COLLATE=POSIX sort`

for header_with_path in $headers ; do

    #echo $header_with_path
    header=`basename $header_with_path`
    #echo $header
    built_sources="$built_sources $header"
done

specializations=`find .. -name "*specializations" -type f | sort`

for specialization_with_path in $specializations ; do

    #echo $specialization_with_path
    specialization=`basename $specialization_with_path`
    #echo $specialization
    built_sources="$built_sources $specialization"
done

cat <<EOF > Makefile.am
# Note - this file is automatically generated by $0
# do not edit manually

#
# include the magic script!
EXTRA_DIST = rebuild_makefile.sh

EOF

printf '%s' "BUILT_SOURCES =" >> Makefile.am
for built_src in $built_sources ; do
    echo " \\" >> Makefile.am
    printf '%s' "        "$built_src >> Makefile.am
done

echo >> Makefile.am
echo >> Makefile.am
echo "DISTCLEANFILES = \$(BUILT_SOURCES)" >> Makefile.am


# handle libmesh_config.h
# cat <<EOF >> Makefile.am
# #
# # libmesh_config.h rule
# libmesh_config.h: \$(top_builddir)/include/libmesh_config.h
# 	\$(AM_V_GEN)rm -f \$@ && \$(LN_S) -f \$< \$@
#
#   BUILT_SOURCES  += libmesh_config.h
#   DISTCLEANFILES += libmesh_config.h
#
# EOF



# now automatically handle our headers
cat <<EOF >> Makefile.am
#
# libMesh header rules
EOF
for header_with_path in $headers $specializations ; do
    header=`basename $header_with_path`
    source=`echo $header_with_path | sed 's/../$(top_srcdir)\/src\/contrib\/libmesh\/include/'`
    #echo "source = $source"
    cat <<EOF >> Makefile.am
$header: $source
	\$(AM_V_GEN)rm -f \$@ && \$(LN_S) -f \$< \$@

EOF
done
#cat Makefile.am
