.TH "quadrature Directory Reference" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
quadrature Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBquadrature\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_build\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_clough\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_clough_1D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_clough_2D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_clough_3D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_conical\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_conical_2D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_conical_3D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_gauss\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_gauss_1D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_gauss_2D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_gauss_3D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_gm\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_gm_3D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_grid\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_grid_1D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_grid_2D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_grid_3D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_jacobi\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_jacobi_1D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_monomial\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_monomial_2D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_monomial_3D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_rules\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_simpson\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_simpson_1D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_simpson_2D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_simpson_3D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_trap\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_trap_1D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_trap_2D\&.C\fP"
.br
.ti -1c
.RI "file \fBquadrature_trap_3D\&.C\fP"
.br
.in -1c
