.TH "partitioning Directory Reference" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
partitioning Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcentroid_partitioner\&.C\fP"
.br
.ti -1c
.RI "file \fBlinear_partitioner\&.C\fP"
.br
.ti -1c
.RI "file \fBmetis_partitioner\&.C\fP"
.br
.ti -1c
.RI "file \fBparmetis_partitioner\&.C\fP"
.br
.ti -1c
.RI "file \fBpartitioner\&.C\fP"
.br
.ti -1c
.RI "file \fBpartitioner_factory\&.C\fP"
.br
.ti -1c
.RI "file \fBsfc_partitioner\&.C\fP"
.br
.in -1c
