.TH "Structures used by external API functions." 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Structures used by external API functions. \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBex_init_params\fP"
.br
.ti -1c
.RI "struct \fBex_block\fP"
.br
.ti -1c
.RI "struct \fBex_set\fP"
.br
.ti -1c
.RI "struct \fBex_block_params\fP"
.br
.ti -1c
.RI "struct \fBex_set_specs\fP"
.br
.ti -1c
.RI "struct \fBex_var_params\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBex_init_params\fP \fBex_init_params\fP"
.br
.ti -1c
.RI "typedef struct \fBex_block\fP \fBex_block\fP"
.br
.ti -1c
.RI "typedef struct \fBex_set\fP \fBex_set\fP"
.br
.ti -1c
.RI "typedef struct \fBex_block_params\fP \fBex_block_params\fP"
.br
.ti -1c
.RI "typedef struct \fBex_set_specs\fP \fBex_set_specs\fP"
.br
.ti -1c
.RI "typedef struct \fBex_var_params\fP \fBex_var_params\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBex_block\fP  \fBex_block\fP"

.SS "typedef struct \fBex_block_params\fP  \fBex_block_params\fP"

.SS "typedef struct \fBex_init_params\fP  \fBex_init_params\fP"

.SS "typedef struct \fBex_set\fP  \fBex_set\fP"

.SS "typedef struct \fBex_set_specs\fP  \fBex_set_specs\fP"

.SS "typedef struct \fBex_var_params\fP  \fBex_var_params\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
