.TH "elem_quality.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elem_quality.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.ti -1c
.RI "\fBlibMesh::Quality\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBlibMesh::Quality::name\fP (const ElemQuality q)"
.br
.ti -1c
.RI "std::string \fBlibMesh::Quality::describe\fP (const ElemQuality q)"
.br
.ti -1c
.RI "std::vector< ElemQuality > \fBlibMesh::Quality::valid\fP (const ElemType t)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBlibMesh::Quality::num_quals\fP = 16"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
