.TH "enum_solver_type.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enum_solver_type.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlibMesh::SolverType\fP { \fBlibMesh::CG\fP =0, \fBlibMesh::CGN\fP, \fBlibMesh::CGS\fP, \fBlibMesh::CR\fP, \fBlibMesh::QMR\fP, \fBlibMesh::TCQMR\fP, \fBlibMesh::TFQMR\fP, \fBlibMesh::BICG\fP, \fBlibMesh::BICGSTAB\fP, \fBlibMesh::MINRES\fP, \fBlibMesh::GMRES\fP, \fBlibMesh::LSQR\fP, \fBlibMesh::JACOBI\fP, \fBlibMesh::SOR_FORWARD\fP, \fBlibMesh::SOR_BACKWARD\fP, \fBlibMesh::SSOR\fP, \fBlibMesh::RICHARDSON\fP, \fBlibMesh::CHEBYSHEV\fP, \fBlibMesh::INVALID_SOLVER\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
