.TH "enum_eigen_solver_type.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enum_eigen_solver_type.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlibMesh::EigenSolverType\fP { \fBlibMesh::POWER\fP =0, \fBlibMesh::LAPACK\fP, \fBlibMesh::SUBSPACE\fP, \fBlibMesh::ARNOLDI\fP, \fBlibMesh::LANCZOS\fP, \fBlibMesh::KRYLOVSCHUR\fP, \fBlibMesh::INVALID_EIGENSOLVER\fP }"
.br
.ti -1c
.RI "enum \fBlibMesh::EigenProblemType\fP { \fBlibMesh::NHEP\fP =0, \fBlibMesh::HEP\fP, \fBlibMesh::GNHEP\fP, \fBlibMesh::GHEP\fP, \fBlibMesh::INVALID_EIGENPROBLEMTYPE\fP }"
.br
.ti -1c
.RI "enum \fBlibMesh::PositionOfSpectrum\fP { \fBlibMesh::LARGEST_MAGNITUDE\fP =0, \fBlibMesh::SMALLEST_MAGNITUDE\fP, \fBlibMesh::LARGEST_REAL\fP, \fBlibMesh::SMALLEST_REAL\fP, \fBlibMesh::LARGEST_IMAGINARY\fP, \fBlibMesh::SMALLEST_IMAGINARY\fP, \fBlibMesh::INVALID_Postion_of_Spectrum\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
