.TH "ex_block_params" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ex_block_params \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exodusII\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid_int\fP * \fBedge_blk_id\fP"
.br
.ti -1c
.RI "char ** \fBedge_type\fP"
.br
.ti -1c
.RI "int * \fBnum_edge_this_blk\fP"
.br
.ti -1c
.RI "int * \fBnum_nodes_per_edge\fP"
.br
.ti -1c
.RI "int * \fBnum_attr_edge\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBface_blk_id\fP"
.br
.ti -1c
.RI "char ** \fBface_type\fP"
.br
.ti -1c
.RI "int * \fBnum_face_this_blk\fP"
.br
.ti -1c
.RI "int * \fBnum_nodes_per_face\fP"
.br
.ti -1c
.RI "int * \fBnum_attr_face\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBelem_blk_id\fP"
.br
.ti -1c
.RI "char ** \fBelem_type\fP"
.br
.ti -1c
.RI "int * \fBnum_elem_this_blk\fP"
.br
.ti -1c
.RI "int * \fBnum_nodes_per_elem\fP"
.br
.ti -1c
.RI "int * \fBnum_edges_per_elem\fP"
.br
.ti -1c
.RI "int * \fBnum_faces_per_elem\fP"
.br
.ti -1c
.RI "int * \fBnum_attr_elem\fP"
.br
.ti -1c
.RI "int \fBdefine_maps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 302 of file exodusII\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int ex_block_params::define_maps"

.PP
Definition at line 320 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_block_params::edge_blk_id"

.PP
Definition at line 303 of file exodusII\&.h\&.
.SS "char** ex_block_params::edge_type"

.PP
Definition at line 304 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_block_params::elem_blk_id"

.PP
Definition at line 313 of file exodusII\&.h\&.
.SS "char** ex_block_params::elem_type"

.PP
Definition at line 314 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_block_params::face_blk_id"

.PP
Definition at line 308 of file exodusII\&.h\&.
.SS "char** ex_block_params::face_type"

.PP
Definition at line 309 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_attr_edge"

.PP
Definition at line 307 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_attr_elem"

.PP
Definition at line 319 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_attr_face"

.PP
Definition at line 312 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_edge_this_blk"

.PP
Definition at line 305 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_edges_per_elem"

.PP
Definition at line 317 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_elem_this_blk"

.PP
Definition at line 315 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_face_this_blk"

.PP
Definition at line 310 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_faces_per_elem"

.PP
Definition at line 318 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_nodes_per_edge"

.PP
Definition at line 306 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_nodes_per_elem"

.PP
Definition at line 316 of file exodusII\&.h\&.
.SS "int* ex_block_params::num_nodes_per_face"

.PP
Definition at line 311 of file exodusII\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
