.TH "ex_set" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ex_set \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exodusII\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int64_t \fBid\fP"
.br
.ti -1c
.RI "\fBex_entity_type\fP \fBtype\fP"
.br
.ti -1c
.RI "int64_t \fBnum_entry\fP"
.br
.ti -1c
.RI "int64_t \fBnum_distribution_factor\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBentry_list\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBextra_list\fP"
.br
.ti -1c
.RI "void * \fBdistribution_factor_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 292 of file exodusII\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "void* ex_set::distribution_factor_list"

.PP
Definition at line 299 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_set::entry_list"

.PP
Definition at line 297 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_set::extra_list"

.PP
Definition at line 298 of file exodusII\&.h\&.
.SS "int64_t ex_set::id"

.PP
Definition at line 293 of file exodusII\&.h\&.
.SS "int64_t ex_set::num_distribution_factor"

.PP
Definition at line 296 of file exodusII\&.h\&.
.SS "int64_t ex_set::num_entry"

.PP
Definition at line 295 of file exodusII\&.h\&.
.SS "\fBex_entity_type\fP ex_set::type"

.PP
Definition at line 294 of file exodusII\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
