.TH "ex_set_specs" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ex_set_specs \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <exodusII\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid_int\fP * \fBsets_ids\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBnum_entries_per_set\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBnum_dist_per_set\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBsets_entry_index\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBsets_dist_index\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBsets_entry_list\fP"
.br
.ti -1c
.RI "\fBvoid_int\fP * \fBsets_extra_list\fP"
.br
.ti -1c
.RI "void * \fBsets_dist_fact\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 323 of file exodusII\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvoid_int\fP* ex_set_specs::num_dist_per_set"

.PP
Definition at line 326 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_set_specs::num_entries_per_set"

.PP
Definition at line 325 of file exodusII\&.h\&.
.SS "void* ex_set_specs::sets_dist_fact"

.PP
Definition at line 331 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_set_specs::sets_dist_index"

.PP
Definition at line 328 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_set_specs::sets_entry_index"

.PP
Definition at line 327 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_set_specs::sets_entry_list"

.PP
Definition at line 329 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_set_specs::sets_extra_list"

.PP
Definition at line 330 of file exodusII\&.h\&.
.SS "\fBvoid_int\fP* ex_set_specs::sets_ids"

.PP
Definition at line 324 of file exodusII\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
