.TH "exact_error_estimator.C" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exact_error_estimator.C \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "error_per_cell \fBlibMesh::resize\fP (mesh\&.max_elem_id())"
.br
.ti -1c
.RI "\fBlibMesh::if\fP (solution_vector &&solution_vector!=system\&.solution\&.get())"
.br
.ti -1c
.RI "\fBlibMesh::for\fP (unsigned int var=0;var< \fBn_vars\fP;var++)"
.br
.ti -1c
.RI "this \fBlibMesh::reduce_error\fP (error_per_cell, system\&.comm())"
.br
.ti -1c
.RI "\fBlibMesh::START_LOG\fP ('std::sqrt()','ExactErrorEstimator')"
.br
.ti -1c
.RI "\fBlibMesh::STOP_LOG\fP ('std::sqrt()','ExactErrorEstimator')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void 
.br
ExactErrorEstimator::estimate_error(const 
.br
System &system, ErrorVector 
.br
&error_per_cell, const 
.br
NumericVector< Number >
.br
 *solution_vector, bool 
.br
estimate_parent_error) void 
.br
ExactErrorEstimator const 
.br
unsigned in \fBlibMesh::dim\fP ) = mesh\&.mesh_dimension()"
.br
.ti -1c
.RI "const unsigned int \fBlibMesh::n_vars\fP = system\&.n_vars()"
.br
.ti -1c
.RI "const DofMap & \fBlibMesh::dof_map\fP = \fBsystem\&.get_dof_map\fP()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
