EXTERN_C_FOR_PETSC_END
NAME
EXTERN_C_FOR_PETSC_END -
SYNOPSIS
Functions
std::streambuf * out_buf (NULL)
std::streambuf * err_buf (NULL)
void libmesh_handleFPE (int, siginfo_t *info, void *)
void indices_to_fieldsplit (const libMesh::Parallel::Communicator &comm, const std::vector< dof_id_type > &indices, PC my_pc, const std::string &field_name)
Variables
AutoPtr< GetPot > command_line (NULL)
AutoPtr< std::ofstream > _ofstream (NULL)
AutoPtr
< libMesh::Threads::task_scheduler_init > task_scheduler (NULL)"
bool libmesh_initialized_mpi = false
bool libmesh_initialized_petsc = false
bool libmesh_initialized_slepc = false
Function Documentation
std::streambuf* EXTERN_C_FOR_PETSC_END::err_buf (NULL)
Referenced by libMesh::if().
void EXTERN_C_FOR_PETSC_END::indices_to_fieldsplit (const libMesh::Parallel::Communicator &comm, const std::vector< dof_id_type > &indices, PCmy_pc, const std::string &field_name)
Definition at line 36 of file petsc_auto_fieldsplit.C.
References libMesh::CHKERRABORT(), libMesh::Parallel::Communicator::get(), libMesh::MeshTools::Generation::Private::idx(), ierr, and PETSC_COPY_VALUES.
Referenced by libMesh::petsc_auto_fieldsplit().
{
  const PetscInt *idx = PETSC_NULL;
  if (!indices.empty())
    idx = reinterpret_cast<const PetscInt*>(&indices[0]);
  IS is;
  int ierr = ISCreateLibMesh(comm.get(), indices.size(),
                             idx, PETSC_COPY_VALUES, &is);
  CHKERRABORT(comm.get(), ierr);
  ierr = PCFieldSplitSetIS(my_pc, field_name.c_str(), is);
  CHKERRABORT(comm.get(), ierr);
}
void EXTERN_C_FOR_PETSC_END::libmesh_handleFPE (int, siginfo_t *info, void *)
Floating point exception handler -- courtesy of Cody Permann & MOOSE team
Definition at line 106 of file libmesh.C.
References libMesh::err.
Referenced by libMesh::enableFPE().
{
  libMesh::err << std::endl;
  libMesh::err << "Floating point exception signaled (";
  switch (info->si_code)
    {
    case FPE_INTDIV: libMesh::err << "integer divide by zero"; break;
    case FPE_INTOVF: libMesh::err << "integer overflow"; break;
    case FPE_FLTDIV: libMesh::err << "floating point divide by zero"; break;
    case FPE_FLTOVF: libMesh::err << "floating point overflow"; break;
    case FPE_FLTUND: libMesh::err << "floating point underflow"; break;
    case FPE_FLTRES: libMesh::err << "floating point inexact result"; break;
    case FPE_FLTINV: libMesh::err << "invalid floating point operation"; break;
    case FPE_FLTSUB: libMesh::err << "subscript out of range"; break;
    default: libMesh::err << "unrecognized"; break;
    }
  libMesh::err << ")!" << std::endl;
  libMesh::err << std::endl;
  libMesh::err << "To track this down, compile debug version, start debugger, set breakpoint for 'libmesh_handleFPE' and run" << std::endl;
  libMesh::err << "In gdb do:" << std::endl;
  libMesh::err << " break libmesh_handleFPE" << std::endl;
  libMesh::err << " run ..." << std::endl;
  libMesh::err << " bt" << std::endl;
  libmesh_error();
}
std::streambuf* EXTERN_C_FOR_PETSC_END::out_buf (NULL)
Referenced by libMesh::if().
Variable Documentation
AutoPtr<std::ofstream> EXTERN_C_FOR_PETSC_END::_ofstream(NULL)
Referenced by libMesh::if().
AutoPtr<GetPot> EXTERN_C_FOR_PETSC_END::command_line(NULL)
Referenced by libMesh::command_line_next(), libMesh::command_line_value(), libMesh::command_line_vector(), and libMesh::on_command_line().
bool EXTERN_C_FOR_PETSC_END::libmesh_initialized_mpi = false
Definition at line 92 of file libmesh.C.
Referenced by libMesh::if().
bool EXTERN_C_FOR_PETSC_END::libmesh_initialized_petsc = false
Definition at line 95 of file libmesh.C.
Referenced by libMesh::if().
bool EXTERN_C_FOR_PETSC_END::libmesh_initialized_slepc = false
Definition at line 98 of file libmesh.C.
Referenced by libMesh::if().
AutoPtr<libMesh::Threads::task_scheduler_init> EXTERN_C_FOR_PETSC_END::task_scheduler(NULL)
Author
Generated automatically by Doxygen for libMesh from the source code.