.TH "Variables controlling the compression, name size, and integer size." 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Variables controlling the compression, name size, and integer size. \- 
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBex_option_type\fP \fBex_option_type\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBex_option_type\fP { \fBEX_OPT_MAX_NAME_LENGTH\fP = 1, \fBEX_OPT_COMPRESSION_TYPE\fP, \fBEX_OPT_COMPRESSION_LEVEL\fP, \fBEX_OPT_COMPRESSION_SHUFFLE\fP, \fBEX_OPT_INTEGER_SIZE_API\fP, \fBEX_OPT_INTEGER_SIZE_DB\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBex_option_type\fP \fBex_option_type\fP"

.PP
Definition at line 188 of file exodusII\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBex_option_type\fP"

.PP
\fBSee Also:\fP
.RS 4
\fBex_set_option()\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEX_OPT_MAX_NAME_LENGTH \fP\fP
.TP
\fB\fIEX_OPT_COMPRESSION_TYPE \fP\fP
.TP
\fB\fIEX_OPT_COMPRESSION_LEVEL \fP\fP
.TP
\fB\fIEX_OPT_COMPRESSION_SHUFFLE \fP\fP
.TP
\fB\fIEX_OPT_INTEGER_SIZE_API \fP\fP
.TP
\fB\fIEX_OPT_INTEGER_SIZE_DB \fP\fP
.PP
Definition at line 180 of file exodusII\&.h\&.
.PP
.nf
180                       {
181     EX_OPT_MAX_NAME_LENGTH = 1,
182     EX_OPT_COMPRESSION_TYPE,     /* Currently not used\&. GZip by default */
183     EX_OPT_COMPRESSION_LEVEL,    /* 0 (disabled/fastest) \&.\&.\&. 9 (best/slowest) */
184     EX_OPT_COMPRESSION_SHUFFLE,  /* 0 (disabled); 1 (enabled) */
185     EX_OPT_INTEGER_SIZE_API,     /* See *_INT64_* values above */
186     EX_OPT_INTEGER_SIZE_DB /* (query only) */
187   };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
