.TH "getpot.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
getpot.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGETPOT_NAMESPACE::GetPot\fP"
.br
.ti -1c
.RI "struct \fBGETPOT_NAMESPACE::GetPot::variable\fP"
.br
.ti -1c
.RI "struct \fBGETPOT_NAMESPACE::GetPot::ltstr\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBGETPOT_NAMESPACE\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< std::string > \fBSTRING_VECTOR\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<std::string> \fBSTRING_VECTOR\fP"

.PP
Definition at line 94 of file getpot\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
