.TH "libMesh::Parallel::BufferType< T >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Parallel::BufferType< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parallel\&.h>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct libMesh::Parallel::BufferType< T >"
Define the data type to be used for data arrays whne encoding a potentially-variable-size object of type T\&. 
.PP
Definition at line 451 of file parallel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
