.TH "libMesh::LinearSolutionMonitor" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::LinearSolutionMonitor \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diff_solver\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBoperator()\fP (const \fBNumericVector\fP< \fBNumber\fP > &delta_u, const double &norm_delta_u, const \fBNumericVector\fP< \fBNumber\fP > &u, const double &norm_u, const \fBNumericVector\fP< \fBNumber\fP > &res, const double &norm_res, const unsigned int iteration)=0"
.br
.ti -1c
.RI "virtual \fB~LinearSolutionMonitor\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Functor for use as callback in solve of nonlinear solver\&. 
.PP
Definition at line 44 of file diff_solver\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "libMesh::LinearSolutionMonitor::~LinearSolutionMonitor ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 53 of file diff_solver\&.h\&.
.PP
.nf
53 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void libMesh::LinearSolutionMonitor::operator() (const \fBNumericVector\fP< \fBNumber\fP > &delta_u, const double &norm_delta_u, const \fBNumericVector\fP< \fBNumber\fP > &u, const double &norm_u, const \fBNumericVector\fP< \fBNumber\fP > &res, const double &norm_res, const unsigned intiteration)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
