.TH "libMesh::ScalarTraits< std::complex< T > >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::ScalarTraits< std::complex< T > > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <compare_types\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBvalue\fP = \fBScalarTraits\fP<T>::value"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct libMesh::ScalarTraits< std::complex< T > >"

.PP
Definition at line 78 of file compare_types\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > const bool \fBlibMesh::ScalarTraits\fP< std::complex< T > >::value = \fBScalarTraits\fP<T>::value\fC [static]\fP"

.PP
Definition at line 78 of file compare_types\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
