libMesh::PetscNonlinearSolver< T >
NAME
libMesh::PetscNonlinearSolver< T > -
SYNOPSIS
#include <petsc_nonlinear_solver.h>
Inherits libMesh::NonlinearSolver< T >.
Inherited by libMesh::PetscDMNonlinearSolver< T >.
Public Types
typedef NonlinearImplicitSystem sys_type
Public Member Functions
PetscNonlinearSolver (sys_type &system)
~PetscNonlinearSolver ()
virtual void clear ()
virtual void init (const char *name=NULL)
SNES snes ()
virtual std::pair< unsigned
int, Real > solve (SparseMatrix< T > &, NumericVector< T > &, NumericVector< T > &, const double, const unsigned int)"
virtual void print_converged_reason ()
SNESConvergedReason get_converged_reason ()
virtual int get_total_linear_iterations ()
virtual unsigned get_current_nonlinear_iteration_number () const
void set_residual_zero_out (bool state)
void set_jacobian_zero_out (bool state)
void use_default_monitor (bool state)
bool initialized () const
const sys_type & system () const
sys_type & system ()
void attach_preconditioner (Preconditioner< T > *preconditioner)
const Parallel::Communicator & comm () const
processor_id_type n_processors () const
processor_id_type processor_id () const
Static Public Member Functions
static AutoPtr
< NonlinearSolver< T > > build (sys_type &s, const SolverPackage solver_package=libMesh::default_solver_package())"
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
void(* residual )(const NumericVector< Number > &X, NumericVector< Number > &R, sys_type &S)
NonlinearImplicitSystem::ComputeResidual * residual_object
void(* jacobian )(const NumericVector< Number > &X, SparseMatrix< Number > &J, sys_type &S)
NonlinearImplicitSystem::ComputeJacobian * jacobian_object
void(* matvec )(const NumericVector< Number > &X, NumericVector< Number > *R, SparseMatrix< Number > *J, sys_type &S)
NonlinearImplicitSystem::ComputeResidualandJacobian * residual_and_jacobian_object
void(* bounds )(NumericVector< Number > &XL, NumericVector< Number > &XU, sys_type &S)
NonlinearImplicitSystem::ComputeBounds * bounds_object
void(* nullspace )(std::vector< NumericVector< Number > * > &sp, sys_type &S)
NonlinearImplicitSystem::ComputeVectorSubspace * nullspace_object
void(* nearnullspace )(std::vector< NumericVector< Number > * > &sp, sys_type &S)
NonlinearImplicitSystem::ComputeVectorSubspace * nearnullspace_object
void(* user_presolve )(sys_type &S)
unsigned int max_nonlinear_iterations
unsigned int max_function_evaluations
Real absolute_residual_tolerance
Real relative_residual_tolerance
Real absolute_step_tolerance
Real relative_step_tolerance
unsigned int max_linear_iterations
Real initial_linear_tolerance
Real minimum_linear_tolerance
bool converged
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts"
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
SNES _snes
SNESConvergedReason _reason
PetscInt _n_linear_iterations
unsigned _current_nonlinear_iteration_number
bool _zero_out_residual
bool _zero_out_jacobian
bool _default_monitor
sys_type & _system
bool _is_initialized
Preconditioner< T > * _preconditioner
const Parallel::Communicator & _communicator
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects"
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
void build_mat_null_space (NonlinearImplicitSystem::ComputeVectorSubspace *computeSubspaceObject, void(*)(std::vector< NumericVector< Number > * > &, sys_type &), MatNullSpace *)
Friends
PetscErrorCode __libmesh_petsc_snes_residual (SNES snes, Vec x, Vec r, void *ctx)
PetscErrorCode __libmesh_petsc_snes_jacobian (SNES snes, Vec x, Mat *jac, Mat *pc, MatStructure *msflag, void *ctx)
PetscErrorCode __libmesh_petsc_snes_jacobian (SNES snes, Vec x, Mat jac, Mat pc, void *ctx)
Detailed Description
template<typename T>class libMesh::PetscNonlinearSolver< T >
This class provides an interface to PETSc iterative solvers that is compatible with the libMesh NonlinearSolver<>
Author:
Benjamin Kirk, 2002-2007
Definition at line 63 of file petsc_nonlinear_solver.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts [protected], [inherited]
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
template<typename T> typedef NonlinearImplicitSystem libMesh::PetscNonlinearSolver< T >::sys_type
The type of system
Definition at line 69 of file petsc_nonlinear_solver.h.
Constructor & Destructor Documentation
template<typename T> libMesh::PetscNonlinearSolver< T >::PetscNonlinearSolver (sys_type &system) [explicit]
Constructor. Initializes Petsc data structures
template<typename T > libMesh::PetscNonlinearSolver< T >::~PetscNonlinearSolver ()
Destructor.
Definition at line 267 of file petsc_nonlinear_solver.C.
{
  this->clear ();
}
Member Function Documentation
template<typename T> void libMesh::NonlinearSolver< T >::attach_preconditioner (Preconditioner< T > *preconditioner) [inherited]
Attaches a Preconditioner object to be used during the linear solves.
Definition at line 91 of file nonlinear_solver.C.
References libMesh::libMeshPrivateData::_is_initialized, and libMesh::err.
{
  if(this->_is_initialized)
    {
      libMesh::err << "Preconditioner must be attached before the solver is initialized!"<<std::endl;
      libmesh_error();
    }
  _preconditioner = preconditioner;
}
template<typename T > AutoPtr< NonlinearSolver< T > > libMesh::NonlinearSolver< T >::build (sys_type &s, const SolverPackagesolver_package = libMesh::default_solver_package()) [static], [inherited]
Builds a NonlinearSolver using the nonlinear solver package specified by solver_package
Definition at line 38 of file nonlinear_solver.C.
References libMesh::err, libMesh::on_command_line(), libMesh::PETSC_SOLVERS, libMesh::AutoPtr< Tp >::reset(), and libMesh::TRILINOS_SOLVERS.
{
  AutoPtr<NonlinearSolver<T> > ap;
  // Build the appropriate solver
  switch (solver_package)
    {
#ifdef LIBMESH_HAVE_PETSC
    case PETSC_SOLVERS:
#if PETSC_VERSION_LESS_THAN(3,3,0)
      ap.reset(new PetscNonlinearSolver<T>(s));
      break;
#else
      if (libMesh::on_command_line ("--use-petsc-dm")){
        ap.reset(new PetscDMNonlinearSolver<T>(s));
      }
      else {
        ap.reset(new PetscNonlinearSolver<T>(s));
      }
      break;
#endif
#endif // LIBMESH_HAVE_PETSC
#ifdef LIBMESH_HAVE_NOX
    case TRILINOS_SOLVERS:
      ap.reset(new NoxNonlinearSolver<T>(s));
      break;
#endif
    default:
      libMesh::err << "ERROR: Unrecognized solver package: "
                   << solver_package
                   << std::endl;
      libmesh_error();
    }
  return ap;
}
template<typename T > void libMesh::PetscNonlinearSolver< T >::build_mat_null_space (NonlinearImplicitSystem::ComputeVectorSubspace *computeSubspaceObject, void(*)(std::vector< NumericVector< Number > * > &, sys_type &)computeSubspace, MatNullSpace *msp) [private]
Definition at line 369 of file petsc_nonlinear_solver.C.
References libMesh::comm, ierr, and libMesh::PetscVector< T >::vec().
{
  PetscErrorCode ierr;
  std::vector<NumericVector<Number>* > sp;
  if (computeSubspaceObject)
    (*computeSubspaceObject)(sp, this->system());
  else
    (*computeSubspace)(sp, this->system());
  *msp = PETSC_NULL;
  if (sp.size())
    {
      Vec *modes;
      PetscScalar *dots;
      PetscInt nmodes = sp.size();
#if PETSC_RELEASE_LESS_THAN(3,5,0)
      ierr = PetscMalloc2(nmodes,Vec,&modes,nmodes,PetscScalar,&dots);
#else
      ierr = PetscMalloc2(nmodes,&modes,nmodes,&dots);
#endif
      LIBMESH_CHKERRABORT(ierr);
      for (PetscInt i=0; i<nmodes; ++i)
        {
          PetscVector<T>* pv = libmesh_cast_ptr<PetscVector<T>*>(sp[i]);
          Vec v = pv->vec();
          ierr = VecDuplicate(v, modes+i);
          LIBMESH_CHKERRABORT(ierr);
          ierr = VecCopy(v,modes[i]);
          LIBMESH_CHKERRABORT(ierr);
        }
      // Normalize.
      ierr = VecNormalize(modes[0],PETSC_NULL);
      LIBMESH_CHKERRABORT(ierr);
      for (PetscInt i=1; i<nmodes; i++)
        {
          // Orthonormalize vec[i] against vec[0:i-1]
          ierr = VecMDot(modes[i],i,modes,dots);
          LIBMESH_CHKERRABORT(ierr);
          for (PetscInt j=0; j<i; j++)
            dots[j] *= -1.;
          ierr = VecMAXPY(modes[i],i,dots,modes);
          LIBMESH_CHKERRABORT(ierr);
          ierr = VecNormalize(modes[i],PETSC_NULL);
          LIBMESH_CHKERRABORT(ierr);
        }
      ierr = MatNullSpaceCreate(this->comm().get(), PETSC_FALSE, nmodes, modes, msp);
      LIBMESH_CHKERRABORT(ierr);
      for (PetscInt i=0; i<nmodes; ++i)
        {
          ierr = VecDestroy(modes+i);
          LIBMESH_CHKERRABORT(ierr);
        }
      ierr = PetscFree2(modes,dots);
      LIBMESH_CHKERRABORT(ierr);
    }
}
template<typename T > void libMesh::PetscNonlinearSolver< T >::clear () [virtual]
Release all memory and clear data structures.
Reimplemented from libMesh::NonlinearSolver< T >.
Definition at line 275 of file petsc_nonlinear_solver.C.
References libMesh::_current_nonlinear_iteration_number, libMesh::libMeshPrivateData::_is_initialized, and libMesh::initialized().
{
  if (this->initialized())
    {
      this->_is_initialized = false;
      PetscErrorCode ierr=0;
      ierr = LibMeshSNESDestroy(&_snes);
      LIBMESH_CHKERRABORT(ierr);
      // Reset the nonlinear iteration counter. This information is only relevant
      // *during* the solve(). After the solve is completed it should return to
      // the default value of 0.
      _current_nonlinear_iteration_number = 0;
    }
}
const Parallel::Communicator& libMesh::ParallelObject::comm () const [inline], [inherited]
Returns:
a reference to the Parallel::Communicator object used by this mesh.
Definition at line 86 of file parallel_object.h.
References libMesh::ParallelObject::_communicator.
Referenced by libMesh::__libmesh_petsc_diff_solver_monitor(), libMesh::__libmesh_petsc_diff_solver_residual(), libMesh::__libmesh_petsc_snes_residual(), libMesh::MeshRefinement::_coarsen_elements(), libMesh::ExactSolution::_compute_error(), libMesh::MetisPartitioner::_do_partition(), libMesh::ParmetisPartitioner::_do_repartition(), libMesh::UniformRefinementEstimator::_estimate_error(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_get_diagonal(), libMesh::SlepcEigenSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult(), libMesh::PetscLinearSolver< T >::_petsc_shell_matrix_mult_add(), libMesh::EquationSystems::_read_impl(), libMesh::MeshRefinement::_refine_elements(), libMesh::ParallelMesh::add_elem(), libMesh::ImplicitSystem::add_matrix(), libMesh::ParallelMesh::add_node(), libMesh::System::add_vector(), libMesh::UnstructuredMesh::all_second_order(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::FEMSystem::assemble_qoi(), libMesh::MeshCommunication::assign_global_indices(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::DofMap::attach_matrix(), libMesh::MeshTools::bounding_box(), libMesh::System::calculate_norm(), libMesh::MeshRefinement::coarsen_elements(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), libMesh::Problem_Interface::computePreconditioner(), libMesh::MeshTools::correct_node_proc_ids(), libMesh::MeshCommunication::delete_remote_elements(), libMesh::DofMap::distribute_dofs(), DMlibMeshFunction(), DMLibMeshSetSystem(), DMVariableBounds_libMesh(), libMesh::MeshRefinement::eliminate_unrefined_patches(), libMesh::WeightedPatchRecoveryErrorEstimator::estimate_error(), libMesh::PatchRecoveryErrorEstimator::estimate_error(), libMesh::JumpErrorEstimator::estimate_error(), libMesh::AdjointRefinementEstimator::estimate_error(), libMesh::MeshRefinement::flag_elements_by_elem_fraction(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::for(), libMesh::CondensedEigenSystem::get_eigenpair(), libMesh::ImplicitSystem::get_linear_solver(), libMesh::LocationMap< T >::init(), libMesh::TimeSolver::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::EigenSystem::init_data(), libMesh::EigenSystem::init_matrices(), libMesh::ParmetisPartitioner::initialize(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_flags(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshCommunication::make_elems_parallel_consistent(), libMesh::MeshRefinement::make_flags_parallel_consistent(), libMesh::MeshCommunication::make_node_ids_parallel_consistent(), libMesh::MeshCommunication::make_node_proc_ids_parallel_consistent(), libMesh::MeshCommunication::make_nodes_parallel_consistent(), libMesh::MeshRefinement::make_refinement_compatible(), libMesh::FEMSystem::mesh_position_set(), libMesh::MeshSerializer::MeshSerializer(), libMesh::ParallelMesh::n_active_elem(), libMesh::MeshTools::n_active_levels(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::CondensedEigenSystem::n_global_non_condensed_dofs(), libMesh::MeshTools::n_levels(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::MeshTools::n_p_levels(), libMesh::ParallelMesh::parallel_max_elem_id(), libMesh::ParallelMesh::parallel_max_node_id(), libMesh::ParallelMesh::parallel_n_elem(), libMesh::ParallelMesh::parallel_n_nodes(), libMesh::Partitioner::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::petsc_auto_fieldsplit(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshBase::prepare_for_use(), libMesh::System::project_vector(), libMesh::Nemesis_IO::read(), libMesh::XdrIO::read(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::MeshRefinement::refine_and_coarsen_elements(), libMesh::MeshRefinement::refine_elements(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::MeshBase::subdomain_ids(), libMesh::BoundaryInfo::sync(), libMesh::Parallel::sync_element_data_by_parent_id(), libMesh::MeshRefinement::test_level_one(), libMesh::MeshRefinement::test_unflagged(), libMesh::MeshTools::total_weight(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::UnstructuredMesh::write(), libMesh::LegacyXdrIO::write_mesh(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), and libMesh::DivaIO::write_stream().
  { return _communicator; }
void libMesh::ReferenceCounter::disable_print_counter_info () [static], [inherited]
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = false;
  return;
}
void libMesh::ReferenceCounter::enable_print_counter_info () [static], [inherited]
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = true;
  return;
}
template<typename T > SNESConvergedReason libMesh::PetscNonlinearSolver< T >::get_converged_reason ()
Returns the currently-available (or most recently obtained, if the SNES object has been destroyed) convergence reason. Refer to PETSc docs for the meaning of different SNESConvergedReasons.
Definition at line 593 of file petsc_nonlinear_solver.C.
References libMesh::initialized().
{
  PetscErrorCode ierr=0;
  if (this->initialized())
    {
      ierr = SNESGetConvergedReason(_snes, &_reason);
      LIBMESH_CHKERRABORT(ierr);
    }
  return _reason;
}
template<typename T> virtual unsigned libMesh::PetscNonlinearSolver< T >::get_current_nonlinear_iteration_number () const [inline], [virtual]
If called during the solve(), for example by the user-specified residual or Jacobian function, returns the current nonlinear iteration number.
Implements libMesh::NonlinearSolver< T >.
Definition at line 131 of file petsc_nonlinear_solver.h.
References libMesh::PetscNonlinearSolver< T >::_current_nonlinear_iteration_number.
{ return _current_nonlinear_iteration_number; }
std::string libMesh::ReferenceCounter::get_info () [static], [inherited]
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
{
#if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
  std::ostringstream oss;
  oss << '\n'
      << " ---------------------------------------------------------------------------- \n"
      << "| Reference count information |\n"
      << " ---------------------------------------------------------------------------- \n";
  for (Counts::iterator it = _counts.begin();
       it != _counts.end(); ++it)
    {
      const std::string name(it->first);
      const unsigned int creations = it->second.first;
      const unsigned int destructions = it->second.second;
      oss << "| " << name << " reference count information:\n"
          << "| Creations: " << creations << '\n'
          << "| Destructions: " << destructions << '\n';
    }
  oss << " ---------------------------------------------------------------------------- \n";
  return oss.str();
#else
  return "";
#endif
}
template<typename T > int libMesh::PetscNonlinearSolver< T >::get_total_linear_iterations () [virtual]
Get the total number of linear iterations done in the last solve
Implements libMesh::NonlinearSolver< T >.
Definition at line 607 of file petsc_nonlinear_solver.C.
{
  return _n_linear_iterations;
}
void libMesh::ReferenceCounter::increment_constructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.first++;
}
void libMesh::ReferenceCounter::increment_destructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.second++;
}
template<typename T > void libMesh::PetscNonlinearSolver< T >::init (const char *name = NULL) [virtual]
Initialize data structures if not done so already. May assign a name to the solver in some implementations
Implements libMesh::NonlinearSolver< T >.
Reimplemented in libMesh::PetscDMNonlinearSolver< T >.
Definition at line 296 of file petsc_nonlinear_solver.C.
References libMesh::__libmesh_petsc_preconditioner_apply(), libMesh::__libmesh_petsc_preconditioner_setup(), libMesh::__libmesh_petsc_snes_monitor(), libMesh::libMeshPrivateData::_is_initialized, libMesh::comm, libMesh::initialized(), and pc.
Referenced by libMesh::PetscDMNonlinearSolver< T >::init(), and libMesh::PetscNonlinearSolver< T >::snes().
{
  // Initialize the data structures if not done so already.
  if (!this->initialized())
    {
      this->_is_initialized = true;
      PetscErrorCode ierr=0;
#if PETSC_VERSION_LESS_THAN(2,1,2)
      // At least until Petsc 2.1.1, the SNESCreate had a different calling syntax.
      // The second argument was of type SNESProblemType, and could have a value of
      // either SNES_NONLINEAR_EQUATIONS or SNES_UNCONSTRAINED_MINIMIZATION.
      ierr = SNESCreate(this->comm().get(), SNES_NONLINEAR_EQUATIONS, &_snes);
      LIBMESH_CHKERRABORT(ierr);
#else
      ierr = SNESCreate(this->comm().get(),&_snes);
      LIBMESH_CHKERRABORT(ierr);
#endif
      if (name)
        {
          ierr = SNESSetOptionsPrefix(_snes, name);
          LIBMESH_CHKERRABORT(ierr);
        }
      if (_default_monitor)
        {
#if PETSC_VERSION_LESS_THAN(2,3,3)
          ierr = SNESSetMonitor (_snes, __libmesh_petsc_snes_monitor,
                                 this, PETSC_NULL);
#else
          // API name change in PETSc 2.3.3
          ierr = SNESMonitorSet (_snes, __libmesh_petsc_snes_monitor,
                                 this, PETSC_NULL);
#endif
          LIBMESH_CHKERRABORT(ierr);
        }
#if PETSC_VERSION_LESS_THAN(3,1,0)
      // Cannot call SNESSetOptions before SNESSetFunction when using
      // any matrix free options with PETSc 3.1.0+
      ierr = SNESSetFromOptions(_snes);
      LIBMESH_CHKERRABORT(ierr);
#endif
      if(this->_preconditioner)
        {
          KSP ksp;
          ierr = SNESGetKSP (_snes, &ksp);
          LIBMESH_CHKERRABORT(ierr);
          PC pc;
          ierr = KSPGetPC(ksp,&pc);
          LIBMESH_CHKERRABORT(ierr);
          this->_preconditioner->init();
          PCSetType(pc, PCSHELL);
          PCShellSetContext(pc,(void*)this->_preconditioner);
          //Re-Use the shell functions from petsc_linear_solver
          PCShellSetSetUp(pc,__libmesh_petsc_preconditioner_setup);
          PCShellSetApply(pc,__libmesh_petsc_preconditioner_apply);
        }
    }
}
template<typename T> bool libMesh::NonlinearSolver< T >::initialized () const [inline], [inherited]
Returns:
true if the data structures are initialized, false otherwise.
Definition at line 86 of file nonlinear_solver.h.
{ return _is_initialized; }
static unsigned int libMesh::ReferenceCounter::n_objects () [inline], [static], [inherited]
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
  { return _n_objects; }
processor_id_type libMesh::ParallelObject::n_processors () const [inline], [inherited]
Returns:
the number of processors in the group.
Definition at line 92 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::size().
Referenced by libMesh::ParmetisPartitioner::_do_repartition(), libMesh::ParallelMesh::add_elem(), libMesh::ParallelMesh::add_node(), libMesh::LaplaceMeshSmoother::allgather_graph(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::ParallelMesh::assign_unique_ids(), libMesh::AztecLinearSolver< T >::AztecLinearSolver(), libMesh::ParallelMesh::clear(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::UnstructuredMesh::create_pid_mesh(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EnsightIO::EnsightIO(), libMesh::MeshBase::get_info(), libMesh::EquationSystems::init(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::Nemesis_IO_Helper::initialize(), libMesh::MeshTools::libmesh_assert_valid_dof_ids(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshTools::libmesh_assert_valid_refinement_flags(), libMesh::DofMap::local_variable_indices(), libMesh::MeshBase::n_active_elem_on_proc(), libMesh::MeshBase::n_elem_on_proc(), libMesh::MeshBase::n_nodes_on_proc(), libMesh::Partitioner::partition(), libMesh::MeshBase::partition(), libMesh::Partitioner::partition_unpartitioned_elements(), libMesh::PetscLinearSolver< T >::PetscLinearSolver(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::MeshTools::processor_bounding_box(), libMesh::System::project_vector(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::UnstructuredMesh::read(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::System::read_serialized_vector(), libMesh::Partitioner::repartition(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::BoundaryInfo::sync(), libMesh::ParallelMesh::update_parallel_id_counts(), libMesh::CheckpointIO::write(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bcs(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::XdrIO::write_serialized_nodes(), and libMesh::XdrIO::write_serialized_nodesets().
  { return libmesh_cast_int<processor_id_type>(_communicator.size()); }
template<typename T > void libMesh::PetscNonlinearSolver< T >::print_converged_reason () [virtual]
Prints a useful message about why the latest nonlinear solve con(di)verged.
Reimplemented from libMesh::NonlinearSolver< T >.
Definition at line 583 of file petsc_nonlinear_solver.C.
References libMesh::out.
{
  libMesh::out << "Nonlinear solver convergence/divergence reason: "
               << SNESConvergedReasons[this->get_converged_reason()] << std::endl;
}
void libMesh::ReferenceCounter::print_info (std::ostream &out = libMesh::out) [static], [inherited]
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
{
  if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
}
processor_id_type libMesh::ParallelObject::processor_id () const [inline], [inherited]
Returns:
the rank of this processor in the group.
Definition at line 98 of file parallel_object.h.
References libMesh::ParallelObject::_communicator, and libMesh::Parallel::Communicator::rank().
Referenced by libMesh::MetisPartitioner::_do_partition(), libMesh::EquationSystems::_read_impl(), libMesh::SerialMesh::active_local_elements_begin(), libMesh::ParallelMesh::active_local_elements_begin(), libMesh::SerialMesh::active_local_elements_end(), libMesh::ParallelMesh::active_local_elements_end(), libMesh::SerialMesh::active_local_subdomain_elements_begin(), libMesh::ParallelMesh::active_local_subdomain_elements_begin(), libMesh::SerialMesh::active_local_subdomain_elements_end(), libMesh::ParallelMesh::active_local_subdomain_elements_end(), libMesh::SerialMesh::active_not_local_elements_begin(), libMesh::ParallelMesh::active_not_local_elements_begin(), libMesh::SerialMesh::active_not_local_elements_end(), libMesh::ParallelMesh::active_not_local_elements_end(), libMesh::ParallelMesh::add_elem(), libMesh::DofMap::add_neighbors_to_send_list(), libMesh::ParallelMesh::add_node(), libMesh::UnstructuredMesh::all_second_order(), libMesh::ParmetisPartitioner::assign_partitioning(), libMesh::ParallelMesh::assign_unique_ids(), libMesh::EquationSystems::build_discontinuous_solution_vector(), libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::ParmetisPartitioner::build_graph(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::DofMap::build_sparsity(), libMesh::ParallelMesh::clear(), libMesh::ExodusII_IO_Helper::close(), libMesh::Nemesis_IO_Helper::compute_border_node_ids(), libMesh::Nemesis_IO_Helper::compute_communication_map_parameters(), libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::Nemesis_IO_Helper::compute_node_communication_maps(), libMesh::Nemesis_IO_Helper::compute_num_global_elem_blocks(), libMesh::Nemesis_IO_Helper::compute_num_global_nodesets(), libMesh::Nemesis_IO_Helper::compute_num_global_sidesets(), libMesh::Nemesis_IO_Helper::construct_nemesis_filename(), libMesh::ExodusII_IO_Helper::create(), libMesh::DofMap::distribute_dofs(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::DofMap::end_dof(), libMesh::DofMap::end_old_dof(), libMesh::EnsightIO::EnsightIO(), libMesh::UnstructuredMesh::find_neighbors(), libMesh::DofMap::first_dof(), libMesh::DofMap::first_old_dof(), libMesh::Nemesis_IO_Helper::get_cmap_params(), libMesh::Nemesis_IO_Helper::get_eb_info_global(), libMesh::Nemesis_IO_Helper::get_elem_cmap(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::MeshBase::get_info(), libMesh::Nemesis_IO_Helper::get_init_global(), libMesh::Nemesis_IO_Helper::get_init_info(), libMesh::Nemesis_IO_Helper::get_loadbal_param(), libMesh::Nemesis_IO_Helper::get_node_cmap(), libMesh::Nemesis_IO_Helper::get_node_map(), libMesh::Nemesis_IO_Helper::get_ns_param_global(), libMesh::Nemesis_IO_Helper::get_ss_param_global(), libMesh::MeshFunction::gradient(), libMesh::MeshFunction::hessian(), libMesh::SystemSubsetBySubdomain::init(), libMesh::ParmetisPartitioner::initialize(), libMesh::ExodusII_IO_Helper::initialize(), libMesh::ExodusII_IO_Helper::initialize_element_variables(), libMesh::ExodusII_IO_Helper::initialize_global_variables(), libMesh::ExodusII_IO_Helper::initialize_nodal_variables(), libMesh::SparsityPattern::Build::join(), libMesh::DofMap::last_dof(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::SerialMesh::local_elements_begin(), libMesh::ParallelMesh::local_elements_begin(), libMesh::SerialMesh::local_elements_end(), libMesh::ParallelMesh::local_elements_end(), libMesh::SerialMesh::local_level_elements_begin(), libMesh::ParallelMesh::local_level_elements_begin(), libMesh::SerialMesh::local_level_elements_end(), libMesh::ParallelMesh::local_level_elements_end(), libMesh::SerialMesh::local_nodes_begin(), libMesh::ParallelMesh::local_nodes_begin(), libMesh::SerialMesh::local_nodes_end(), libMesh::ParallelMesh::local_nodes_end(), libMesh::SerialMesh::local_not_level_elements_begin(), libMesh::ParallelMesh::local_not_level_elements_begin(), libMesh::SerialMesh::local_not_level_elements_end(), libMesh::ParallelMesh::local_not_level_elements_end(), libMesh::DofMap::local_variable_indices(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::MeshBase::n_active_local_elem(), libMesh::BoundaryInfo::n_boundary_conds(), libMesh::BoundaryInfo::n_edge_conds(), libMesh::DofMap::n_local_dofs(), libMesh::System::n_local_dofs(), libMesh::MeshBase::n_local_elem(), libMesh::MeshBase::n_local_nodes(), libMesh::BoundaryInfo::n_nodeset_conds(), libMesh::SerialMesh::not_local_elements_begin(), libMesh::ParallelMesh::not_local_elements_begin(), libMesh::SerialMesh::not_local_elements_end(), libMesh::ParallelMesh::not_local_elements_end(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::SparsityPattern::Build::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::MeshFunction::operator()(), libMesh::ParallelMesh::ParallelMesh(), libMesh::System::point_gradient(), libMesh::System::point_hessian(), libMesh::System::point_value(), libMesh::System::project_vector(), libMesh::Nemesis_IO_Helper::put_cmap_params(), libMesh::Nemesis_IO_Helper::put_elem_cmap(), libMesh::Nemesis_IO_Helper::put_elem_map(), libMesh::Nemesis_IO_Helper::put_loadbal_param(), libMesh::Nemesis_IO_Helper::put_node_cmap(), libMesh::Nemesis_IO_Helper::put_node_map(), libMesh::Nemesis_IO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::UnstructuredMesh::read(), libMesh::CheckpointIO::read_connectivity(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::System::read_header(), libMesh::System::read_legacy_data(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::XdrIO::read_serialized_bc_names(), libMesh::XdrIO::read_serialized_bcs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::System::read_serialized_data(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::System::read_serialized_vector(), libMesh::System::read_serialized_vectors(), libMesh::MeshData::read_xdr(), libMesh::Partitioner::set_node_processor_ids(), libMesh::DofMap::set_nonlocal_dof_objects(), libMesh::LaplaceMeshSmoother::smooth(), libMesh::BoundaryInfo::sync(), libMesh::MeshTools::total_weight(), libMesh::ParallelMesh::update_parallel_id_counts(), libMesh::MeshTools::weight(), libMesh::ExodusII_IO::write(), libMesh::CheckpointIO::write(), libMesh::XdrIO::write(), libMesh::UnstructuredMesh::write(), libMesh::EquationSystems::write(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::ExodusII_IO_Helper::write_element_values(), libMesh::ExodusII_IO_Helper::write_elements(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO_Helper::write_global_values(), libMesh::System::write_header(), libMesh::ExodusII_IO::write_information_records(), libMesh::ExodusII_IO_Helper::write_information_records(), libMesh::ExodusII_IO_Helper::write_nodal_coordinates(), libMesh::UCDIO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), libMesh::ExodusII_IO_Helper::write_nodal_values(), libMesh::ExodusII_IO_Helper::write_nodesets(), libMesh::Nemesis_IO_Helper::write_nodesets(), libMesh::System::write_parallel_data(), libMesh::System::write_SCALAR_dofs(), libMesh::XdrIO::write_serialized_bc_names(), libMesh::XdrIO::write_serialized_bcs(), libMesh::System::write_serialized_blocked_dof_objects(), libMesh::XdrIO::write_serialized_connectivity(), libMesh::System::write_serialized_data(), libMesh::XdrIO::write_serialized_nodes(), libMesh::XdrIO::write_serialized_nodesets(), libMesh::XdrIO::write_serialized_subdomain_names(), libMesh::System::write_serialized_vector(), libMesh::System::write_serialized_vectors(), libMesh::ExodusII_IO_Helper::write_sidesets(), libMesh::Nemesis_IO_Helper::write_sidesets(), libMesh::ExodusII_IO::write_timestep(), and libMesh::ExodusII_IO_Helper::write_timestep().
  { return libmesh_cast_int<processor_id_type>(_communicator.rank()); }
template<typename T> void libMesh::PetscNonlinearSolver< T >::set_jacobian_zero_out (boolstate) [inline]
Set if the jacobian should be zeroed out in the callback
Definition at line 141 of file petsc_nonlinear_solver.h.
References libMesh::PetscNonlinearSolver< T >::_zero_out_jacobian.
{ _zero_out_jacobian = state; }
template<typename T> void libMesh::PetscNonlinearSolver< T >::set_residual_zero_out (boolstate) [inline]
Set if the residual should be zeroed out in the callback
Definition at line 136 of file petsc_nonlinear_solver.h.
References libMesh::PetscNonlinearSolver< T >::_zero_out_residual.
{ _zero_out_residual = state; }
template<typename T> SNES libMesh::PetscNonlinearSolver< T >::snes () [inline]
Returns the raw PETSc snes context pointer.
Definition at line 96 of file petsc_nonlinear_solver.h.
References libMesh::PetscNonlinearSolver< T >::_snes, and libMesh::PetscNonlinearSolver< T >::init().
{ this->init(); return _snes; }
template<typename T > std::pair< unsigned int, Real > libMesh::PetscNonlinearSolver< T >::solve (SparseMatrix< T > &jac_in, NumericVector< T > &x_in, NumericVector< T > &r_in, const double, const unsignedint) [virtual]
Call the Petsc solver. It calls the method below, using the same matrix for the system and preconditioner matrices.
Implements libMesh::NonlinearSolver< T >.
Reimplemented in libMesh::PetscDMNonlinearSolver< T >.
Definition at line 443 of file petsc_nonlinear_solver.C.
References libMesh::__libmesh_petsc_snes_jacobian(), libMesh::__libmesh_petsc_snes_residual(), libMesh::TriangleWrapper::init(), libMesh::PetscMatrix< T >::mat(), libMesh::Real, libMesh::START_LOG(), and libMesh::STOP_LOG().
{
  START_LOG("solve()", "PetscNonlinearSolver");
  this->init ();
  // Make sure the data passed in are really of Petsc types
  PetscMatrix<T>* jac = libmesh_cast_ptr<PetscMatrix<T>*>(&jac_in);
  PetscVector<T>* x = libmesh_cast_ptr<PetscVector<T>*>(&x_in);
  PetscVector<T>* r = libmesh_cast_ptr<PetscVector<T>*>(&r_in);
  PetscErrorCode ierr=0;
  PetscInt n_iterations =0;
  // Should actually be a PetscReal, but I don't know which version of PETSc first introduced PetscReal
  Real final_residual_norm=0.;
  ierr = SNESSetFunction (_snes, r->vec(), __libmesh_petsc_snes_residual, this);
  LIBMESH_CHKERRABORT(ierr);
  // Only set the jacobian function if we've been provided with something to call.
  // This allows a user to set their own jacobian function if they want to
  if (this->jacobian || this->jacobian_object || this->residual_and_jacobian_object)
    {
      ierr = SNESSetJacobian (_snes, jac->mat(), jac->mat(), __libmesh_petsc_snes_jacobian, this);
      LIBMESH_CHKERRABORT(ierr);
    }
#if !PETSC_VERSION_LESS_THAN(3,3,0)
  // Only set the nullspace if we have a way of computing it and the result is non-empty.
  if (this->nullspace || this->nullspace_object)
    {
      MatNullSpace msp;
      this->build_mat_null_space(this->nullspace_object, this->nullspace, &msp);
      if (msp)
        {
          ierr = MatSetNullSpace(jac->mat(), msp);
          LIBMESH_CHKERRABORT(ierr);
          ierr = MatNullSpaceDestroy(&msp);
          LIBMESH_CHKERRABORT(ierr);
        }
    }
  // Only set the nearnullspace if we have a way of computing it and the result is non-empty.
  if (this->nearnullspace || this->nearnullspace_object)
    {
      MatNullSpace msp = PETSC_NULL;
      this->build_mat_null_space(this->nearnullspace_object, this->nearnullspace, &msp);
      if(msp) {
        ierr = MatSetNearNullSpace(jac->mat(), msp);
        LIBMESH_CHKERRABORT(ierr);
        ierr = MatNullSpaceDestroy(&msp);
        LIBMESH_CHKERRABORT(ierr);
      }
    }
#endif
  // Have the Krylov subspace method use our good initial guess rather than 0
  KSP ksp;
  ierr = SNESGetKSP (_snes, &ksp);
  LIBMESH_CHKERRABORT(ierr);
  // Set the tolerances for the iterative solver. Use the user-supplied
  // tolerance for the relative residual & leave the others at default values
  ierr = KSPSetTolerances (ksp, this->initial_linear_tolerance, PETSC_DEFAULT,
                           PETSC_DEFAULT, this->max_linear_iterations);
  LIBMESH_CHKERRABORT(ierr);
  // Set the tolerances for the non-linear solver.
  ierr = SNESSetTolerances(_snes, this->absolute_residual_tolerance, this->relative_residual_tolerance,
                           this->relative_step_tolerance, this->max_nonlinear_iterations, this->max_function_evaluations);
  LIBMESH_CHKERRABORT(ierr);
  //Pull in command-line options
  KSPSetFromOptions(ksp);
  SNESSetFromOptions(_snes);
  if (this->user_presolve)
    this->user_presolve(this->system());
  //Set the preconditioning matrix
  if(this->_preconditioner)
    {
      this->_preconditioner->set_matrix(jac_in);
      this->_preconditioner->init();
    }
  // ierr = KSPSetInitialGuessNonzero (ksp, PETSC_TRUE);
  // LIBMESH_CHKERRABORT(ierr);
  // Older versions (at least up to 2.1.5) of SNESSolve took 3 arguments,
  // the last one being a pointer to an int to hold the number of iterations required.
# if PETSC_VERSION_LESS_THAN(2,2,0)
  ierr = SNESSolve (_snes, x->vec(), &n_iterations);
  LIBMESH_CHKERRABORT(ierr);
  // 2.2.x style
#elif PETSC_VERSION_LESS_THAN(2,3,0)
  ierr = SNESSolve (_snes, x->vec());
  LIBMESH_CHKERRABORT(ierr);
  // 2.3.x & newer style
#else
  ierr = SNESSolve (_snes, PETSC_NULL, x->vec());
  LIBMESH_CHKERRABORT(ierr);
  ierr = SNESGetIterationNumber(_snes,&n_iterations);
  LIBMESH_CHKERRABORT(ierr);
  ierr = SNESGetLinearSolveIterations(_snes, &_n_linear_iterations);
  LIBMESH_CHKERRABORT(ierr);
  ierr = SNESGetFunctionNorm(_snes,&final_residual_norm);
  LIBMESH_CHKERRABORT(ierr);
#endif
  // Get and store the reason for convergence
  SNESGetConvergedReason(_snes, &_reason);
  //Based on Petsc 2.3.3 documentation all diverged reasons are negative
  this->converged = (_reason >= 0);
  this->clear();
  STOP_LOG("solve()", "PetscNonlinearSolver");
  // return the # of its. and the final residual norm.
  return std::make_pair(n_iterations, final_residual_norm);
}
template<typename T> const sys_type& libMesh::NonlinearSolver< T >::system () const [inline], [inherited]
Returns:
a constant reference to the system we are solving.
Definition at line 220 of file nonlinear_solver.h.
Referenced by libMesh::__libmesh_petsc_snes_residual(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner().
{ return _system; }
template<typename T> sys_type& libMesh::NonlinearSolver< T >::system () [inline], [inherited]
Returns:
a writeable reference to the system we are solving.
Definition at line 225 of file nonlinear_solver.h.
{ return _system; }
template<typename T> void libMesh::PetscNonlinearSolver< T >::use_default_monitor (boolstate) [inline]
Set to true to use the libMeash's default monitor, set to false to use your own
Definition at line 146 of file petsc_nonlinear_solver.h.
References libMesh::PetscNonlinearSolver< T >::_default_monitor.
{ _default_monitor = state; }
Friends And Related Function Documentation
template<typename T> PetscErrorCode __libmesh_petsc_snes_jacobian (SNESsnes, Vecx, Mat *jac, Mat *pc, MatStructure *msflag, void *ctx) [friend]
template<typename T> PetscErrorCode __libmesh_petsc_snes_jacobian (SNESsnes, Vecx, Matjac, Matpc, void *ctx) [friend]
template<typename T> PetscErrorCode __libmesh_petsc_snes_residual (SNESsnes, Vecx, Vecr, void *ctx) [friend]
Definition at line 78 of file petsc_nonlinear_solver.C.
  {
    START_LOG("residual()", "PetscNonlinearSolver");
    PetscErrorCode ierr=0;
    libmesh_assert(x);
    libmesh_assert(r);
    libmesh_assert(ctx);
    PetscNonlinearSolver<Number>* solver =
      static_cast<PetscNonlinearSolver<Number>*> (ctx);
    // Get the current iteration number from the snes object,
    // store it in the PetscNonlinearSolver object for possible use
    // by the user's residual function.
    {
      PetscInt n_iterations = 0;
      ierr = SNESGetIterationNumber(snes, &n_iterations);
      CHKERRABORT(solver->comm().get(),ierr);
      solver->_current_nonlinear_iteration_number = static_cast<unsigned>(n_iterations);
    }
    NonlinearImplicitSystem &sys = solver->system();
    PetscVector<Number>& X_sys = *libmesh_cast_ptr<PetscVector<Number>*>(sys.solution.get());
    PetscVector<Number>& R_sys = *libmesh_cast_ptr<PetscVector<Number>*>(sys.rhs);
    PetscVector<Number> X_global(x, sys.comm()), R(r, sys.comm());
    // Use the systems update() to get a good local version of the parallel solution
    X_global.swap(X_sys);
    R.swap(R_sys);
    sys.get_dof_map().enforce_constraints_exactly(sys);
    sys.update();
    //Swap back
    X_global.swap(X_sys);
    R.swap(R_sys);
    if (solver->_zero_out_residual)
      R.zero();
    //-----------------------------------------------------------------------------
    // if the user has provided both function pointers and objects only the pointer
    // will be used, so catch that as an error
    if (solver->residual && solver->residual_object)
      {
        libMesh::err << "ERROR: cannot specifiy both a function and object to compute the Residual!" << std::endl;
        libmesh_error();
      }
    if (solver->matvec && solver->residual_and_jacobian_object)
      {
        libMesh::err << "ERROR: cannot specifiy both a function and object to compute the combined Residual & Jacobian!" << std::endl;
        libmesh_error();
      }
    //-----------------------------------------------------------------------------
    if (solver->residual != NULL) solver->residual (*sys.current_local_solution.get(), R, sys);
    else if (solver->residual_object != NULL) solver->residual_object->residual (*sys.current_local_solution.get(), R, sys);
    else if (solver->matvec != NULL) solver->matvec (*sys.current_local_solution.get(), &R, NULL, sys);
    else if (solver->residual_and_jacobian_object != NULL) solver->residual_and_jacobian_object->residual_and_jacobian (*sys.current_local_solution.get(), &R, NULL, sys);
    else libmesh_error();
    R.close();
    X_global.close();
    STOP_LOG("residual()", "PetscNonlinearSolver");
    return ierr;
  }
Member Data Documentation
const Parallel::Communicator& libMesh::ParallelObject::_communicator [protected], [inherited]
Definition at line 104 of file parallel_object.h.
Referenced by libMesh::EquationSystems::build_solution_vector(), libMesh::ParallelObject::comm(), libMesh::EquationSystems::get_solution(), libMesh::ParallelObject::n_processors(), libMesh::ParallelObject::operator=(), and libMesh::ParallelObject::processor_id().
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts [static], [protected], [inherited]
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
template<typename T> unsigned libMesh::PetscNonlinearSolver< T >::_current_nonlinear_iteration_number [protected]
Stores the current nonlinear iteration number
Definition at line 171 of file petsc_nonlinear_solver.h.
Referenced by libMesh::__libmesh_petsc_snes_residual(), and libMesh::PetscNonlinearSolver< T >::get_current_nonlinear_iteration_number().
template<typename T> bool libMesh::PetscNonlinearSolver< T >::_default_monitor [protected]
true if we want the default monitor to be set, false for no monitor (i.e. user code can use their own)
Definition at line 186 of file petsc_nonlinear_solver.h.
Referenced by libMesh::PetscNonlinearSolver< T >::use_default_monitor().
bool libMesh::ReferenceCounter::_enable_print_counter = true [static], [protected], [inherited]
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
template<typename T> bool libMesh::NonlinearSolver< T >::_is_initialized [protected], [inherited]
Flag indicating if the data structures have been initialized.
Definition at line 301 of file nonlinear_solver.h.
Referenced by libMesh::NonlinearSolver< Number >::initialized().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex [static], [protected], [inherited]
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
template<typename T> PetscInt libMesh::PetscNonlinearSolver< T >::_n_linear_iterations [protected]
Stores the total number of linear iterations from the last solve.
Definition at line 166 of file petsc_nonlinear_solver.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects [static], [protected], [inherited]
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<typename T> Preconditioner<T>* libMesh::NonlinearSolver< T >::_preconditioner [protected], [inherited]
Holds the Preconditioner object to be used for the linear solves.
Definition at line 306 of file nonlinear_solver.h.
template<typename T> SNESConvergedReason libMesh::PetscNonlinearSolver< T >::_reason [protected]
Store the reason for SNES convergence/divergence for use even after the _snes has been cleared. Note that print_converged_reason() will always try to get the current reason with SNESGetConvergedReason(), but if the SNES object has already been cleared, it will fall back on this stored value. Note that this value is therefore necessarily not cleared by the clear() function.
Definition at line 161 of file petsc_nonlinear_solver.h.
template<typename T> SNES libMesh::PetscNonlinearSolver< T >::_snes [protected]
Nonlinear solver context
Definition at line 152 of file petsc_nonlinear_solver.h.
Referenced by libMesh::PetscNonlinearSolver< T >::snes().
template<typename T> sys_type& libMesh::NonlinearSolver< T >::_system [protected], [inherited]
A reference to the system we are solving.
Definition at line 296 of file nonlinear_solver.h.
Referenced by libMesh::NonlinearSolver< Number >::system().
template<typename T> bool libMesh::PetscNonlinearSolver< T >::_zero_out_jacobian [protected]
true to zero out jacobian before going into application level call-back, otherwise false
Definition at line 181 of file petsc_nonlinear_solver.h.
Referenced by libMesh::PetscNonlinearSolver< T >::set_jacobian_zero_out().
template<typename T> bool libMesh::PetscNonlinearSolver< T >::_zero_out_residual [protected]
true to zero out residual before going into application level call-back, otherwise false
Definition at line 176 of file petsc_nonlinear_solver.h.
Referenced by libMesh::__libmesh_petsc_snes_residual(), and libMesh::PetscNonlinearSolver< T >::set_residual_zero_out().
template<typename T> Real libMesh::NonlinearSolver< T >::absolute_residual_tolerance [inherited]
The NonlinearSolver should exit after the residual is reduced to either less than absolute_residual_tolerance or less than relative_residual_tolerance times the initial residual.
Users should increase any of these tolerances that they want to use for a stopping condition.
Definition at line 252 of file nonlinear_solver.h.
template<typename T> Real libMesh::NonlinearSolver< T >::absolute_step_tolerance [inherited]
The NonlinearSolver should exit after the full nonlinear step norm is reduced to either less than absolute_step_tolerance or less than relative_step_tolerance times the largest nonlinear solution which has been seen so far.
Users should increase any of these tolerances that they want to use for a stopping condition.
Note that not all NonlinearSolvers support relative_step_tolerance!
Definition at line 266 of file nonlinear_solver.h.
template<typename T> void(* libMesh::NonlinearSolver< T >::bounds)(NumericVector< Number > &XL, NumericVector< Number > &XU, sys_type &S) [inherited]
Function that computes the lower and upper bounds XL and XU on the solution of the nonlinear system.
Definition at line 176 of file nonlinear_solver.h.
template<typename T> NonlinearImplicitSystem::ComputeBounds* libMesh::NonlinearSolver< T >::bounds_object [inherited]
Object that computes the bounds vectors $ XL $ and $ XU $.
Definition at line 182 of file nonlinear_solver.h.
template<typename T> bool libMesh::NonlinearSolver< T >::converged [inherited]
After a call to solve this will reflect whether or not the nonlinear solve was successful.
Definition at line 290 of file nonlinear_solver.h.
template<typename T> Real libMesh::NonlinearSolver< T >::initial_linear_tolerance [inherited]
Any required linear solves will at first be done with this tolerance; the NonlinearSolver may tighten the tolerance for later solves.
Definition at line 279 of file nonlinear_solver.h.
template<typename T> void(* libMesh::NonlinearSolver< T >::jacobian)(const NumericVector< Number > &X, SparseMatrix< Number > &J, sys_type &S) [inherited]
Function that computes the Jacobian J(X) of the nonlinear system at the input iterate X.
Definition at line 144 of file nonlinear_solver.h.
Referenced by libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner().
template<typename T> NonlinearImplicitSystem::ComputeJacobian* libMesh::NonlinearSolver< T >::jacobian_object [inherited]
Object that computes the Jacobian J(X) of the nonlinear system at the input iterate X.
Definition at line 152 of file nonlinear_solver.h.
Referenced by libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner().
template<typename T> void(* libMesh::NonlinearSolver< T >::matvec)(const NumericVector< Number > &X, NumericVector< Number > *R, SparseMatrix< Number > *J, sys_type &S) [inherited]
Function that computes either the residual $ R(X) $ or the Jacobian $ J(X) $ of the nonlinear system at the input iterate $ X $. Note that either R or J could be XSNULL.
Definition at line 160 of file nonlinear_solver.h.
Referenced by libMesh::__libmesh_petsc_snes_residual(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner().
template<typename T> unsigned int libMesh::NonlinearSolver< T >::max_function_evaluations [inherited]
Maximum number of function evaluations.
Definition at line 240 of file nonlinear_solver.h.
template<typename T> unsigned int libMesh::NonlinearSolver< T >::max_linear_iterations [inherited]
Each linear solver step should exit after max_linear_iterations is exceeded.
Definition at line 273 of file nonlinear_solver.h.
template<typename T> unsigned int libMesh::NonlinearSolver< T >::max_nonlinear_iterations [inherited]
Maximum number of non-linear iterations.
Definition at line 235 of file nonlinear_solver.h.
template<typename T> Real libMesh::NonlinearSolver< T >::minimum_linear_tolerance [inherited]
The tolerance for linear solves is kept above this minimum
Definition at line 284 of file nonlinear_solver.h.
template<typename T> void(* libMesh::NonlinearSolver< T >::nearnullspace)(std::vector< NumericVector< Number > * > &sp, sys_type &S) [inherited]
Function that computes a basis for the Jacobian's near nullspace -- the set of 'low energy modes' -- that can be used for AMG coarsening, if the solver supports it (e.g., ML, PETSc's GAMG).
Definition at line 205 of file nonlinear_solver.h.
template<typename T> NonlinearImplicitSystem::ComputeVectorSubspace* libMesh::NonlinearSolver< T >::nearnullspace_object [inherited]
A callable object that computes a basis for the Jacobian's near nullspace -- the set of 'low energy modes' -- that can be used for AMG coarsening, if the solver supports it (e.g., ML, PETSc's GAMG).
Definition at line 212 of file nonlinear_solver.h.
template<typename T> void(* libMesh::NonlinearSolver< T >::nullspace)(std::vector< NumericVector< Number > * > &sp, sys_type &S) [inherited]
Function that computes a basis for the Jacobian's nullspace -- the kernel or the 'zero energy modes' -- that can be used in solving a degenerate problem iteratively, if the solver supports it (e.g., PETSc's KSP).
Definition at line 190 of file nonlinear_solver.h.
template<typename T> NonlinearImplicitSystem::ComputeVectorSubspace* libMesh::NonlinearSolver< T >::nullspace_object [inherited]
A callable object that computes a basis for the Jacobian's nullspace -- the kernel or the 'zero energy modes' -- that can be used in solving a degenerate problem iteratively, if the solver supports it (e.g., PETSc's KSP).
Definition at line 198 of file nonlinear_solver.h.
template<typename T> Real libMesh::NonlinearSolver< T >::relative_residual_tolerance [inherited]
Definition at line 253 of file nonlinear_solver.h.
template<typename T> Real libMesh::NonlinearSolver< T >::relative_step_tolerance [inherited]
Definition at line 267 of file nonlinear_solver.h.
template<typename T> void(* libMesh::NonlinearSolver< T >::residual)(const NumericVector< Number > &X, NumericVector< Number > &R, sys_type &S) [inherited]
Function that computes the residual R(X) of the nonlinear system at the input iterate X.
Definition at line 130 of file nonlinear_solver.h.
Referenced by libMesh::__libmesh_petsc_snes_residual(), and libMesh::Problem_Interface::computeF().
template<typename T> NonlinearImplicitSystem::ComputeResidualandJacobian* libMesh::NonlinearSolver< T >::residual_and_jacobian_object [inherited]
Object that computes either the residual $ R(X) $ or the Jacobian $ J(X) $ of the nonlinear system at the input iterate $ X $. Note that either R or J could be XSNULL.
Definition at line 171 of file nonlinear_solver.h.
Referenced by libMesh::__libmesh_petsc_snes_residual(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner().
template<typename T> NonlinearImplicitSystem::ComputeResidual* libMesh::NonlinearSolver< T >::residual_object [inherited]
Object that computes the residual R(X) of the nonlinear system at the input iterate X.
Definition at line 138 of file nonlinear_solver.h.
Referenced by libMesh::__libmesh_petsc_snes_residual(), and libMesh::Problem_Interface::computeF().
template<typename T> void(* libMesh::NonlinearSolver< T >::user_presolve)(sys_type &S) [inherited]
Definition at line 215 of file nonlinear_solver.h.
Author
Generated automatically by Doxygen for libMesh from the source code.