.TH "libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nonlinear_implicit_system\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ComputeResidualandJacobian\fP ()"
.br
.ti -1c
.RI "virtual void \fBresidual_and_jacobian\fP (const \fBNumericVector\fP< \fBNumber\fP > &X, \fBNumericVector\fP< \fBNumber\fP > *R, \fBSparseMatrix\fP< \fBNumber\fP > *J, \fBsys_type\fP &S)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class to be used to calculate the residual and Jacobian simultaneously of a nonlinear system\&. 
.PP
Definition at line 157 of file nonlinear_implicit_system\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian::~ComputeResidualandJacobian ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 160 of file nonlinear_implicit_system\&.h\&.
.PP
.nf
160 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian::residual_and_jacobian (const \fBNumericVector\fP< \fBNumber\fP > &X, \fBNumericVector\fP< \fBNumber\fP > *R, \fBSparseMatrix\fP< \fBNumber\fP > *J, \fBsys_type\fP &S)\fC [pure virtual]\fP"
Residual & Jacobian function, calculated simultaneously\&. This function will be called to compute the residual and jacobian simultaneously and must be implemented by the user in a derived class\&. 
.PP
Referenced by libMesh::__libmesh_petsc_snes_residual(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
