.TH "libMesh::System::Assembly" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::System::Assembly \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <system\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Assembly\fP ()"
.br
.ti -1c
.RI "virtual void \fBassemble\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class to be used for sysem assembly\&. A user class derived from this class may be used to assemble the system by attaching an object with the method \fCattach_assemble_object\fP\&. 
.PP
Definition at line 122 of file system\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual libMesh::System::Assembly::~Assembly ()\fC [inline]\fP, \fC [virtual]\fP"
Destructor\&. Virtual because we will have virtual functions\&. 
.PP
Definition at line 128 of file system\&.h\&.
.PP
.nf
128 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void libMesh::System::Assembly::assemble ()\fC [pure virtual]\fP"
\fBAssembly\fP function\&. This function will be called to assemble the system prior to a solve and must be provided by the user in a derived class\&. 
.PP
Referenced by libMesh::System::user_assembly()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
