.TH "libMesh::Linear< T >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Linear< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linear\&.h>\fP
.PP
Inherits T\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLinear\fP (\fBEquationSystems\fP &es)"
.br
.ti -1c
.RI "\fBLinear\fP (\fBEquationSystems\fP &es, const std::string &name, const unsigned int number)"
.br
.ti -1c
.RI "\fB~Linear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T = Solver>class libMesh::Linear< T >"
This is a generic class that defines a linear to be used in a simulation\&. A user can define a linear by deriving from this class and implementing certain functions\&.
.PP
\fBAuthor:\fP
.RS 4
Benjamin S\&. Kirk, 2003-2004\&. 
.RE
.PP

.PP
Definition at line 45 of file linear\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBlibMesh::Linear\fP< T >::\fBLinear\fP (\fBEquationSystems\fP &es)\fC [inline]\fP, \fC [explicit]\fP"
Constructor\&. Requires a reference to a system to be solved\&. 
.PP
Definition at line 74 of file linear\&.h\&.
.PP
.nf
74                                      :
75   T (es)
76 {
77   libmesh_deprecated();
78 }
.fi
.SS "template<class T > \fBlibMesh::Linear\fP< T >::\fBLinear\fP (\fBEquationSystems\fP &es, const std::string &name, const unsigned intnumber)\fC [inline]\fP"
Constructor\&. Requires a referece to the \fC\fBEquationSystems\fP\fP object\&. 
.PP
Definition at line 84 of file linear\&.h\&.
.PP
.nf
86                                               :
87   T (es, name, number)
88 {
89   libmesh_deprecated();
90 }
.fi
.SS "template<class T > \fBlibMesh::Linear\fP< T >::~\fBLinear\fP ()\fC [inline]\fP"
Destructor\&. 
.PP
Definition at line 96 of file linear\&.h\&.
.PP
.nf
97 {
98 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
