libMesh::MeshTools::Private
NAME
libMesh::MeshTools::Private -
SYNOPSIS
Functions
void globally_renumber_nodes_and_elements (MeshBase &)
Function Documentation
void libMesh::MeshTools::Private::globally_renumber_nodes_and_elements (MeshBase &mesh)
There is no reason for a user to ever call this function.
This function determines partition-agnostic global indices for all nodes and elements in the mesh. Note that after this function is called the mesh will likely be in an inconsistent state, i.e. mesh.nodes(i)->id() != i in the nodes container. Direct node/element access via the mesh.node(n) or mesh.elem(e) functions will likely fail. The original numbering can (and should) be restored with a subsequent call to fix_node_and_element_numbering().
Definition at line 1448 of file mesh_tools.C.
References libMesh::MeshCommunication::assign_global_indices().
Referenced by libMesh::EquationSystems::_read_impl(), and libMesh::EquationSystems::write().
{
  MeshCommunication().assign_global_indices(mesh);
}
Author
Generated automatically by Doxygen for libMesh from the source code.