.TH "libMesh::HPSelector" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::HPSelector \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hp_selector\&.h>\fP
.PP
Inherited by \fBlibMesh::HPCoarsenTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHPSelector\fP ()"
.br
.ti -1c
.RI "virtual \fB~HPSelector\fP ()"
.br
.ti -1c
.RI "virtual void \fBselect_refinement\fP (\fBSystem\fP &system)=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< float > \fBcomponent_scale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Subclasses of this abstract base class choose between h refining and p elevation\&. Currently we assume that a set of elements has already been flagged for h refinement, and we may want to change some of those elements to be flagged for p refinement\&.
.PP
\fBAuthor:\fP
.RS 4
Roy H\&. Stogner, 2006\&. 
.RE
.PP

.PP
Definition at line 47 of file hp_selector\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "libMesh::HPSelector::HPSelector ()\fC [inline]\fP"
Constructor\&. 
.PP
Definition at line 54 of file hp_selector\&.h\&.
.PP
.nf
54 {}
.fi
.SS "virtual libMesh::HPSelector::~HPSelector ()\fC [inline]\fP, \fC [virtual]\fP"
Destructor\&. 
.PP
Definition at line 59 of file hp_selector\&.h\&.
.PP
.nf
59 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void libMesh::HPSelector::select_refinement (\fBSystem\fP &system)\fC [pure virtual]\fP"
This pure virtual function must be redefined in derived classes to take a mesh flagged for h refinement and potentially change the desired refinement type\&. 
.PP
Implemented in \fBlibMesh::HPCoarsenTest\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<float> libMesh::HPSelector::component_scale"
This vector can be used to 'scale' certain variables in a system\&. If the mask is not empty, the consideration given to each component's h and p error estimates will be scaled by component_scale[c]\&. 
.PP
Definition at line 77 of file hp_selector\&.h\&.
.PP
Referenced by libMesh::HPCoarsenTest::select_refinement()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
