libMesh::ExodusII_IO_Helper::Conversion
NAME
libMesh::ExodusII_IO_Helper::Conversion -
SYNOPSIS
#include <exodusII_io_helper.h>
Public Member Functions
Conversion (const int *nm, size_t nm_size, const int *inm, size_t inm_size, const int *sm, size_t sm_size, const int *ism, size_t ism_size, const ElemType ct, std::string ex_type)
int get_node_map (int i) const
int get_inverse_node_map (int i) const
int get_side_map (int i) const
int get_inverse_side_map (int i) const
ElemType get_canonical_type () const
std::string exodus_elem_type () const
Private Attributes
const int * node_map
size_t node_map_size
const int * inverse_node_map
size_t inverse_node_map_size
const int * side_map
size_t side_map_size
const int * inverse_side_map
size_t inverse_side_map_size
const ElemType canonical_type
const std::string exodus_type
Detailed Description
Definition at line 593 of file exodusII_io_helper.h.
Constructor & Destructor Documentation
libMesh::ExodusII_IO_Helper::Conversion::Conversion (const int *nm, size_tnm_size, const int *inm, size_tinm_size, const int *sm, size_tsm_size, const int *ism, size_tism_size, const ElemTypect, std::stringex_type) [inline]
Constructor. Initializes the const private member variables.
Definition at line 601 of file exodusII_io_helper.h.
    : node_map(nm),
      node_map_size(nm_size),
      inverse_node_map(inm),
      inverse_node_map_size(inm_size),
      side_map(sm),
      side_map_size(sm_size),
      inverse_side_map(ism),
      inverse_side_map_size(ism_size),
      canonical_type(ct),
      exodus_type(ex_type)
  {}
Member Function Documentation
std::string libMesh::ExodusII_IO_Helper::Conversion::exodus_elem_type () const [inline]
Returns the string corresponding to the Exodus type for this element
Definition at line 678 of file exodusII_io_helper.h.
References exodus_type.
Referenced by libMesh::ExodusII_IO_Helper::write_elements(), and libMesh::Nemesis_IO_Helper::write_elements().
{ return exodus_type; }
ElemType libMesh::ExodusII_IO_Helper::Conversion::get_canonical_type () const [inline]
Returns the canonical element type for this element. The canonical element type is the standard element type understood by this library.
Definition at line 673 of file exodusII_io_helper.h.
References canonical_type.
Referenced by libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), libMesh::Nemesis_IO::read(), and libMesh::ExodusII_IO_Helper::write_elements().
{ return canonical_type; }
int libMesh::ExodusII_IO_Helper::Conversion::get_inverse_node_map (inti) const [inline]
Returns the ith component of the inverse node map for this element. The inverse node map maps the libmesh node numbering to Exodus' node numbering. Note that all elements except Hex27 currently have the same node numbering as libmesh elements.
Definition at line 640 of file exodusII_io_helper.h.
References inverse_node_map, and inverse_node_map_size.
Referenced by libMesh::ExodusII_IO_Helper::write_elements().
  {
    libmesh_assert_less (static_cast<size_t>(i), inverse_node_map_size);
    return inverse_node_map[i];
  }
int libMesh::ExodusII_IO_Helper::Conversion::get_inverse_side_map (inti) const [inline]
Returns the ith component of the side map for this element. The side map maps the libMesh side numbering format to this exodus's format.
Definition at line 662 of file exodusII_io_helper.h.
References inverse_side_map, and inverse_side_map_size.
Referenced by libMesh::Nemesis_IO_Helper::compute_internal_and_border_elems_and_internal_nodes(), libMesh::ExodusII_IO_Helper::write_sidesets(), and libMesh::Nemesis_IO_Helper::write_sidesets().
  {
    libmesh_assert_less (static_cast<size_t>(i), inverse_side_map_size);
    return inverse_side_map[i];
  }
int libMesh::ExodusII_IO_Helper::Conversion::get_node_map (inti) const [inline]
Returns the ith component of the node map for this element. The node map maps the exodusII node numbering format to this library's format.
Definition at line 628 of file exodusII_io_helper.h.
References node_map, and node_map_size.
Referenced by libMesh::Nemesis_IO_Helper::build_element_and_node_maps(), and libMesh::Nemesis_IO::read().
  {
    libmesh_assert_less (static_cast<size_t>(i), node_map_size);
    return node_map[i];
  }
int libMesh::ExodusII_IO_Helper::Conversion::get_side_map (inti) const [inline]
Returns the ith component of the side map for this element. The side map maps the exodusII side numbering format to this library's format.
Definition at line 651 of file exodusII_io_helper.h.
References side_map, and side_map_size.
Referenced by libMesh::Nemesis_IO::read(), and libMesh::ExodusII_IO::read().
  {
    libmesh_assert_less (static_cast<size_t>(i), side_map_size);
    return side_map[i];
  }
Member Data Documentation
const ElemType libMesh::ExodusII_IO_Helper::Conversion::canonical_type [private]
The canonical (i.e. standard for this library) element type.
Definition at line 728 of file exodusII_io_helper.h.
Referenced by get_canonical_type().
const std::string libMesh::ExodusII_IO_Helper::Conversion::exodus_type [private]
The string corresponding to the Exodus type for this element
Definition at line 733 of file exodusII_io_helper.h.
Referenced by exodus_elem_type().
const int* libMesh::ExodusII_IO_Helper::Conversion::inverse_node_map [private]
Pointer to the inverse node map for this element. For all elements except for the Hex27, this is the same as the node map.
Definition at line 697 of file exodusII_io_helper.h.
Referenced by get_inverse_node_map().
size_t libMesh::ExodusII_IO_Helper::Conversion::inverse_node_map_size [private]
The size of the inverse node map array, this helps with bounds checking...
Definition at line 702 of file exodusII_io_helper.h.
Referenced by get_inverse_node_map().
const int* libMesh::ExodusII_IO_Helper::Conversion::inverse_side_map [private]
Pointer to the inverse side map for this element.
Definition at line 717 of file exodusII_io_helper.h.
Referenced by get_inverse_side_map().
size_t libMesh::ExodusII_IO_Helper::Conversion::inverse_side_map_size [private]
The size of the inverse side map array, this helps with bounds checking...
Definition at line 722 of file exodusII_io_helper.h.
Referenced by get_inverse_side_map().
const int* libMesh::ExodusII_IO_Helper::Conversion::node_map [private]
Pointer to the node map for this element.
Definition at line 685 of file exodusII_io_helper.h.
Referenced by get_node_map().
size_t libMesh::ExodusII_IO_Helper::Conversion::node_map_size [private]
The size of the node map array, this helps with bounds checking...
Definition at line 690 of file exodusII_io_helper.h.
Referenced by get_node_map().
const int* libMesh::ExodusII_IO_Helper::Conversion::side_map [private]
Pointer to the side map for this element.
Definition at line 707 of file exodusII_io_helper.h.
Referenced by get_side_map().
size_t libMesh::ExodusII_IO_Helper::Conversion::side_map_size [private]
The size of the side map array, this helps with bounds checking...
Definition at line 712 of file exodusII_io_helper.h.
Referenced by get_side_map().
Author
Generated automatically by Doxygen for libMesh from the source code.