.TH "libMesh::Parallel::BufferType< Elem >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Parallel::BufferType< Elem > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parallel_elem\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBlargest_id_type\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>struct libMesh::Parallel::BufferType< Elem >"

.PP
Definition at line 39 of file parallel_elem\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBlargest_id_type\fP \fBlibMesh::Parallel::BufferType\fP< \fBElem\fP >::\fBtype\fP"

.PP
Definition at line 40 of file parallel_elem\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
