libMesh::XdrMGF
NAME
libMesh::XdrMGF -
SYNOPSIS
#include <xdr_mgf.h>
Inherited by libMesh::XdrMESH, and libMesh::XdrSOLN.
Public Types
enum XdrIO_TYPE { UNKNOWN = -1, ENCODE =0, DECODE, W_ASCII, R_ASCII }
Public Member Functions
XdrMGF ()
XdrMGF ()
void init (XdrIO_TYPE t, const char *fn, const char *type, int icnt)
virtual ~XdrMGF ()
void fini ()
int dataBlk (int *array, int numvar, int size)
int dataBlk (Real *array, int numvar, int size)
LegacyXdrIO::FileFormat get_orig_flag () const
void set_orig_flag (LegacyXdrIO::FileFormat in_orig_flag)
void set_num_levels (unsigned int num_levels)
unsigned int get_num_levels ()
Protected Attributes
unsigned int _num_levels
XdrIO_TYPE m_type
XDR * mp_xdr_handle
LegacyXdrIO::FileFormat orig_flag
std::ifstream mp_in
std::ofstream mp_out
Private Member Functions
void tokenize_first_line (const char *p)
Private Attributes
std::FILE * mp_fp
Detailed Description
This class is taken directly from MGF. It facilitates reading and writing binary solution/mesh files using the xdr binary format, which allows for portable binary files across various platforms. For more information on the xdr format, see the standard C include file rpc/rpc.h.
Author:
Bill Barth, Robert McLay.
There are essentially two inheritance trees and six classes: XdrMGF XdrHEAD ^ ^ ^ ^ | | | | XdrMESH XdrSOLN XdrMHEAD XdrSHEAD
XdrHEAD, XdrMHEAD, and XdrSHEAD just read the headers of solution and mesh files.
XdrMGF, XdrMESH, and XdrSOLN handle the 'meat' of the files: everything other than the headers.
Definition at line 85 of file xdr_mgf.h.
Member Enumeration Documentation
enum libMesh::XdrMGF::XdrIO_TYPE
This enum specifies the access permission which will be acquired for the current xdr file. Note that it is only possible to read (DECODE) or write (ENCODE) but not both. For ASCII type files, use WRITE or READ instead!
Enumerator
UNKNOWN
ENCODE
DECODE
W_ASCII
R_ASCII
Definition at line 98 of file xdr_mgf.h.
                  {UNKNOWN = -1, ENCODE=0, DECODE,
                   W_ASCII , R_ASCII};
Constructor & Destructor Documentation
libMesh::XdrMGF::XdrMGF () [inline]
Constructor. Intializes the access type, xdr file handle, xdr file pointer, and originator flag. Zero is a good default value for the flag, since that is the DEAL identifier. The xdr file handle is a struct defined in the standard C header rpc/rpc.h.
Definition at line 115 of file xdr_mgf.h.
: _num_levels(0), m_type(UNKNOWN), mp_xdr_handle(0), orig_flag(LegacyXdrIO::LIBM), mp_fp(0) {}
libMesh::XdrMGF::XdrMGF () [inline]
Definition at line 117 of file xdr_mgf.h.
: _num_levels(0), m_type(UNKNOWN), orig_flag(LegacyXdrIO::LIBM), mp_fp(0) {}
libMesh::XdrMGF::~XdrMGF () [virtual]
Destructor. Frees the memory which was allocated to contain several strings.
Definition at line 28 of file xdr_mgf.C.
References fini().
{
  this->fini();
}
Member Function Documentation
int libMesh::XdrMGF::dataBlk (int *array, intnumvar, intsize)
Reads/Writes a block of ints to/from the current xdr file/file handle.
Parameters:
array Pointer to data to be read/written
numvar The total number of variables (size of the array)
size The size of each individual variable in the array
Definition at line 278 of file xdr_mgf.C.
References DECODE, ENCODE, libMesh::libmesh_assert(), m_type, mp_in, mp_out, mp_xdr_handle, R_ASCII, and W_ASCII.
Referenced by libMesh::XdrMESH::BC(), libMesh::XdrMESH::coord(), libMesh::XdrMESH::Icon(), and libMesh::XdrSOLN::values().
{
  int totalSize = numvar*size;
  switch (m_type)
    {
#ifdef LIBMESH_HAVE_XDR
    case (XdrMGF::DECODE):
    case (XdrMGF::ENCODE):
      {
        xdr_vector(mp_xdr_handle,
                   (char *) &array[0],
                   totalSize,
                   sizeof(int),
                   (xdrproc_t) xdr_int);
        break;
      }
#endif
    case (XdrMGF::W_ASCII):
      {
        for (int i=0; i<size; i++)
          {
            for (int j=0; j<numvar; j++)
              mp_out << array[i*numvar + j] << " ";
            mp_out << '\n';
          }
        mp_out.flush();
        break;
      }
    case (XdrMGF::R_ASCII):
      {
        libmesh_assert (mp_in.good());
        for (int i=0; i<size; i++)
          {
            for (int j=0; j<numvar; j++)
              {
                mp_in >> array[i*numvar + j];
              }
            mp_in.ignore(); // Read newline
          }
        break;
      }
    default:
      // Unknown access type
      libmesh_error();
    }
  return totalSize;
}
int libMesh::XdrMGF::dataBlk (Real *array, intnumvar, intsize)
Read/Writes a block of Reals to/from the current xdr file/file handle.
Definition at line 341 of file xdr_mgf.C.
References DECODE, ENCODE, libMesh::libmesh_assert(), m_type, mp_in, mp_out, mp_xdr_handle, R_ASCII, libMesh::Real, and W_ASCII.
{
  int totalSize = numvar*size;
  // If this function is called by coord(),
  // numvar is the problem dimension, and
  // size is the number of nodes in the problem.
  //libMesh::out << "Total amount of data to be written: " << totalSize << std::endl;
  switch (m_type)
    {
#ifdef LIBMESH_HAVE_XDR
    case (XdrMGF::DECODE):
    case (XdrMGF::ENCODE):
      {
        // FIXME - this is probably broken for Real == long double
        // RHS
        xdr_vector(mp_xdr_handle,
                   (char *) &array[0],
                   totalSize,
                   sizeof(Real),
                   (xdrproc_t) xdr_REAL);
      }
#endif
    case (XdrMGF::W_ASCII):
      {
        // Save stream flags
        std::ios_base::fmtflags out_flags = mp_out.flags();
        // We will use scientific notation with a precision of 16
        // digits in the following output. The desired precision and
        // format will automatically determine the width.
        mp_out << std::scientific
               << std::setprecision(16);
        for (int i=0; i<size; i++)
          {
            for (int j=0; j<numvar; j++)
              mp_out << array[i*numvar + j] << " \t";
            mp_out << '\n';
          }
        // Restore stream flags
        mp_out.flags(out_flags);
        mp_out.flush();
        break;
      }
    case (XdrMGF::R_ASCII):
      {
        libmesh_assert (mp_in.good());
        for (int i=0; i<size; i++)
          {
            libmesh_assert (mp_in.good());
            for (int j=0; j<numvar; j++)
              mp_in >> array[i*numvar + j];
            mp_in.ignore(); // Read newline
          }
        break;
      }
    default:
      // Unknown access type
      libmesh_error();
    }
  return totalSize;
}
void libMesh::XdrMGF::fini ()
Finalizes operations on the current xdr file handle, and closes the xdr file.
Uses xdr_destroy found in rpc/rpc.h.
Definition at line 35 of file xdr_mgf.C.
References mp_fp, and mp_xdr_handle.
Referenced by init(), and ~XdrMGF().
{
#ifdef LIBMESH_HAVE_XDR
  if (mp_xdr_handle)
    {
      //libMesh::out << "Destroying XDR file handle." << std::endl;
      xdr_destroy(mp_xdr_handle);
    }
  //libMesh::out << "Deleting the file handle pointer." << std::endl;
  delete mp_xdr_handle;
  mp_xdr_handle = NULL;
#endif
  if (mp_fp)
    {
      //libMesh::out << "Closing file." << std::endl;
      std::fflush(mp_fp);
      std::fclose(mp_fp);
    }
  mp_fp = NULL;
}
unsigned int libMesh::XdrMGF::get_num_levels () [inline]
Get number of levels
Definition at line 190 of file xdr_mgf.h.
References _num_levels.
Referenced by libMesh::XdrMESH::header(), init(), and libMesh::LegacyXdrIO::read_mesh().
{ return _num_levels; }
LegacyXdrIO::FileFormat libMesh::XdrMGF::get_orig_flag () const [inline]
Get the originator flag.
Definition at line 174 of file xdr_mgf.h.
References orig_flag.
Referenced by init(), libMesh::LegacyXdrIO::read_mesh(), and libMesh::LegacyXdrIO::write_mesh().
{ return orig_flag; }
void libMesh::XdrMGF::init (XdrMGF::XdrIO_TYPEt, const char *fn, const char *type, inticnt)
Initialization of the xdr file. This function performs the following operations: {itemize} Closes the old xdr file if necessary.
Creates a new xdr file name and opens this file.
Opens the appropriate xdr file handle.
Reads/Writes a signature to the file.
{itemize}
Definition at line 68 of file xdr_mgf.C.
References libMesh::LegacyXdrIO::DEAL, DECODE, ENCODE, libMesh::err, fini(), get_num_levels(), get_orig_flag(), libMesh::LegacyXdrIO::LIBM, m_type, libMesh::LegacyXdrIO::MGF, mp_fp, mp_in, mp_out, mp_xdr_handle, libMesh::Quality::name(), orig_flag, libMesh::out, R_ASCII, tokenize_first_line(), and W_ASCII.
Referenced by libMesh::XdrSOLN::init(), and libMesh::XdrMESH::init().
{
  m_type=t;
  // Close old file if necessary
  if (mp_fp) this->fini();
  // Open file
  switch (m_type)
    {
#ifdef LIBMESH_HAVE_XDR
    case (XdrMGF::ENCODE):
    case (XdrMGF::DECODE):
      {
        mp_fp = fopen (fn, (m_type == ENCODE) ? "w" : "r");
        // Make sure the file is ready for use
        if (!mp_fp)
          {
            libMesh::err << "XDR Error: Accessing file: "
                         << fn
                         << " failed."
                         << std::endl;
            libmesh_error();
          }
        // Create the XDR handle
        mp_xdr_handle = new XDR;
        xdrstdio_create(mp_xdr_handle,
                        mp_fp,
                        ((m_type == ENCODE) ? XDR_ENCODE : XDR_DECODE));
        break;
      }
#endif
    case (XdrMGF::R_ASCII):
      {
        mp_in.open(fn, std::ios::in);
        // Make sure it opened correctly
        if (!mp_in.good())
          libmesh_file_error(fn);
        break;
      }
    case (XdrMGF::W_ASCII):
      {
        mp_out.open(fn, std::ios::out);
        // Make sure it opened correctly
        if (!mp_out.good())
          libmesh_file_error(fn);
        break;
      }
    default:
      {
        libMesh::out << "Unrecognized file access type!" << std::endl;
        libmesh_error();
      }
    }
  // Read/Write the file signature
  const int bufLen = 12;
  char buf[bufLen+1];
  switch (m_type)
    {
#ifdef LIBMESH_HAVE_XDR
    case (XdrMGF::ENCODE):
      {
        char* p = &buf[0];
        const LegacyXdrIO::FileFormat orig = this->get_orig_flag();
        std::ostringstream name;
        if (orig == LegacyXdrIO::DEAL)
          name << "DEAL 003:003";
        else if (orig == LegacyXdrIO::MGF)
          name << "MGF 002:000";
        else if (orig == LegacyXdrIO::LIBM)
          name << "LIBM " << this->get_num_levels();
        else
          libmesh_error();
        // Fill the buffer
        std::sprintf(&buf[0], "%s", name.str().c_str());
        xdr_string(mp_xdr_handle, &p, bufLen); // Writes binary signature
        break;
      }
    case (XdrMGF::DECODE):
      {
        char* p = &buf[0];
        xdr_string(mp_xdr_handle, &p, bufLen); // Reads binary signature
        // Set the number of levels used in the mesh
        this->tokenize_first_line(p);
        break;
      }
#endif
    case (XdrMGF::W_ASCII):
      {
        const LegacyXdrIO::FileFormat orig = this->get_orig_flag();
        if (orig == LegacyXdrIO::DEAL)
          std::sprintf(&buf[0], "%s %03d:%03d", "DEAL", 3, 3);
        else if (orig == LegacyXdrIO::MGF)
          std::sprintf(&buf[0], "%s %03d:%03d", "MGF ", 2, 0);
        else if (orig == LegacyXdrIO::LIBM)
          std::sprintf(&buf[0], "%s %d", "LIBM", this->get_num_levels());
        mp_out << buf << '\n';
        break;
      }
    case (XdrMGF::R_ASCII):
      {
#ifdef __HP_aCC
        // weirdly, _only_ here aCC
        // is not fond of mp_in.getline()
        // however, using mp_in.getline()
        // further below is ok...
        std::string buf_buf;
        std::getline (mp_in, buf_buf, '\n');
        libmesh_assert_less_equal (buf_buf.size(), bufLen);
        buf_buf.copy (buf, std::string::npos);
#else
        // Here we first use getline() to grab the very
        // first line of the file into a char buffer. Then
        // this line is tokenized to look for:
        // 1.) The name LIBM, which specifies the new Mesh style.
        // 2.) The number of levels in the Mesh which is being read.
        // Note that "buf" will be further processed below, here we
        // are just attempting to get the number of levels.
        mp_in.getline(buf, bufLen+1);
#endif
        // Determine the number of levels in this mesh
        this->tokenize_first_line(buf);
        break;
      }
    default:
      libmesh_error();
    }
  // If you are reading or decoding, process the signature
  if ((m_type == R_ASCII) || (m_type == DECODE))
    {
      char name[5];
      std::strncpy(name, &buf[0], 4);
      name[4] = '\0';
      if (std::strcmp (name, "DEAL") == 0)
        {
          this->orig_flag = LegacyXdrIO::DEAL; // 0 is the DEAL identifier by definition
        }
      else if (std::strcmp (name, "MGF ") == 0)
        {
          this->orig_flag = LegacyXdrIO::MGF; // 1 is the MGF identifier by definition
        }
      else if (std::strcmp (name, "LIBM") == 0)
        {
          this->orig_flag = LegacyXdrIO::LIBM; // the New and Improved XDA
        }
      else
        {
          libMesh::err <<
            "No originating software can be determined for header string '" <<
            name << "'. Error." << std::endl;
          libmesh_error();
        }
    }
}
void libMesh::XdrMGF::set_num_levels (unsigned intnum_levels) [inline]
Set number of levels
Definition at line 185 of file xdr_mgf.h.
References _num_levels.
Referenced by libMesh::LegacyXdrIO::write_mesh().
{ _num_levels = num_levels; }
void libMesh::XdrMGF::set_orig_flag (LegacyXdrIO::FileFormatin_orig_flag) [inline]
Set the originator flag.
Definition at line 179 of file xdr_mgf.h.
References orig_flag.
Referenced by libMesh::LegacyXdrIO::read_mesh(), and libMesh::LegacyXdrIO::write_mesh().
{ orig_flag = in_orig_flag; }
void libMesh::XdrMGF::tokenize_first_line (const char *p) [inline], [private]
This function allows us to set the number of levels in the mesh when reading.
Definition at line 258 of file xdr_mgf.h.
References _num_levels.
Referenced by init().
  {
    std::string buf_str(p);
    std::stringstream ss(buf_str);
    char token[256];
    ss >> token;
    if(std::strcmp(token,"LIBM") == 0)
      {
        ss >> token;
        _num_levels = std::atoi(token);
      }
  }
Member Data Documentation
unsigned int libMesh::XdrMGF::_num_levels [protected]
Number of levels of refinement in the mesh
Definition at line 197 of file xdr_mgf.h.
Referenced by get_num_levels(), set_num_levels(), and tokenize_first_line().
XdrIO_TYPE libMesh::XdrMGF::m_type [protected]
Specifies the read/write permission for the current xdr file. Possibilities are: {itemize} UNKNOWN = -1 ENCODE = 0 DECODE = 1 {itemize}
Definition at line 210 of file xdr_mgf.h.
Referenced by dataBlk(), libMesh::XdrSOLN::header(), libMesh::XdrMESH::header(), and init().
std::FILE* libMesh::XdrMGF::mp_fp [private]
Definition at line 252 of file xdr_mgf.h.
Referenced by fini(), and init().
std::ifstream libMesh::XdrMGF::mp_in [protected]
An input file stream object
Definition at line 244 of file xdr_mgf.h.
Referenced by dataBlk(), libMesh::XdrSOLN::header(), libMesh::XdrMESH::header(), and init().
std::ofstream libMesh::XdrMGF::mp_out [protected]
An output file stream object.
Definition at line 249 of file xdr_mgf.h.
Referenced by dataBlk(), libMesh::XdrSOLN::header(), libMesh::XdrMESH::header(), and init().
XDR* libMesh::XdrMGF::mp_xdr_handle [protected]
Pointer to the standard {xdr} struct. See the standard header file rpc/rpc.h for more information.
Definition at line 220 of file xdr_mgf.h.
Referenced by dataBlk(), fini(), libMesh::XdrSOLN::header(), libMesh::XdrMESH::header(), and init().
LegacyXdrIO::FileFormat libMesh::XdrMGF::orig_flag [protected]
Flag indicating how much checking we need to do. We can read in mgf meshes more quickly because there is only one type of element in these meshes. Deal meshes on the other hand will require a check for each element to find out what type it is. Possible values are: {itemize} 0: It's an DEAL style mesh 1: It's a MGF style mesh {itemize}
Definition at line 239 of file xdr_mgf.h.
Referenced by get_orig_flag(), libMesh::XdrMESH::header(), init(), and set_orig_flag().
Author
Generated automatically by Doxygen for libMesh from the source code.