.TH "libMesh::NonlinearImplicitSystem::ComputeJacobian" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::NonlinearImplicitSystem::ComputeJacobian \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nonlinear_implicit_system\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ComputeJacobian\fP ()"
.br
.ti -1c
.RI "virtual void \fBjacobian\fP (const \fBNumericVector\fP< \fBNumber\fP > &X, \fBSparseMatrix\fP< \fBNumber\fP > &J, \fBsys_type\fP &S)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class to be used to calculate the Jacobian of a nonlinear system\&. 
.PP
Definition at line 97 of file nonlinear_implicit_system\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual libMesh::NonlinearImplicitSystem::ComputeJacobian::~ComputeJacobian ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 100 of file nonlinear_implicit_system\&.h\&.
.PP
.nf
100 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void libMesh::NonlinearImplicitSystem::ComputeJacobian::jacobian (const \fBNumericVector\fP< \fBNumber\fP > &X, \fBSparseMatrix\fP< \fBNumber\fP > &J, \fBsys_type\fP &S)\fC [pure virtual]\fP"
Jacobian function\&. This function will be called to compute the jacobian and must be implemented by the user in a derived class\&. 
.PP
Referenced by libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
