.TH "libMesh::Threads::split" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Threads::split \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <threads\&.h>\fP
.SH "Detailed Description"
.PP 
Dummy 'splitting object' used to distinguish splitting constructors from copy constructors\&. 
.PP
Definition at line 488 of file threads\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
