.TH "libmesh_base.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmesh_base.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.ti -1c
.RI "\fBlibMesh::libMeshPrivateData\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBprocessor_id_type\fP \fBlibMesh::n_processors\fP ()"
.br
.ti -1c
.RI "\fBprocessor_id_type\fP \fBlibMesh::processor_id\fP ()"
.br
.ti -1c
.RI "\fBprocessor_id_type\fP \fBlibMesh::global_n_processors\fP ()"
.br
.ti -1c
.RI "\fBprocessor_id_type\fP \fBlibMesh::global_processor_id\fP ()"
.br
.ti -1c
.RI "unsigned int \fBlibMesh::n_threads\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "processor_id_type \fBlibMesh::libMeshPrivateData::_n_processors\fP = 1"
.br
.ti -1c
.RI "processor_id_type \fBlibMesh::libMeshPrivateData::_processor_id\fP = 0"
.br
.ti -1c
.RI "int \fBlibMesh::libMeshPrivateData::_n_threads\fP = 1"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
