libMesh::Parallel::DataType
NAME
libMesh::Parallel::DataType -
SYNOPSIS
#include <parallel.h>
Inherited by libMesh::Parallel::StandardType< T >, libMesh::Parallel::StandardType< Hilbert::HilbertIndices >, libMesh::Parallel::StandardType< Point >, libMesh::Parallel::StandardType< std::complex< T > >, libMesh::Parallel::StandardType< std::pair< T1, T2 > >, libMesh::Parallel::StandardType< TensorValue< T > >, libMesh::Parallel::StandardType< TypeTensor< T > >, libMesh::Parallel::StandardType< TypeVector< T > >, and libMesh::Parallel::StandardType< VectorValue< T > >.
Public Member Functions
DataType ()
DataType (const DataType &other)
DataType (const data_type &type)
DataType (const DataType &other, unsigned int count)
DataType (const DataType &, unsigned int)
DataType & operator= (const DataType &other)
DataType & operator= (const data_type &type)
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
Encapsulates the MPI_Datatype.
Definition at line 234 of file parallel.h.
Constructor & Destructor Documentation
libMesh::Parallel::DataType::DataType () [inline]
Definition at line 237 of file parallel.h.
Referenced by libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType().
: _datatype() {}
libMesh::Parallel::DataType::DataType (const DataType &other) [inline]
Definition at line 239 of file parallel.h.
                                   :
    _datatype(other._datatype)
  {}
libMesh::Parallel::DataType::DataType (const data_type &type) [inline]
Definition at line 243 of file parallel.h.
                                   :
    _datatype(type)
  {}
libMesh::Parallel::DataType::DataType (const DataType &other, unsigned intcount) [inline]
Definition at line 248 of file parallel.h.
References _datatype, and commit().
  {
    MPI_Type_contiguous(count, other._datatype, &_datatype);
    this->commit();
  }
libMesh::Parallel::DataType::DataType (const DataType &, unsignedint) [inline]
Definition at line 254 of file parallel.h.
  {
  }
Member Function Documentation
void libMesh::Parallel::DataType::commit () [inline]
Definition at line 277 of file parallel.h.
References _datatype.
Referenced by DataType().
  {
#ifdef LIBMESH_HAVE_MPI
    MPI_Type_commit (&_datatype);
#endif
  }
void libMesh::Parallel::DataType::free () [inline]
Definition at line 284 of file parallel.h.
References _datatype.
Referenced by libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), libMesh::Parallel::StandardType< std::complex< T > >::~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
  {
#ifdef LIBMESH_HAVE_MPI
    MPI_Type_free (&_datatype);
#endif
  }
libMesh::Parallel::DataType::operator const data_type & () const [inline]
Definition at line 265 of file parallel.h.
References _datatype.
  { return _datatype; }
libMesh::Parallel::DataType::operator data_type & () [inline]
Definition at line 268 of file parallel.h.
References _datatype.
  { return _datatype; }
DataType& libMesh::Parallel::DataType::operator= (const DataType &other) [inline]
Definition at line 259 of file parallel.h.
References _datatype.
  { _datatype = other._datatype; return *this; }
DataType& libMesh::Parallel::DataType::operator= (const data_type &type) [inline]
Definition at line 262 of file parallel.h.
References _datatype.
  { _datatype = type; return *this; }
Member Data Documentation
data_type libMesh::Parallel::DataType::_datatype [protected]
Definition at line 293 of file parallel.h.
Referenced by commit(), DataType(), free(), operator const data_type &(), operator data_type &(), operator=(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), and libMesh::Parallel::StandardType< Point >::StandardType().
Author
Generated automatically by Doxygen for libMesh from the source code.