libMesh::RBAssemblyExpansion
NAME
libMesh::RBAssemblyExpansion -
SYNOPSIS
#include <rb_assembly_expansion.h>
Inherits libMesh::ReferenceCountedObject< RBAssemblyExpansion >.
Inherited by libMesh::TransientRBAssemblyExpansion.
Public Member Functions
RBAssemblyExpansion ()
virtual ~RBAssemblyExpansion ()
void perform_A_interior_assembly (unsigned int q, FEMContext &context)
void perform_A_boundary_assembly (unsigned int q, FEMContext &context)
void perform_F_interior_assembly (unsigned int q, FEMContext &context)
void perform_F_boundary_assembly (unsigned int q, FEMContext &context)
void perform_output_interior_assembly (unsigned int output_index, unsigned int q_l, FEMContext &context)
void perform_output_boundary_assembly (unsigned int output_index, unsigned int q_l, FEMContext &context)
unsigned int get_n_A_terms () const
unsigned int get_n_F_terms () const
unsigned int get_n_outputs () const
unsigned int get_n_output_terms (unsigned int output_index) const
void attach_A_assembly (ElemAssembly *Aq_assembly)
void attach_multiple_A_assembly (std::vector< ElemAssembly * > Aq_assembly)
void attach_F_assembly (ElemAssembly *Fq_assembly)
void attach_multiple_F_assembly (std::vector< ElemAssembly * > Fq_assembly)
virtual void attach_output_assembly (std::vector< ElemAssembly * > output_assembly)
virtual void attach_output_assembly (ElemAssembly *output_assembly)
ElemAssembly & get_A_assembly (unsigned int q)
ElemAssembly & get_F_assembly (unsigned int q)
ElemAssembly & get_output_assembly (unsigned int output_index, unsigned int q_l)
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts"
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects"
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
std::vector< ElemAssembly * > _A_assembly_vector
std::vector< ElemAssembly * > _F_assembly_vector
std::vector< std::vector
< ElemAssembly * > > _output_assembly_vector"
Detailed Description
This class stores the set of ElemAssembly functor objects that define the 'parameter-independent expansion' of a PDE.
Author:
David J. Knezevic, 2011
Definition at line 43 of file rb_assembly_expansion.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts [protected], [inherited]
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::RBAssemblyExpansion::RBAssemblyExpansion ()
Constructor.
virtual libMesh::RBAssemblyExpansion::~RBAssemblyExpansion () [inline], [virtual]
Destructor.
Definition at line 55 of file rb_assembly_expansion.h.
{}
Member Function Documentation
void libMesh::RBAssemblyExpansion::attach_A_assembly (ElemAssembly *Aq_assembly)
Attach ElemAssembly object for the left-hand side (both interior and boundary assembly).
void libMesh::RBAssemblyExpansion::attach_F_assembly (ElemAssembly *Fq_assembly)
Attach ElemAssembly object for the right-hand side (both interior and boundary assembly).
void libMesh::RBAssemblyExpansion::attach_multiple_A_assembly (std::vector< ElemAssembly * >Aq_assembly)
Attach multiple ElemAssembly objects for the left-hand side (both interior and boundary assembly).
void libMesh::RBAssemblyExpansion::attach_multiple_F_assembly (std::vector< ElemAssembly * >Fq_assembly)
Attach multiple ElemAssembly objects for the right-hand side (both interior and boundary assembly).
virtual void libMesh::RBAssemblyExpansion::attach_output_assembly (std::vector< ElemAssembly * >output_assembly) [virtual]
Attach ElemAssembly object for an output (both interior and boundary assembly). In this case we pass in vector arguments to allow for Q_l > 1.
virtual void libMesh::RBAssemblyExpansion::attach_output_assembly (ElemAssembly *output_assembly) [virtual]
Attach ElemAssembly object for an output (both interior and boundary assembly). This function provides simpler syntax in the case that Q_l = 1; we do not need to use a vector in this case.
void libMesh::ReferenceCounter::disable_print_counter_info () [static], [inherited]
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = false;
  return;
}
void libMesh::ReferenceCounter::enable_print_counter_info () [static], [inherited]
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = true;
  return;
}
ElemAssembly& libMesh::RBAssemblyExpansion::get_A_assembly (unsigned intq)
Return a reference to the specified A_assembly object.
ElemAssembly& libMesh::RBAssemblyExpansion::get_F_assembly (unsigned intq)
Return a reference to the specified F_assembly object.
std::string libMesh::ReferenceCounter::get_info () [static], [inherited]
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
{
#if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
  std::ostringstream oss;
  oss << '\n'
      << " ---------------------------------------------------------------------------- \n"
      << "| Reference count information |\n"
      << " ---------------------------------------------------------------------------- \n";
  for (Counts::iterator it = _counts.begin();
       it != _counts.end(); ++it)
    {
      const std::string name(it->first);
      const unsigned int creations = it->second.first;
      const unsigned int destructions = it->second.second;
      oss << "| " << name << " reference count information:\n"
          << "| Creations: " << creations << '\n'
          << "| Destructions: " << destructions << '\n';
    }
  oss << " ---------------------------------------------------------------------------- \n";
  return oss.str();
#else
  return "";
#endif
}
unsigned int libMesh::RBAssemblyExpansion::get_n_A_terms () const
Get Q_a, the number of terms in the affine expansion for the bilinear form.
unsigned int libMesh::RBAssemblyExpansion::get_n_F_terms () const
Get Q_f, the number of terms in the affine expansion for the right-hand side.
unsigned int libMesh::RBAssemblyExpansion::get_n_output_terms (unsigned intoutput_index) const
Get the number of affine terms associated with the specified output.
unsigned int libMesh::RBAssemblyExpansion::get_n_outputs () const
Get n_outputs, the number output functionals.
ElemAssembly& libMesh::RBAssemblyExpansion::get_output_assembly (unsigned intoutput_index, unsigned intq_l)
Return a reference to the specified output assembly object.
void libMesh::ReferenceCounter::increment_constructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.first++;
}
void libMesh::ReferenceCounter::increment_destructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.second++;
}
static unsigned int libMesh::ReferenceCounter::n_objects () [inline], [static], [inherited]
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
  { return _n_objects; }
void libMesh::RBAssemblyExpansion::perform_A_boundary_assembly (unsigned intq, FEMContext &context)
Perform the specified A boundary assembly.
void libMesh::RBAssemblyExpansion::perform_A_interior_assembly (unsigned intq, FEMContext &context)
Perform the specified A interior assembly.
void libMesh::RBAssemblyExpansion::perform_F_boundary_assembly (unsigned intq, FEMContext &context)
Perform the specified F boundary assembly.
void libMesh::RBAssemblyExpansion::perform_F_interior_assembly (unsigned intq, FEMContext &context)
Perform the specified F interior assembly.
void libMesh::RBAssemblyExpansion::perform_output_boundary_assembly (unsigned intoutput_index, unsigned intq_l, FEMContext &context)
Perform the specified output assembly.
void libMesh::RBAssemblyExpansion::perform_output_interior_assembly (unsigned intoutput_index, unsigned intq_l, FEMContext &context)
Perform the specified output assembly.
void libMesh::ReferenceCounter::print_info (std::ostream &out = libMesh::out) [static], [inherited]
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
{
  if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
}
Member Data Documentation
std::vector<ElemAssembly*> libMesh::RBAssemblyExpansion::_A_assembly_vector [private]
Vectors storing the function pointers to the assembly routines for the affine operators, both interior and boundary assembly.
Definition at line 178 of file rb_assembly_expansion.h.
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts [static], [protected], [inherited]
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true [static], [protected], [inherited]
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
std::vector<ElemAssembly*> libMesh::RBAssemblyExpansion::_F_assembly_vector [private]
Vector storing the function pointers to the assembly routines for the rhs affine vectors.
Definition at line 184 of file rb_assembly_expansion.h.
Threads::spin_mutex libMesh::ReferenceCounter::_mutex [static], [protected], [inherited]
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects [static], [protected], [inherited]
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
std::vector< std::vector<ElemAssembly*> > libMesh::RBAssemblyExpansion::_output_assembly_vector [private]
Vector storing the function pointers to the assembly routines for the outputs. Element interior part.
Definition at line 190 of file rb_assembly_expansion.h.
Author
Generated automatically by Doxygen for libMesh from the source code.