.TH "libMesh::Predicates::is_null< T >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Predicates::is_null< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <single_predicates\&.h>\fP
.PP
Inherits \fBlibMesh::Predicates::predicate< T >\fP\&.
.PP
Inherited by \fBlibMesh::Predicates::not_null< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~is_null\fP ()"
.br
.ti -1c
.RI "virtual bool \fBoperator()\fP (const T &it) const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBpredicate\fP< T > * \fBclone\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct libMesh::Predicates::is_null< T >"

.PP
Definition at line 68 of file single_predicates\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> virtual \fBlibMesh::Predicates::is_null\fP< T >::~\fBis_null\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 70 of file single_predicates\&.h\&.
.PP
.nf
70 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual \fBpredicate\fP<T>* \fBlibMesh::Predicates::is_null\fP< T >::clone () const\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBlibMesh::Predicates::predicate< T >\fP\&.
.PP
Reimplemented in \fBlibMesh::Predicates::not_null< T >\fP\&.
.PP
Definition at line 74 of file single_predicates\&.h\&.
.PP
.nf
74 { return new is_null<T>(*this); }
.fi
.SS "template<typename T> virtual bool \fBlibMesh::Predicates::is_null\fP< T >::operator() (const T &it) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBlibMesh::Predicates::predicate< T >\fP\&.
.PP
Reimplemented in \fBlibMesh::Predicates::not_null< T >\fP\&.
.PP
Definition at line 71 of file single_predicates\&.h\&.
.PP
Referenced by libMesh::Predicates::not_null< T >::operator()()\&.
.PP
.nf
71 { return *it == NULL; }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
