libMesh::Parallel::MessageTag
NAME
libMesh::Parallel::MessageTag -
SYNOPSIS
#include <parallel.h>
Public Member Functions
MessageTag (int tagvalue=invalid_tag)
MessageTag (const MessageTag &other)
~MessageTag ()
int value () const
Static Public Attributes
static const int invalid_tag = INT_MIN
Private Member Functions
MessageTag (int tagvalue, const Communicator *comm)
Private Attributes
int _tagvalue
const Communicator * _comm
Friends
class Communicator
Detailed Description
Encapsulates the MPI tag integers.
Definition at line 172 of file parallel.h.
Constructor & Destructor Documentation
libMesh::Parallel::MessageTag::MessageTag (inttagvalue = invalid_tag) [inline], [explicit]
Explicit constructor, to discourage using 'magic numbers' as tags. Communicator::get_unique_tag is recommended instead.
Definition at line 185 of file parallel.h.
    : _tagvalue(tagvalue), _comm(NULL) {}
libMesh::Parallel::MessageTag::MessageTag (const MessageTag &other) [inline]
Copy constructor. Helps Communicator do reference counting on unique tags
Definition at line 1097 of file parallel_implementation.h.
References _comm, _tagvalue, and libMesh::Parallel::Communicator::reference_unique_tag().
  : _tagvalue(other._tagvalue), _comm(other._comm)
{
  if (_comm)
    _comm->reference_unique_tag(_tagvalue);
}
libMesh::Parallel::MessageTag::~MessageTag () [inline]
Destructor. Helps Communicator do reference counting on unique tags
Definition at line 1089 of file parallel_implementation.h.
References _comm, _tagvalue, and libMesh::Parallel::Communicator::dereference_unique_tag().
{
  if (_comm)
    _comm->dereference_unique_tag(_tagvalue);
}
libMesh::Parallel::MessageTag::MessageTag (inttagvalue, const Communicator *comm) [inline], [private]
Definition at line 209 of file parallel.h.
    : _tagvalue(tagvalue), _comm(comm) {}
Member Function Documentation
int libMesh::Parallel::MessageTag::value () const [inline]
Definition at line 200 of file parallel.h.
References _tagvalue.
Referenced by libMesh::Parallel::Communicator::probe(), libMesh::Parallel::Communicator::receive(), libMesh::Parallel::Communicator::send(), and libMesh::Parallel::Communicator::send_receive().
                    {
    return _tagvalue;
  }
Friends And Related Function Documentation
friend class Communicator [friend]
Definition at line 213 of file parallel.h.
Member Data Documentation
const Communicator* libMesh::Parallel::MessageTag::_comm [private]
Definition at line 206 of file parallel.h.
Referenced by MessageTag(), and ~MessageTag().
int libMesh::Parallel::MessageTag::_tagvalue [private]
Definition at line 205 of file parallel.h.
Referenced by MessageTag(), value(), and ~MessageTag().
const int libMesh::Parallel::MessageTag::invalid_tag = INT_MIN [static]
Invalid tag, to allow for default construction.
Definition at line 179 of file parallel.h.
Author
Generated automatically by Doxygen for libMesh from the source code.