libMesh::mesh_inserter_iterator< T >
NAME
libMesh::mesh_inserter_iterator< T > -
SYNOPSIS
#include <mesh_inserter_iterator.h>
Inherits iterator< std::output_iterator_tag, T >.
Public Member Functions
mesh_inserter_iterator (MeshBase &m)
void operator= (Elem *e)
void operator= (Node *n)
void operator= (Point *p)
mesh_inserter_iterator & operator++ ()
mesh_inserter_iterator operator++ (int)
mesh_inserter_iterator & operator* ()
Private Attributes
MeshBase & mesh
Detailed Description
template<typename T>struct libMesh::mesh_inserter_iterator< T >
Definition at line 41 of file mesh_inserter_iterator.h.
Constructor & Destructor Documentation
template<typename T > libMesh::mesh_inserter_iterator< T >::mesh_inserter_iterator (MeshBase &m) [inline]
Definition at line 44 of file mesh_inserter_iterator.h.
Referenced by libMesh::mesh_inserter_iterator< T >::operator++().
: mesh(m) {}
Member Function Documentation
template<typename T > mesh_inserter_iterator& libMesh::mesh_inserter_iterator< T >::operator* () [inline]
Definition at line 64 of file mesh_inserter_iterator.h.
{ return *this; }
template<typename T > mesh_inserter_iterator& libMesh::mesh_inserter_iterator< T >::operator++ () [inline]
Definition at line 52 of file mesh_inserter_iterator.h.
                                       {
    return *this;
  }
template<typename T > mesh_inserter_iterator libMesh::mesh_inserter_iterator< T >::operator++ (int) [inline]
Definition at line 56 of file mesh_inserter_iterator.h.
References libMesh::mesh_inserter_iterator< T >::mesh_inserter_iterator().
                                         {
    return mesh_inserter_iterator(*this);
  }
template<typename T > void libMesh::mesh_inserter_iterator< T >::operator= (Elem *e) [inline]
Definition at line 46 of file mesh_inserter_iterator.h.
References libMesh::MeshBase::add_elem(), and libMesh::mesh_inserter_iterator< T >::mesh.
{ mesh.add_elem(e); }
template<typename T > void libMesh::mesh_inserter_iterator< T >::operator= (Node *n) [inline]
Definition at line 48 of file mesh_inserter_iterator.h.
References libMesh::MeshBase::insert_node(), and libMesh::mesh_inserter_iterator< T >::mesh.
{ mesh.insert_node(n); }
template<typename T > void libMesh::mesh_inserter_iterator< T >::operator= (Point *p) [inline]
Definition at line 50 of file mesh_inserter_iterator.h.
References libMesh::MeshBase::add_point(), and libMesh::mesh_inserter_iterator< T >::mesh.
{ mesh.add_point(*p); }
Member Data Documentation
template<typename T > MeshBase& libMesh::mesh_inserter_iterator< T >::mesh [private]
Definition at line 67 of file mesh_inserter_iterator.h.
Referenced by libMesh::mesh_inserter_iterator< T >::operator=().
Author
Generated automatically by Doxygen for libMesh from the source code.