libMesh::Parallel::Request
NAME
libMesh::Parallel::Request -
SYNOPSIS
#include <parallel.h>
Public Member Functions
Request ()
Request (const request &r)
Request (const Request &other)
void cleanup ()
Request & operator= (const Request &other)
Request & operator= (const request &r)
~Request ()
request * get ()
const request * get () const
Status wait ()
bool test ()
bool test (status &status)
void add_post_wait_work (PostWaitWork *work)
Private Attributes
request _request
std::pair< std::vector
< PostWaitWork * >, unsigned
int > * post_wait_work"
Detailed Description
Encapsulates the MPI_Request
Definition at line 395 of file parallel.h.
Constructor & Destructor Documentation
libMesh::Parallel::Request::Request () [inline]
Definition at line 626 of file parallel_implementation.h.
                         :
#ifdef LIBMESH_HAVE_MPI
  _request(MPI_REQUEST_NULL),
#else
  _request(),
#endif
  post_wait_work(NULL)
{}
libMesh::Parallel::Request::Request (const request &r) [inline]
Definition at line 635 of file parallel_implementation.h.
                                         :
  _request(r),
  post_wait_work(NULL)
{}
libMesh::Parallel::Request::Request (const Request &other) [inline]
Definition at line 640 of file parallel_implementation.h.
References post_wait_work.
                                             :
  _request(other._request),
  post_wait_work(other.post_wait_work)
{
  // operator= should behave like a shared pointer
  if (post_wait_work)
    post_wait_work->second++;
}
libMesh::Parallel::Request::~Request () [inline]
Definition at line 693 of file parallel_implementation.h.
References cleanup().
                          {
  this->cleanup();
}
Member Function Documentation
void libMesh::Parallel::Request::add_post_wait_work (PostWaitWork *work) [inline]
Definition at line 760 of file parallel_implementation.h.
References post_wait_work.
Referenced by libMesh::Parallel::Communicator::receive(), libMesh::Parallel::Communicator::receive_packed_range(), libMesh::Parallel::Communicator::send(), and libMesh::Parallel::Communicator::send_packed_range().
{
  if (!post_wait_work)
    post_wait_work = new
      std::pair<std::vector <PostWaitWork* >, unsigned int>
      (std::vector <PostWaitWork* >(), 1);
  post_wait_work->first.push_back(work);
}
void libMesh::Parallel::Request::cleanup () [inline]
Definition at line 649 of file parallel_implementation.h.
References libMesh::libmesh_assert(), and post_wait_work.
Referenced by operator=(), and ~Request().
{
  if (post_wait_work)
    {
      // Decrement the use count
      post_wait_work->second--;
      if (!post_wait_work->second)
        {
#ifdef DEBUG
          // If we're done using this request, then we'd better have
          // done the work we waited for
          for (std::vector<PostWaitWork*>::iterator i =
                 post_wait_work->first.begin();
               i != post_wait_work->first.end(); ++i)
            libmesh_assert(!(*i));
#endif
          delete post_wait_work;
          post_wait_work = NULL;
        }
    }
}
request* libMesh::Parallel::Request::get () [inline]
Definition at line 412 of file parallel.h.
References _request.
Referenced by libMesh::Parallel::Communicator::receive(), and libMesh::Parallel::Communicator::send().
{ return &_request; }
const request* libMesh::Parallel::Request::get () const [inline]
Definition at line 414 of file parallel.h.
References _request.
{ return &_request; }
Request & libMesh::Parallel::Request::operator= (const Request &other) [inline]
Definition at line 672 of file parallel_implementation.h.
References _request, cleanup(), and post_wait_work.
{
  this->cleanup();
  _request = other._request;
  post_wait_work = other.post_wait_work;
  // operator= should behave like a shared pointer
  if (post_wait_work)
    post_wait_work->second++;
  return *this;
}
Request & libMesh::Parallel::Request::operator= (const request &r) [inline]
Definition at line 685 of file parallel_implementation.h.
References _request, cleanup(), and post_wait_work.
{
  this->cleanup();
  _request = r;
  post_wait_work = NULL;
  return *this;
}
bool libMesh::Parallel::Request::test () [inline]
Definition at line 722 of file parallel_implementation.h.
References _request, and libMesh::libmesh_assert().
{
#ifdef LIBMESH_HAVE_MPI
  int val=0;
  MPI_Test (&_request,
            &val,
            MPI_STATUS_IGNORE);
  if (val)
    {
      libmesh_assert (_request == MPI_REQUEST_NULL);
      libmesh_assert_equal_to (val, 1);
    }
  return val;
#else
  return true;
#endif
}
bool libMesh::Parallel::Request::test (status &status) [inline]
Definition at line 743 of file parallel_implementation.h.
References _request.
{
  int val=0;
  MPI_Test (&_request,
            &val,
            &stat);
  return val;
}
Status libMesh::Parallel::Request::wait () [inline]
Definition at line 697 of file parallel_implementation.h.
References _request, libMesh::Parallel::Status::get(), libMesh::libmesh_assert(), post_wait_work, libMesh::START_LOG(), and libMesh::STOP_LOG().
Referenced by libMesh::Parallel::Communicator::send_receive(), libMesh::Parallel::Communicator::send_receive_packed_range(), and libMesh::Parallel::wait().
{
  START_LOG("wait()", "Parallel::Request");
  Status stat;
#ifdef LIBMESH_HAVE_MPI
  MPI_Wait (&_request, stat.get());
#endif
  if (post_wait_work)
    for (std::vector<PostWaitWork*>::iterator i =
           post_wait_work->first.begin();
         i != post_wait_work->first.end(); ++i)
      {
        // The user should never try to give us NULL work or try
        // to wait() twice.
        libmesh_assert (*i);
        (*i)->run();
        delete (*i);
        *i = NULL;
      }
  STOP_LOG("wait()", "Parallel::Request");
  return stat;
}
Member Data Documentation
request libMesh::Parallel::Request::_request [private]
Definition at line 425 of file parallel.h.
Referenced by get(), operator=(), test(), and wait().
std::pair<std::vector <PostWaitWork* >, unsigned int>* libMesh::Parallel::Request::post_wait_work [private]
Definition at line 431 of file parallel.h.
Referenced by add_post_wait_work(), cleanup(), operator=(), Request(), and wait().
Author
Generated automatically by Doxygen for libMesh from the source code.