libMesh::mapvector< Val, index_t >
NAME
libMesh::mapvector< Val, index_t > -
SYNOPSIS
#include <mapvector.h>
Inherits map< index_t, Val >.
Classes
class const_veclike_iterator
class veclike_iterator
Public Types
typedef std::map< index_t, Val > maptype
Public Member Functions
Val & operator[] (const index_t &k)
Val operator[] (const index_t &k) const
void erase (index_t i)
void erase (const veclike_iterator &pos)
veclike_iterator begin ()
const_veclike_iterator begin () const
veclike_iterator end ()
const_veclike_iterator end () const
Detailed Description
template<typename Val, typename index_t = unsigned int>class libMesh::mapvector< Val, index_t >
This mapvector templated class is intended to provide the performance characteristics of a std::map with an interface more closely resembling that of a std::vector, for use with ParallelMesh.
Author:
Roy H. Stogner
Definition at line 38 of file mapvector.h.
Member Typedef Documentation
template<typename Val, typename index_t = unsigned int> typedef std::map<index_t, Val> libMesh::mapvector< Val, index_t >::maptype
Definition at line 41 of file mapvector.h.
Member Function Documentation
template<typename Val, typename index_t = unsigned int> veclike_iterator libMesh::mapvector< Val, index_t >::begin () [inline]
Definition at line 124 of file mapvector.h.
Referenced by libMesh::ParallelMesh::fix_broken_node_and_element_numbering(), and libMesh::ParallelMesh::renumber_dof_objects().
                           {
    return veclike_iterator(maptype::begin());
  }
template<typename Val, typename index_t = unsigned int> const_veclike_iterator libMesh::mapvector< Val, index_t >::begin () const [inline]
Definition at line 128 of file mapvector.h.
                                       {
    return const_veclike_iterator(maptype::begin());
  }
template<typename Val, typename index_t = unsigned int> veclike_iterator libMesh::mapvector< Val, index_t >::end () [inline]
Definition at line 132 of file mapvector.h.
Referenced by libMesh::ParallelMesh::fix_broken_node_and_element_numbering(), libMesh::mapvector< libMesh::Elem *, dof_id_type >::operator[](), and libMesh::ParallelMesh::renumber_dof_objects().
                         {
    return veclike_iterator(maptype::end());
  }
template<typename Val, typename index_t = unsigned int> const_veclike_iterator libMesh::mapvector< Val, index_t >::end () const [inline]
Definition at line 136 of file mapvector.h.
                                     {
    return const_veclike_iterator(maptype::end());
  }
template<typename Val, typename index_t = unsigned int> void libMesh::mapvector< Val, index_t >::erase (index_ti) [inline]
Definition at line 116 of file mapvector.h.
Referenced by libMesh::ParallelMesh::renumber_dof_objects().
                        {
    maptype::erase(i);
  }
template<typename Val, typename index_t = unsigned int> void libMesh::mapvector< Val, index_t >::erase (const veclike_iterator &pos) [inline]
Definition at line 120 of file mapvector.h.
                                          {
    maptype::erase(pos.it);
  }
template<typename Val, typename index_t = unsigned int> Val& libMesh::mapvector< Val, index_t >::operator[] (const index_t &k) [inline]
Definition at line 43 of file mapvector.h.
  {
    return maptype::operator[](k);
  }
template<typename Val, typename index_t = unsigned int> Val libMesh::mapvector< Val, index_t >::operator[] (const index_t &k) const [inline]
Definition at line 47 of file mapvector.h.
  {
    typename maptype::const_iterator it = this->find(k);
    return it == this->end().it? Val() : it->second;
  }
Author
Generated automatically by Doxygen for libMesh from the source code.