libMesh::DGFEMContext
NAME
libMesh::DGFEMContext -
SYNOPSIS
#include <dg_fem_context.h>
Inherits libMesh::FEMContext.
Public Types
typedef std::map< const
NumericVector< Number >
 *, std::pair< DenseVector
< Number >, std::vector
< DenseSubVector< Number >
 * > > >::iterator localized_vectors_iterator"
Public Member Functions
DGFEMContext (const System &sys)
virtual ~DGFEMContext ()
virtual void side_fe_reinit ()
void neighbor_side_fe_reinit ()
const std::vector< dof_id_type > & get_neighbor_dof_indices () const
const std::vector< dof_id_type > & get_neighbor_dof_indices (unsigned int var) const
const DenseVector< Number > & get_neighbor_residual () const
DenseVector< Number > & get_neighbor_residual ()
const DenseSubVector< Number > & get_neighbor_residual (unsigned int var) const
DenseSubVector< Number > & get_neighbor_residual (unsigned int var)
const DenseMatrix< Number > & get_elem_elem_jacobian () const
DenseMatrix< Number > & get_elem_elem_jacobian ()
const DenseSubMatrix< Number > & get_elem_elem_jacobian (unsigned int var1, unsigned int var2) const
DenseSubMatrix< Number > & get_elem_elem_jacobian (unsigned int var1, unsigned int var2)
const DenseMatrix< Number > & get_elem_neighbor_jacobian () const
DenseMatrix< Number > & get_elem_neighbor_jacobian ()
const DenseSubMatrix< Number > & get_elem_neighbor_jacobian (unsigned int var1, unsigned int var2) const
DenseSubMatrix< Number > & get_elem_neighbor_jacobian (unsigned int var1, unsigned int var2)
const DenseMatrix< Number > & get_neighbor_elem_jacobian () const
DenseMatrix< Number > & get_neighbor_elem_jacobian ()
const DenseSubMatrix< Number > & get_neighbor_elem_jacobian (unsigned int var1, unsigned int var2) const
DenseSubMatrix< Number > & get_neighbor_elem_jacobian (unsigned int var1, unsigned int var2)
const DenseMatrix< Number > & get_neighbor_neighbor_jacobian () const
DenseMatrix< Number > & get_neighbor_neighbor_jacobian ()
const DenseSubMatrix< Number > & get_neighbor_neighbor_jacobian (unsigned int var1, unsigned int var2) const
DenseSubMatrix< Number > & get_neighbor_neighbor_jacobian (unsigned int var1, unsigned int var2)
void set_neighbor (const Elem &neighbor)
const Elem & get_neighbor () const
bool dg_terms_are_active () const
template<typename OutputShape > void get_neighbor_side_fe (unsigned int var, FEGenericBase< OutputShape > *&fe) const
bool has_side_boundary_id (boundary_id_type id) const
std::vector< boundary_id_type > side_boundary_ids () const
Number interior_value (unsigned int var, unsigned int qp) const
template<typename OutputType > void interior_value (unsigned int var, unsigned int qp, OutputType &u) const
Number side_value (unsigned int var, unsigned int qp) const
template<typename OutputType > void side_value (unsigned int var, unsigned int qp, OutputType &u) const
Number point_value (unsigned int var, const Point &p) const
template<typename OutputType > void point_value (unsigned int var, const Point &p, OutputType &u) const
Gradient interior_gradient (unsigned int var, unsigned int qp) const
template<typename OutputType > void interior_gradient (unsigned int var, unsigned int qp, OutputType &du) const
Gradient side_gradient (unsigned int var, unsigned int qp) const
template<typename OutputType > void side_gradient (unsigned int var, unsigned int qp, OutputType &du) const
Gradient point_gradient (unsigned int var, const Point &p) const
template<typename OutputType > void point_gradient (unsigned int var, const Point &p, OutputType &grad_u) const
Tensor interior_hessian (unsigned int var, unsigned int qp) const
template<typename OutputType > void interior_hessian (unsigned int var, unsigned int qp, OutputType &d2u) const
Tensor side_hessian (unsigned int var, unsigned int qp) const
template<typename OutputType > void side_hessian (unsigned int var, unsigned int qp, OutputType &d2u) const
Tensor point_hessian (unsigned int var, const Point &p) const
template<typename OutputType > void point_hessian (unsigned int var, const Point &p, OutputType &hess_u) const
Number fixed_interior_value (unsigned int var, unsigned int qp) const
template<typename OutputType > void fixed_interior_value (unsigned int var, unsigned int qp, OutputType &u) const
Number fixed_side_value (unsigned int var, unsigned int qp) const
template<typename OutputType > void fixed_side_value (unsigned int var, unsigned int qp, OutputType &u) const
Number fixed_point_value (unsigned int var, const Point &p) const
template<typename OutputType > void fixed_point_value (unsigned int var, const Point &p, OutputType &u) const
Gradient fixed_interior_gradient (unsigned int var, unsigned int qp) const
template<typename OutputType > void fixed_interior_gradient (unsigned int var, unsigned int qp, OutputType &grad_u) const
Gradient fixed_side_gradient (unsigned int var, unsigned int qp) const
template<typename OutputType > void fixed_side_gradient (unsigned int var, unsigned int qp, OutputType &grad_u) const
Gradient fixed_point_gradient (unsigned int var, const Point &p) const
template<typename OutputType > void fixed_point_gradient (unsigned int var, const Point &p, OutputType &grad_u) const
Tensor fixed_interior_hessian (unsigned int var, unsigned int qp) const
template<typename OutputType > void fixed_interior_hessian (unsigned int var, unsigned int qp, OutputType &hess_u) const
Tensor fixed_side_hessian (unsigned int var, unsigned int qp) const
template<typename OutputType > void fixed_side_hessian (unsigned int var, unsigned int qp, OutputType &hess_u) const
Tensor fixed_point_hessian (unsigned int var, const Point &p) const
template<typename OutputType > void fixed_point_hessian (unsigned int var, const Point &p, OutputType &hess_u) const
template<typename OutputShape > void get_element_fe (unsigned int var, FEGenericBase< OutputShape > *&fe) const
FEBase * get_element_fe (unsigned int var) const
template<typename OutputShape > void get_side_fe (unsigned int var, FEGenericBase< OutputShape > *&fe) const
FEBase * get_side_fe (unsigned int var) const
template<typename OutputShape > void get_edge_fe (unsigned int var, FEGenericBase< OutputShape > *&fe) const
FEBase * get_edge_fe (unsigned int var) const
template<typename OutputType > void interior_values (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &interior_values_vector) const
template<typename OutputType > void side_values (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &side_values_vector) const
template<typename OutputType > void interior_gradients (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &interior_gradients_vector) const
template<typename OutputType > void side_gradients (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &side_gradients_vector) const
template<typename OutputType > void interior_hessians (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &d2u_vals) const
template<typename OutputType > void side_hessians (unsigned int var, const NumericVector< Number > &_system_vector, std::vector< OutputType > &d2u_vals) const
template<typename OutputType > void interior_curl (unsigned int var, unsigned int qp, OutputType &curl_u) const
template<typename OutputType > void point_curl (unsigned int var, const Point &p, OutputType &curl_u) const
template<typename OutputType > void interior_div (unsigned int var, unsigned int qp, OutputType &div_u) const
virtual void elem_reinit (Real theta)
virtual void elem_side_reinit (Real theta)
virtual void elem_edge_reinit (Real theta)
virtual void pre_fe_reinit (const System &, const Elem *e)
void elem_fe_reinit ()
void edge_fe_reinit ()
const QBase & get_element_qrule () const
const QBase & get_side_qrule () const
const QBase & get_edge_qrule () const
virtual void set_mesh_system (System *sys)
const System * get_mesh_system () const
System * get_mesh_system ()
unsigned int get_mesh_x_var () const
void set_mesh_x_var (unsigned int x_var)
unsigned int get_mesh_y_var () const
void set_mesh_y_var (unsigned int y_var)
unsigned int get_mesh_z_var () const
void set_mesh_z_var (unsigned int z_var)
const Elem & get_elem () const
Elem & get_elem ()
unsigned char get_side () const
unsigned char get_edge () const
unsigned char get_dim () const
void elem_position_set (Real theta)
void elem_position_get ()
unsigned int n_vars () const
const System & get_system () const
const DenseVector< Number > & get_elem_solution () const
DenseVector< Number > & get_elem_solution ()
const DenseSubVector< Number > & get_elem_solution (unsigned int var) const
const DenseVector< Number > & get_elem_fixed_solution () const
DenseVector< Number > & get_elem_fixed_solution ()
const DenseSubVector< Number > & get_elem_fixed_solution (unsigned int var) const
const DenseVector< Number > & get_elem_residual () const
DenseVector< Number > & get_elem_residual ()
const DenseSubVector< Number > & get_elem_residual (unsigned int var) const
DenseSubVector< Number > & get_elem_residual (unsigned int var)
const DenseMatrix< Number > & get_elem_jacobian () const
DenseMatrix< Number > & get_elem_jacobian ()
const DenseSubMatrix< Number > & get_elem_jacobian (unsigned int var1, unsigned int var2) const
DenseSubMatrix< Number > & get_elem_jacobian (unsigned int var1, unsigned int var2)
const std::vector< Number > & get_qois () const
std::vector< Number > & get_qois ()
const std::vector< DenseVector
< Number > > & get_qoi_derivatives () const "
std::vector< DenseVector
< Number > > & get_qoi_derivatives ()"
const DenseSubVector< Number > & get_qoi_derivatives (unsigned int qoi, unsigned int var) const
DenseSubVector< Number > & get_qoi_derivatives (unsigned int qoi, unsigned int var)
const std::vector< dof_id_type > & get_dof_indices () const
std::vector< dof_id_type > & get_dof_indices ()
const std::vector< dof_id_type > & get_dof_indices (unsigned int var) const
Real get_system_time () const
Real get_time () const
void set_time (Real time_in)
Real get_elem_solution_derivative () const
Real get_fixed_solution_derivative () const
bool is_adjoint () const
bool & is_adjoint ()
void set_deltat_pointer (Real *dt)
Real get_deltat_value ()
void add_localized_vector (NumericVector< Number > &_localized_vector, const System &_sys)
DenseVector< Number > & get_localized_vector (const NumericVector< Number > &_localized_vector)
const DenseVector< Number > & get_localized_vector (const NumericVector< Number > &_localized_vector) const
DenseSubVector< Number > & get_localized_subvector (const NumericVector< Number > &_localized_vector, unsigned int _var)
const DenseSubVector< Number > & get_localized_subvector (const NumericVector< Number > &_localized_vector, unsigned int _var) const
Public Attributes
System * _mesh_sys
unsigned int _mesh_x_var
unsigned int _mesh_y_var
unsigned int _mesh_z_var
unsigned char side
unsigned char edge
Real time
const Real system_time
Real elem_solution_derivative
Real fixed_solution_derivative
Protected Member Functions
template<typename OutputShape > AutoPtr< FEGenericBase
< OutputShape > > build_new_fe (const FEGenericBase< OutputShape > *fe, const Point &p) const "
Protected Attributes
std::map< FEType, FEAbstract * > _element_fe
std::map< FEType, FEAbstract * > _side_fe
std::map< FEType, FEAbstract * > _edge_fe
std::vector< FEAbstract * > _element_fe_var
std::vector< FEAbstract * > _side_fe_var
std::vector< FEAbstract * > _edge_fe_var
BoundaryInfo * _boundary_info
const Elem * elem
unsigned char dim
QBase * element_qrule
QBase * side_qrule
QBase * edge_qrule
std::map< const NumericVector
< Number > *, std::pair
< DenseVector< Number >
, std::vector< DenseSubVector
< Number > * > > > localized_vectors"
DenseVector< Number > elem_solution
std::vector< DenseSubVector
< Number > * > elem_subsolutions"
DenseVector< Number > elem_fixed_solution
std::vector< DenseSubVector
< Number > * > elem_fixed_subsolutions"
DenseVector< Number > elem_residual
DenseMatrix< Number > elem_jacobian
std::vector< Number > elem_qoi
std::vector< DenseVector
< Number > > elem_qoi_derivative"
std::vector< std::vector
< DenseSubVector< Number > * > > elem_qoi_subderivatives"
std::vector< DenseSubVector
< Number > * > elem_subresiduals"
std::vector< std::vector
< DenseSubMatrix< Number > * > > elem_subjacobians"
std::vector< dof_id_type > dof_indices
std::vector< std::vector
< dof_id_type > > dof_indices_var"
Private Attributes
const Elem * _neighbor
DenseVector< Number > _neighbor_residual
DenseMatrix< Number > _elem_elem_jacobian
DenseMatrix< Number > _elem_neighbor_jacobian
DenseMatrix< Number > _neighbor_elem_jacobian
DenseMatrix< Number > _neighbor_neighbor_jacobian
std::vector< DenseSubVector
< Number > * > _neighbor_subresiduals"
std::vector< std::vector
< DenseSubMatrix< Number > * > > _elem_elem_subjacobians"
std::vector< std::vector
< DenseSubMatrix< Number > * > > _elem_neighbor_subjacobians"
std::vector< std::vector
< DenseSubMatrix< Number > * > > _neighbor_elem_subjacobians"
std::vector< std::vector
< DenseSubMatrix< Number > * > > _neighbor_neighbor_subjacobians"
std::vector< dof_id_type > _neighbor_dof_indices
std::vector< std::vector
< dof_id_type > > _neighbor_dof_indices_var"
std::map< FEType, FEAbstract * > _neighbor_side_fe
std::vector< FEAbstract * > _neighbor_side_fe_var
bool _dg_terms_active
Detailed Description
This class extends FEMContext in order to provide extra data required to perform local element residual and Jacobian assembly in the case of a discontinuous Galerkin (DG) discretization.
Definition at line 39 of file dg_fem_context.h.
Member Typedef Documentation
typedef std::map<const NumericVector<Number>*, std::pair<DenseVector<Number>, std::vector<DenseSubVector<Number>*> > >::iterator libMesh::DiffContext::localized_vectors_iterator [inherited]
Typedef for the localized_vectors iterator
Definition at line 340 of file diff_context.h.
Constructor & Destructor Documentation
libMesh::DGFEMContext::DGFEMContext (const System &sys) [explicit]
Constructor. Allocates some but fills no data structures.
Definition at line 29 of file dg_fem_context.C.
References _elem_elem_jacobian, _elem_elem_subjacobians, _elem_neighbor_jacobian, _elem_neighbor_subjacobians, _neighbor_elem_jacobian, _neighbor_elem_subjacobians, _neighbor_neighbor_jacobian, _neighbor_neighbor_subjacobians, _neighbor_residual, _neighbor_side_fe, _neighbor_side_fe_var, _neighbor_subresiduals, libMesh::FEAbstract::build(), libMesh::FEMContext::dim, libMesh::libmesh_assert(), libMesh::System::n_vars(), and libMesh::System::variable_type().
  : FEMContext(sys),
    _neighbor(NULL),
    _neighbor_dof_indices_var(sys.n_vars()),
    _dg_terms_active(false)
{
  libmesh_experimental();
  unsigned int nv = sys.n_vars();
  libmesh_assert (nv);
  _neighbor_subresiduals.reserve(nv);
  _elem_elem_subjacobians.resize(nv);
  _elem_neighbor_subjacobians.resize(nv);
  _neighbor_elem_subjacobians.resize(nv);
  _neighbor_neighbor_subjacobians.resize(nv);
  for (unsigned int i=0; i != nv; ++i)
    {
      _neighbor_subresiduals.push_back(new DenseSubVector<Number>(_neighbor_residual));
      _elem_elem_subjacobians[i].reserve(nv);
      _elem_neighbor_subjacobians[i].reserve(nv);
      _neighbor_elem_subjacobians[i].reserve(nv);
      _neighbor_neighbor_subjacobians[i].reserve(nv);
      for (unsigned int j=0; j != nv; ++j)
        {
          _elem_elem_subjacobians[i].push_back
            (new DenseSubMatrix<Number>(_elem_elem_jacobian));
          _elem_neighbor_subjacobians[i].push_back
            (new DenseSubMatrix<Number>(_elem_neighbor_jacobian));
          _neighbor_elem_subjacobians[i].push_back
            (new DenseSubMatrix<Number>(_neighbor_elem_jacobian));
          _neighbor_neighbor_subjacobians[i].push_back
            (new DenseSubMatrix<Number>(_neighbor_neighbor_jacobian));
        }
    }
  _neighbor_side_fe_var.resize(nv);
  for (unsigned int i=0; i != nv; ++i)
    {
      FEType fe_type = sys.variable_type(i);
      if ( _neighbor_side_fe[fe_type] == NULL )
        {
          _neighbor_side_fe[fe_type] = FEAbstract::build(dim, fe_type).release();
        }
      _neighbor_side_fe_var[i] = _neighbor_side_fe[fe_type];
    }
}
libMesh::DGFEMContext::~DGFEMContext () [virtual]
Destructor.
Definition at line 80 of file dg_fem_context.C.
References _elem_elem_subjacobians, _elem_neighbor_subjacobians, _neighbor_elem_subjacobians, _neighbor_neighbor_subjacobians, _neighbor_side_fe, and _neighbor_subresiduals.
{
  for (std::size_t i=0; i != _neighbor_subresiduals.size(); ++i)
    {
      delete _neighbor_subresiduals[i];
      for (std::size_t j=0; j != _elem_elem_subjacobians[i].size(); ++j)
        {
          delete _elem_elem_subjacobians[i][j];
          delete _elem_neighbor_subjacobians[i][j];
          delete _neighbor_elem_subjacobians[i][j];
          delete _neighbor_neighbor_subjacobians[i][j];
        }
    }
  // Delete the FE objects
  for (std::map<FEType, FEAbstract *>::iterator i = _neighbor_side_fe.begin();
       i != _neighbor_side_fe.end(); ++i)
    delete i->second;
  _neighbor_side_fe.clear();
}
Member Function Documentation
void libMesh::DiffContext::add_localized_vector (NumericVector< Number > &_localized_vector, const System &_sys) [inherited]
Adds a vector to the map of localized vectors. We can later evaluate interior_values, interior_gradients and side_values for these fields these vectors represent.
Definition at line 125 of file diff_context.C.
References libMesh::DiffContext::localized_vectors, and libMesh::System::n_vars().
{
  // Make an empty pair keyed with a reference to this _localized_vector
  localized_vectors[&_localized_vector] = std::make_pair(DenseVector<Number>(), std::vector<DenseSubVector<Number>*>());
  unsigned int nv = _sys.n_vars();
  localized_vectors[&_localized_vector].second.reserve(nv);
  // Fill the DenseSubVector with nv copies of DenseVector
  for(unsigned int i=0; i != nv; ++i)
    localized_vectors[&_localized_vector].second.push_back(new DenseSubVector<Number>(localized_vectors[&_localized_vector].first));
}
template<typename OutputShape > template AutoPtr< FEGenericBase< RealGradient > > libMesh::FEMContext::build_new_fe (const FEGenericBase< OutputShape > *fe, const Point &p) const [protected], [inherited]
Helper function to reduce some code duplication in the *_point_* methods.
Definition at line 1698 of file fem_context.C.
References libMesh::Elem::dim(), libMesh::FEMContext::dim, libMesh::FEMContext::elem, libMesh::FEAbstract::get_fe_type(), and libMesh::FEInterface::inverse_map().
Referenced by libMesh::FEMContext::fixed_point_gradient(), libMesh::FEMContext::fixed_point_hessian(), libMesh::FEMContext::fixed_point_value(), libMesh::FEMContext::point_curl(), libMesh::FEMContext::point_gradient(), libMesh::FEMContext::point_hessian(), and libMesh::FEMContext::point_value().
{
  FEType fe_type = fe->get_fe_type();
  AutoPtr<FEGenericBase<OutputShape> > fe_new(FEGenericBase<OutputShape>::build(elem->dim(), fe_type));
  // Map the physical co-ordinates to the master co-ordinates using the inverse_map from fe_interface.h
  // Build a vector of point co-ordinates to send to reinit
  std::vector<Point> coor(1, FEInterface::inverse_map(dim, fe_type, elem, p));
  // Reinitialize the element and compute the shape function values at coor
  fe_new->reinit (elem, &coor);
  return fe_new;
}
bool libMesh::DGFEMContext::dg_terms_are_active () const [inline]
Are the DG terms active, i.e. have they been assembled?
Definition at line 231 of file dg_fem_context.h.
References _dg_terms_active.
  { return _dg_terms_active; }
void libMesh::FEMContext::edge_fe_reinit () [inherited]
Reinitializes edge FE objects on the current geometric element
Definition at line 1437 of file fem_context.C.
References libMesh::FEMContext::_edge_fe, libMesh::FEMContext::dim, libMesh::FEMContext::edge, and libMesh::FEMContext::elem.
Referenced by libMesh::FEMContext::elem_edge_reinit().
{
  libmesh_assert_equal_to (dim, 3);
  // Initialize all the interior FE objects on elem/edge.
  // Logging of FE::reinit is done in the FE functions
  std::map<FEType, FEAbstract *>::iterator local_fe_end = _edge_fe.end();
  for (std::map<FEType, FEAbstract *>::iterator i = _edge_fe.begin();
       i != local_fe_end; ++i)
    {
      i->second->edge_reinit(elem, edge);
    }
}
void libMesh::FEMContext::elem_edge_reinit (Realtheta) [virtual], [inherited]
Reinitialize Elem and edge FE objects if necessary for integration at a new point in time: specifically, handle moving elements in moving mesh schemes.
Reimplemented from libMesh::DiffContext.
Definition at line 1395 of file fem_context.C.
References libMesh::FEMContext::_mesh_sys, libMesh::FEMContext::_update_time_from_system(), libMesh::FEMContext::edge_fe_reinit(), and libMesh::FEMContext::elem_position_set().
{
  // Update the "time" variable of this context object
  this->_update_time_from_system(theta);
  // Handle a moving element if necessary
  if (_mesh_sys)
    {
      // FIXME - not threadsafe yet!
      elem_position_set(theta);
      edge_fe_reinit();
    }
}
void libMesh::FEMContext::elem_fe_reinit () [inherited]
Reinitializes interior FE objects on the current geometric element
Definition at line 1410 of file fem_context.C.
References libMesh::FEMContext::_element_fe, and libMesh::FEMContext::elem.
Referenced by libMesh::FEMContext::elem_reinit(), and libMesh::FEMSystem::mesh_position_set().
{
  // Initialize all the interior FE objects on elem.
  // Logging of FE::reinit is done in the FE functions
  std::map<FEType, FEAbstract *>::iterator local_fe_end = _element_fe.end();
  for (std::map<FEType, FEAbstract *>::iterator i = _element_fe.begin();
       i != local_fe_end; ++i)
    {
      i->second->reinit(elem);
    }
}
void libMesh::FEMContext::elem_position_get () [inherited]
Uses the geometry of elem to set the coordinate data specified by mesh_*_position configuration.
Definition at line 1453 of file fem_context.C.
References libMesh::FEMContext::_element_fe_var, libMesh::FEMContext::_mesh_sys, libMesh::FEMContext::_mesh_x_var, libMesh::FEMContext::_mesh_y_var, libMesh::FEMContext::_mesh_z_var, libMesh::Elem::default_order(), libMesh::FEMContext::elem, libMesh::DiffContext::elem_subsolutions, libMesh::invalid_uint, libMesh::LAGRANGE, libMesh::libmesh_assert(), n_nodes, libMesh::Elem::n_nodes(), libMesh::n_threads, and libMesh::Elem::point().
Referenced by libMesh::FEMSystem::mesh_position_get().
{
  // This is too expensive to call unless we've been asked to move the mesh
  libmesh_assert (_mesh_sys);
  // This will probably break with threading when two contexts are
  // operating on elements which share a node
  libmesh_assert_equal_to (libMesh::n_threads(), 1);
  // If the coordinate data is in our own system, it's already
  // been set up for us
  // if (_mesh_sys == this->number())
  // {
  unsigned int n_nodes = elem->n_nodes();
  // For simplicity we demand that mesh coordinates be stored
  // in a format that allows a direct copy
  libmesh_assert(_mesh_x_var == libMesh::invalid_uint ||
                 (_element_fe_var[_mesh_x_var]->get_fe_type().family
                  == LAGRANGE &&
                  _element_fe_var[_mesh_x_var]->get_fe_type().order
                  == elem->default_order()));
  libmesh_assert(_mesh_y_var == libMesh::invalid_uint ||
                 (_element_fe_var[_mesh_y_var]->get_fe_type().family
                  == LAGRANGE &&
                  _element_fe_var[_mesh_y_var]->get_fe_type().order
                  == elem->default_order()));
  libmesh_assert(_mesh_z_var == libMesh::invalid_uint ||
                 (_element_fe_var[_mesh_z_var]->get_fe_type().family
                  == LAGRANGE &&
                  _element_fe_var[_mesh_z_var]->get_fe_type().order
                  == elem->default_order()));
  // Get degree of freedom coefficients from point coordinates
  if (_mesh_x_var != libMesh::invalid_uint)
    for (unsigned int i=0; i != n_nodes; ++i)
      (*elem_subsolutions[_mesh_x_var])(i) = elem->point(i)(0);
  if (_mesh_y_var != libMesh::invalid_uint)
    for (unsigned int i=0; i != n_nodes; ++i)
      (*elem_subsolutions[_mesh_y_var])(i) = elem->point(i)(1);
  if (_mesh_z_var != libMesh::invalid_uint)
    for (unsigned int i=0; i != n_nodes; ++i)
      (*elem_subsolutions[_mesh_z_var])(i) = elem->point(i)(2);
  // }
  // FIXME - If the coordinate data is not in our own system, someone
  // had better get around to implementing that... - RHS
  // else
  // {
  // libmesh_not_implemented();
  // }
}
void libMesh::FEMContext::elem_position_set (Realtheta) [inline], [inherited]
Uses the coordinate data specified by mesh_*_position configuration to set the geometry of elem to the value it would take after a fraction theta of a timestep.
Definition at line 758 of file fem_context.h.
References libMesh::FEMContext::_do_elem_position_set(), and libMesh::FEMContext::_mesh_sys.
Referenced by libMesh::FEMContext::elem_edge_reinit(), libMesh::FEMContext::elem_reinit(), libMesh::FEMContext::elem_side_reinit(), and libMesh::FEMSystem::mesh_position_set().
{
  if (_mesh_sys)
    this->_do_elem_position_set(theta);
}
void libMesh::FEMContext::elem_reinit (Realtheta) [virtual], [inherited]
Reinitialize all my FEM context data on a given element for the given system Reinitialize Elem and FE objects if necessary for integration at a new point in time: specifically, handle moving elements in moving mesh schemes.
Reimplemented from libMesh::DiffContext.
Definition at line 1358 of file fem_context.C.
References libMesh::FEMContext::_mesh_sys, libMesh::FEMContext::_update_time_from_system(), libMesh::FEMContext::elem_fe_reinit(), libMesh::FEMContext::elem_position_set(), and libMesh::n_threads.
{
  // Update the "time" variable of this context object
  this->_update_time_from_system(theta);
  // Handle a moving element if necessary.
  if (_mesh_sys)
    // We assume that the ``default'' state
    // of the mesh is its final, theta=1.0
    // position, so we don't bother with
    // mesh motion in that case.
    if (theta != 1.0)
      {
        // FIXME - ALE is not threadsafe yet!
        libmesh_assert_equal_to (libMesh::n_threads(), 1);
        elem_position_set(theta);
      }
  elem_fe_reinit();
}
void libMesh::FEMContext::elem_side_reinit (Realtheta) [virtual], [inherited]
Reinitialize Elem and side FE objects if necessary for integration at a new point in time: specifically, handle moving elements in moving mesh schemes.
Reimplemented from libMesh::DiffContext.
Definition at line 1380 of file fem_context.C.
References libMesh::FEMContext::_mesh_sys, libMesh::FEMContext::_update_time_from_system(), libMesh::FEMContext::elem_position_set(), and libMesh::FEMContext::side_fe_reinit().
{
  // Update the "time" variable of this context object
  this->_update_time_from_system(theta);
  // Handle a moving element if necessary
  if (_mesh_sys)
    {
      // FIXME - not threadsafe yet!
      elem_position_set(theta);
      side_fe_reinit();
    }
}
Gradient libMesh::FEMContext::fixed_interior_gradient (unsigned intvar, unsigned intqp) const [inherited]
Returns the gradient of the fixed_solution variable var at the quadrature point qp on the current element interior. This API currently present for backward compatibility.
Definition at line 973 of file fem_context.C.
{
  Gradient du;
  this->fixed_interior_gradient( var, qp, du );
  return du;
}
template<typename OutputType > void libMesh::FEMContext::fixed_interior_gradient (unsigned intvar, unsigned intqp, OutputType &grad_u) const [inherited]
Returns the gradient of the fixed_solution variable var at the quadrature point qp on the current element interior. This is the preferred API.
Tensor libMesh::FEMContext::fixed_interior_hessian (unsigned intvar, unsigned intqp) const [inherited]
Returns the hessian of the fixed_solution variable var at the quadrature point qp on the current element interior. This API currently present for backward compatibility.
Definition at line 1020 of file fem_context.C.
{
  Tensor d2u;
  this->fixed_interior_hessian( var, qp, d2u );
  return d2u;
}
template<typename OutputType > void libMesh::FEMContext::fixed_interior_hessian (unsigned intvar, unsigned intqp, OutputType &hess_u) const [inherited]
Returns the hessian of the fixed_solution variable var at the quadrature point qp on the current element interior. This is the preferred API.
Definition at line 1031 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::FEGenericBase< T >::get_d2phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<
    typename TensorTools::DecrementRank<
    typename TensorTools::DecrementRank<
    OutputType>::type>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_fixed_subsolutions.size(), var);
  libmesh_assert(elem_fixed_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_fixed_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor> > &d2phi = fe->get_d2phi();
  // Accumulate solution second derivatives
  d2u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    d2u.add_scaled(d2phi[l][qp], coef(l));
  return;
}
Number libMesh::FEMContext::fixed_interior_value (unsigned intvar, unsigned intqp) const [inherited]
Returns the value of the fixed_solution variable var at the quadrature point qp on the current element interior. This API currently present for backward compatibility.
Definition at line 928 of file fem_context.C.
{
  Number u = 0.;
  this->fixed_interior_value( var, qp, u );
  return u;
}
template<typename OutputType > void libMesh::FEMContext::fixed_interior_value (unsigned intvar, unsigned intqp, OutputType &u) const [inherited]
Returns the value of the fixed_solution variable var at the quadrature point qp on the current element interior. This is the preferred API.
Definition at line 940 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::FEGenericBase< T >::get_phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_fixed_subsolutions.size(), var);
  libmesh_assert(elem_fixed_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_fixed_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<OutputShape> > &phi = fe->get_phi();
  // Accumulate solution value
  u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    u += phi[l][qp] * coef(l);
  return;
}
Gradient libMesh::FEMContext::fixed_point_gradient (unsigned intvar, const Point &p) const [inherited]
Returns the gradient of the fixed_solution variable var at the physical point p on the current element. This API currently present for backward compatibility.
Definition at line 1253 of file fem_context.C.
{
  Gradient grad_u;
  this->fixed_point_gradient( var, p, grad_u );
  return grad_u;
}
template<typename OutputType > void libMesh::FEMContext::fixed_point_gradient (unsigned intvar, const Point &p, OutputType &grad_u) const [inherited]
Returns the gradient of the fixed_solution variable var at the physical point p on the current element. This is the preferred API.
Definition at line 1265 of file fem_context.C.
References libMesh::FEMContext::build_new_fe(), libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal
    <typename TensorTools::DecrementRank<OutputType>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_fixed_subsolutions.size(), var);
  libmesh_assert(elem_fixed_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_fixed_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Build a FE for calculating u(p)
  AutoPtr<FEGenericBase<OutputShape> > fe_new = this->build_new_fe( fe, p );
  // Get the values of the shape function derivatives
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient> >& dphi = fe_new->get_dphi();
  grad_u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    grad_u.add_scaled(dphi[l][0], coef(l));
  return;
}
Tensor libMesh::FEMContext::fixed_point_hessian (unsigned intvar, const Point &p) const [inherited]
Returns the hessian of the fixed_solution variable var at the physical point p on the current element. This API currently present for backward compatibility.
Definition at line 1303 of file fem_context.C.
{
  Tensor hess_u;
  this->fixed_point_hessian( var, p, hess_u );
  return hess_u;
}
template<typename OutputType > void libMesh::FEMContext::fixed_point_hessian (unsigned intvar, const Point &p, OutputType &hess_u) const [inherited]
Returns the hessian of the fixed_solution variable var at the physical point p on the current element. This is the preferred API.
Definition at line 1315 of file fem_context.C.
References libMesh::FEMContext::build_new_fe(), libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<
    typename TensorTools::DecrementRank<
    typename TensorTools::DecrementRank<
    OutputType>::type>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_fixed_subsolutions.size(), var);
  libmesh_assert(elem_fixed_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_fixed_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Build a FE for calculating u(p)
  AutoPtr<FEGenericBase<OutputShape> > fe_new = this->build_new_fe( fe, p );
  // Get the values of the shape function derivatives
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor> >& d2phi = fe_new->get_d2phi();
  hess_u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    hess_u.add_scaled(d2phi[l][0], coef(l));
  return;
}
Number libMesh::FEMContext::fixed_point_value (unsigned intvar, const Point &p) const [inherited]
Returns the value of the fixed_solution variable var at the physical point p on the current element. This API currently present for backward compatibility.
Definition at line 1208 of file fem_context.C.
{
  Number u = 0.;
  this->fixed_point_value( var, p, u );
  return u;
}
template<typename OutputType > void libMesh::FEMContext::fixed_point_value (unsigned intvar, const Point &p, OutputType &u) const [inherited]
Returns the value of the fixed_solution variable var at the physical point p on the current element. This is the preferred API.
Definition at line 1218 of file fem_context.C.
References libMesh::FEMContext::build_new_fe(), libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_fixed_subsolutions.size(), var);
  libmesh_assert(elem_fixed_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_fixed_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Build a FE for calculating u(p)
  AutoPtr<FEGenericBase<OutputShape> > fe_new = this->build_new_fe( fe, p );
  // Get the values of the shape function derivatives
  const std::vector<std::vector<OutputShape> >& phi = fe_new->get_phi();
  u = 0.;
  for (unsigned int l=0; l != n_dofs; l++)
    u += phi[l][0] * coef(l);
  return;
}
Gradient libMesh::FEMContext::fixed_side_gradient (unsigned intvar, unsigned intqp) const [inherited]
Returns the gradient of the fixed_solution variable var at the quadrature point qp on the current element side. This API currently present for backward compatibility.
Definition at line 1113 of file fem_context.C.
{
  Gradient du;
  this->fixed_side_gradient( var, qp, du );
  return du;
}
template<typename OutputType > void libMesh::FEMContext::fixed_side_gradient (unsigned intvar, unsigned intqp, OutputType &grad_u) const [inherited]
Returns the gradient of the fixed_solution variable var at the quadrature point qp on the current element side. This is the preferred API.
Definition at line 1124 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::FEGenericBase< T >::get_dphi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal
    <typename TensorTools::DecrementRank<OutputType>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_fixed_subsolutions.size(), var);
  libmesh_assert(elem_fixed_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_fixed_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient> > &dphi = the_side_fe->get_dphi();
  // Accumulate solution derivatives
  du = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    du.add_scaled(dphi[l][qp], coef(l));
  return;
}
Tensor libMesh::FEMContext::fixed_side_hessian (unsigned intvar, unsigned intqp) const [inherited]
Returns the hessian of the fixed_solution variable var at the quadrature point qp on the current element side. This API currently present for backward compatibility.
Definition at line 1160 of file fem_context.C.
{
  Tensor d2u;
  this->fixed_side_hessian( var, qp, d2u );
  return d2u;
}
template<typename OutputType > void libMesh::FEMContext::fixed_side_hessian (unsigned intvar, unsigned intqp, OutputType &hess_u) const [inherited]
Returns the hessian of the fixed_solution variable var at the quadrature point qp on the current element side. This is the preferred API.
Definition at line 1170 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::FEGenericBase< T >::get_d2phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<
    typename TensorTools::DecrementRank<
    typename TensorTools::DecrementRank<
    OutputType>::type>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_fixed_subsolutions.size(), var);
  libmesh_assert(elem_fixed_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_fixed_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor> > &d2phi = the_side_fe->get_d2phi();
  // Accumulate solution second derivatives
  d2u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    d2u.add_scaled(d2phi[l][qp], coef(l));
  return;
}
Number libMesh::FEMContext::fixed_side_value (unsigned intvar, unsigned intqp) const [inherited]
Returns the value of the fixed_solution variable var at the quadrature point qp on the current element side. This API currently present for backward compatibility.
Definition at line 1069 of file fem_context.C.
{
  Number u = 0.;
  this->fixed_side_value( var, qp, u );
  return u;
}
template<typename OutputType > void libMesh::FEMContext::fixed_side_value (unsigned intvar, unsigned intqp, OutputType &u) const [inherited]
Returns the value of the fixed_solution variable var at the quadrature point qp on the current element side. This is the preferred API.
Definition at line 1080 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::FEGenericBase< T >::get_phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_fixed_subsolutions.size(), var);
  libmesh_assert(elem_fixed_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_fixed_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<OutputShape> > &phi = the_side_fe->get_phi();
  // Accumulate solution value
  u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    u += phi[l][qp] * coef(l);
  return;
}
Real libMesh::DiffContext::get_deltat_value () [inherited]
Returns the value currently pointed to by this class's _deltat member
Definition at line 117 of file diff_context.C.
References libMesh::DiffContext::_deltat, and libMesh::libmesh_assert().
Referenced by libMesh::FEMContext::_update_time_from_system().
{
  libmesh_assert(_deltat);
  return *_deltat;
}
unsigned char libMesh::FEMContext::get_dim () const [inline], [inherited]
Accessor for cached element dimension
Definition at line 636 of file fem_context.h.
References libMesh::FEMContext::dim.
  { return dim; }
const std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices () const [inline], [inherited]
Accessor for element dof indices
Definition at line 235 of file diff_context.h.
References libMesh::DiffContext::dof_indices.
Referenced by libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::numerical_jacobian(), libMesh::EulerSolver::side_residual(), and libMesh::Euler2Solver::side_residual().
  { return dof_indices; }
std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices () [inline], [inherited]
Non-const accessor for element dof indices
Definition at line 241 of file diff_context.h.
References libMesh::DiffContext::dof_indices.
  { return dof_indices; }
const std::vector<dof_id_type>& libMesh::DiffContext::get_dof_indices (unsigned intvar) const [inline], [inherited]
Accessor for element dof indices of a particular variable corresponding to the index argument.
Definition at line 248 of file diff_context.h.
References libMesh::DiffContext::dof_indices_var.
  { return dof_indices_var[var]; }
unsigned char libMesh::FEMContext::get_edge () const [inline], [inherited]
Accessor for current edge of Elem object
Definition at line 630 of file fem_context.h.
References libMesh::FEMContext::edge.
  { return edge; }
template<typename OutputShape > void libMesh::FEMContext::get_edge_fe (unsigned intvar, FEGenericBase< OutputShape > *&fe) const [inline], [inherited]
Accessor for edge (3D only!) finite element object for variable var.
Definition at line 796 of file fem_context.h.
References libMesh::FEMContext::_edge_fe_var.
{
  libmesh_assert_less ( var, _edge_fe_var.size() );
  fe = libmesh_cast_ptr<FEGenericBase<OutputShape>*>( _edge_fe_var[var] );
}
FEBase * libMesh::FEMContext::get_edge_fe (unsigned intvar) const [inline], [inherited]
Accessor for edge finite element object for scalar-valued variable var.
Definition at line 803 of file fem_context.h.
References libMesh::FEMContext::_edge_fe_var.
{
  libmesh_assert_less ( var, _edge_fe_var.size() );
  return libmesh_cast_ptr<FEBase*>( _edge_fe_var[var] );
}
const QBase& libMesh::FEMContext::get_edge_qrule () const [inline], [inherited]
Accessor for element edge quadrature rule.
Definition at line 541 of file fem_context.h.
References libMesh::FEMContext::edge_qrule.
  { return *(this->edge_qrule); }
const Elem& libMesh::FEMContext::get_elem () const [inline], [inherited]
Accessor for current Elem object
Definition at line 612 of file fem_context.h.
References libMesh::FEMContext::elem.
Referenced by libMesh::FEMSystem::mesh_position_set(), and libMesh::FEMSystem::numerical_jacobian().
  { return *elem; }
Elem& libMesh::FEMContext::get_elem () [inline], [inherited]
Accessor for current Elem object
Definition at line 618 of file fem_context.h.
References libMesh::FEMContext::elem.
  { return *(const_cast<Elem*>(elem)); }
const DenseMatrix<Number>& libMesh::DGFEMContext::get_elem_elem_jacobian () const [inline]
Const accessor for element-element Jacobian.
Definition at line 110 of file dg_fem_context.h.
References _elem_elem_jacobian.
  { return _elem_elem_jacobian; }
DenseMatrix<Number>& libMesh::DGFEMContext::get_elem_elem_jacobian () [inline]
Non-const accessor for element-element Jacobian.
Definition at line 116 of file dg_fem_context.h.
References _elem_elem_jacobian.
  { return _elem_elem_jacobian; }
const DenseSubMatrix<Number>& libMesh::DGFEMContext::get_elem_elem_jacobian (unsigned intvar1, unsigned intvar2) const [inline]
Const accessor for element-element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 123 of file dg_fem_context.h.
References _elem_elem_subjacobians.
  { return *(_elem_elem_subjacobians[var1][var2]); }
DenseSubMatrix<Number>& libMesh::DGFEMContext::get_elem_elem_jacobian (unsigned intvar1, unsigned intvar2) [inline]
Non-const accessor for element-element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 130 of file dg_fem_context.h.
References _elem_elem_subjacobians.
  { return *(_elem_elem_subjacobians[var1][var2]); }
const DenseVector<Number>& libMesh::DiffContext::get_elem_fixed_solution () const [inline], [inherited]
Accessor for element fixed solution.
Definition at line 126 of file diff_context.h.
References libMesh::DiffContext::elem_fixed_solution.
Referenced by libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::SteadySolver::element_residual(), libMesh::EulerSolver::side_residual(), libMesh::Euler2Solver::side_residual(), and libMesh::SteadySolver::side_residual().
  { return elem_fixed_solution; }
DenseVector<Number>& libMesh::DiffContext::get_elem_fixed_solution () [inline], [inherited]
Non-const accessor for element fixed solution.
Definition at line 132 of file diff_context.h.
References libMesh::DiffContext::elem_fixed_solution.
  { return elem_fixed_solution; }
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_fixed_solution (unsigned intvar) const [inline], [inherited]
Accessor for element fixed solution of a particular variable corresponding to the variable index argument.
Definition at line 139 of file diff_context.h.
References libMesh::DiffContext::elem_fixed_subsolutions.
  { return *(elem_fixed_subsolutions[var]); }
const DenseMatrix<Number>& libMesh::DiffContext::get_elem_jacobian () const [inline], [inherited]
Const accessor for element Jacobian.
Definition at line 171 of file diff_context.h.
References libMesh::DiffContext::elem_jacobian.
Referenced by libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::FEMSystem::numerical_jacobian(), libMesh::EulerSolver::side_residual(), and libMesh::Euler2Solver::side_residual().
  { return elem_jacobian; }
DenseMatrix<Number>& libMesh::DiffContext::get_elem_jacobian () [inline], [inherited]
Non-const accessor for element Jacobian.
Definition at line 177 of file diff_context.h.
References libMesh::DiffContext::elem_jacobian.
  { return elem_jacobian; }
const DenseSubMatrix<Number>& libMesh::DiffContext::get_elem_jacobian (unsigned intvar1, unsigned intvar2) const [inline], [inherited]
Const accessor for element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 184 of file diff_context.h.
References libMesh::DiffContext::elem_subjacobians.
  { return *(elem_subjacobians[var1][var2]); }
DenseSubMatrix<Number>& libMesh::DiffContext::get_elem_jacobian (unsigned intvar1, unsigned intvar2) [inline], [inherited]
Non-const accessor for element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 191 of file diff_context.h.
References libMesh::DiffContext::elem_subjacobians.
  { return *(elem_subjacobians[var1][var2]); }
const DenseMatrix<Number>& libMesh::DGFEMContext::get_elem_neighbor_jacobian () const [inline]
Const accessor for element-neighbor Jacobian.
Definition at line 136 of file dg_fem_context.h.
References _elem_neighbor_jacobian.
  { return _elem_neighbor_jacobian; }
DenseMatrix<Number>& libMesh::DGFEMContext::get_elem_neighbor_jacobian () [inline]
Non-const accessor for element -neighborJacobian.
Definition at line 142 of file dg_fem_context.h.
References _elem_neighbor_jacobian.
  { return _elem_neighbor_jacobian; }
const DenseSubMatrix<Number>& libMesh::DGFEMContext::get_elem_neighbor_jacobian (unsigned intvar1, unsigned intvar2) const [inline]
Const accessor for element-neighbor Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 149 of file dg_fem_context.h.
References _elem_neighbor_subjacobians.
  { return *(_elem_neighbor_subjacobians[var1][var2]); }
DenseSubMatrix<Number>& libMesh::DGFEMContext::get_elem_neighbor_jacobian (unsigned intvar1, unsigned intvar2) [inline]
Non-const accessor for element-neighbor Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 156 of file dg_fem_context.h.
References _elem_neighbor_subjacobians.
  { return *(_elem_neighbor_subjacobians[var1][var2]); }
const DenseVector<Number>& libMesh::DiffContext::get_elem_residual () const [inline], [inherited]
Const accessor for element residual.
Definition at line 145 of file diff_context.h.
References libMesh::DiffContext::elem_residual.
Referenced by libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::FEMSystem::numerical_jacobian(), libMesh::EulerSolver::side_residual(), and libMesh::Euler2Solver::side_residual().
  { return elem_residual; }
DenseVector<Number>& libMesh::DiffContext::get_elem_residual () [inline], [inherited]
Non-const accessor for element residual.
Definition at line 151 of file diff_context.h.
References libMesh::DiffContext::elem_residual.
  { return elem_residual; }
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_residual (unsigned intvar) const [inline], [inherited]
Const accessor for element residual of a particular variable corresponding to the variable index argument.
Definition at line 158 of file diff_context.h.
References libMesh::DiffContext::elem_subresiduals.
  { return *(elem_subresiduals[var]); }
DenseSubVector<Number>& libMesh::DiffContext::get_elem_residual (unsigned intvar) [inline], [inherited]
Non-const accessor for element residual of a particular variable corresponding to the variable index argument.
Definition at line 165 of file diff_context.h.
References libMesh::DiffContext::elem_subresiduals.
  { return *(elem_subresiduals[var]); }
const DenseVector<Number>& libMesh::DiffContext::get_elem_solution () const [inline], [inherited]
Accessor for element solution.
Definition at line 107 of file diff_context.h.
References libMesh::DiffContext::elem_solution.
Referenced by libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::SteadySolver::element_residual(), libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::numerical_jacobian(), libMesh::EulerSolver::side_residual(), libMesh::Euler2Solver::side_residual(), and libMesh::SteadySolver::side_residual().
  { return elem_solution; }
DenseVector<Number>& libMesh::DiffContext::get_elem_solution () [inline], [inherited]
Non-const accessor for element solution.
Definition at line 113 of file diff_context.h.
References libMesh::DiffContext::elem_solution.
  { return elem_solution; }
const DenseSubVector<Number>& libMesh::DiffContext::get_elem_solution (unsigned intvar) const [inline], [inherited]
Accessor for element solution of a particular variable corresponding to the variable index argument.
Definition at line 120 of file diff_context.h.
References libMesh::DiffContext::elem_subsolutions.
  { return *(elem_subsolutions[var]); }
Real libMesh::DiffContext::get_elem_solution_derivative () const [inline], [inherited]
Definition at line 269 of file diff_context.h.
References libMesh::DiffContext::elem_solution_derivative.
  { return elem_solution_derivative; }
template<typename OutputShape > void libMesh::FEMContext::get_element_fe (unsigned intvar, FEGenericBase< OutputShape > *&fe) const [inline], [inherited]
Accessor for interior finite element object for variable var.
Definition at line 766 of file fem_context.h.
References libMesh::FEMContext::_element_fe_var.
Referenced by libMesh::FEMSystem::init_context().
{
  libmesh_assert_less ( var, _element_fe_var.size() );
  fe = libmesh_cast_ptr<FEGenericBase<OutputShape>*>( _element_fe_var[var] );
}
FEBase * libMesh::FEMContext::get_element_fe (unsigned intvar) const [inline], [inherited]
Accessor for interior finite element object for scalar-valued variable var.
Definition at line 773 of file fem_context.h.
References libMesh::FEMContext::_element_fe_var.
{
  libmesh_assert_less ( var, _element_fe_var.size() );
  return libmesh_cast_ptr<FEBase*>( _element_fe_var[var] );
}
const QBase& libMesh::FEMContext::get_element_qrule () const [inline], [inherited]
Accessor for element interior quadrature rule.
Definition at line 529 of file fem_context.h.
References libMesh::FEMContext::element_qrule.
  { return *(this->element_qrule); }
Real libMesh::DiffContext::get_fixed_solution_derivative () const [inline], [inherited]
Definition at line 272 of file diff_context.h.
References libMesh::DiffContext::fixed_solution_derivative.
  { return fixed_solution_derivative; }
DenseSubVector< Number > & libMesh::DiffContext::get_localized_subvector (const NumericVector< Number > &_localized_vector, unsigned int_var) [inherited]
Return a reference to DenseSubVector localization of _localized_vector at variable _var contained in the localized_vectors map
Definition at line 155 of file diff_context.C.
References libMesh::DiffContext::localized_vectors.
Referenced by libMesh::FEMContext::interior_values().
{
  return *localized_vectors[&_localized_vector].second[_var];
}
const DenseSubVector< Number > & libMesh::DiffContext::get_localized_subvector (const NumericVector< Number > &_localized_vector, unsigned int_var) const [inherited]
const accessible version of get_localized_subvector function
Definition at line 161 of file diff_context.C.
References libMesh::libmesh_assert(), and libMesh::DiffContext::localized_vectors.
{
  std::map<const NumericVector<Number>*, std::pair<DenseVector<Number>, std::vector<DenseSubVector<Number>*> > >::const_iterator
    localized_vectors_it = localized_vectors.find(&_localized_vector);
  libmesh_assert(localized_vectors_it != localized_vectors.end());
  return *localized_vectors_it->second.second[_var];
}
DenseVector< Number > & libMesh::DiffContext::get_localized_vector (const NumericVector< Number > &_localized_vector) [inherited]
Return a reference to DenseVector localization of _localized_vector contained in the localized_vectors map
Definition at line 140 of file diff_context.C.
References libMesh::DiffContext::localized_vectors.
{
  return localized_vectors[&_localized_vector].first;
}
const DenseVector< Number > & libMesh::DiffContext::get_localized_vector (const NumericVector< Number > &_localized_vector) const [inherited]
const accessible version of get_localized_vector function
Definition at line 146 of file diff_context.C.
References libMesh::libmesh_assert(), and libMesh::DiffContext::localized_vectors.
{
  std::map<const NumericVector<Number>*, std::pair<DenseVector<Number>, std::vector<DenseSubVector<Number>*> > >::const_iterator
    localized_vectors_it = localized_vectors.find(&_localized_vector);
  libmesh_assert(localized_vectors_it != localized_vectors.end());
  return localized_vectors_it->second.first;
}
const System* libMesh::FEMContext::get_mesh_system () const [inline], [inherited]
Accessor for moving mesh System
Definition at line 558 of file fem_context.h.
References libMesh::FEMContext::_mesh_sys.
  { return this->_mesh_sys; }
System* libMesh::FEMContext::get_mesh_system () [inline], [inherited]
Accessor for moving mesh System
Definition at line 564 of file fem_context.h.
References libMesh::FEMContext::_mesh_sys.
  { return this->_mesh_sys; }
unsigned int libMesh::FEMContext::get_mesh_x_var () const [inline], [inherited]
Accessor for x-variable of moving mesh System
Definition at line 570 of file fem_context.h.
References libMesh::FEMContext::_mesh_x_var.
  { return _mesh_x_var; }
unsigned int libMesh::FEMContext::get_mesh_y_var () const [inline], [inherited]
Accessor for y-variable of moving mesh System
Definition at line 584 of file fem_context.h.
References libMesh::FEMContext::_mesh_y_var.
  { return _mesh_y_var; }
unsigned int libMesh::FEMContext::get_mesh_z_var () const [inline], [inherited]
Accessor for z-variable of moving mesh System
Definition at line 598 of file fem_context.h.
References libMesh::FEMContext::_mesh_z_var.
  { return _mesh_z_var; }
const Elem& libMesh::DGFEMContext::get_neighbor () const [inline]
Accessor for current neighbor Elem object for assembling DG terms.
Definition at line 225 of file dg_fem_context.h.
References _neighbor.
Referenced by neighbor_side_fe_reinit().
  { return *_neighbor; }
const std::vector<dof_id_type>& libMesh::DGFEMContext::get_neighbor_dof_indices () const [inline]
Accessor for neighbor dof indices
Definition at line 71 of file dg_fem_context.h.
References _neighbor_dof_indices.
  { return _neighbor_dof_indices; }
const std::vector<dof_id_type>& libMesh::DGFEMContext::get_neighbor_dof_indices (unsigned intvar) const [inline]
Accessor for element dof indices of a particular variable corresponding to the index argument.
Definition at line 78 of file dg_fem_context.h.
References _neighbor_dof_indices_var.
  { return _neighbor_dof_indices_var[var]; }
const DenseMatrix<Number>& libMesh::DGFEMContext::get_neighbor_elem_jacobian () const [inline]
Const accessor for element-neighbor Jacobian.
Definition at line 162 of file dg_fem_context.h.
References _neighbor_elem_jacobian.
  { return _neighbor_elem_jacobian; }
DenseMatrix<Number>& libMesh::DGFEMContext::get_neighbor_elem_jacobian () [inline]
Non-const accessor for element Jacobian.
Definition at line 168 of file dg_fem_context.h.
References _neighbor_elem_jacobian.
  { return _neighbor_elem_jacobian; }
const DenseSubMatrix<Number>& libMesh::DGFEMContext::get_neighbor_elem_jacobian (unsigned intvar1, unsigned intvar2) const [inline]
Const accessor for neighbor-element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 175 of file dg_fem_context.h.
References _neighbor_elem_subjacobians.
  { return *(_neighbor_elem_subjacobians[var1][var2]); }
DenseSubMatrix<Number>& libMesh::DGFEMContext::get_neighbor_elem_jacobian (unsigned intvar1, unsigned intvar2) [inline]
Non-const accessor for neighbor-element Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 182 of file dg_fem_context.h.
References _neighbor_elem_subjacobians.
  { return *(_neighbor_elem_subjacobians[var1][var2]); }
const DenseMatrix<Number>& libMesh::DGFEMContext::get_neighbor_neighbor_jacobian () const [inline]
Const accessor for element-neighbor Jacobian.
Definition at line 188 of file dg_fem_context.h.
References _neighbor_neighbor_jacobian.
  { return _neighbor_neighbor_jacobian; }
DenseMatrix<Number>& libMesh::DGFEMContext::get_neighbor_neighbor_jacobian () [inline]
Non-const accessor for element Jacobian.
Definition at line 194 of file dg_fem_context.h.
References _neighbor_neighbor_jacobian.
  { return _neighbor_neighbor_jacobian; }
const DenseSubMatrix<Number>& libMesh::DGFEMContext::get_neighbor_neighbor_jacobian (unsigned intvar1, unsigned intvar2) const [inline]
Const accessor for neighbor-neighbor Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 201 of file dg_fem_context.h.
References _neighbor_neighbor_subjacobians.
  { return *(_neighbor_neighbor_subjacobians[var1][var2]); }
DenseSubMatrix<Number>& libMesh::DGFEMContext::get_neighbor_neighbor_jacobian (unsigned intvar1, unsigned intvar2) [inline]
Non-const accessor for neighbor-neighbor Jacobian of particular variables corresponding to the variable index arguments.
Definition at line 208 of file dg_fem_context.h.
References _neighbor_neighbor_subjacobians.
  { return *(_neighbor_neighbor_subjacobians[var1][var2]); }
const DenseVector<Number>& libMesh::DGFEMContext::get_neighbor_residual () const [inline]
Const accessor for neighbor residual.
Definition at line 84 of file dg_fem_context.h.
References _neighbor_residual.
  { return _neighbor_residual; }
DenseVector<Number>& libMesh::DGFEMContext::get_neighbor_residual () [inline]
Non-const accessor for neighbor residual.
Definition at line 90 of file dg_fem_context.h.
References _neighbor_residual.
  { return _neighbor_residual; }
const DenseSubVector<Number>& libMesh::DGFEMContext::get_neighbor_residual (unsigned intvar) const [inline]
Const accessor for neighbor residual of a particular variable corresponding to the variable index argument.
Definition at line 97 of file dg_fem_context.h.
References _neighbor_subresiduals.
  { return *(_neighbor_subresiduals[var]); }
DenseSubVector<Number>& libMesh::DGFEMContext::get_neighbor_residual (unsigned intvar) [inline]
Non-const accessor for neighbor residual of a particular variable corresponding to the variable index argument.
Definition at line 104 of file dg_fem_context.h.
References _neighbor_subresiduals.
  { return *(_neighbor_subresiduals[var]); }
template<typename OutputShape > void libMesh::DGFEMContext::get_neighbor_side_fe (unsigned intvar, FEGenericBase< OutputShape > *&fe) const [inline]
Accessor for neighbor edge/face (2D/3D) finite element object for variable var.
Definition at line 300 of file dg_fem_context.h.
References _neighbor_side_fe_var.
{
  libmesh_assert_less ( var, _neighbor_side_fe_var.size() );
  fe = libmesh_cast_ptr<FEGenericBase<OutputShape>*>( _neighbor_side_fe_var[var] );
}
const std::vector<DenseVector<Number> >& libMesh::DiffContext::get_qoi_derivatives () const [inline], [inherited]
Const accessor for QoI derivatives.
Definition at line 209 of file diff_context.h.
References libMesh::DiffContext::elem_qoi_derivative.
  { return elem_qoi_derivative; }
std::vector<DenseVector<Number> >& libMesh::DiffContext::get_qoi_derivatives () [inline], [inherited]
Non-const accessor for QoI derivatives.
Definition at line 215 of file diff_context.h.
References libMesh::DiffContext::elem_qoi_derivative.
  { return elem_qoi_derivative; }
const DenseSubVector<Number>& libMesh::DiffContext::get_qoi_derivatives (unsigned intqoi, unsigned intvar) const [inline], [inherited]
Const accessor for QoI derivative of a particular qoi and variable corresponding to the index arguments.
Definition at line 222 of file diff_context.h.
References libMesh::DiffContext::elem_qoi_subderivatives.
  { return *(elem_qoi_subderivatives[qoi][var]); }
DenseSubVector<Number>& libMesh::DiffContext::get_qoi_derivatives (unsigned intqoi, unsigned intvar) [inline], [inherited]
Non-const accessor for QoI derivative of a particular qoi and variable corresponding to the index arguments.
Definition at line 229 of file diff_context.h.
References libMesh::DiffContext::elem_qoi_subderivatives.
  { return *(elem_qoi_subderivatives[qoi][var]); }
const std::vector<Number>& libMesh::DiffContext::get_qois () const [inline], [inherited]
Const accessor for QoI vector.
Definition at line 197 of file diff_context.h.
References libMesh::DiffContext::elem_qoi.
  { return elem_qoi; }
std::vector<Number>& libMesh::DiffContext::get_qois () [inline], [inherited]
Non-const accessor for QoI vector.
Definition at line 203 of file diff_context.h.
References libMesh::DiffContext::elem_qoi.
  { return elem_qoi; }
unsigned char libMesh::FEMContext::get_side () const [inline], [inherited]
Accessor for current side of Elem object
Definition at line 624 of file fem_context.h.
References libMesh::FEMContext::side.
  { return side; }
template<typename OutputShape > void libMesh::FEMContext::get_side_fe (unsigned intvar, FEGenericBase< OutputShape > *&fe) const [inline], [inherited]
Accessor for edge/face (2D/3D) finite element object for variable var.
Definition at line 781 of file fem_context.h.
References libMesh::FEMContext::_side_fe_var.
{
  libmesh_assert_less ( var, _side_fe_var.size() );
  fe = libmesh_cast_ptr<FEGenericBase<OutputShape>*>( _side_fe_var[var] );
}
FEBase * libMesh::FEMContext::get_side_fe (unsigned intvar) const [inline], [inherited]
Accessor for side finite element object for scalar-valued variable var.
Definition at line 788 of file fem_context.h.
References libMesh::FEMContext::_side_fe_var.
{
  libmesh_assert_less ( var, _side_fe_var.size() );
  return libmesh_cast_ptr<FEBase*>( _side_fe_var[var] );
}
const QBase& libMesh::FEMContext::get_side_qrule () const [inline], [inherited]
Accessor for element side quadrature rule.
Definition at line 535 of file fem_context.h.
References libMesh::FEMContext::side_qrule.
  { return *(this->side_qrule); }
const System& libMesh::DiffContext::get_system () const [inline], [inherited]
Accessor for associated system.
Definition at line 101 of file diff_context.h.
References libMesh::DiffContext::_system.
Referenced by neighbor_side_fe_reinit().
  { return _system; }
Real libMesh::DiffContext::get_system_time () const [inline], [inherited]
Accessor for the time variable stored in the system class.
Definition at line 254 of file diff_context.h.
References libMesh::DiffContext::system_time.
  { return system_time; }
Real libMesh::DiffContext::get_time () const [inline], [inherited]
Accessor for the time for which the current nonlinear_solution is defined.
Definition at line 260 of file diff_context.h.
References libMesh::DiffContext::time.
  { return time; }
bool libMesh::FEMContext::has_side_boundary_id (boundary_id_typeid) const [inherited]
Reports if the boundary id is found on the current side
Definition at line 143 of file fem_context.C.
References libMesh::FEMContext::_boundary_info, libMesh::FEMContext::elem, libMesh::BoundaryInfo::has_boundary_id(), and libMesh::FEMContext::side.
{
  return _boundary_info->has_boundary_id(elem, side, id);
}
template<typename OutputType > template void libMesh::FEMContext::interior_curl< Gradient > (unsigned intvar, unsigned intqp, OutputType &curl_u) const [inherited]
Returns the curl of the solution variable var at the physical point p on the current element.
Definition at line 416 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::FEGenericBase< T >::get_curl_phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputShape> > &curl_phi = fe->get_curl_phi();
  // Accumulate solution curl
  curl_u = 0.;
  for (unsigned int l=0; l != n_dofs; l++)
    curl_u.add_scaled(curl_phi[l][qp], coef(l));
  return;
}
template<typename OutputType > template void libMesh::FEMContext::interior_div< Number > (unsigned intvar, unsigned intqp, OutputType &div_u) const [inherited]
Returns the divergence of the solution variable var at the physical point p on the current element.
Definition at line 449 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::FEGenericBase< T >::get_div_phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename
    TensorTools::IncrementRank
    <typename TensorTools::MakeReal<OutputType>::type>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputDivergence> > &div_phi = fe->get_div_phi();
  // Accumulate solution curl
  div_u = 0.;
  for (unsigned int l=0; l != n_dofs; l++)
    div_u += div_phi[l][qp] * coef(l);
  return;
}
Gradient libMesh::FEMContext::interior_gradient (unsigned intvar, unsigned intqp) const [inherited]
Returns the gradient of the solution variable var at the quadrature point qp on the current element interior. This API currently present for backward compatibility.
Definition at line 235 of file fem_context.C.
{
  Gradient du;
  this->interior_gradient( var, qp, du );
  return du;
}
template<typename OutputType > void libMesh::FEMContext::interior_gradient (unsigned intvar, unsigned intqp, OutputType &du) const [inherited]
Returns the gradient of the solution variable var at the quadrature point qp on the current element interior. This is the preferred API.
Definition at line 247 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::FEGenericBase< T >::get_dphi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal
    <typename TensorTools::DecrementRank<OutputType>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient> > &dphi = fe->get_dphi();
  // Accumulate solution derivatives
  du = 0;
  for (unsigned int l=0; l != n_dofs; l++)
    du.add_scaled(dphi[l][qp], coef(l));
  return;
}
template<typename OutputType > template void libMesh::FEMContext::interior_gradients< Tensor > (unsigned intvar, const NumericVector< Number > &_system_vector, std::vector< OutputType > &interior_gradients_vector) const [inherited]
Fills a vector with the gradient of the solution variable var at all the quadrature points in the current element interior. This is the preferred API.
Definition at line 284 of file fem_context.C.
References libMesh::FEGenericBase< T >::get_dphi(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal
    <typename TensorTools::DecrementRank<OutputType>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  const DenseSubVector<Number> &coef = get_localized_subvector(_system_vector, var);
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient> > &dphi = fe->get_dphi();
  // Loop over all the q_points in this finite element
  for (unsigned int qp=0; qp != du_vals.size(); qp++)
    {
      OutputType &du = du_vals[qp];
      // Compute the gradient at this q_point
      du = 0;
      for (unsigned int l=0; l != n_dofs; l++)
        du.add_scaled(dphi[l][qp], coef(l));
    }
  return;
}
Tensor libMesh::FEMContext::interior_hessian (unsigned intvar, unsigned intqp) const [inherited]
Returns the hessian of the solution variable var at the quadrature point qp on the current element interior. This API currently present for backward compatibility.
Definition at line 323 of file fem_context.C.
{
  Tensor d2u;
  this->interior_hessian( var, qp, d2u );
  return d2u;
}
template<typename OutputType > void libMesh::FEMContext::interior_hessian (unsigned intvar, unsigned intqp, OutputType &d2u) const [inherited]
Returns the hessian of the solution variable var at the quadrature point qp on the current element interior. This is the preferred API.
Definition at line 333 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::FEGenericBase< T >::get_d2phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<
    typename TensorTools::DecrementRank<
    typename TensorTools::DecrementRank<
    OutputType>::type>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor> > &d2phi = fe->get_d2phi();
  // Accumulate solution second derivatives
  d2u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    d2u.add_scaled(d2phi[l][qp], coef(l));
  return;
}
template<typename OutputType > template void libMesh::FEMContext::interior_hessians< Tensor > (unsigned intvar, const NumericVector< Number > &_system_vector, std::vector< OutputType > &d2u_vals) const [inherited]
Fills a vector of hessians of the _system_vector at the all the quadrature points in the current element interior. This is the preferred API.
Definition at line 371 of file fem_context.C.
References libMesh::FEGenericBase< T >::get_d2phi(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<
    typename TensorTools::DecrementRank<
    typename TensorTools::DecrementRank<
    OutputType>::type>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  const DenseSubVector<Number> &coef = get_localized_subvector(_system_vector, var);
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor> > &d2phi = fe->get_d2phi();
  // Loop over all the q_points in this finite element
  for (unsigned int qp=0; qp != d2u_vals.size(); qp++)
    {
      OutputType &d2u = d2u_vals[qp];
      // Compute the gradient at this q_point
      d2u = 0;
      for (unsigned int l=0; l != n_dofs; l++)
        d2u.add_scaled(d2phi[l][qp], coef(l));
    }
  return;
}
Number libMesh::FEMContext::interior_value (unsigned intvar, unsigned intqp) const [inherited]
Returns the value of the solution variable var at the quadrature point qp on the current element interior. This API currently present for backward compatibility.
Definition at line 156 of file fem_context.C.
{
  Number u = 0.;
  this->interior_value( var, qp, u );
  return u;
}
template<typename OutputType > void libMesh::FEMContext::interior_value (unsigned intvar, unsigned intqp, OutputType &u) const [inherited]
Returns the value of the solution variable var at the quadrature point qp on the current element interior. This is the preferred API.
Definition at line 166 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::FEGenericBase< T >::get_phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<OutputShape> > &phi = fe->get_phi();
  // Accumulate solution value
  u = 0.;
  for (unsigned int l=0; l != n_dofs; l++)
    u += phi[l][qp] * coef(l);
  return;
}
template<typename OutputType > template void libMesh::FEMContext::interior_values< Gradient > (unsigned intvar, const NumericVector< Number > &_system_vector, std::vector< OutputType > &interior_values_vector) const [inherited]
Fills a vector of values of the _system_vector at the all the quadrature points in the current element interior.
Definition at line 199 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::get_localized_subvector(), libMesh::FEGenericBase< T >::get_phi(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  const DenseSubVector<Number> &coef = get_localized_subvector(_system_vector, var);
  // Get the finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<OutputShape> > &phi = fe->get_phi();
  // Loop over all the q_points on this element
  for (unsigned int qp=0; qp != u_vals.size(); qp++)
    {
      OutputType &u = u_vals[qp];
      // Compute the value at this q_point
      u = 0.;
      for (unsigned int l=0; l != n_dofs; l++)
        u += phi[l][qp] * coef(l);
    }
  return;
}
bool libMesh::DiffContext::is_adjoint () const [inline], [inherited]
Accessor for querying whether we need to do a primal or adjoint solve
Definition at line 279 of file diff_context.h.
References libMesh::DiffContext::_is_adjoint.
Referenced by libMesh::FEMSystem::build_context().
  { return _is_adjoint; }
bool& libMesh::DiffContext::is_adjoint () [inline], [inherited]
Accessor for setting whether we need to do a primal or adjoint solve
Definition at line 286 of file diff_context.h.
References libMesh::DiffContext::_is_adjoint.
  { return _is_adjoint; }
unsigned int libMesh::DiffContext::n_vars () const [inline], [inherited]
Number of variables in solution.
Definition at line 95 of file diff_context.h.
References libMesh::DiffContext::dof_indices_var.
  { return libmesh_cast_int<unsigned int>(dof_indices_var.size()); }
void libMesh::DGFEMContext::neighbor_side_fe_reinit ()
Initialize neighbor side data needed to assemble DG terms. The neighbor element is determined by the current value of get_neighbor().
Definition at line 112 of file dg_fem_context.C.
References _dg_terms_active, _elem_elem_jacobian, _elem_elem_subjacobians, _elem_neighbor_jacobian, _elem_neighbor_subjacobians, _neighbor_dof_indices, _neighbor_dof_indices_var, _neighbor_elem_jacobian, _neighbor_elem_subjacobians, _neighbor_neighbor_jacobian, _neighbor_neighbor_subjacobians, _neighbor_residual, _neighbor_side_fe, _neighbor_subresiduals, libMesh::FEMContext::_side_fe, libMesh::FEMContext::dim, libMesh::DiffContext::dof_indices, libMesh::DofMap::dof_indices(), libMesh::DiffContext::dof_indices_var, libMesh::System::get_dof_map(), get_neighbor(), libMesh::DiffContext::get_system(), libMesh::FEAbstract::get_xyz(), libMesh::FEInterface::inverse_map(), libMesh::System::n_vars(), libMesh::DenseVector< T >::resize(), and libMesh::DenseMatrix< T >::resize().
{
  // Call this *after* side_fe_reinit
  // Initialize all the neighbor side FE objects based on inverse mapping
  // the quadrature points on the current side
  std::vector<Point> qface_side_points;
  std::vector<Point> qface_neighbor_points;
  std::map<FEType, FEAbstract *>::iterator local_fe_end = _neighbor_side_fe.end();
  for (std::map<FEType, FEAbstract *>::iterator i = _neighbor_side_fe.begin();
       i != local_fe_end; ++i)
    {
      FEType neighbor_side_fe_type = i->first;
      FEAbstract* side_fe = _side_fe[neighbor_side_fe_type];
      qface_side_points = side_fe->get_xyz();
      FEInterface::inverse_map (dim,
                                neighbor_side_fe_type,
                                &get_neighbor(),
                                qface_side_points,
                                qface_neighbor_points);
      i->second->reinit(&get_neighbor(), &qface_neighbor_points);
    }
  // Set boolean flag to indicate that the DG terms are active on this element
  _dg_terms_active = true;
  // Also, initialize data required for DG assembly on the current side,
  // analogously to FEMContext::pre_fe_reinit
  // Initialize the per-element data for elem.
  get_system().get_dof_map().dof_indices (&get_neighbor(), _neighbor_dof_indices);
  const unsigned int n_dofs = dof_indices.size();
  const unsigned int n_neighbor_dofs = libmesh_cast_int<unsigned int>
    (_neighbor_dof_indices.size());
  // These resize calls also zero out the residual and jacobian
  _neighbor_residual.resize(n_neighbor_dofs);
  _elem_elem_jacobian.resize(n_dofs, n_dofs);
  _elem_neighbor_jacobian.resize(n_dofs, n_neighbor_dofs);
  _neighbor_elem_jacobian.resize(n_neighbor_dofs, n_dofs);
  _neighbor_neighbor_jacobian.resize(n_neighbor_dofs, n_neighbor_dofs);
  // Initialize the per-variable data for elem.
  {
    unsigned int sub_dofs = 0;
    for (unsigned int i=0; i != get_system().n_vars(); ++i)
      {
        get_system().get_dof_map().dof_indices (&get_neighbor(), _neighbor_dof_indices_var[i], i);
        const unsigned int n_dofs_var = libmesh_cast_int<unsigned int>
          (_neighbor_dof_indices_var[i].size());
        _neighbor_subresiduals[i]->reposition
          (sub_dofs, n_dofs_var);
        for (unsigned int j=0; j != i; ++j)
          {
            const unsigned int n_dofs_var_j =
              libmesh_cast_int<unsigned int>
              (dof_indices_var[j].size());
            _elem_elem_subjacobians[i][j]->reposition
              (sub_dofs, _neighbor_subresiduals[j]->i_off(),
               n_dofs_var, n_dofs_var_j);
            _elem_elem_subjacobians[j][i]->reposition
              (_neighbor_subresiduals[j]->i_off(), sub_dofs,
               n_dofs_var_j, n_dofs_var);
            _elem_neighbor_subjacobians[i][j]->reposition
              (sub_dofs, _neighbor_subresiduals[j]->i_off(),
               n_dofs_var, n_dofs_var_j);
            _elem_neighbor_subjacobians[j][i]->reposition
              (_neighbor_subresiduals[j]->i_off(), sub_dofs,
               n_dofs_var_j, n_dofs_var);
            _neighbor_elem_subjacobians[i][j]->reposition
              (sub_dofs, _neighbor_subresiduals[j]->i_off(),
               n_dofs_var, n_dofs_var_j);
            _neighbor_elem_subjacobians[j][i]->reposition
              (_neighbor_subresiduals[j]->i_off(), sub_dofs,
               n_dofs_var_j, n_dofs_var);
            _neighbor_neighbor_subjacobians[i][j]->reposition
              (sub_dofs, _neighbor_subresiduals[j]->i_off(),
               n_dofs_var, n_dofs_var_j);
            _neighbor_neighbor_subjacobians[j][i]->reposition
              (_neighbor_subresiduals[j]->i_off(), sub_dofs,
               n_dofs_var_j, n_dofs_var);
          }
        _elem_elem_subjacobians[i][i]->reposition
          (sub_dofs, sub_dofs,
           n_dofs_var,
           n_dofs_var);
        _elem_neighbor_subjacobians[i][i]->reposition
          (sub_dofs, sub_dofs,
           n_dofs_var,
           n_dofs_var);
        _neighbor_elem_subjacobians[i][i]->reposition
          (sub_dofs, sub_dofs,
           n_dofs_var,
           n_dofs_var);
        _neighbor_neighbor_subjacobians[i][i]->reposition
          (sub_dofs, sub_dofs,
           n_dofs_var,
           n_dofs_var);
        sub_dofs += n_dofs_var;
      }
    libmesh_assert_equal_to (sub_dofs, n_dofs);
  }
}
template<typename OutputType > template void libMesh::FEMContext::point_curl< Gradient > (unsigned intvar, const Point &p, OutputType &curl_u) const [inherited]
Returns the curl of the solution variable var at the physical point p on the current element.
Definition at line 893 of file fem_context.C.
References libMesh::FEMContext::build_new_fe(), libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Build a FE for calculating u(p)
  AutoPtr<FEGenericBase<OutputShape> > fe_new = this->build_new_fe( fe, p );
  // Get the values of the shape function derivatives
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputShape> >& curl_phi = fe_new->get_curl_phi();
  curl_u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    curl_u.add_scaled(curl_phi[l][0], coef(l));
  return;
}
Gradient libMesh::FEMContext::point_gradient (unsigned intvar, const Point &p) const [inherited]
Returns the gradient of the solution variable var at the physical point p on the current element. This API currently present for backward compatibility.
Definition at line 790 of file fem_context.C.
{
  Gradient grad_u;
  this->point_gradient( var, p, grad_u );
  return grad_u;
}
template<typename OutputType > void libMesh::FEMContext::point_gradient (unsigned intvar, const Point &p, OutputType &grad_u) const [inherited]
Returns the gradient of the solution variable var at the physical point p on the current element. This is the preferred API.
Definition at line 802 of file fem_context.C.
References libMesh::FEMContext::build_new_fe(), libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal
    <typename TensorTools::DecrementRank<OutputType>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Build a FE for calculating u(p)
  AutoPtr<FEGenericBase<OutputShape> > fe_new = this->build_new_fe( fe, p );
  // Get the values of the shape function derivatives
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient> >& dphi = fe_new->get_dphi();
  grad_u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    grad_u.add_scaled(dphi[l][0], coef(l));
  return;
}
Tensor libMesh::FEMContext::point_hessian (unsigned intvar, const Point &p) const [inherited]
Returns the hessian of the solution variable var at the physical point p on the current element. This API currently present for backward compatibility.
Definition at line 841 of file fem_context.C.
{
  Tensor hess_u;
  this->point_hessian( var, p, hess_u );
  return hess_u;
}
template<typename OutputType > void libMesh::FEMContext::point_hessian (unsigned intvar, const Point &p, OutputType &hess_u) const [inherited]
Returns the hessian of the solution variable var at the physical point p on the current element. This is the preferred API.
Definition at line 852 of file fem_context.C.
References libMesh::FEMContext::build_new_fe(), libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<
    typename TensorTools::DecrementRank<
    typename TensorTools::DecrementRank<
    OutputType>::type>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Build a FE for calculating u(p)
  AutoPtr<FEGenericBase<OutputShape> > fe_new = this->build_new_fe( fe, p );
  // Get the values of the shape function derivatives
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor> >& d2phi = fe_new->get_d2phi();
  hess_u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    hess_u.add_scaled(d2phi[l][0], coef(l));
  return;
}
Number libMesh::FEMContext::point_value (unsigned intvar, const Point &p) const [inherited]
Returns the value of the solution variable var at the physical point p on the current element. This API currently present for backward compatibility.
Definition at line 745 of file fem_context.C.
{
  Number u = 0.;
  this->point_value( var, p, u );
  return u;
}
template<typename OutputType > void libMesh::FEMContext::point_value (unsigned intvar, const Point &p, OutputType &u) const [inherited]
Returns the value of the solution variable var at the physical point p on the current element. This is the preferred API.
Definition at line 755 of file fem_context.C.
References libMesh::FEMContext::build_new_fe(), libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* fe = NULL;
  this->get_element_fe<OutputShape>( var, fe );
  // Build a FE for calculating u(p)
  AutoPtr<FEGenericBase<OutputShape> > fe_new = this->build_new_fe( fe, p );
  // Get the values of the shape function derivatives
  const std::vector<std::vector<OutputShape> >& phi = fe_new->get_phi();
  u = 0.;
  for (unsigned int l=0; l != n_dofs; l++)
    u += phi[l][0] * coef(l);
  return;
}
void libMesh::FEMContext::pre_fe_reinit (const System &sys, const Elem *e) [virtual], [inherited]
Reinitializes local data vectors/matrices on the current geometric element
Definition at line 1584 of file fem_context.C.
References libMesh::System::current_local_solution, libMesh::DiffContext::dof_indices, libMesh::DofMap::dof_indices(), libMesh::DiffContext::dof_indices_var, libMesh::FEMContext::elem, libMesh::DiffContext::elem_fixed_solution, libMesh::DiffContext::elem_fixed_subsolutions, libMesh::DiffContext::elem_jacobian, libMesh::DiffContext::elem_qoi_derivative, libMesh::DiffContext::elem_qoi_subderivatives, libMesh::DiffContext::elem_residual, libMesh::DiffContext::elem_solution, libMesh::DiffContext::elem_subjacobians, libMesh::DiffContext::elem_subresiduals, libMesh::DiffContext::elem_subsolutions, libMesh::NumericVector< T >::get(), libMesh::System::get_dof_map(), libMesh::DenseVector< T >::get_values(), libMesh::DiffContext::localized_vectors, libMesh::System::n_vars(), libMesh::System::qoi, libMesh::DenseVector< T >::resize(), libMesh::DenseMatrix< T >::resize(), libMesh::resize(), and libMesh::System::use_fixed_solution.
Referenced by libMesh::FEMSystem::mesh_position_get(), libMesh::FEMSystem::mesh_position_set(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), and libMesh::System::project_vector().
{
  elem = e;
  // Initialize the per-element data for elem.
  sys.get_dof_map().dof_indices (elem, dof_indices);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices.size());
  const std::size_t n_qoi = sys.qoi.size();
  if (sys.use_fixed_solution)
    elem_fixed_solution.resize(n_dofs);
  sys.current_local_solution->get(dof_indices, elem_solution.get_values());
  // These resize calls also zero out the residual and jacobian
  elem_residual.resize(n_dofs);
  elem_jacobian.resize(n_dofs, n_dofs);
  elem_qoi_derivative.resize(n_qoi);
  elem_qoi_subderivatives.resize(n_qoi);
  for (std::size_t q=0; q != n_qoi; ++q)
    elem_qoi_derivative[q].resize(n_dofs);
  // Initialize the per-variable data for elem.
  {
    unsigned int sub_dofs = 0;
    for (unsigned int i=0; i != sys.n_vars(); ++i)
      {
        sys.get_dof_map().dof_indices (elem, dof_indices_var[i], i);
        const unsigned int n_dofs_var = libmesh_cast_int<unsigned int>
          (dof_indices_var[i].size());
        elem_subsolutions[i]->reposition
          (sub_dofs, n_dofs_var);
        if (sys.use_fixed_solution)
          elem_fixed_subsolutions[i]->reposition
            (sub_dofs, n_dofs_var);
        elem_subresiduals[i]->reposition
          (sub_dofs, n_dofs_var);
        for (std::size_t q=0; q != n_qoi; ++q)
          elem_qoi_subderivatives[q][i]->reposition
            (sub_dofs, n_dofs_var);
        for (unsigned int j=0; j != i; ++j)
          {
            const unsigned int n_dofs_var_j =
              libmesh_cast_int<unsigned int>
              (dof_indices_var[j].size());
            elem_subjacobians[i][j]->reposition
              (sub_dofs, elem_subresiduals[j]->i_off(),
               n_dofs_var, n_dofs_var_j);
            elem_subjacobians[j][i]->reposition
              (elem_subresiduals[j]->i_off(), sub_dofs,
               n_dofs_var_j, n_dofs_var);
          }
        elem_subjacobians[i][i]->reposition
          (sub_dofs, sub_dofs,
           n_dofs_var,
           n_dofs_var);
        sub_dofs += n_dofs_var;
      }
    libmesh_assert_equal_to (sub_dofs, n_dofs);
  }
  // Now do the localization for the user requested vectors
  DiffContext::localized_vectors_iterator localized_vec_it = localized_vectors.begin();
  const DiffContext::localized_vectors_iterator localized_vec_end = localized_vectors.end();
  for(; localized_vec_it != localized_vec_end; ++localized_vec_it)
    {
      const NumericVector<Number>& current_localized_vector = *localized_vec_it->first;
      DenseVector<Number>& target_vector = localized_vec_it->second.first;
      current_localized_vector.get(dof_indices, target_vector.get_values());
      // Initialize the per-variable data for elem.
      unsigned int sub_dofs = 0;
      for (unsigned int i=0; i != sys.n_vars(); ++i)
        {
          const unsigned int n_dofs_var = libmesh_cast_int<unsigned int>
            (dof_indices_var[i].size());
          sys.get_dof_map().dof_indices (elem, dof_indices_var[i], i);
          localized_vec_it->second.second[i]->reposition
            (sub_dofs, n_dofs_var);
          sub_dofs += n_dofs_var;
        }
      libmesh_assert_equal_to (sub_dofs, n_dofs);
    }
}
void libMesh::DiffContext::set_deltat_pointer (Real *dt) [inherited]
Points the _deltat member of this class at a timestep value stored in the creating System, for example DiffSystem::deltat
Definition at line 109 of file diff_context.C.
References libMesh::DiffContext::_deltat.
Referenced by libMesh::FEMSystem::build_context(), and libMesh::FEMSystem::init_context().
{
  // We may actually want to be able to set this pointer to NULL, so
  // don't report an error for that.
  _deltat = dt;
}
virtual void libMesh::FEMContext::set_mesh_system (System *sys) [inline], [virtual], [inherited]
Tells the FEMContext that system sys contains the isoparametric Lagrangian variables which correspond to the coordinates of mesh nodes, in problems where the mesh itself is expected to move in time.
This should be set automatically if the FEMPhysics requires it.
Definition at line 552 of file fem_context.h.
References libMesh::FEMContext::_mesh_sys, and libMesh::sys.
Referenced by libMesh::FEMSystem::build_context().
  { this->_mesh_sys = sys; }
void libMesh::FEMContext::set_mesh_x_var (unsigned intx_var) [inline], [inherited]
Accessor for x-variable of moving mesh System
This should be set automatically if the FEMPhysics requires it.
Definition at line 578 of file fem_context.h.
References libMesh::FEMContext::_mesh_x_var.
Referenced by libMesh::FEMSystem::build_context().
  { _mesh_x_var = x_var; }
void libMesh::FEMContext::set_mesh_y_var (unsigned inty_var) [inline], [inherited]
Accessor for y-variable of moving mesh System
This should be set automatically if the FEMPhysics requires it.
Definition at line 592 of file fem_context.h.
References libMesh::FEMContext::_mesh_y_var.
Referenced by libMesh::FEMSystem::build_context().
  { _mesh_y_var = y_var; }
void libMesh::FEMContext::set_mesh_z_var (unsigned intz_var) [inline], [inherited]
Accessor for z-variable of moving mesh System
This should be set automatically if the FEMPhysics requires it.
Definition at line 606 of file fem_context.h.
References libMesh::FEMContext::_mesh_z_var.
Referenced by libMesh::FEMSystem::build_context().
  { _mesh_z_var = z_var; }
void libMesh::DGFEMContext::set_neighbor (const Elem &neighbor) [inline]
Set the neighbor element which we will use to assemble DG terms. Note that we do not assume that this element is get_elem().neighbor(side) because we also need to be able to handle the special case of DG terms on 'cracks' in a mesh to model certain types of interface conditions. In this case, we need to be able to specify the neighbor element manually. Also, this should give us more flexibility to handle non-conforming meshes.
Definition at line 219 of file dg_fem_context.h.
References _neighbor.
  { _neighbor = &neighbor; }
void libMesh::DiffContext::set_time (Realtime_in) [inline], [inherited]
Set the time for which the current nonlinear_solution is defined.
Definition at line 266 of file diff_context.h.
References libMesh::DiffContext::time.
  { time = time_in; }
std::vector< boundary_id_type > libMesh::FEMContext::side_boundary_ids () const [inherited]
Lists the boundary ids found on the current side
Definition at line 149 of file fem_context.C.
References libMesh::FEMContext::_boundary_info, libMesh::BoundaryInfo::boundary_ids(), libMesh::FEMContext::elem, and libMesh::FEMContext::side.
{
  return _boundary_info->boundary_ids(elem, side);
}
void libMesh::DGFEMContext::side_fe_reinit () [virtual]
Override side_fe_reinit to set a boolean flag so that by default DG terms are assumed to be inactive. DG terms are only active if neighbor_side_fe_reinit is called.
Reimplemented from libMesh::FEMContext.
Definition at line 103 of file dg_fem_context.C.
References _dg_terms_active, and libMesh::FEMContext::side_fe_reinit().
{
  FEMContext::side_fe_reinit();
  // By default we assume that the DG terms are inactive
  // They are only active if neighbor_side_fe_reinit is called
  _dg_terms_active = false;
}
Gradient libMesh::FEMContext::side_gradient (unsigned intvar, unsigned intqp) const [inherited]
Returns the gradient of the solution variable var at the quadrature point qp on the current element side. This API currently present for backward compatibility.
Definition at line 564 of file fem_context.C.
{
  Gradient du;
  this->side_gradient( var, qp, du );
  return du;
}
template<typename OutputType > void libMesh::FEMContext::side_gradient (unsigned intvar, unsigned intqp, OutputType &du) const [inherited]
Returns the gradient of the solution variable var at the quadrature point qp on the current element side. This is the preferred API.
Definition at line 575 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::FEGenericBase< T >::get_dphi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal
    <typename TensorTools::DecrementRank<OutputType>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector< typename FEGenericBase<OutputShape>::OutputGradient> > &dphi = the_side_fe->get_dphi();
  // Accumulate solution derivatives
  du = 0.;
  for (unsigned int l=0; l != n_dofs; l++)
    du.add_scaled(dphi[l][qp], coef(l));
  return;
}
template<typename OutputType > template void libMesh::FEMContext::side_gradients< Tensor > (unsigned intvar, const NumericVector< Number > &_system_vector, std::vector< OutputType > &side_gradients_vector) const [inherited]
Fills a vector with the gradient of the solution variable var at all the quadrature points on the current element side. This is the preferred API.
Definition at line 612 of file fem_context.C.
References libMesh::FEGenericBase< T >::get_dphi(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal
    <typename TensorTools::DecrementRank<OutputType>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  const DenseSubVector<Number> &coef = get_localized_subvector(_system_vector, var);
  // Get finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputGradient> > &dphi = the_side_fe->get_dphi();
  // Loop over all the q_points in this finite element
  for (unsigned int qp=0; qp != du_vals.size(); qp++)
    {
      OutputType &du = du_vals[qp];
      du = 0;
      // Compute the gradient at this q_point
      for (unsigned int l=0; l != n_dofs; l++)
        du.add_scaled(dphi[l][qp], coef(l));
    }
  return;
}
Tensor libMesh::FEMContext::side_hessian (unsigned intvar, unsigned intqp) const [inherited]
Returns the hessian of the solution variable var at the quadrature point qp on the current element side. This API currently present for backward compatibility.
Definition at line 651 of file fem_context.C.
{
  Tensor d2u;
  this->side_hessian( var, qp, d2u );
  return d2u;
}
template<typename OutputType > void libMesh::FEMContext::side_hessian (unsigned intvar, unsigned intqp, OutputType &d2u) const [inherited]
Returns the hessian of the solution variable var at the quadrature point qp on the current element side. This is the preferred API.
Definition at line 661 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::FEGenericBase< T >::get_d2phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<
    typename TensorTools::DecrementRank<
    typename TensorTools::DecrementRank<
    OutputType>::type>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor> > &d2phi = the_side_fe->get_d2phi();
  // Accumulate solution second derivatives
  d2u = 0.0;
  for (unsigned int l=0; l != n_dofs; l++)
    d2u.add_scaled(d2phi[l][qp], coef(l));
  return;
}
template<typename OutputType > template void libMesh::FEMContext::side_hessians< Tensor > (unsigned intvar, const NumericVector< Number > &_system_vector, std::vector< OutputType > &d2u_vals) const [inherited]
Fills a vector of hessians of the _system_vector at the all the quadrature points on the current element side. This is the preferred API.
Definition at line 699 of file fem_context.C.
References libMesh::FEGenericBase< T >::get_d2phi(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<
    typename TensorTools::DecrementRank<
    typename TensorTools::DecrementRank<
    OutputType>::type>::type>::type
    OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  const DenseSubVector<Number> &coef = get_localized_subvector(_system_vector, var);
  // Get finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<typename FEGenericBase<OutputShape>::OutputTensor> > &d2phi = the_side_fe->get_d2phi();
  // Loop over all the q_points in this finite element
  for (unsigned int qp=0; qp != d2u_vals.size(); qp++)
    {
      OutputType &d2u = d2u_vals[qp];
      // Compute the gradient at this q_point
      d2u = 0;
      for (unsigned int l=0; l != n_dofs; l++)
        d2u.add_scaled(d2phi[l][qp], coef(l));
    }
  return;
}
Number libMesh::FEMContext::side_value (unsigned intvar, unsigned intqp) const [inherited]
Returns the value of the solution variable var at the quadrature point qp on the current element side. This API currently present for backward compatibility.
Definition at line 483 of file fem_context.C.
{
  Number u = 0.;
  this->side_value( var, qp, u );
  return u;
}
template<typename OutputType > void libMesh::FEMContext::side_value (unsigned intvar, unsigned intqp, OutputType &u) const [inherited]
Returns the value of the solution variable var at the quadrature point qp on the current element side. This is the preferred API.
Definition at line 494 of file fem_context.C.
References libMesh::DiffContext::dof_indices, libMesh::DiffContext::dof_indices_var, libMesh::DiffContext::elem_subsolutions, libMesh::FEGenericBase< T >::get_phi(), libMesh::libmesh_assert(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  libmesh_assert_greater (elem_subsolutions.size(), var);
  libmesh_assert(elem_subsolutions[var]);
  DenseSubVector<Number> &coef = *elem_subsolutions[var];
  // Get finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<OutputShape> > &phi = the_side_fe->get_phi();
  // Accumulate solution value
  u = 0.;
  for (unsigned int l=0; l != n_dofs; l++)
    u += phi[l][qp] * coef(l);
  return;
}
template<typename OutputType > template void libMesh::FEMContext::side_values< Gradient > (unsigned intvar, const NumericVector< Number > &_system_vector, std::vector< OutputType > &side_values_vector) const [inherited]
Fills a vector of values of the _system_vector at the all the quadrature points on the current element side.
Definition at line 528 of file fem_context.C.
References libMesh::FEGenericBase< T >::get_phi(), and libMesh::libmesh_assert_greater().
{
  typedef typename TensorTools::MakeReal<OutputType>::type OutputShape;
  // Get local-to-global dof index lookup
  libmesh_assert_greater (dof_indices.size(), var);
  const unsigned int n_dofs = libmesh_cast_int<unsigned int>
    (dof_indices_var[var].size());
  // Get current local coefficients
  const DenseSubVector<Number> &coef = get_localized_subvector(_system_vector, var);
  // Get the finite element object
  FEGenericBase<OutputShape>* the_side_fe = NULL;
  this->get_side_fe<OutputShape>( var, the_side_fe );
  // Get shape function values at quadrature point
  const std::vector<std::vector<OutputShape> > &phi = the_side_fe->get_phi();
  // Loop over all the q_points on this element
  for (unsigned int qp=0; qp != u_vals.size(); qp++)
    {
      OutputType &u = u_vals[qp];
      // Compute the value at this q_point
      u = 0.;
      for (unsigned int l=0; l != n_dofs; l++)
        u += phi[l][qp] * coef(l);
    }
  return;
}
Member Data Documentation
BoundaryInfo* libMesh::FEMContext::_boundary_info [protected], [inherited]
Saved pointer to BoundaryInfo on the mesh for this System. Used to answer boundary id requests.
Definition at line 700 of file fem_context.h.
Referenced by libMesh::FEMContext::has_side_boundary_id(), and libMesh::FEMContext::side_boundary_ids().
bool libMesh::DGFEMContext::_dg_terms_active [private]
Boolean flag to indicate whether or not the DG terms have been assembled and should be used in the global matrix assembly.
Definition at line 295 of file dg_fem_context.h.
Referenced by dg_terms_are_active(), neighbor_side_fe_reinit(), and side_fe_reinit().
std::map<FEType, FEAbstract*> libMesh::FEMContext::_edge_fe [protected], [inherited]
Definition at line 685 of file fem_context.h.
Referenced by libMesh::FEMContext::edge_fe_reinit(), libMesh::FEMContext::FEMContext(), and libMesh::FEMContext::~FEMContext().
std::vector<FEAbstract*> libMesh::FEMContext::_edge_fe_var [protected], [inherited]
Definition at line 694 of file fem_context.h.
Referenced by libMesh::FEMContext::FEMContext(), and libMesh::FEMContext::get_edge_fe().
DenseMatrix<Number> libMesh::DGFEMContext::_elem_elem_jacobian [private]
The DG Jacobian terms. Trial and test functions come from either element or neighbor.
Definition at line 256 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_elem_elem_jacobian(), and neighbor_side_fe_reinit().
std::vector<std::vector<DenseSubMatrix<Number> *> > libMesh::DGFEMContext::_elem_elem_subjacobians [private]
Definition at line 265 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_elem_elem_jacobian(), neighbor_side_fe_reinit(), and ~DGFEMContext().
DenseMatrix<Number> libMesh::DGFEMContext::_elem_neighbor_jacobian [private]
Definition at line 257 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_elem_neighbor_jacobian(), and neighbor_side_fe_reinit().
std::vector<std::vector<DenseSubMatrix<Number> *> > libMesh::DGFEMContext::_elem_neighbor_subjacobians [private]
Definition at line 266 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_elem_neighbor_jacobian(), neighbor_side_fe_reinit(), and ~DGFEMContext().
std::map<FEType, FEAbstract*> libMesh::FEMContext::_element_fe [protected], [inherited]
Finite element objects for each variable's interior, sides and edges.
Definition at line 683 of file fem_context.h.
Referenced by libMesh::FEMContext::elem_fe_reinit(), libMesh::FEMContext::FEMContext(), and libMesh::FEMContext::~FEMContext().
std::vector<FEAbstract*> libMesh::FEMContext::_element_fe_var [protected], [inherited]
Pointers to the same finite element objects, but indexed by variable number
Definition at line 692 of file fem_context.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::FEMContext::elem_position_get(), libMesh::FEMContext::FEMContext(), and libMesh::FEMContext::get_element_fe().
System* libMesh::FEMContext::_mesh_sys [inherited]
System from which to acquire moving mesh information
Definition at line 655 of file fem_context.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::FEMContext::elem_edge_reinit(), libMesh::FEMContext::elem_position_get(), libMesh::FEMContext::elem_position_set(), libMesh::FEMContext::elem_reinit(), libMesh::FEMContext::elem_side_reinit(), libMesh::FEMContext::get_mesh_system(), and libMesh::FEMContext::set_mesh_system().
unsigned int libMesh::FEMContext::_mesh_x_var [inherited]
Variables from which to acquire moving mesh information
Definition at line 660 of file fem_context.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::FEMContext::elem_position_get(), libMesh::FEMContext::get_mesh_x_var(), and libMesh::FEMContext::set_mesh_x_var().
unsigned int libMesh::FEMContext::_mesh_y_var [inherited]
Definition at line 660 of file fem_context.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::FEMContext::elem_position_get(), libMesh::FEMContext::get_mesh_y_var(), and libMesh::FEMContext::set_mesh_y_var().
unsigned int libMesh::FEMContext::_mesh_z_var [inherited]
Definition at line 660 of file fem_context.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::FEMContext::elem_position_get(), libMesh::FEMContext::get_mesh_z_var(), and libMesh::FEMContext::set_mesh_z_var().
const Elem* libMesh::DGFEMContext::_neighbor [private]
Current neighbor element for assembling DG terms.
Definition at line 245 of file dg_fem_context.h.
Referenced by get_neighbor(), and set_neighbor().
std::vector<dof_id_type> libMesh::DGFEMContext::_neighbor_dof_indices [private]
Global Degree of freedom index lists for the neighbor element
Definition at line 273 of file dg_fem_context.h.
Referenced by get_neighbor_dof_indices(), and neighbor_side_fe_reinit().
std::vector<std::vector<dof_id_type> > libMesh::DGFEMContext::_neighbor_dof_indices_var [private]
Definition at line 274 of file dg_fem_context.h.
Referenced by get_neighbor_dof_indices(), and neighbor_side_fe_reinit().
DenseMatrix<Number> libMesh::DGFEMContext::_neighbor_elem_jacobian [private]
Definition at line 258 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_neighbor_elem_jacobian(), and neighbor_side_fe_reinit().
std::vector<std::vector<DenseSubMatrix<Number> *> > libMesh::DGFEMContext::_neighbor_elem_subjacobians [private]
Definition at line 267 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_neighbor_elem_jacobian(), neighbor_side_fe_reinit(), and ~DGFEMContext().
DenseMatrix<Number> libMesh::DGFEMContext::_neighbor_neighbor_jacobian [private]
Definition at line 259 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_neighbor_neighbor_jacobian(), and neighbor_side_fe_reinit().
std::vector<std::vector<DenseSubMatrix<Number> *> > libMesh::DGFEMContext::_neighbor_neighbor_subjacobians [private]
Definition at line 268 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_neighbor_neighbor_jacobian(), neighbor_side_fe_reinit(), and ~DGFEMContext().
DenseVector<Number> libMesh::DGFEMContext::_neighbor_residual [private]
Residual vector of the neighbor component.
Definition at line 250 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_neighbor_residual(), and neighbor_side_fe_reinit().
std::map<FEType, FEAbstract *> libMesh::DGFEMContext::_neighbor_side_fe [private]
Finite element objects for each variable's sides on the neighbor element. We do not need FE objects for neighbor element interior since we just need to handle DG interface terms here.
Definition at line 283 of file dg_fem_context.h.
Referenced by DGFEMContext(), neighbor_side_fe_reinit(), and ~DGFEMContext().
std::vector<FEAbstract *> libMesh::DGFEMContext::_neighbor_side_fe_var [private]
Pointers to the same finite element objects on the neighbor element, but indexed by variable number
Definition at line 289 of file dg_fem_context.h.
Referenced by DGFEMContext(), and get_neighbor_side_fe().
std::vector<DenseSubVector<Number> *> libMesh::DGFEMContext::_neighbor_subresiduals [private]
Element residual subvectors and Jacobian submatrices
Definition at line 264 of file dg_fem_context.h.
Referenced by DGFEMContext(), get_neighbor_residual(), neighbor_side_fe_reinit(), and ~DGFEMContext().
std::map<FEType, FEAbstract*> libMesh::FEMContext::_side_fe [protected], [inherited]
Definition at line 684 of file fem_context.h.
Referenced by libMesh::FEMContext::FEMContext(), neighbor_side_fe_reinit(), libMesh::FEMContext::side_fe_reinit(), and libMesh::FEMContext::~FEMContext().
std::vector<FEAbstract*> libMesh::FEMContext::_side_fe_var [protected], [inherited]
Definition at line 693 of file fem_context.h.
Referenced by libMesh::FEMContext::FEMContext(), and libMesh::FEMContext::get_side_fe().
unsigned char libMesh::FEMContext::dim [protected], [inherited]
Cached dimension of elements in this mesh
Definition at line 710 of file fem_context.h.
Referenced by libMesh::FEMContext::build_new_fe(), DGFEMContext(), libMesh::FEMContext::edge_fe_reinit(), libMesh::FEMContext::FEMContext(), libMesh::FEMContext::get_dim(), and neighbor_side_fe_reinit().
std::vector<dof_id_type> libMesh::DiffContext::dof_indices [protected], [inherited]
Global Degree of freedom index lists
Definition at line 419 of file diff_context.h.
Referenced by libMesh::FEMContext::fixed_interior_hessian(), libMesh::FEMContext::fixed_interior_value(), libMesh::FEMContext::fixed_point_gradient(), libMesh::FEMContext::fixed_point_hessian(), libMesh::FEMContext::fixed_point_value(), libMesh::FEMContext::fixed_side_gradient(), libMesh::FEMContext::fixed_side_hessian(), libMesh::FEMContext::fixed_side_value(), libMesh::DiffContext::get_dof_indices(), libMesh::FEMContext::interior_curl(), libMesh::FEMContext::interior_div(), libMesh::FEMContext::interior_gradient(), libMesh::FEMContext::interior_hessian(), libMesh::FEMContext::interior_value(), libMesh::FEMContext::interior_values(), neighbor_side_fe_reinit(), libMesh::FEMContext::point_curl(), libMesh::FEMContext::point_gradient(), libMesh::FEMContext::point_hessian(), libMesh::FEMContext::point_value(), libMesh::FEMContext::pre_fe_reinit(), libMesh::FEMContext::side_gradient(), libMesh::FEMContext::side_hessian(), and libMesh::FEMContext::side_value().
std::vector<std::vector<dof_id_type> > libMesh::DiffContext::dof_indices_var [protected], [inherited]
Definition at line 420 of file diff_context.h.
Referenced by libMesh::FEMContext::fixed_interior_hessian(), libMesh::FEMContext::fixed_interior_value(), libMesh::FEMContext::fixed_point_gradient(), libMesh::FEMContext::fixed_point_hessian(), libMesh::FEMContext::fixed_point_value(), libMesh::FEMContext::fixed_side_gradient(), libMesh::FEMContext::fixed_side_hessian(), libMesh::FEMContext::fixed_side_value(), libMesh::DiffContext::get_dof_indices(), libMesh::FEMContext::interior_curl(), libMesh::FEMContext::interior_div(), libMesh::FEMContext::interior_gradient(), libMesh::FEMContext::interior_hessian(), libMesh::FEMContext::interior_value(), libMesh::FEMContext::interior_values(), libMesh::DiffContext::n_vars(), neighbor_side_fe_reinit(), libMesh::FEMContext::point_curl(), libMesh::FEMContext::point_gradient(), libMesh::FEMContext::point_hessian(), libMesh::FEMContext::point_value(), libMesh::FEMContext::pre_fe_reinit(), libMesh::FEMContext::side_gradient(), libMesh::FEMContext::side_hessian(), and libMesh::FEMContext::side_value().
unsigned char libMesh::FEMContext::edge [inherited]
Current edge for edge_* to examine
Definition at line 670 of file fem_context.h.
Referenced by libMesh::FEMContext::edge_fe_reinit(), and libMesh::FEMContext::get_edge().
QBase* libMesh::FEMContext::edge_qrule [protected], [inherited]
Quadrature rules for element edges. If the FEM context is told to prepare for edge integration on 3D elements, it will try to find a quadrature rule that correctly integrates all variables
Definition at line 731 of file fem_context.h.
Referenced by libMesh::FEMContext::FEMContext(), libMesh::FEMContext::get_edge_qrule(), and libMesh::FEMContext::~FEMContext().
const Elem* libMesh::FEMContext::elem [protected], [inherited]
Current element for element_* to examine
Definition at line 705 of file fem_context.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::FEMContext::build_new_fe(), libMesh::FEMContext::edge_fe_reinit(), libMesh::FEMContext::elem_fe_reinit(), libMesh::FEMContext::elem_position_get(), libMesh::FEMContext::get_elem(), libMesh::FEMContext::has_side_boundary_id(), libMesh::FEMContext::pre_fe_reinit(), libMesh::FEMContext::side_boundary_ids(), and libMesh::FEMContext::side_fe_reinit().
DenseVector<Number> libMesh::DiffContext::elem_fixed_solution [protected], [inherited]
Element by element components of nonlinear_solution at a fixed point in a timestep, for optional use by e.g. stabilized methods
Definition at line 385 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_elem_fixed_solution(), and libMesh::FEMContext::pre_fe_reinit().
std::vector<DenseSubVector<Number> *> libMesh::DiffContext::elem_fixed_subsolutions [protected], [inherited]
Definition at line 386 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::FEMContext::fixed_interior_hessian(), libMesh::FEMContext::fixed_interior_value(), libMesh::FEMContext::fixed_point_gradient(), libMesh::FEMContext::fixed_point_hessian(), libMesh::FEMContext::fixed_point_value(), libMesh::FEMContext::fixed_side_gradient(), libMesh::FEMContext::fixed_side_hessian(), libMesh::FEMContext::fixed_side_value(), libMesh::DiffContext::get_elem_fixed_solution(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::DiffContext::~DiffContext().
DenseMatrix<Number> libMesh::DiffContext::elem_jacobian [protected], [inherited]
Element jacobian: derivatives of elem_residual with respect to elem_solution
Definition at line 397 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_elem_jacobian(), and libMesh::FEMContext::pre_fe_reinit().
std::vector<Number> libMesh::DiffContext::elem_qoi [protected], [inherited]
Element quantity of interest contributions
Definition at line 402 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), and libMesh::DiffContext::get_qois().
std::vector<DenseVector<Number> > libMesh::DiffContext::elem_qoi_derivative [protected], [inherited]
Element quantity of interest derivative contributions
Definition at line 407 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_qoi_derivatives(), and libMesh::FEMContext::pre_fe_reinit().
std::vector<std::vector<DenseSubVector<Number> *> > libMesh::DiffContext::elem_qoi_subderivatives [protected], [inherited]
Definition at line 408 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_qoi_derivatives(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::DiffContext::~DiffContext().
DenseVector<Number> libMesh::DiffContext::elem_residual [protected], [inherited]
Element residual vector
Definition at line 391 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_elem_residual(), and libMesh::FEMContext::pre_fe_reinit().
DenseVector<Number> libMesh::DiffContext::elem_solution [protected], [inherited]
Element by element components of nonlinear_solution as adjusted by a time_solver
Definition at line 377 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_elem_solution(), and libMesh::FEMContext::pre_fe_reinit().
Real libMesh::DiffContext::elem_solution_derivative [inherited]
The derivative of elem_solution with respect to the nonlinear solution, for use by systems constructing jacobians with elem_fixed_solution based methods
Definition at line 310 of file diff_context.h.
Referenced by libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::DiffContext::get_elem_solution_derivative(), libMesh::EulerSolver::side_residual(), and libMesh::Euler2Solver::side_residual().
std::vector<std::vector<DenseSubMatrix<Number> *> > libMesh::DiffContext::elem_subjacobians [protected], [inherited]
Definition at line 414 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_elem_jacobian(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::DiffContext::~DiffContext().
std::vector<DenseSubVector<Number> *> libMesh::DiffContext::elem_subresiduals [protected], [inherited]
Element residual subvectors and Jacobian submatrices
Definition at line 413 of file diff_context.h.
Referenced by libMesh::DiffContext::DiffContext(), libMesh::DiffContext::get_elem_residual(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::DiffContext::~DiffContext().
std::vector<DenseSubVector<Number> *> libMesh::DiffContext::elem_subsolutions [protected], [inherited]
Definition at line 378 of file diff_context.h.
Referenced by libMesh::FEMContext::_do_elem_position_set(), libMesh::DiffContext::DiffContext(), libMesh::FEMContext::elem_position_get(), libMesh::DiffContext::get_elem_solution(), libMesh::FEMContext::interior_curl(), libMesh::FEMContext::interior_div(), libMesh::FEMContext::interior_gradient(), libMesh::FEMContext::interior_hessian(), libMesh::FEMContext::interior_value(), libMesh::FEMContext::point_curl(), libMesh::FEMContext::point_gradient(), libMesh::FEMContext::point_hessian(), libMesh::FEMContext::point_value(), libMesh::FEMContext::pre_fe_reinit(), libMesh::FEMContext::side_gradient(), libMesh::FEMContext::side_hessian(), libMesh::FEMContext::side_value(), and libMesh::DiffContext::~DiffContext().
QBase* libMesh::FEMContext::element_qrule [protected], [inherited]
Quadrature rule for element interior. The FEM context will try to find a quadrature rule that correctly integrates all variables
Definition at line 717 of file fem_context.h.
Referenced by libMesh::FEMContext::FEMContext(), libMesh::FEMContext::get_element_qrule(), and libMesh::FEMContext::~FEMContext().
Real libMesh::DiffContext::fixed_solution_derivative [inherited]
The derivative of elem_fixed_solution with respect to the nonlinear solution, for use by systems constructing jacobians with elem_fixed_solution based methods
Definition at line 317 of file diff_context.h.
Referenced by libMesh::EulerSolver::element_residual(), libMesh::Euler2Solver::element_residual(), libMesh::SteadySolver::element_residual(), libMesh::DiffContext::get_fixed_solution_derivative(), libMesh::EulerSolver::side_residual(), libMesh::Euler2Solver::side_residual(), and libMesh::SteadySolver::side_residual().
std::map<const NumericVector<Number>*, std::pair<DenseVector<Number>, std::vector<DenseSubVector<Number>*> > > libMesh::DiffContext::localized_vectors [protected], [inherited]
Contains pointers to vectors the user has asked to be localized, keyed with pairs of element localized versions of that vector and per variable views
Definition at line 371 of file diff_context.h.
Referenced by libMesh::DiffContext::add_localized_vector(), libMesh::DiffContext::get_localized_subvector(), libMesh::DiffContext::get_localized_vector(), libMesh::FEMContext::pre_fe_reinit(), and libMesh::DiffContext::~DiffContext().
unsigned char libMesh::FEMContext::side [inherited]
Current side for side_* to examine
Definition at line 665 of file fem_context.h.
Referenced by libMesh::FEMContext::get_side(), libMesh::FEMContext::has_side_boundary_id(), libMesh::FEMContext::side_boundary_ids(), and libMesh::FEMContext::side_fe_reinit().
QBase* libMesh::FEMContext::side_qrule [protected], [inherited]
Quadrature rules for element sides The FEM context will try to find a quadrature rule that correctly integrates all variables
Definition at line 724 of file fem_context.h.
Referenced by libMesh::FEMContext::FEMContext(), libMesh::FEMContext::get_side_qrule(), and libMesh::FEMContext::~FEMContext().
const Real libMesh::DiffContext::system_time [inherited]
This is the time stored in the System class at the time this context was created, i.e. the time at the beginning of the current timestep. This value gets set in the constructor and unlike DiffContext::time, is not tweaked mid-timestep by transient solvers: it remains equal to the value it was assigned at construction.
Definition at line 303 of file diff_context.h.
Referenced by libMesh::FEMContext::_update_time_from_system(), and libMesh::DiffContext::get_system_time().
Real libMesh::DiffContext::time [inherited]
For time-dependent problems, this is the time t for which the current nonlinear_solution is defined. FIXME - this needs to be tweaked mid-timestep by all transient solvers!
Definition at line 294 of file diff_context.h.
Referenced by libMesh::FEMContext::_update_time_from_system(), libMesh::DiffContext::get_time(), and libMesh::DiffContext::set_time().
Author
Generated automatically by Doxygen for libMesh from the source code.