.TH "libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parallel\&.h>\fP
.PP
Inherits \fBlibMesh::Parallel::PostWaitWork\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPostWaitUnpackBuffer\fP (const Container &buffer, Context *context, OutputIter \fBout\fP)"
.br
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const Container & \fB_buf\fP"
.br
.ti -1c
.RI "Context * \fB_context\fP"
.br
.ti -1c
.RI "OutputIter \fB_out\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Container, typename Context, typename OutputIter>struct libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >"

.PP
Definition at line 1178 of file parallel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Container , typename Context , typename OutputIter > \fBlibMesh::Parallel::PostWaitUnpackBuffer\fP< Container, Context, OutputIter >::\fBPostWaitUnpackBuffer\fP (const Container &buffer, Context *context, OutputIterout)\fC [inline]\fP"

.PP
Definition at line 1179 of file parallel\&.h\&.
.PP
.nf
1179                                                                                   :
1180     _buf(buffer), _context(context), _out(out) {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "template<typename Container , typename Context , typename OutputIter > virtual void \fBlibMesh::Parallel::PostWaitUnpackBuffer\fP< Container, Context, OutputIter >::run ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBlibMesh::Parallel::PostWaitWork\fP\&.
.PP
Definition at line 1182 of file parallel\&.h\&.
.PP
References libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >::_buf, libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >::_context, libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >::_out, and libMesh::Parallel::unpack_range()\&.
.PP
.nf
1182 { Parallel::unpack_range(_buf, _context, _out); }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<typename Container , typename Context , typename OutputIter > const Container& \fBlibMesh::Parallel::PostWaitUnpackBuffer\fP< Container, Context, OutputIter >::_buf\fC [private]\fP"

.PP
Definition at line 1185 of file parallel\&.h\&.
.PP
Referenced by libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >::run()\&.
.SS "template<typename Container , typename Context , typename OutputIter > Context* \fBlibMesh::Parallel::PostWaitUnpackBuffer\fP< Container, Context, OutputIter >::_context\fC [private]\fP"

.PP
Definition at line 1186 of file parallel\&.h\&.
.PP
Referenced by libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >::run()\&.
.SS "template<typename Container , typename Context , typename OutputIter > OutputIter \fBlibMesh::Parallel::PostWaitUnpackBuffer\fP< Container, Context, OutputIter >::_out\fC [private]\fP"

.PP
Definition at line 1187 of file parallel\&.h\&.
.PP
Referenced by libMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >::run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
