libMesh::Node::PackedNode
NAME
libMesh::Node::PackedNode -
SYNOPSIS
#include <node.h>
Public Member Functions
PackedNode ()
Point build_point () const
Static Public Member Functions
static MPI_Datatype create_mpi_datatype ()
static void pack (std::vector< largest_id_type > &conn, const Node *node)
static void unpack (std::vector< largest_id_type >::const_iterator start, Node &node)
Public Attributes
dof_id_type id
processor_id_type pid
Real x
Real y
Real z
PackedNode(const Node &node) node processor_id () = pid
return node
Static Public Attributes
static const unsigned int header_size = 2
Detailed Description
Convenient way to communicate nodes. This struct defines a packed up node which can be easily communicated through a derived MPI datatype.
Author:
Benjamin S. Kirk
Date:
2008
Definition at line 147 of file node.h.
Constructor & Destructor Documentation
libMesh::Node::PackedNode::PackedNode () [inline]
Definition at line 158 of file node.h.
                  :
      id(0),
      pid(DofObject::invalid_processor_id),
      x(0.),
      y(0.),
      z(0.)
    {}
Member Function Documentation
Point libMesh::Node::PackedNode::build_point () const [inline]
Definition at line 190 of file node.h.
References libMesh::Point::Point().
    {
      return Point(x,y,z);
    }
MPI_Datatype libMesh::Node::PackedNode::create_mpi_datatype () [static]
Definition at line 79 of file node.C.
References id, and x.
{
  MPI_Datatype packed_node_type;
  MPI_Datatype types[] = { MPI_UNSIGNED, MPI_REAL };
  int blocklengths[] = { 2, 3 };
  MPI_Aint displs[2];
  // create a Packed node and get the addresses of the elements.
  // this will properly handle id/pid getting padded, for example,
  // in which case id and x may not be 2*sizeof(unsigned int) apart.
  Node::PackedNode pn;
#if MPI_VERSION > 1
  MPI_Get_address (&pn.id, &displs[0]);
  MPI_Get_address (&pn.x, &displs[1]);
#else
  MPI_Address (&pn.id, &displs[0]);
  MPI_Address (&pn.x, &displs[1]);
#endif // #if MPI_VERSION > 1
  displs[1] -= displs[0];
  displs[0] = 0;
#if MPI_VERSION > 1
  MPI_Type_create_struct (2, blocklengths, displs, types, &packed_node_type);
#else
  MPI_Type_struct (2, blocklengths, displs, types, &packed_node_type);
#endif // #if MPI_VERSION > 1
  return packed_node_type;
}
void libMesh::Node::PackedNode::pack (std::vector< largest_id_type > &conn, const Node *node) [static]
For each node the serialization is of the form [ processor_id self_ID x1 x2 y1 y2 z1 z2 dof_object_buffer_1 ...] There may be 1 or 3 or 4 ints per coordinate depending on machine architecture.
Definition at line 112 of file node.C.
References libMesh::DofObject::id(), libMesh::libmesh_assert(), libMesh::DofObject::pack_indexing(), libMesh::Node::packed_size(), libMesh::DofObject::processor_id(), and libMesh::Real.
{
  libmesh_assert(node);
  conn.reserve (conn.size() + node->packed_size());
  conn.push_back (static_cast<largest_id_type>(node->processor_id()));
  conn.push_back (static_cast<largest_id_type>(node->id()));
  // use "(a+b-1)/b" trick to get a/b to round up
  static const unsigned int idtypes_per_Real =
    (sizeof(Real) + sizeof(largest_id_type) - 1) / sizeof(largest_id_type);
  for (unsigned int i=0; i != LIBMESH_DIM; ++i)
    {
      const largest_id_type* Real_as_idtypes = reinterpret_cast<const largest_id_type*>(&((*node)(i)));
      for (unsigned int j=0; j != idtypes_per_Real; ++j)
        {
          conn.push_back(Real_as_idtypes[j]);
        }
    }
  node->pack_indexing(std::back_inserter(conn));
}
void libMesh::Node::PackedNode::unpack (std::vector< largest_id_type >::const_iteratorstart, Node &node) [static]
Definition at line 138 of file node.C.
References libMesh::global_n_processors(), libMesh::DofObject::id(), libMesh::DofObject::invalid_processor_id, libMesh::libmesh_assert(), libMesh::DofObject::processor_id(), libMesh::Real, libMesh::DofObject::set_id(), and libMesh::DofObject::unpack_indexing().
{
  processor_id_type processor_id = static_cast<processor_id_type>(*start++);
  libmesh_assert(processor_id == DofObject::invalid_processor_id ||
                 processor_id < libMesh::global_n_processors());
  dof_id_type id = static_cast<dof_id_type>(*start++);
  // use "(a+b-1)/b" trick to get a/b to round up
  static const unsigned int idtypes_per_Real =
    (sizeof(Real) + sizeof(largest_id_type) - 1) / sizeof(largest_id_type);
  std::vector<Real> xyz(3,0.);
  for (unsigned int i=0; i != LIBMESH_DIM; ++i)
    {
      const Real* ints_as_Real = reinterpret_cast<const Real*>(&(*start));
      node(i) = *ints_as_Real;
      start += idtypes_per_Real;
    }
  node.set_id() = id;
  node.processor_id() = processor_id;
  node.unpack_indexing(start);
}
Member Data Documentation
const unsigned int libMesh::Node::PackedNode::header_size = 2 [static]
Definition at line 149 of file node.h.
Referenced by libMesh::Node::packed_size().
dof_id_type libMesh::Node::PackedNode::id
Definition at line 151 of file node.h.
Referenced by create_mpi_datatype().
return libMesh::Node::PackedNode::node
Definition at line 187 of file node.h.
processor_id_type libMesh::Node::PackedNode::pid
Definition at line 152 of file node.h.
PackedNode (const Node &node) node libMesh::Node::PackedNode::processor_id() = pid [explicit]
Definition at line 186 of file node.h.
Real libMesh::Node::PackedNode::x
Definition at line 153 of file node.h.
Referenced by create_mpi_datatype().
Real libMesh::Node::PackedNode::y
Definition at line 155 of file node.h.
Real libMesh::Node::PackedNode::z
Definition at line 156 of file node.h.
Author
Generated automatically by Doxygen for libMesh from the source code.