.TH "libMesh::DofConstraints" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::DofConstraints \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dof_map\&.h>\fP
.PP
Inherits map< dof_id_type, DofConstraintRow, std::less< dof_id_type >, Threads::scalable_allocator< std::pair< const dof_id_type, Number > > >\&.
.SH "Detailed Description"
.PP 
The constraint matrix storage format\&. We're using a class instead of a typedef to allow forward declarations and future flexibility\&. Don't delete this from a pointer-to-std::map; the destructor isn't virtual! 
.PP
Definition at line 95 of file dof_map\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
