libMesh::PointLocatorTree
NAME
libMesh::PointLocatorTree -
SYNOPSIS
#include <point_locator_tree.h>
Inherits libMesh::PointLocatorBase.
Public Member Functions
PointLocatorTree (const MeshBase &mesh, const PointLocatorBase *master=NULL)
PointLocatorTree (const MeshBase &mesh, const Trees::BuildType build_type, const PointLocatorBase *master=NULL)
~PointLocatorTree ()
virtual void clear ()
void init (const Trees::BuildType build_type)
virtual void init ()
virtual const Elem * operator() (const Point &p) const
virtual void enable_out_of_mesh_mode (void)
virtual void disable_out_of_mesh_mode (void)
bool initialized () const
Static Public Member Functions
static AutoPtr< PointLocatorBase > build (const PointLocatorType t, const MeshBase &mesh, const PointLocatorBase *master=NULL)
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts"
Protected Member Functions
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
TreeBase * _tree
const Elem * _element
bool _out_of_mesh_mode
const PointLocatorBase * _master
const MeshBase & _mesh
bool _initialized
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects"
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
This is a point locator. It locates points in space using a tree: given a mesh they return the element and local coordinates for a given point in global coordinates. Use PointLocatorBase::build() to create objects of this type at run time.
Author:
Daniel Dreyer, 2003
Definition at line 52 of file point_locator_tree.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts [protected], [inherited]
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::PointLocatorTree::PointLocatorTree (const MeshBase &mesh, const PointLocatorBase *master = NULL)
Constructor. Needs the mesh in which the points should be located. Optionally takes a master interpolator. This master helps in saving memory by reducing the number of trees in use. Only the master locator holds a tree, the others simply use the master's tree.
Definition at line 37 of file point_locator_tree.C.
References init(), and libMesh::Trees::NODES.
                                                                    :
  PointLocatorBase (mesh,master),
  _tree (NULL),
  _element (NULL),
  _out_of_mesh_mode(false)
{
  this->init(Trees::NODES);
}
libMesh::PointLocatorTree::PointLocatorTree (const MeshBase &mesh, const Trees::BuildTypebuild_type, const PointLocatorBase *master = NULL)
Constructor. Needs the mesh in which the points should be located. Allows the user to specify the method to use when building the tree. Optionally takes a master interpolator. This master helps in saving memory by reducing the number of trees in use. Only the master locator holds a tree, the others simply use the master's tree. Allows the user to specify the build type.
Definition at line 50 of file point_locator_tree.C.
References init().
                                                                    :
  PointLocatorBase (mesh,master),
  _tree (NULL),
  _element (NULL),
  _out_of_mesh_mode(false)
{
  this->init(build_type);
}
libMesh::PointLocatorTree::~PointLocatorTree ()
Destructor.
Definition at line 64 of file point_locator_tree.C.
References clear().
{
  this->clear ();
}
Member Function Documentation
AutoPtr< PointLocatorBase > libMesh::PointLocatorBase::build (const PointLocatorTypet, const MeshBase &mesh, const PointLocatorBase *master = NULL) [static], [inherited]
Builds an PointLocator for the mesh mesh. Optionally takes a master PointLocator to save memory. An AutoPtr<PointLocatorBase> is returned to prevent memory leak. This way the user need not remember to delete the object.
Definition at line 56 of file point_locator_base.C.
References libMesh::err, libMesh::LIST, and libMesh::TREE.
Referenced by libMesh::MeshBase::point_locator(), and libMesh::MeshBase::sub_point_locator().
{
  switch (t)
    {
    case TREE:
      {
        AutoPtr<PointLocatorBase> ap(new PointLocatorTree(mesh,
                                                          master));
        return ap;
      }
    case LIST:
      {
        AutoPtr<PointLocatorBase> ap(new PointLocatorList(mesh,
                                                          master));
        return ap;
      }
    default:
      {
        libMesh::err << "ERROR: Bad PointLocatorType = " << t << std::endl;
        libmesh_error();
      }
    }
  libmesh_error();
  AutoPtr<PointLocatorBase> ap(NULL);
  return ap;
}
void libMesh::PointLocatorTree::clear () [virtual]
Clears the locator. This function frees dynamic memory with 'delete'.
Implements libMesh::PointLocatorBase.
Definition at line 72 of file point_locator_tree.C.
References libMesh::PointLocatorBase::_master, and _tree.
Referenced by ~PointLocatorTree().
{
  // only delete the tree when we are the master
  if (this->_tree != NULL)
    {
      if (this->_master == NULL)
        // we own the tree
        delete this->_tree;
      else
        // someone else owns and therefore deletes the tree
        this->_tree = NULL;
    }
}
void libMesh::PointLocatorTree::disable_out_of_mesh_mode (void) [virtual]
Disables out-of-mesh mode (default). If asked to find a point that is contained in no mesh at all, the point locator will now crash.
Implements libMesh::PointLocatorBase.
Definition at line 270 of file point_locator_tree.C.
{
  _out_of_mesh_mode = false;
}
void libMesh::ReferenceCounter::disable_print_counter_info () [static], [inherited]
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = false;
  return;
}
void libMesh::PointLocatorTree::enable_out_of_mesh_mode (void) [virtual]
Enables out-of-mesh mode. In this mode, if asked to find a point that is contained in no mesh at all, the point locator will return a NULL pointer instead of crashing. Per default, this mode is off.
Implements libMesh::PointLocatorBase.
Definition at line 245 of file point_locator_tree.C.
References libMesh::err.
{
  /* Out-of-mesh mode is currently only supported if all of the
     elements have affine mappings. The reason is that for quadratic
     mappings, it is not easy to construct a relyable bounding box of
     the element, and thus, the fallback linear search in \p
     operator() is required. Hence, out-of-mesh mode would be
     extremely slow. */
  if(!_out_of_mesh_mode)
    {
#ifdef DEBUG
      MeshBase::const_element_iterator pos = this->_mesh.active_elements_begin();
      const MeshBase::const_element_iterator end_pos = this->_mesh.active_elements_end();
      for ( ; pos != end_pos; ++pos)
        if (!(*pos)->has_affine_map())
          {
            libMesh::err << "ERROR: Out-of-mesh mode is currently only supported if all elements have affine mappings." << std::endl;
            libmesh_error();
          }
#endif
      _out_of_mesh_mode = true;
    }
}
void libMesh::ReferenceCounter::enable_print_counter_info () [static], [inherited]
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = true;
  return;
}
std::string libMesh::ReferenceCounter::get_info () [static], [inherited]
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
{
#if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
  std::ostringstream oss;
  oss << '\n'
      << " ---------------------------------------------------------------------------- \n"
      << "| Reference count information |\n"
      << " ---------------------------------------------------------------------------- \n";
  for (Counts::iterator it = _counts.begin();
       it != _counts.end(); ++it)
    {
      const std::string name(it->first);
      const unsigned int creations = it->second.first;
      const unsigned int destructions = it->second.second;
      oss << "| " << name << " reference count information:\n"
          << "| Creations: " << creations << '\n'
          << "| Destructions: " << destructions << '\n';
    }
  oss << " ---------------------------------------------------------------------------- \n";
  return oss.str();
#else
  return "";
#endif
}
void libMesh::ReferenceCounter::increment_constructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.first++;
}
void libMesh::ReferenceCounter::increment_destructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.second++;
}
void libMesh::PointLocatorTree::init (const Trees::BuildTypebuild_type)
Initializes the locator, so that the operator() methods can be used. This function allocates dynamic memory with 'new'.
Definition at line 90 of file point_locator_tree.C.
References _element, libMesh::PointLocatorBase::_initialized, libMesh::PointLocatorBase::_master, libMesh::PointLocatorBase::_mesh, _tree, std::abs(), libMesh::MeshTools::bounding_box(), libMesh::err, libMesh::PointLocatorBase::initialized(), libMesh::libmesh_assert(), libMesh::MeshBase::mesh_dimension(), libMesh::Real, libMesh::START_LOG(), and libMesh::STOP_LOG().
{
  libmesh_assert (!this->_tree);
  if (this->_initialized)
    {
      libMesh::err << "ERROR: Already initialized! Will ignore this call..."
                   << std::endl;
    }
  else
    {
      if (this->_master == NULL)
        {
          START_LOG("init(no master)", "PointLocatorTree");
          if (this->_mesh.mesh_dimension() == 3)
            _tree = new Trees::OctTree (this->_mesh, 200, build_type);
          else
            {
              // A 1D/2D mesh in 3D space needs special consideration.
              // If the mesh is planar XY, we want to build a QuadTree
              // to search efficiently. If the mesh is truly a manifold,
              // then we need an octree
#if LIBMESH_DIM > 2
              bool is_planar_xy = false;
              // Build the bounding box for the mesh. If the delta-z bound is
              // negligibly small then we can use a quadtree.
              {
                MeshTools::BoundingBox bbox = MeshTools::bounding_box(this->_mesh);
                const Real
                  Dx = bbox.second(0) - bbox.first(0),
                  Dz = bbox.second(2) - bbox.first(2);
                if (std::abs(Dz/(Dx + 1.e-20)) < 1e-10)
                  is_planar_xy = true;
              }
              if (!is_planar_xy)
                _tree = new Trees::OctTree (this->_mesh, 200, build_type);
              else
#endif
#if LIBMESH_DIM > 1
                _tree = new Trees::QuadTree (this->_mesh, 200, build_type);
#else
              _tree = new Trees::BinaryTree (this->_mesh, 200, build_type);
#endif
            }
          STOP_LOG("init(no master)", "PointLocatorTree");
        }
      else
        {
          // We are _not_ the master. Let our Tree point to
          // the master's tree. But for this we first transform
          // the master in a state for which we are friends.
          // And make sure the master @e has a tree!
          const PointLocatorTree* my_master =
            libmesh_cast_ptr<const PointLocatorTree*>(this->_master);
          if (my_master->initialized())
            this->_tree = my_master->_tree;
          else
            {
              libMesh::err << "ERROR: Initialize master first, then servants!"
                           << std::endl;
              libmesh_error();
            }
        }
      // Not all PointLocators may own a tree, but all of them
      // use their own element pointer. Let the element pointer
      // be unique for every interpolator.
      // Suppose the interpolators are used concurrently
      // at different locations in the mesh, then it makes quite
      // sense to have unique start elements.
      this->_element = NULL;
    }
  // ready for take-off
  this->_initialized = true;
}
virtual void libMesh::PointLocatorTree::init () [inline], [virtual]
Initializes the locator, so that the operator() methods can be used. This function allocates dynamic memory with 'new'.
Implements libMesh::PointLocatorBase.
Definition at line 108 of file point_locator_tree.h.
References init(), and libMesh::Trees::NODES.
Referenced by init(), and PointLocatorTree().
{ this->init(Trees::NODES); }
bool libMesh::PointLocatorBase::initialized () const [inline], [inherited]
Returns:
true when this object is properly initialized and ready for use, false otherwise.
Definition at line 150 of file point_locator_base.h.
References libMesh::PointLocatorBase::_initialized.
Referenced by init(), and libMesh::PointLocatorList::init().
{
  return (this->_initialized);
}
static unsigned int libMesh::ReferenceCounter::n_objects () [inline], [static], [inherited]
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
  { return _n_objects; }
const Elem * libMesh::PointLocatorTree::operator() (const Point &p) const [virtual]
Locates the element in which the point with global coordinates p is located. The mutable _element member is used to cache the result and allow it to be used during the next call to operator().
Implements libMesh::PointLocatorBase.
Definition at line 185 of file point_locator_tree.C.
References libMesh::libmesh_assert(), libMesh::START_LOG(), and libMesh::STOP_LOG().
{
  libmesh_assert (this->_initialized);
  START_LOG("operator()", "PointLocatorTree");
  // First check the element from last time before asking the tree
  if (this->_element==NULL || !(this->_element->contains_point(p)))
    {
      // ask the tree
      this->_element = this->_tree->find_element (p);
      if (this->_element == NULL)
        {
          /* No element seems to contain this point. If out-of-mesh
             mode is enabled, just return NULL. If not, however, we
             have to perform a linear search before we call \p
             libmesh_error() since in the case of curved elements, the
             bounding box computed in \p TreeNode::insert(const
             Elem*) might be slightly inaccurate. */
          if(!_out_of_mesh_mode)
            {
              START_LOG("linear search", "PointLocatorTree");
              MeshBase::const_element_iterator pos = this->_mesh.active_elements_begin();
              const MeshBase::const_element_iterator end_pos = this->_mesh.active_elements_end();
              for ( ; pos != end_pos; ++pos)
                if ((*pos)->contains_point(p))
                  {
                    STOP_LOG("linear search", "PointLocatorTree");
                    STOP_LOG("operator()", "PointLocatorTree");
                    return this->_element = (*pos);
                  }
              /*
                if (this->_element == NULL)
                {
                libMesh::err << std::endl
                << " ******** Serious Problem. Could not find an Element "
                << "in the Mesh"
                << std:: endl
                << " ******** that contains the Point "
                << p;
                libmesh_error();
                }
              */
              STOP_LOG("linear search", "PointLocatorTree");
            }
        }
    }
  // If we found an element, it should be active
  libmesh_assert (!this->_element || this->_element->active());
  STOP_LOG("operator()", "PointLocatorTree");
  // return the element
  return this->_element;
}
void libMesh::ReferenceCounter::print_info (std::ostream &out = libMesh::out) [static], [inherited]
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
{
  if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
}
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts [static], [protected], [inherited]
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
const Elem* libMesh::PointLocatorTree::_element [mutable], [protected]
Pointer to the last element that was found by the tree. Chances are that this may be close to the next call to operator()...
Definition at line 147 of file point_locator_tree.h.
Referenced by init().
bool libMesh::ReferenceCounter::_enable_print_counter = true [static], [protected], [inherited]
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
bool libMesh::PointLocatorBase::_initialized [protected], [inherited]
true when properly initialized, false otherwise.
Definition at line 142 of file point_locator_base.h.
Referenced by init(), libMesh::PointLocatorList::init(), and libMesh::PointLocatorBase::initialized().
const PointLocatorBase* libMesh::PointLocatorBase::_master [protected], [inherited]
Const pointer to our master, initialized to NULL if none given. When using multiple PointLocators, one can be assigned master and be in charge of something that all can have access to.
Definition at line 132 of file point_locator_base.h.
Referenced by libMesh::PointLocatorList::clear(), clear(), init(), and libMesh::PointLocatorList::init().
const MeshBase& libMesh::PointLocatorBase::_mesh [protected], [inherited]
constant reference to the mesh in which the point is looked for.
Definition at line 137 of file point_locator_base.h.
Referenced by init(), and libMesh::PointLocatorList::init().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex [static], [protected], [inherited]
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects [static], [protected], [inherited]
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
bool libMesh::PointLocatorTree::_out_of_mesh_mode [protected]
true if out-of-mesh mode is enabled. See enable_out_of_mesh_mode() for details.
Definition at line 153 of file point_locator_tree.h.
TreeBase* libMesh::PointLocatorTree::_tree [protected]
Pointer to our tree. The tree is built at run-time through init(). For servant PointLocators (not master), this simply points to the tree of the master.
Definition at line 140 of file point_locator_tree.h.
Referenced by clear(), and init().
Author
Generated automatically by Doxygen for libMesh from the source code.