libMesh::ConstFEMFunction< Output >
NAME
libMesh::ConstFEMFunction< Output > -
SYNOPSIS
#include <const_fem_function.h>
Inherits libMesh::FEMFunctionBase< Output >.
Public Member Functions
ConstFEMFunction (const Output c)
~ConstFEMFunction ()
virtual AutoPtr
< FEMFunctionBase< Output > > clone () const "
virtual Output operator() (const FEMContext &, const Point &, const Real=0.)
virtual void operator() (const FEMContext &, const Point &, const Real, DenseVector< Output > &output)
virtual void init_context (const FEMContext &)
void operator() (const FEMContext &, const Point &p, DenseVector< Output > &output)
virtual Output component (const FEMContext &, unsigned int i, const Point &p, Real time=0.)
Protected Attributes
unsigned int var_index
Private Attributes
Output _c
Detailed Description
template<typename Output = Number>class libMesh::ConstFEMFunction< Output >
Definition at line 30 of file const_fem_function.h.
Constructor & Destructor Documentation
template<typename Output = Number> libMesh::ConstFEMFunction< Output >::ConstFEMFunction (const Outputc) [inline]
Definition at line 33 of file const_fem_function.h.
References libMesh::ConstFEMFunction< Output >::_c.
Referenced by libMesh::ConstFEMFunction< Output >::clone().
{_c = c;}
template<typename Output = Number> libMesh::ConstFEMFunction< Output >::~ConstFEMFunction () [inline]
Definition at line 35 of file const_fem_function.h.
{}
Member Function Documentation
template<typename Output = Number> virtual AutoPtr<FEMFunctionBase<Output> > libMesh::ConstFEMFunction< Output >::clone () const [inline], [virtual]
Returns a new copy of the function. The new copy should be as ``deep'' as necessary to allow independent destruction and simultaneous evaluations of the copies in different threads.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 37 of file const_fem_function.h.
References libMesh::ConstFEMFunction< Output >::ConstFEMFunction().
  {return AutoPtr<FEMFunctionBase<Output> >( new ConstFEMFunction(*this) ); }
template<typename Output > Output libMesh::FEMFunctionBase< Output >::component (const FEMContext &context, unsigned inti, const Point &p, Realtime = 0.) [inline], [virtual], [inherited]
Returns:
the vector component i at coordinate p and time time. Subclasses aren't required to overload this, since the default implementation is based on the full vector evaluation, which is often correct. Subclasses are recommended to overload this, since the default implementation is based on a vector evaluation, which is usually unnecessarily inefficient.
Definition at line 135 of file fem_function_base.h.
Referenced by libMesh::System::project_vector().
{
  DenseVector<Output> outvec(i+1);
  (*this)(context, p, time, outvec);
  return outvec(i);
}
template<typename Output = Number> virtual void libMesh::FEMFunctionBase< Output >::init_context (const FEMContext &) [inline], [virtual], [inherited]
Prepares a context object for use.
Most problems will want to reimplement this for efficiency, in order to call FE::get_*() as their particular function requires.
Definition at line 68 of file fem_function_base.h.
{}
template<typename Output = Number> virtual Output libMesh::ConstFEMFunction< Output >::operator() (const FEMContext &, const Point &p, const Realtime = 0.) [inline], [virtual]
Returns:
the scalar value at coordinate p and time time, which defaults to zero. Purely virtual, so you have to overload it. Note that this cannot be a const method, check MeshFunction.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 40 of file const_fem_function.h.
References libMesh::ConstFEMFunction< Output >::_c.
  { return _c; }
template<typename Output = Number> virtual void libMesh::ConstFEMFunction< Output >::operator() (const FEMContext &, const Point &p, const Realtime, DenseVector< Output > &output) [inline], [virtual]
Return function for vectors. Returns in output the values of the data at the coordinate p and for time time. Purely virtual, so you have to overload it. Note that this cannot be a const method, check MeshFunction.
Implements libMesh::FEMFunctionBase< Output >.
Definition at line 44 of file const_fem_function.h.
References libMesh::ConstFEMFunction< Output >::_c, and libMesh::DenseVector< T >::size().
  {for(unsigned int i = 0; i < output.size(); i++ )
      output(i) = _c;}
template<typename Output> void libMesh::FEMFunctionBase< Output >::operator() (const FEMContext &context, const Point &p, DenseVector< Output > &output) [inline], [inherited]
Return function for vectors. Returns in output the values of the data at the coordinate p.
Definition at line 146 of file fem_function_base.h.
{
  // Call the time-dependent function with t=0.
  this->operator()(context, p, 0., output);
}
Member Data Documentation
template<typename Output = Number> Output libMesh::ConstFEMFunction< Output >::_c [private]
Definition at line 51 of file const_fem_function.h.
Referenced by libMesh::ConstFEMFunction< Output >::ConstFEMFunction(), and libMesh::ConstFEMFunction< Output >::operator()().
template<typename Output = Number> unsigned int libMesh::FEMFunctionBase< Output >::var_index [protected], [inherited]
Variable index to decide which overloaded function should be accessed
Definition at line 129 of file fem_function_base.h.
Author
Generated automatically by Doxygen for libMesh from the source code.