.TH "libMesh::FiniteElements" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::FiniteElements \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBFEClough\fP< 2 > \fBFEClough2D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 1, \fBHIERARCHIC\fP > \fBFEHierarchic1D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 2, \fBHIERARCHIC\fP > \fBFEHierarchic2D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 3, \fBHIERARCHIC\fP > \fBFEHierarchic3D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 1, \fBL2_HIERARCHIC\fP > \fBFEL2Hierarchic1D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 2, \fBL2_HIERARCHIC\fP > \fBFEL2Hierarchic2D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 3, \fBL2_HIERARCHIC\fP > \fBFEL2Hierarchic3D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 1, \fBLAGRANGE\fP > \fBFELagrange1D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 2, \fBLAGRANGE\fP > \fBFELagrange2D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 3, \fBLAGRANGE\fP > \fBFELagrange3D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 1, \fBL2_LAGRANGE\fP > \fBFEL2Lagrange1D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 2, \fBL2_LAGRANGE\fP > \fBFEL2Lagrange2D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 3, \fBL2_LAGRANGE\fP > \fBFEL2Lagrange3D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 1, \fBMONOMIAL\fP > \fBFEMonomial1D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 2, \fBMONOMIAL\fP > \fBFEMonomial2D\fP"
.br
.ti -1c
.RI "typedef \fBFE\fP< 3, \fBMONOMIAL\fP > \fBFEMonomial3D\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provide Typedefs for various element types\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBFEClough\fP<2> \fBlibMesh::FiniteElements::FEClough2D\fP"
Convenient definition for a 2D Clough-Tocher finite element\&. 
.PP
Definition at line 938 of file fe\&.h\&.
.SS "typedef \fBFE\fP<1,\fBHIERARCHIC\fP> \fBlibMesh::FiniteElements::FEHierarchic1D\fP"
Convenient definition for a 1D Hierarchic finite element\&. 
.PP
Definition at line 944 of file fe\&.h\&.
.SS "typedef \fBFE\fP<2,\fBHIERARCHIC\fP> \fBlibMesh::FiniteElements::FEHierarchic2D\fP"
Convenient definition for a 2D Hierarchic finite element\&. 
.PP
Definition at line 950 of file fe\&.h\&.
.SS "typedef \fBFE\fP<3,\fBHIERARCHIC\fP> \fBlibMesh::FiniteElements::FEHierarchic3D\fP"
Convenient definition for a 3D Hierarchic finite element\&. 
.PP
Definition at line 956 of file fe\&.h\&.
.SS "typedef \fBFE\fP<1,\fBL2_HIERARCHIC\fP> \fBlibMesh::FiniteElements::FEL2Hierarchic1D\fP"
Convenient definition for a 1D Discontinuous Hierarchic finite element\&. 
.PP
Definition at line 963 of file fe\&.h\&.
.SS "typedef \fBFE\fP<2,\fBL2_HIERARCHIC\fP> \fBlibMesh::FiniteElements::FEL2Hierarchic2D\fP"
Convenient definition for a 2D Discontinuous Hierarchic finite element\&. 
.PP
Definition at line 969 of file fe\&.h\&.
.SS "typedef \fBFE\fP<3,\fBL2_HIERARCHIC\fP> \fBlibMesh::FiniteElements::FEL2Hierarchic3D\fP"
Convenient definition for a 3D Discontinuous Hierarchic finite element\&. 
.PP
Definition at line 975 of file fe\&.h\&.
.SS "typedef \fBFE\fP<1,\fBL2_LAGRANGE\fP> \fBlibMesh::FiniteElements::FEL2Lagrange1D\fP"
Convenient definition for a 1D Discontinuous Lagrange finite element\&. 
.PP
Definition at line 1001 of file fe\&.h\&.
.SS "typedef \fBFE\fP<2,\fBL2_LAGRANGE\fP> \fBlibMesh::FiniteElements::FEL2Lagrange2D\fP"
Convenient definition for a 2D Discontinuous Lagrange finite element\&. 
.PP
Definition at line 1007 of file fe\&.h\&.
.SS "typedef \fBFE\fP<3,\fBL2_LAGRANGE\fP> \fBlibMesh::FiniteElements::FEL2Lagrange3D\fP"
Convenient definition for a 3D Discontinuous Lagrange finite element\&. 
.PP
Definition at line 1013 of file fe\&.h\&.
.SS "typedef \fBFE\fP<1,\fBLAGRANGE\fP> \fBlibMesh::FiniteElements::FELagrange1D\fP"
Convenient definition for a 1D Lagrange finite element\&. 
.PP
Definition at line 982 of file fe\&.h\&.
.SS "typedef \fBFE\fP<2,\fBLAGRANGE\fP> \fBlibMesh::FiniteElements::FELagrange2D\fP"
Convenient definition for a 2D Lagrange finite element\&. 
.PP
Definition at line 988 of file fe\&.h\&.
.SS "typedef \fBFE\fP<3,\fBLAGRANGE\fP> \fBlibMesh::FiniteElements::FELagrange3D\fP"
Convenient definition for a 3D Lagrange finite element\&. 
.PP
Definition at line 994 of file fe\&.h\&.
.SS "typedef \fBFE\fP<1,\fBMONOMIAL\fP> \fBlibMesh::FiniteElements::FEMonomial1D\fP"
Convenient definition for a 1D Monomial finite element\&. 
.PP
Definition at line 1020 of file fe\&.h\&.
.SS "typedef \fBFE\fP<2,\fBMONOMIAL\fP> \fBlibMesh::FiniteElements::FEMonomial2D\fP"
Convenient definition for a 2D Monomial finite element\&. 
.PP
Definition at line 1026 of file fe\&.h\&.
.SS "typedef \fBFE\fP<3,\fBMONOMIAL\fP> \fBlibMesh::FiniteElements::FEMonomial3D\fP"
Convenient definition for a 3D Monomial finite element\&. 
.PP
Definition at line 1032 of file fe\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
