libMesh::QGrundmann_Moller
NAME
libMesh::QGrundmann_Moller -
SYNOPSIS
#include <quadrature_gm.h>
Inherits libMesh::QBase.
Public Member Functions
QGrundmann_Moller (const unsigned int _dim, const Order _order=INVALID_ORDER)
~QGrundmann_Moller ()
QuadratureType type () const
ElemType get_elem_type () const
unsigned int get_p_level () const
unsigned int n_points () const
unsigned int get_dim () const
const std::vector< Point > & get_points () const
std::vector< Point > & get_points ()
const std::vector< Real > & get_weights () const
std::vector< Real > & get_weights ()
Point qp (const unsigned int i) const
Real w (const unsigned int i) const
void init (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
Order get_order () const
void print_info (std::ostream &os=libMesh::out) const
void scale (std::pair< Real, Real > old_range, std::pair< Real, Real > new_range)
virtual bool shapes_need_reinit ()
Static Public Member Functions
static AutoPtr< QBase > build (const std::string &name, const unsigned int _dim, const Order _order=INVALID_ORDER)
static AutoPtr< QBase > build (const QuadratureType _qt, const unsigned int _dim, const Order _order=INVALID_ORDER)
static void print_info (std::ostream &out=libMesh::out)
static std::string get_info ()
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
bool allow_rules_with_negative_weights
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts"
Protected Member Functions
virtual void init_0D (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
virtual void init_2D (const ElemType, unsigned int=0)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
libMesh::err<< 'ERROR: Seems
as if this quadrature rule'
<< std::endl<< ' is not
implemented for 2D.'<< std::endl;libmesh_error();}#endif virtual void init_3D(const ElemType, unsigned int=0)#ifndef DEBUG{}#else{libMesh::err<< 'ERROR: Seems as if this quadrature rule'<< std::endl<< ' is not implemented for 3D.'<< std::endl;libmesh_error();}#endif void tensor_product_quad(const QBase &q1D);void tensor_product_hex(const QBase &q1D);void tensor_product_prism(const QBase &q1D, const QBase &q2D);const unsigned int _dim;const Order _order;ElemType _type;unsigned int _p_level;std::vector< Point > _points"
std::vector< Real > _weights
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects"
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
void init_1D (const ElemType, unsigned int=0)
void init_3D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0)
void gm_rule (unsigned int s)
void compose_all (unsigned int s, unsigned int p, std::vector< std::vector< unsigned int > > &result)
Detailed Description
This class implements the Grundmann-Moller quadrature rules for tetrahedra. The GM rules are well-defined for simplices of arbitrary dimension and to any order, but the rules by Dunavant for two-dimensional simplices are in general superior. This is primarily due to the fact that the GM rules contain a significant proportion of negative weights, making them susceptible to round-off error at high-order.
The GM rules are interesting in 3D because they overlap with the conical product rules at higher order while having significantly fewer evaluation points, making them potentially much more efficient. The table below gives a comparison between the number of points in a conical product (CP) rule and the GM rule of equivalent order. The GM rules are defined to be exact for polynomials of degree d=2*s+1, s=0,1,2,3,... The table also gives the percentage of each GM rule's weights which are negative. Although the percentage of negative weights does not grow particularly quickly, the amplification factor (a measure of the effect of round-off) defined as
amp. factor = $ \frac{1}{V} \sum \|w_i\|, $
where V is the volume of the reference element, does grow quickly. (A rule with all positive has has an amplification factor of 1.0 by definition.)
s | d | N. CP | N. GM | % neg wts | amp. factor
-----------------------------------------------------------------
 | 1 | | 1 | |
 | 2-3 | | 5 | |
 | 4-5 | | 15 | |
 | 6-7 | | 35 | 31.43 | 11.94
 | 8-9 | 5^3=125 | 70 | 34.29 | 25.35
 | 10-11 | 6^3=216 | 126 | 36.51 | 54.14
 | 12-13 | 7^3=343 | 210 | 38.10 | 116.30
 | 14-15 | 8^3=512 | 330 | 39.39 | 251.10
 | 16-17 | 9^3=729 | 495 | 40.40 | 544.68
 | 18-19 | 10^3=1,000 | 715 | 41.26 | 1186.16
 | 20-21 | 11^3=1,331 | 1,001 | 41.96 | 2591.97
 | 22-23 | 12^3=1,728 | 1,365 | 42.56 | 5680.75
...
 | 32-33 | 17^3=4,913 | 4,845 |
 | 34-35 | 18^3=5,832 | 5,985 | <= Cross-over point, CP has fewer points for d >= 34
 | 36-37 | 19^3=6,859 | 7,315 |
...
 | 42-43 | 22^3=10,648 | 12,650 |
Reference: Axel Grundmann and Michael M"{o}ller, 'Invariant Integration Formulas for the N-Simplex
     by Combinatorial Methods,' SIAM Journal on Numerical Analysis, Volume 15, Number 2, April 1978, pages 282-290.
Reference LGPL Fortran90 code by John Burkardt can be found here: http://people.scs.fsu.edu/~burkardt/f_src/gm_rules/gm_rules.html
Author:
John W. Peterson, 2008
Definition at line 100 of file quadrature_gm.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts [protected], [inherited]
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::QGrundmann_Moller::QGrundmann_Moller (const unsigned int_dim, const Order_order = INVALID_ORDER)
Constructor. Declares the order of the quadrature rule.
Definition at line 32 of file quadrature_gm.C.
                                                    : QBase(d,o)
{
}
libMesh::QGrundmann_Moller::~QGrundmann_Moller ()
Destructor.
Definition at line 39 of file quadrature_gm.C.
{
}
Member Function Documentation
AutoPtr< QBase > libMesh::QBase::build (const std::string &name, const unsigned int_dim, const Order_order = INVALID_ORDER) [static], [inherited]
Builds a specific quadrature rule, identified through the name string. An AutoPtr<QBase> is returned to prevent a memory leak. This way the user need not remember to delete the object. Enables run-time decision of the quadrature rule. The input parameter name must be mappable through the Utility::string_to_enum<>() function.
Definition at line 40 of file quadrature_build.C.
Referenced by libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::attach_quadrature_rule().
{
  return QBase::build (Utility::string_to_enum<QuadratureType> (type),
                       _dim,
                       _order);
}
AutoPtr< QBase > libMesh::QBase::build (const QuadratureType_qt, const unsigned int_dim, const Order_order = INVALID_ORDER) [static], [inherited]
Builds a specific quadrature rule, identified through the QuadratureType. An AutoPtr<QBase> is returned to prevent a memory leak. This way the user need not remember to delete the object. Enables run-time decision of the quadrature rule.
Definition at line 51 of file quadrature_build.C.
References libMesh::err, libMesh::FIRST, libMesh::FORTYTHIRD, libMesh::out, libMesh::QCLOUGH, libMesh::QGAUSS, libMesh::QGRID, libMesh::QGRUNDMANN_MOLLER, libMesh::QJACOBI_1_0, libMesh::QJACOBI_2_0, libMesh::QMONOMIAL, libMesh::QSIMPSON, libMesh::QTRAP, libMesh::THIRD, and libMesh::TWENTYTHIRD.
{
  switch (_qt)
    {
    case QCLOUGH:
      {
#ifdef DEBUG
        if (_order > TWENTYTHIRD)
          {
            libMesh::out << "WARNING: Clough quadrature implemented" << std::endl
                         << " up to TWENTYTHIRD order." << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QClough(_dim, _order));
        return ap;
      }
    case QGAUSS:
      {
#ifdef DEBUG
        if (_order > FORTYTHIRD)
          {
            libMesh::out << "WARNING: Gauss quadrature implemented" << std::endl
                         << " up to FORTYTHIRD order." << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QGauss(_dim, _order));
        return ap;
      }
    case QJACOBI_1_0:
      {
#ifdef DEBUG
        if (_order > TWENTYTHIRD)
          {
            libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                         << " up to TWENTYTHIRD order." << std::endl;
          }
        if (_dim > 1)
          {
            libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                         << " in 1D only." << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QJacobi(_dim, _order, 1, 0));
        return ap;
      }
    case QJACOBI_2_0:
      {
#ifdef DEBUG
        if (_order > TWENTYTHIRD)
          {
            libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                         << " up to TWENTYTHIRD order." << std::endl;
          }
        if (_dim > 1)
          {
            libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                         << " in 1D only." << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QJacobi(_dim, _order, 2, 0));
        return ap;
      }
    case QSIMPSON:
      {
#ifdef DEBUG
        if (_order > THIRD)
          {
            libMesh::out << "WARNING: Simpson rule provides only" << std::endl
                         << " THIRD order!" << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QSimpson(_dim));
        return ap;
      }
    case QTRAP:
      {
#ifdef DEBUG
        if (_order > FIRST)
          {
            libMesh::out << "WARNING: Trapezoidal rule provides only" << std::endl
                         << " FIRST order!" << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QTrap(_dim));
        return ap;
      }
    case QGRID:
      {
        AutoPtr<QBase> ap(new QGrid(_dim, _order));
        return ap;
      }
    case QGRUNDMANN_MOLLER:
      {
        AutoPtr<QBase> ap(new QGrundmann_Moller(_dim, _order));
        return ap;
      }
    case QMONOMIAL:
      {
        AutoPtr<QBase> ap(new QMonomial(_dim, _order));
        return ap;
      }
    default:
      {
        libMesh::err << "ERROR: Bad qt=" << _qt << std::endl;
        libmesh_error();
      }
    }
  libmesh_error();
  AutoPtr<QBase> ap(NULL);
  return ap;
}
void libMesh::QGrundmann_Moller::compose_all (unsigned ints, unsigned intp, std::vector< std::vector< unsigned int > > &result) [private]
Routine which generates p-compositions of a given order, s, as well as permutations thereof. This routine is called internally by the gm_rule() routine, you should not call this yourself!
Definition at line 144 of file quadrature_gm.C.
References libMesh::libmesh_assert_greater().
Referenced by gm_rule().
{
  // Clear out results remaining from previous calls
  result.clear();
  // Allocate storage for a workspace. The workspace will periodically
  // be copied into the result container.
  std::vector<unsigned int> workspace(p);
  // The first result is always (s,0,...,0)
  workspace[0] = s;
  result.push_back(workspace);
  // the value of the first non-zero entry
  unsigned int head_value=s;
  // When head_index=-1, it refers to "off the front" of the array. Therefore,
  // this needs to be a regular int rather than unsigned. I initially tried to
  // do this with head_index unsigned and an else statement below, but then there
  // is the special case: (1,0,...,0) which does not work correctly.
  int head_index = -1;
  // At the end, all the entries will be in the final slot of workspace
  while (workspace.back() != s)
    {
      // Uncomment for debugging
      //libMesh::out << "previous head_value=" << head_value << " -> ";
      // If the previous head value is still larger than 1, reset the index
      // to "off the front" of the array
      if (head_value > 1)
        head_index = -1;
      // Either move the index onto the front of the array or on to
      // the next value.
      head_index++;
      // Get current value of the head entry
      head_value = workspace[head_index];
      // Uncomment for debugging
      //std::copy(workspace.begin(), workspace.end(), std::ostream_iterator<int>(libMesh::out, " "));
      //libMesh::out << ", head_index=" << head_index;
      //libMesh::out << ", head_value=" << head_value << " -> ";
      // Put a zero into the head_index of the array. If head_index==0,
      // this will be overwritten in the next line with head_value-1.
      workspace[head_index] = 0;
      // The initial entry gets the current head value, minus 1.
      // If head_value > 1, the next loop iteration will start back
      // at workspace[0] again.
      libmesh_assert_greater (head_value, 0);
      workspace[0] = head_value - 1;
      // Increment the head+1 value
      workspace[head_index+1] += 1;
      // Save this composition in the results
      result.push_back(workspace);
      // Uncomment for debugging
      //std::copy(workspace.begin(), workspace.end(), std::ostream_iterator<int>(libMesh::out, " "));
      //libMesh::out<<"\n";
    }
}
void libMesh::ReferenceCounter::disable_print_counter_info () [static], [inherited]
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = false;
  return;
}
void libMesh::ReferenceCounter::enable_print_counter_info () [static], [inherited]
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = true;
  return;
}
unsigned int libMesh::QBase::get_dim () const [inline], [inherited]
Returns:
the dimension of the quadrature rule.
Definition at line 123 of file quadrature.h.
Referenced by libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::attach_quadrature_rule(), libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), and libMesh::QConical::conical_product_tri().
{ return _dim; }
ElemType libMesh::QBase::get_elem_type () const [inline], [inherited]
Returns:
the current element type we're set up for
Definition at line 104 of file quadrature.h.
  { return _type; }
std::string libMesh::ReferenceCounter::get_info () [static], [inherited]
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
{
#if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
  std::ostringstream oss;
  oss << '\n'
      << " ---------------------------------------------------------------------------- \n"
      << "| Reference count information |\n"
      << " ---------------------------------------------------------------------------- \n";
  for (Counts::iterator it = _counts.begin();
       it != _counts.end(); ++it)
    {
      const std::string name(it->first);
      const unsigned int creations = it->second.first;
      const unsigned int destructions = it->second.second;
      oss << "| " << name << " reference count information:\n"
          << "| Creations: " << creations << '\n'
          << "| Destructions: " << destructions << '\n';
    }
  oss << " ---------------------------------------------------------------------------- \n";
  return oss.str();
#else
  return "";
#endif
}
Order libMesh::QBase::get_order () const [inline], [inherited]
Returns:
the order of the quadrature rule.
Definition at line 169 of file quadrature.h.
Referenced by libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::attach_quadrature_rule().
{ return static_cast<Order>(_order + _p_level); }
unsigned int libMesh::QBase::get_p_level () const [inline], [inherited]
Returns:
the current p refinement level we're initialized with
Definition at line 110 of file quadrature.h.
  { return _p_level; }
const std::vector<Point>& libMesh::QBase::get_points () const [inline], [inherited]
Returns:
a std::vector containing the quadrature point locations on a reference object.
Definition at line 129 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by libMesh::QClough::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::FESubdivision::reinit().
{ return _points; }
std::vector<Point>& libMesh::QBase::get_points () [inline], [inherited]
Returns:
a std::vector containing the quadrature point locations on a reference object as a writeable reference.
Definition at line 135 of file quadrature.h.
References libMesh::QBase::_points.
{ return _points; }
const std::vector<Real>& libMesh::QBase::get_weights () const [inline], [inherited]
Returns:
a std::vector containing the quadrature weights.
Definition at line 140 of file quadrature.h.
References libMesh::QBase::_weights.
Referenced by libMesh::QClough::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::FESubdivision::reinit().
{ return _weights; }
std::vector<Real>& libMesh::QBase::get_weights () [inline], [inherited]
Returns:
a std::vector containing the quadrature weights.
Definition at line 145 of file quadrature.h.
References libMesh::QBase::_weights.
{ return _weights; }
void libMesh::QGrundmann_Moller::gm_rule (unsigned ints) [private]
This routine is called from the different cases of init_3D(). It actually fills the _points and _weights vectors for a given rule index, s.
Definition at line 47 of file quadrature_gm.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, compose_all(), libMesh::dim, std::max(), libMesh::Real, and libMesh::MeshTools::weight().
Referenced by init_3D().
{
  // A GM rule of index s can integrate polynomials of degree 2*s+1 exactly
  const unsigned int degree = 2*s+1;
  // Here we are considering only tetrahedra rules, so dim==3
  const unsigned int dim = 3;
  // The number of points for rule of index s is
  // (dim+1+s)! / (dim+1)! / s!
  // In 3D, this is = 1/24 * P_{i=1}^4 (s+i)
  const unsigned int n_pts = (s+4)*(s+3)*(s+2)*(s+1) / 24;
  //libMesh::out << "n_pts=" << n_pts << std::endl;
  // Allocate space for points and weights
  _points.resize(n_pts);
  _weights.resize(n_pts);
  // (-1)^i -> This one flips sign at each iteration of the i-loop below.
  int one_pm=1;
  // Where we store all the integer point compositions/permutations
  std::vector<std::vector<unsigned int> > permutations;
  // Index into the vector where we should start adding the next round of points/weights
  std::size_t offset=0;
  // Implement the GM formula 4.1 on page 286 of the paper
  for (unsigned int i=0; i<=s; ++i)
    {
      // Get all the ordered compositions (and their permutations)
      // of |beta| = s-i into dim+1=4 parts
      compose_all(s-i, dim+1, permutations);
      //libMesh::out << "n. permutations=" << permutations.size() << std::endl;
      for (unsigned int p=0; p<permutations.size(); ++p)
        {
          // We use the first dim=3 entries of each permutation to
          // construct an integration point.
          for (unsigned int j=0; j<3; ++j)
            _points[offset+p](j) =
              static_cast<Real>(2.*permutations[p][j] + 1.) /
              static_cast<Real>( degree + dim - 2.*i );
        }
      // Compute the weight for this i, being careful to avoid overflow.
      // This technique is borrowed from Burkardt's code as well.
      // Use once for each of the points obtained from the permutations array.
      Real weight = one_pm;
      // This for loop needs to run for dim, degree, or dim+degree-i iterations,
      // whichever is largest.
      const unsigned int weight_loop_index =
        std::max(dim, std::max(degree, degree+dim-i));
      for (unsigned int j=1; j<=weight_loop_index; ++j)
        {
          if (j <= degree) // Accumulate (d+n-2i)^d term
            weight *= static_cast<Real>(degree+dim-2*i);
          if (j <= 2*s) // Accumulate 2^{-2s}
            weight *= 0.5;
          if (j <= i) // Accumulate (i!)^{-1}
            weight /= static_cast<Real>(j);
          if (j <= degree+dim-i) // Accumulate ( (d+n-i)! )^{-1}
            weight /= static_cast<Real>(j);
        }
      // This is the weight for each of the points computed previously
      for (unsigned int j=0; j<permutations.size(); ++j)
        _weights[offset+j] = weight;
      // Change sign for next iteration
      one_pm = -one_pm;
      // Update offset for the next set of points
      offset += permutations.size();
    }
}
void libMesh::ReferenceCounter::increment_constructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.first++;
}
void libMesh::ReferenceCounter::increment_destructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.second++;
}
void libMesh::QBase::init (const ElemTypetype = INVALID_ELEM, unsigned intp_level = 0) [inherited]
Initializes the data structures to contain a quadrature rule for an object of type type.
Definition at line 27 of file quadrature.C.
References libMesh::QBase::init_0D(), libMesh::QBase::init_1D(), and libMesh::QBase::init_2D().
Referenced by libMesh::QClough::init_1D(), libMesh::QTrap::init_2D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGrid::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGrid::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::QGauss(), libMesh::QJacobi::QJacobi(), libMesh::QSimpson::QSimpson(), libMesh::QTrap::QTrap(), and libMesh::FESubdivision::reinit().
{
  // check to see if we have already
  // done the work for this quadrature rule
  if (t == _type && p == _p_level)
    return;
  else
    {
      _type = t;
      _p_level = p;
    }
  switch(_dim)
    {
    case 0:
      this->init_0D(_type,_p_level);
      return;
    case 1:
      this->init_1D(_type,_p_level);
      return;
    case 2:
      this->init_2D(_type,_p_level);
      return;
    case 3:
      this->init_3D(_type,_p_level);
      return;
    default:
      libmesh_error();
    }
}
void libMesh::QBase::init_0D (const ElemTypetype = INVALID_ELEM, unsigned intp_level = 0) [protected], [virtual], [inherited]
Initializes the 0D quadrature rule by filling the points and weights vectors with the appropriate values. Generally this is just one point with weight 1.
Definition at line 71 of file quadrature.C.
References libMesh::QBase::_points, and libMesh::QBase::_weights.
Referenced by libMesh::QBase::init().
{
  _points.resize(1);
  _weights.resize(1);
  _points[0] = Point(0.);
  _weights[0] = 1.0;
}
void libMesh::QGrundmann_Moller::init_1D (const ElemTypetype, unsignedp_level = 0) [inline], [private], [virtual]
Initializes the 1D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. It is assumed that derived quadrature rules will at least define the init_1D function, therefore it is pure virtual.
Implements libMesh::QBase.
Definition at line 123 of file quadrature_gm.h.
  {
    // See about making this non-pure virtual in the base class
    libmesh_error();
  }
virtual void libMesh::QBase::init_2D (const ElemType, unsigned int = 0) [inline], [protected], [virtual], [inherited]
Initializes the 2D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. Should not be pure virtual since a derived quadrature rule may only be defined in 1D. If not redefined, gives an error (when DEBUG defined) when called.
Reimplemented in libMesh::QMonomial, libMesh::QGrid, libMesh::QConical, libMesh::QSimpson, libMesh::QGauss, libMesh::QClough, and libMesh::QTrap.
Definition at line 246 of file quadrature.h.
Referenced by libMesh::QBase::init().
  {}
void libMesh::QGrundmann_Moller::init_3D (const ElemType_type = INVALID_ELEM, unsigned intp_level = 0) [private]
The GM rules are only defined for 3D since better 2D rules for simplexes are available.
Definition at line 28 of file quadrature_gm_3D.C.
References libMesh::QBase::allow_rules_with_negative_weights, libMesh::err, gm_rule(), libMesh::TET10, and libMesh::TET4.
{
  // Nearly all GM rules contain negative weights, so if you are not
  // allowing rules with negative weights, we cannot continue!
  if (!allow_rules_with_negative_weights)
    {
      libMesh::err << "You requested a Grundmann-Moller rule but\n"
                   << "are not allowing rules with negative weights!\n"
                   << "Either select a different quadrature class or\n"
                   << "set allow_rules_with_negative_weights==true."
                   << std::endl;
      libmesh_error();
    }
  switch (type_in)
    {
    case TET4:
    case TET10:
      {
        // Untested above _order=23 but should work...
        gm_rule( (_order + 2*p)/2 );
        return;
      } // end case TET4, TET10
      //---------------------------------------------
      // Unsupported element type
    default:
      {
        libMesh::err << "ERROR: Unsupported element type: " << type_in << std::endl;
        libmesh_error();
      }
    } // end switch (type_in)
  // We must have returned or errored-out by this point. If not,
  // throw an error now.
  libmesh_error();
  return;
}
static unsigned int libMesh::ReferenceCounter::n_objects () [inline], [static], [inherited]
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
  { return _n_objects; }
unsigned int libMesh::QBase::n_points () const [inline], [inherited]
Returns:
the number of points associated with the quadrature rule.
Definition at line 116 of file quadrature.h.
References libMesh::QBase::_points, and libMesh::libmesh_assert().
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::ProjectFEMSolution::operator()(), and libMesh::QBase::print_info().
  { libmesh_assert (!_points.empty());
    return libmesh_cast_int<unsigned int>(_points.size()); }
void libMesh::ReferenceCounter::print_info (std::ostream &out = libMesh::out) [static], [inherited]
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
{
  if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
}
void libMesh::QBase::print_info (std::ostream &os = libMesh::out) const [inline], [inherited]
Prints information relevant to the quadrature rule, by default to libMesh::out.
Definition at line 362 of file quadrature.h.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::libmesh_assert(), and libMesh::QBase::n_points().
Referenced by libMesh::operator<<().
{
  libmesh_assert(!_points.empty());
  libmesh_assert(!_weights.empty());
  os << "N_Q_Points=" << this->n_points() << std::endl << std::endl;
  for (unsigned int qpoint=0; qpoint<this->n_points(); qpoint++)
    {
      os << " Point " << qpoint << ":\n"
         << " "
         << _points[qpoint]
         << " Weight:\n "
         << " w=" << _weights[qpoint] << "\n" << std::endl;
    }
}
Point libMesh::QBase::qp (const unsigned inti) const [inline], [inherited]
Returns:
the $ i^{th} $ quadrature point on the reference object.
Definition at line 150 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), and libMesh::QConical::conical_product_tri().
  { libmesh_assert_less (i, _points.size()); return _points[i]; }
void libMesh::QBase::scale (std::pair< Real, Real >old_range, std::pair< Real, Real >new_range) [inherited]
Maps the points of a 1D interval quadrature rule (typically [-1,1]) to any other 1D interval (typically [0,1]) and scales the weights accordingly. The quadrature rule will be mapped from the entries of old_range to the entries of new_range.
Definition at line 82 of file quadrature.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::libmesh_assert_greater(), and libMesh::Real.
Referenced by libMesh::QConical::conical_product_tet(), and libMesh::QConical::conical_product_tri().
{
  // Make sure we are in 1D
  libmesh_assert_equal_to (_dim, 1);
  // Make sure that we have sane ranges
  libmesh_assert_greater (new_range.second, new_range.first);
  libmesh_assert_greater (old_range.second, old_range.first);
  // Make sure there are some points
  libmesh_assert_greater (_points.size(), 0);
  // We're mapping from old_range -> new_range
  for (unsigned int i=0; i<_points.size(); i++)
    {
      _points[i](0) =
        (_points[i](0) - old_range.first) *
        (new_range.second - new_range.first) /
        (old_range.second - old_range.first) +
        new_range.first;
    }
  // Compute the scale factor and scale the weights
  const Real scfact = (new_range.second - new_range.first) /
    (old_range.second - old_range.first);
  for (unsigned int i=0; i<_points.size(); i++)
    _weights[i] *= scfact;
}
virtual bool libMesh::QBase::shapes_need_reinit () [inline], [virtual], [inherited]
Returns true if the shape functions need to be recalculated.
This can happen if the number of points or their positions change.
By default this will return false.
Definition at line 198 of file quadrature.h.
{ return false; }
QuadratureType libMesh::QGrundmann_Moller::type () const [inline], [virtual]
Returns:
QGRUNDMANN_MOLLER
Implements libMesh::QBase.
Definition at line 118 of file quadrature_gm.h.
References libMesh::QGRUNDMANN_MOLLER.
{ return QGRUNDMANN_MOLLER; }
Real libMesh::QBase::w (const unsigned inti) const [inline], [inherited]
Returns:
the $ i^{th} $ quadrature weight.
Definition at line 156 of file quadrature.h.
References libMesh::QBase::_weights.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), and libMesh::QConical::conical_product_tri().
  { libmesh_assert_less (i, _weights.size()); return _weights[i]; }
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts [static], [protected], [inherited]
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true [static], [protected], [inherited]
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex [static], [protected], [inherited]
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects [static], [protected], [inherited]
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
libMesh::err<< 'ERROR: Seems as if this quadrature rule' << std::endl << ' is not implemented for 2D.' << std::endl; libmesh_error(); }#endif virtual void init_3D (const ElemType, unsigned int =0)#ifndef DEBUG {}#else { libMesh::err << 'ERROR: Seems as if this quadrature rule' << std::endl << ' is not implemented for 3D.' << std::endl; libmesh_error(); }#endif void tensor_product_quad (const QBase& q1D); void tensor_product_hex (const QBase& q1D); void tensor_product_prism (const QBase& q1D, const QBase& q2D); const unsigned int _dim; const Order _order; ElemType _type; unsigned int _p_level; std::vector<Point> libMesh::QBase::_points [protected], [inherited]
Definition at line 332 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), libMesh::QBase::get_points(), gm_rule(), libMesh::QBase::init_0D(), libMesh::QTrap::init_1D(), libMesh::QClough::init_1D(), libMesh::QGauss::init_1D(), libMesh::QSimpson::init_1D(), libMesh::QGrid::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QTrap::init_2D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGrid::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGrid::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), libMesh::QBase::n_points(), libMesh::QBase::print_info(), libMesh::QBase::qp(), libMesh::QBase::scale(), libMesh::QMonomial::stroud_rule(), and libMesh::QMonomial::wissmann_rule().
std::vector<Real> libMesh::QBase::_weights [protected], [inherited]
The value of the quadrature weights.
Definition at line 337 of file quadrature.h.
Referenced by libMesh::QConical::conical_product_pyramid(), libMesh::QConical::conical_product_tet(), libMesh::QConical::conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), libMesh::QBase::get_weights(), gm_rule(), libMesh::QBase::init_0D(), libMesh::QTrap::init_1D(), libMesh::QClough::init_1D(), libMesh::QGauss::init_1D(), libMesh::QSimpson::init_1D(), libMesh::QGrid::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QTrap::init_2D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGrid::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGrid::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), libMesh::QBase::print_info(), libMesh::QBase::scale(), libMesh::QMonomial::stroud_rule(), libMesh::QBase::w(), and libMesh::QMonomial::wissmann_rule().
bool libMesh::QBase::allow_rules_with_negative_weights [inherited]
Flag (default true) controlling the use of quadrature rules with negative weights. Set this to false to ONLY use (potentially) safer but more expensive rules with all positive weights.
Negative weights typically appear in Gaussian quadrature rules over three-dimensional elements. Rules with negative weights can be unsuitable for some problems. For example, it is possible for a rule with negative weights to obtain a negative result when integrating a positive function.
A particular example: if rules with negative weights are not allowed, a request for TET,THIRD (5 points) will return the TET,FIFTH (14 points) rule instead, nearly tripling the computational effort required!
Definition at line 215 of file quadrature.h.
Referenced by libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and init_3D().
Author
Generated automatically by Doxygen for libMesh from the source code.