.TH "libMesh::mapvector< Val, index_t >::const_veclike_iterator" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::mapvector< Val, index_t >::const_veclike_iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mapvector\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconst_veclike_iterator\fP (const typename maptype::const_iterator &i)"
.br
.ti -1c
.RI "\fBconst_veclike_iterator\fP (const \fBconst_veclike_iterator\fP &i)"
.br
.ti -1c
.RI "\fBconst_veclike_iterator\fP (const \fBveclike_iterator\fP &i)"
.br
.ti -1c
.RI "const Val & \fBoperator*\fP () const "
.br
.ti -1c
.RI "\fBconst_veclike_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBconst_veclike_iterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBconst_veclike_iterator\fP &other) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBconst_veclike_iterator\fP &other) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "maptype::const_iterator \fBit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Val, typename index_t = unsigned int>class libMesh::mapvector< Val, index_t >::const_veclike_iterator"

.PP
Definition at line 83 of file mapvector\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Val, typename index_t = unsigned int> \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::const_veclike_iterator (const typename maptype::const_iterator &i)\fC [inline]\fP"

.PP
Definition at line 86 of file mapvector\&.h\&.
.PP
.nf
87       : it(i) {}
.fi
.SS "template<typename Val, typename index_t = unsigned int> \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::const_veclike_iterator (const \fBconst_veclike_iterator\fP &i)\fC [inline]\fP"

.PP
Definition at line 89 of file mapvector\&.h\&.
.PP
.nf
90       : it(i\&.it) {}
.fi
.SS "template<typename Val, typename index_t = unsigned int> \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::const_veclike_iterator (const \fBveclike_iterator\fP &i)\fC [inline]\fP"

.PP
Definition at line 92 of file mapvector\&.h\&.
.PP
.nf
93       : it(i\&.it) {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "template<typename Val, typename index_t = unsigned int> bool \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::operator!= (const \fBconst_veclike_iterator\fP &other) const\fC [inline]\fP"

.PP
Definition at line 109 of file mapvector\&.h\&.
.PP
References libMesh::mapvector< Val, index_t >::const_veclike_iterator::it\&.
.PP
.nf
109                                                                {
110       return it != other\&.it;
111     }
.fi
.SS "template<typename Val, typename index_t = unsigned int> const Val& \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::operator* () const\fC [inline]\fP"

.PP
Definition at line 95 of file mapvector\&.h\&.
.PP
References libMesh::mapvector< Val, index_t >::const_veclike_iterator::it\&.
.PP
.nf
95 { return it->second; }
.fi
.SS "template<typename Val, typename index_t = unsigned int> \fBconst_veclike_iterator\fP& \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::operator++ ()\fC [inline]\fP"

.PP
Definition at line 97 of file mapvector\&.h\&.
.PP
References libMesh::mapvector< Val, index_t >::const_veclike_iterator::it\&.
.PP
.nf
97 { ++it; return *this; }
.fi
.SS "template<typename Val, typename index_t = unsigned int> \fBconst_veclike_iterator\fP \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::operator++ (int)\fC [inline]\fP"

.PP
Definition at line 99 of file mapvector\&.h\&.
.PP
.nf
99                                            {
100       veclike_iterator i = *this;
101       ++(*this);
102       return i;
103     }
.fi
.SS "template<typename Val, typename index_t = unsigned int> bool \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::operator== (const \fBconst_veclike_iterator\fP &other) const\fC [inline]\fP"

.PP
Definition at line 105 of file mapvector\&.h\&.
.PP
References libMesh::mapvector< Val, index_t >::const_veclike_iterator::it\&.
.PP
.nf
105                                                                {
106       return it == other\&.it;
107     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<typename Val, typename index_t = unsigned int> maptype::const_iterator \fBlibMesh::mapvector\fP< Val, index_t >::const_veclike_iterator::it"

.PP
Definition at line 113 of file mapvector\&.h\&.
.PP
Referenced by libMesh::mapvector< Val, index_t >::const_veclike_iterator::operator!=(), libMesh::mapvector< Val, index_t >::const_veclike_iterator::operator*(), libMesh::mapvector< Val, index_t >::const_veclike_iterator::operator++(), and libMesh::mapvector< Val, index_t >::const_veclike_iterator::operator==()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
