.TH "libMesh::SensitivityData::ConstRow" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::SensitivityData::ConstRow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sensitivity_data\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstRow\fP (const \fBSensitivityData\fP &sd, unsigned int qoi)"
.br
.ti -1c
.RI "const \fBNumber\fP & \fBoperator[]\fP (unsigned int parameter)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const \fBSensitivityData\fP & \fB_sd\fP"
.br
.ti -1c
.RI "unsigned int \fB_qoi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file sensitivity_data\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "libMesh::SensitivityData::ConstRow::ConstRow (const \fBSensitivityData\fP &sd, unsigned intqoi)\fC [inline]\fP"

.PP
Definition at line 59 of file sensitivity_data\&.h\&.
.PP
.nf
59 : _sd(sd), _qoi(qoi) {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "const \fBNumber\fP& libMesh::SensitivityData::ConstRow::operator[] (unsigned intparameter)\fC [inline]\fP"

.PP
Definition at line 61 of file sensitivity_data\&.h\&.
.PP
References _qoi, _sd, and libMesh::SensitivityData::derivative()\&.
.PP
.nf
61 { return _sd\&.derivative(_qoi, parameter); }
.fi
.SH "Member Data Documentation"
.PP 
.SS "unsigned int libMesh::SensitivityData::ConstRow::_qoi\fC [private]\fP"

.PP
Definition at line 64 of file sensitivity_data\&.h\&.
.PP
Referenced by operator[]()\&.
.SS "const \fBSensitivityData\fP& libMesh::SensitivityData::ConstRow::_sd\fC [private]\fP"

.PP
Definition at line 63 of file sensitivity_data\&.h\&.
.PP
Referenced by operator[]()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
