.TH "libMesh::AutoPtrRef< Tp1 >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::AutoPtrRef< Tp1 > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <auto_ptr\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoPtrRef\fP (Tp1 *p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Tp1 * \fB_ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Tp1>struct libMesh::AutoPtrRef< Tp1 >"
A wrapper class to provide \fBAutoPtr\fP with reference semantics\&. For example, an \fBAutoPtr\fP can be assigned (or constructed from) the result of a function which returns an \fBAutoPtr\fP by value\&.
.PP
All the \fBAutoPtrRef\fP stuff should happen behind the scenes\&. 
.PP
Definition at line 58 of file auto_ptr\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Tp1> \fBlibMesh::AutoPtrRef\fP< Tp1 >::\fBAutoPtrRef\fP (Tp1 *p)\fC [inline]\fP, \fC [explicit]\fP"
Constructor\&. 
.PP
Definition at line 69 of file auto_ptr\&.h\&.
.PP
.nf
70     : _ptr(p) {}
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<typename Tp1> Tp1* \fBlibMesh::AutoPtrRef\fP< Tp1 >::_ptr"
The actual pointer\&. 
.PP
Definition at line 63 of file auto_ptr\&.h\&.
.PP
Referenced by libMesh::AutoPtr< libMesh::FETransformationBase< OutputType > >::operator=()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
