.TH "libMesh::DTKEvaluator" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::DTKEvaluator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dtk_evaluator\&.h>\fP
.PP
Inherits FieldEvaluator< int, DataTransferKit::FieldContainer< double > >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef 
.br
DataTransferKit::MeshContainer
.br
< int > \fBMeshContainerType\fP"
.br
.ti -1c
.RI "typedef 
.br
DataTransferKit::FieldContainer
.br
< \fBNumber\fP > \fBFieldContainerType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTKEvaluator\fP (\fBSystem\fP &in_sys, std::string var_name)"
.br
.ti -1c
.RI "\fBFieldContainerType\fP \fBevaluate\fP (const Teuchos::ArrayRCP< int > &elements, const Teuchos::ArrayRCP< double > &coords)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSystem\fP & \fBsys\fP"
.br
.ti -1c
.RI "\fBNumericVector\fP< \fBNumber\fP > & \fBcurrent_local_solution\fP"
.br
.ti -1c
.RI "\fBEquationSystems\fP & \fBes\fP"
.br
.ti -1c
.RI "\fBMeshBase\fP & \fBmesh\fP"
.br
.ti -1c
.RI "unsigned int \fBdim\fP"
.br
.ti -1c
.RI "\fBDofMap\fP & \fBdof_map\fP"
.br
.ti -1c
.RI "unsigned int \fBvar_num\fP"
.br
.ti -1c
.RI "const \fBFEType\fP & \fBfe_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file dtk_evaluator\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef DataTransferKit::FieldContainer<\fBNumber\fP> \fBlibMesh::DTKEvaluator::FieldContainerType\fP"

.PP
Definition at line 47 of file dtk_evaluator\&.h\&.
.SS "typedef DataTransferKit::MeshContainer<int> \fBlibMesh::DTKEvaluator::MeshContainerType\fP"

.PP
Definition at line 46 of file dtk_evaluator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "libMesh::DTKEvaluator::DTKEvaluator (\fBSystem\fP &in_sys, std::stringvar_name)"

.SH "Member Function Documentation"
.PP 
.SS "\fBFieldContainerType\fP libMesh::DTKEvaluator::evaluate (const Teuchos::ArrayRCP< int > &elements, const Teuchos::ArrayRCP< double > &coords)"

.SH "Member Data Documentation"
.PP 
.SS "\fBNumericVector\fP<\fBNumber\fP>& libMesh::DTKEvaluator::current_local_solution\fC [protected]\fP"

.PP
Definition at line 56 of file dtk_evaluator\&.h\&.
.SS "unsigned int libMesh::DTKEvaluator::dim\fC [protected]\fP"

.PP
Definition at line 59 of file dtk_evaluator\&.h\&.
.SS "\fBDofMap\fP& libMesh::DTKEvaluator::dof_map\fC [protected]\fP"

.PP
Definition at line 60 of file dtk_evaluator\&.h\&.
.SS "\fBEquationSystems\fP& libMesh::DTKEvaluator::es\fC [protected]\fP"

.PP
Definition at line 57 of file dtk_evaluator\&.h\&.
.SS "const \fBFEType\fP& libMesh::DTKEvaluator::fe_type\fC [protected]\fP"

.PP
Definition at line 62 of file dtk_evaluator\&.h\&.
.SS "\fBMeshBase\fP& libMesh::DTKEvaluator::mesh\fC [protected]\fP"

.PP
Definition at line 58 of file dtk_evaluator\&.h\&.
.SS "\fBSystem\fP& libMesh::DTKEvaluator::sys\fC [protected]\fP"

.PP
Definition at line 55 of file dtk_evaluator\&.h\&.
.SS "unsigned int libMesh::DTKEvaluator::var_num\fC [protected]\fP"

.PP
Definition at line 61 of file dtk_evaluator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
