libMesh::MacroFunctions
NAME
libMesh::MacroFunctions -
SYNOPSIS
Functions
void here (const char *file, int line, const char *date, const char *time)
void stop (const char *file, int line, const char *date, const char *time)
void report_error (const char *file, int line, const char *date, const char *time)
Function Documentation
void libMesh::MacroFunctions::here (const char *file, intline, const char *date, const char *time)
Definition at line 35 of file libmesh_common.C.
References libMesh::err, and libMesh::global_processor_id().
Referenced by report_error(), and stop().
{
  libMesh::err << "[" << static_cast<std::size_t>(libMesh::global_processor_id()) << "] "
               << file
               << ", line " << line
               << ", compiled " << date
               << " at " << time
               << std::endl;
}
void libMesh::MacroFunctions::report_error (const char *file, intline, const char *date, const char *time)
Definition at line 63 of file libmesh_common.C.
References libMesh::global_n_processors(), here(), libMesh::print_trace(), and libMesh::write_traceout().
{
  if (libMesh::global_n_processors() == 1)
    libMesh::print_trace();
  else
    libMesh::write_traceout();
  libMesh::MacroFunctions::here(file, line, date, time);
}
void libMesh::MacroFunctions::stop (const char *file, intline, const char *date, const char *time)
Definition at line 47 of file libmesh_common.C.
References libMesh::global_n_processors(), here(), and libMesh::out.
Referenced by libMesh::PetscMatrix< T >::row_start(), and libMesh::PetscMatrix< T >::row_stop().
{
  if (libMesh::global_n_processors() == 1)
    {
      libMesh::MacroFunctions::here(file, line, date, time);
#ifdef LIBMESH_HAVE_CSIGNAL
      libMesh::out << "Stopping process " << getpid() << "..." << std::endl;
      std::raise(SIGSTOP);
      libMesh::out << "Continuing process " << getpid() << "..." << std::endl;
#else
      libMesh::out << "WARNING: libmesh_stop() does not work without the <csignal> header file!" << std::endl;
#endif
    }
}
Author
Generated automatically by Doxygen for libMesh from the source code.