.TH "libMesh::EnsightIO::Vectors" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::EnsightIO::Vectors \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdescription\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBcomponents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file ensight_io\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> libMesh::EnsightIO::Vectors::components"

.PP
Definition at line 93 of file ensight_io\&.h\&.
.SS "std::string libMesh::EnsightIO::Vectors::description"

.PP
Definition at line 92 of file ensight_io\&.h\&.
.PP
Referenced by libMesh::EnsightIO::add_vector(), and libMesh::EnsightIO::write_case()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
