.TH "libmesh.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmesh.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibMesh::LibMeshInit\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBlibMesh::initialized\fP ()"
.br
.ti -1c
.RI "bool \fBlibMesh::closed\fP ()"
.br
.ti -1c
.RI "void \fBlibMesh::enableFPE\fP (bool on)"
.br
.ti -1c
.RI "bool \fBlibMesh::on_command_line\fP (const std::string &arg)"
.br
.ti -1c
.RI "template<typename T > T \fBlibMesh::command_line_value\fP (const std::string &name, T value)"
.br
.ti -1c
.RI "template<typename T > T \fBlibMesh::command_line_value\fP (const std::vector< std::string > &name, T value)"
.br
.ti -1c
.RI "template<typename T > T \fBlibMesh::command_line_next\fP (const std::string &name, T value)"
.br
.ti -1c
.RI "template<typename T > void \fBlibMesh::command_line_vector\fP (const std::string &name, std::vector< T > &vec)"
.br
.ti -1c
.RI "SolverPackage \fBlibMesh::default_solver_package\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const Number \fBlibMesh::imaginary\fP"
.br
.ti -1c
.RI "const Real \fBlibMesh::pi\fP"
.br
.ti -1c
.RI "const Number \fBlibMesh::zero\fP = 0\&."
.br
.ti -1c
.RI "const unsigned int \fBlibMesh::invalid_uint\fP = static_cast<unsigned int>(-1)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
