.TH "libMesh::Trees" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Trees \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBTree\fP< 2 > \fBBinaryTree\fP"
.br
.ti -1c
.RI "typedef \fBTree\fP< 4 > \fBQuadTree\fP"
.br
.ti -1c
.RI "typedef \fBTree\fP< 8 > \fBOctTree\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBuildType\fP { \fBNODES\fP =0, \fBELEMENTS\fP, \fBINVALID_BUILD_TYPE\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
For convenience we define QuadTrees and OctTrees explicitly\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBTree\fP<2> \fBlibMesh::Trees::BinaryTree\fP"
A BinaryTree is a tree appropriate for 1D meshes\&. 
.PP
Definition at line 119 of file tree\&.h\&.
.SS "typedef \fBTree\fP<8> \fBlibMesh::Trees::OctTree\fP"
An OctTree is a tree appropriate for 3D meshes\&. 
.PP
Definition at line 131 of file tree\&.h\&.
.SS "typedef \fBTree\fP<4> \fBlibMesh::Trees::QuadTree\fP"
A QuadTree is a tree appropriate for 2D meshes\&. 
.PP
Definition at line 125 of file tree\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBlibMesh::Trees::BuildType\fP"
\fCenum\fP defining how to build the tree\&. \fCNODES\fP will populate the tree with nodes and then replace the nodes with element connectivity, \fCELEMENTS\fP will populate the tree with the elements directly\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINODES \fP\fP
.TP
\fB\fIELEMENTS \fP\fP
.TP
\fB\fIINVALID_BUILD_TYPE \fP\fP
.PP
Definition at line 47 of file tree_base\&.h\&.
.PP
.nf
47                {NODES=0,
48                 ELEMENTS,
49                 INVALID_BUILD_TYPE };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
