.TH "libMesh::PoolAllocator< T >::rebind< U >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::PoolAllocator< T >::rebind< U > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pool_allocator\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBPoolAllocator\fP< U > \fBother\fP"
.br
.ti -1c
.RI "typedef \fBPoolAllocator\fP< U > \fBother\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>template<typename U>struct libMesh::PoolAllocator< T >::rebind< U >"
Methods required for copy construction of containers using this allocator\&. 
.PP
Definition at line 55 of file pool_allocator\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T > template<typename U > typedef \fBPoolAllocator\fP<U> \fBlibMesh::PoolAllocator\fP< T >::\fBrebind\fP< U >::\fBother\fP"

.PP
Definition at line 56 of file pool_allocator\&.h\&.
.SS "template<typename T > template<typename U > typedef \fBPoolAllocator\fP<U> \fBlibMesh::PoolAllocator\fP< T >::\fBrebind\fP< U >::\fBother\fP"

.PP
Definition at line 155 of file pool_allocator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
