libMesh::Threads::recursive_mutex::scoped_lock
NAME
libMesh::Threads::recursive_mutex::scoped_lock -
SYNOPSIS
#include <threads.h>
Public Member Functions
scoped_lock ()
scoped_lock (recursive_mutex &in_rmutex)
~scoped_lock ()
void acquire (recursive_mutex &in_rmutex)
void release ()
scoped_lock ()
scoped_lock (recursive_mutex &)
void acquire (recursive_mutex &)
void release ()
Private Attributes
recursive_mutex * rmutex
Detailed Description
Definition at line 412 of file threads.h.
Constructor & Destructor Documentation
libMesh::Threads::recursive_mutex::scoped_lock::scoped_lock () [inline]
Definition at line 415 of file threads.h.
: rmutex(NULL) {}
libMesh::Threads::recursive_mutex::scoped_lock::scoped_lock (recursive_mutex &in_rmutex) [inline], [explicit]
Definition at line 416 of file threads.h.
References libMesh::Threads::recursive_mutex::lock(), and rmutex.
: rmutex(&in_rmutex) { rmutex->lock(); }
libMesh::Threads::recursive_mutex::scoped_lock::~scoped_lock () [inline]
Definition at line 418 of file threads.h.
References release().
{ release(); }
libMesh::Threads::recursive_mutex::scoped_lock::scoped_lock () [inline]
Definition at line 876 of file threads.h.
{}
libMesh::Threads::recursive_mutex::scoped_lock::scoped_lock (recursive_mutex &) [inline], [explicit]
Definition at line 877 of file threads.h.
{}
Member Function Documentation
void libMesh::Threads::recursive_mutex::scoped_lock::acquire (recursive_mutex &in_rmutex) [inline]
Definition at line 420 of file threads.h.
References libMesh::Threads::recursive_mutex::lock(), and rmutex.
{ rmutex = &in_rmutex; rmutex->lock(); }
void libMesh::Threads::recursive_mutex::scoped_lock::acquire (recursive_mutex &) [inline]
Definition at line 878 of file threads.h.
{}
void libMesh::Threads::recursive_mutex::scoped_lock::release () [inline]
Definition at line 421 of file threads.h.
References rmutex, and libMesh::Threads::recursive_mutex::unlock().
Referenced by ~scoped_lock().
{ if(rmutex) rmutex->unlock(); rmutex = NULL; }
void libMesh::Threads::recursive_mutex::scoped_lock::release () [inline]
Definition at line 879 of file threads.h.
{}
Member Data Documentation
recursive_mutex* libMesh::Threads::recursive_mutex::scoped_lock::rmutex [private]
Definition at line 424 of file threads.h.
Referenced by acquire(), release(), and scoped_lock().
Author
Generated automatically by Doxygen for libMesh from the source code.