.TH "libMesh::ProjectVector" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::ProjectVector \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProjectVector\fP (const \fBSystem\fP &system_in, const \fBNumericVector\fP< \fBNumber\fP > &old_v_in, \fBNumericVector\fP< \fBNumber\fP > &new_v_in)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBConstElemRange\fP &range) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const \fBSystem\fP & \fBsystem\fP"
.br
.ti -1c
.RI "const \fBNumericVector\fP< \fBNumber\fP > & \fBold_vector\fP"
.br
.ti -1c
.RI "\fBNumericVector\fP< \fBNumber\fP > & \fBnew_vector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class implements projecting a vector from an old mesh to the newly refined mesh\&. This may be executed in parallel on multiple threads\&. 
.PP
Definition at line 52 of file system_projection\&.C\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "libMesh::ProjectVector::ProjectVector (const \fBSystem\fP &system_in, const \fBNumericVector\fP< \fBNumber\fP > &old_v_in, \fBNumericVector\fP< \fBNumber\fP > &new_v_in)\fC [inline]\fP"

.PP
Definition at line 60 of file system_projection\&.C\&.
.PP
.nf
62                                                   :
63     system(system_in),
64     old_vector(old_v_in),
65     new_vector(new_v_in)
66   {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "void libMesh::ProjectVector::operator() (const \fBConstElemRange\fP &range) const"

.PP
Definition at line 738 of file system_projection\&.C\&.
.PP
.nf
739 {
740   libmesh_error();
741 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBNumericVector\fP<\fBNumber\fP>& libMesh::ProjectVector::new_vector\fC [private]\fP"

.PP
Definition at line 57 of file system_projection\&.C\&.
.SS "const \fBNumericVector\fP<\fBNumber\fP>& libMesh::ProjectVector::old_vector\fC [private]\fP"

.PP
Definition at line 56 of file system_projection\&.C\&.
.SS "const \fBSystem\fP& libMesh::ProjectVector::system\fC [private]\fP"

.PP
Definition at line 55 of file system_projection\&.C\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
