.TH "libMesh::Parallel::PostWaitDeleteBuffer< Container >" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Parallel::PostWaitDeleteBuffer< Container > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parallel\&.h>\fP
.PP
Inherits \fBlibMesh::Parallel::PostWaitWork\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPostWaitDeleteBuffer\fP (Container *buffer)"
.br
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Container * \fB_buf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Container>struct libMesh::Parallel::PostWaitDeleteBuffer< Container >"

.PP
Definition at line 1193 of file parallel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Container > \fBlibMesh::Parallel::PostWaitDeleteBuffer\fP< Container >::\fBPostWaitDeleteBuffer\fP (Container *buffer)\fC [inline]\fP"

.PP
Definition at line 1194 of file parallel\&.h\&.
.PP
.nf
1194 : _buf(buffer) {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "template<typename Container > virtual void \fBlibMesh::Parallel::PostWaitDeleteBuffer\fP< Container >::run ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBlibMesh::Parallel::PostWaitWork\fP\&.
.PP
Definition at line 1196 of file parallel\&.h\&.
.PP
References libMesh::Parallel::PostWaitDeleteBuffer< Container >::_buf\&.
.PP
.nf
1196 { delete _buf; }
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<typename Container > Container* \fBlibMesh::Parallel::PostWaitDeleteBuffer\fP< Container >::_buf\fC [private]\fP"

.PP
Definition at line 1199 of file parallel\&.h\&.
.PP
Referenced by libMesh::Parallel::PostWaitDeleteBuffer< Container >::run()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
