.TH "libMesh::RBParametrizedFunction" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::RBParametrizedFunction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rb_parametrized_function\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~RBParametrizedFunction\fP ()"
.br
.ti -1c
.RI "virtual \fBNumber\fP \fBevaluate\fP (const \fBRBParameters\fP &, const \fBPoint\fP &, const \fBElem\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple functor class that provides a RBParameter-dependent function\&. 
.PP
Definition at line 38 of file rb_parametrized_function\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual libMesh::RBParametrizedFunction::~RBParametrizedFunction ()\fC [inline]\fP, \fC [virtual]\fP"
Virtual \fBevaluate()\fP gives us a vtable, so there's no cost in adding a virtual destructor for safety's sake\&. 
.PP
Definition at line 46 of file rb_parametrized_function\&.h\&.
.PP
.nf
46 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBNumber\fP libMesh::RBParametrizedFunction::evaluate (const \fBRBParameters\fP &, const \fBPoint\fP &, const \fBElem\fP &)\fC [inline]\fP, \fC [virtual]\fP"
Evaluate this parametrized function for the parameter value \fCmu\fP at the point \fCp\fP\&. 
.PP
Definition at line 52 of file rb_parametrized_function\&.h\&.
.PP
.nf
52 { return 0\&.; }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
