.TH "libMesh::NonlinearImplicitSystem::ComputeResidual" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::NonlinearImplicitSystem::ComputeResidual \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nonlinear_implicit_system\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ComputeResidual\fP ()"
.br
.ti -1c
.RI "virtual void \fBresidual\fP (const \fBNumericVector\fP< \fBNumber\fP > &X, \fBNumericVector\fP< \fBNumber\fP > &R, \fBsys_type\fP &S)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class to be used to calculate the residual of a nonlinear system\&. 
.PP
Definition at line 79 of file nonlinear_implicit_system\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual libMesh::NonlinearImplicitSystem::ComputeResidual::~ComputeResidual ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 82 of file nonlinear_implicit_system\&.h\&.
.PP
.nf
82 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void libMesh::NonlinearImplicitSystem::ComputeResidual::residual (const \fBNumericVector\fP< \fBNumber\fP > &X, \fBNumericVector\fP< \fBNumber\fP > &R, \fBsys_type\fP &S)\fC [pure virtual]\fP"
Residual function\&. This function will be called to compute the residual and must be implemented by the user in a derived class\&. 
.PP
Referenced by libMesh::__libmesh_petsc_snes_residual(), and libMesh::Problem_Interface::computeF()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
