libMesh::Threads::spin_mutex::scoped_lock
NAME
libMesh::Threads::spin_mutex::scoped_lock -
SYNOPSIS
#include <threads.h>
Public Member Functions
scoped_lock ()
scoped_lock (spin_mutex &in_smutex)
~scoped_lock ()
void acquire (spin_mutex &in_smutex)
void release ()
scoped_lock ()
scoped_lock (spin_mutex &in_smutex)
~scoped_lock ()
void acquire (spin_mutex &in_smutex)
void release ()
scoped_lock ()
scoped_lock (spin_mutex &)
void acquire (spin_mutex &)
void release ()
Private Attributes
spin_mutex * smutex
Detailed Description
Definition at line 343 of file threads.h.
Constructor & Destructor Documentation
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock () [inline]
Definition at line 346 of file threads.h.
: smutex(NULL) {}
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock (spin_mutex &in_smutex) [inline], [explicit]
Definition at line 347 of file threads.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
: smutex(&in_smutex) { smutex->lock(); }
libMesh::Threads::spin_mutex::scoped_lock::~scoped_lock () [inline]
Definition at line 349 of file threads.h.
References release().
{ release(); }
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock () [inline]
Definition at line 375 of file threads.h.
: smutex(NULL) {}
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock (spin_mutex &in_smutex) [inline], [explicit]
Definition at line 376 of file threads.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
: smutex(&in_smutex) { smutex->lock(); }
libMesh::Threads::spin_mutex::scoped_lock::~scoped_lock () [inline]
Definition at line 378 of file threads.h.
References release().
{ release(); }
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock () [inline]
Definition at line 856 of file threads.h.
{}
libMesh::Threads::spin_mutex::scoped_lock::scoped_lock (spin_mutex &) [inline], [explicit]
Definition at line 857 of file threads.h.
{}
Member Function Documentation
void libMesh::Threads::spin_mutex::scoped_lock::acquire (spin_mutex &in_smutex) [inline]
Definition at line 351 of file threads.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
{ smutex = &in_smutex; smutex->lock(); }
void libMesh::Threads::spin_mutex::scoped_lock::acquire (spin_mutex &in_smutex) [inline]
Definition at line 380 of file threads.h.
References libMesh::Threads::spin_mutex::lock(), and smutex.
{ smutex = &in_smutex; smutex->lock(); }
void libMesh::Threads::spin_mutex::scoped_lock::acquire (spin_mutex &) [inline]
Definition at line 858 of file threads.h.
{}
void libMesh::Threads::spin_mutex::scoped_lock::release () [inline]
Definition at line 352 of file threads.h.
References smutex, and libMesh::Threads::spin_mutex::unlock().
Referenced by ~scoped_lock().
{ if(smutex) smutex->unlock(); smutex = NULL; }
void libMesh::Threads::spin_mutex::scoped_lock::release () [inline]
Definition at line 381 of file threads.h.
References smutex, and libMesh::Threads::spin_mutex::unlock().
{ if(smutex) smutex->unlock(); smutex = NULL; }
void libMesh::Threads::spin_mutex::scoped_lock::release () [inline]
Definition at line 859 of file threads.h.
{}
Member Data Documentation
spin_mutex * libMesh::Threads::spin_mutex::scoped_lock::smutex [private]
Definition at line 355 of file threads.h.
Referenced by acquire(), release(), and scoped_lock().
Author
Generated automatically by Doxygen for libMesh from the source code.