libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian
NAME
libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian -
SYNOPSIS
#include <nonlinear_implicit_system.h>
Public Member Functions
virtual ~ComputeResidualandJacobian ()
virtual void residual_and_jacobian (const NumericVector< Number > &X, NumericVector< Number > *R, SparseMatrix< Number > *J, sys_type &S)=0
Detailed Description
Abstract base class to be used to calculate the residual and Jacobian simultaneously of a nonlinear system.
Definition at line 157 of file nonlinear_implicit_system.h.
Constructor & Destructor Documentation
virtual libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian::~ComputeResidualandJacobian () [inline], [virtual]
Definition at line 160 of file nonlinear_implicit_system.h.
{}
Member Function Documentation
virtual void libMesh::NonlinearImplicitSystem::ComputeResidualandJacobian::residual_and_jacobian (const NumericVector< Number > &X, NumericVector< Number > *R, SparseMatrix< Number > *J, sys_type &S) [pure virtual]
Residual & Jacobian function, calculated simultaneously. This function will be called to compute the residual and jacobian simultaneously and must be implemented by the user in a derived class.
Referenced by libMesh::__libmesh_petsc_snes_residual(), libMesh::Problem_Interface::computeF(), libMesh::Problem_Interface::computeJacobian(), and libMesh::Problem_Interface::computePreconditioner().
Author
Generated automatically by Doxygen for libMesh from the source code.