libMesh::QConical
NAME
libMesh::QConical -
SYNOPSIS
#include <quadrature_conical.h>
Inherits libMesh::QBase.
Public Member Functions
QConical (const unsigned int _dim, const Order _order=INVALID_ORDER)
~QConical ()
QuadratureType type () const
ElemType get_elem_type () const
unsigned int get_p_level () const
unsigned int n_points () const
unsigned int get_dim () const
const std::vector< Point > & get_points () const
std::vector< Point > & get_points ()
const std::vector< Real > & get_weights () const
std::vector< Real > & get_weights ()
Point qp (const unsigned int i) const
Real w (const unsigned int i) const
void init (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
Order get_order () const
void print_info (std::ostream &os=libMesh::out) const
void scale (std::pair< Real, Real > old_range, std::pair< Real, Real > new_range)
virtual bool shapes_need_reinit ()
Static Public Member Functions
static AutoPtr< QBase > build (const std::string &name, const unsigned int _dim, const Order _order=INVALID_ORDER)
static AutoPtr< QBase > build (const QuadratureType _qt, const unsigned int _dim, const Order _order=INVALID_ORDER)
static void print_info (std::ostream &out=libMesh::out)
static std::string get_info ()
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
bool allow_rules_with_negative_weights
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts"
Protected Member Functions
virtual void init_0D (const ElemType type=INVALID_ELEM, unsigned int p_level=0)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
libMesh::err<< 'ERROR: Seems
as if this quadrature rule'
<< std::endl<< ' is not
implemented for 2D.'<< std::endl;libmesh_error();}#endif virtual void init_3D(const ElemType, unsigned int=0)#ifndef DEBUG{}#else{libMesh::err<< 'ERROR: Seems as if this quadrature rule'<< std::endl<< ' is not implemented for 3D.'<< std::endl;libmesh_error();}#endif void tensor_product_quad(const QBase &q1D);void tensor_product_hex(const QBase &q1D);void tensor_product_prism(const QBase &q1D, const QBase &q2D);const unsigned int _dim;const Order _order;ElemType _type;unsigned int _p_level;std::vector< Point > _points"
std::vector< Real > _weights
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects"
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Member Functions
void init_1D (const ElemType, unsigned int=0)
void init_2D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0)
void init_3D (const ElemType _type=INVALID_ELEM, unsigned int p_level=0)
void conical_product_tri (unsigned int p)
void conical_product_tet (unsigned int p)
void conical_product_pyramid (unsigned int p)
Detailed Description
This class implements the so-called conical product quadrature rules for Tri and Tet elements. These rules are generally non-optimal in the number of evaluation points, but have the nice property of having all positive weights and being well-defined to any order for which their underlying 1D Gauss and Jacobi quadrature rules are available.
The construction of these rules is given by e.g.
Stroud, A.H. 'Approximate Calculation of
Multiple Integrals.', 1972
Definition at line 43 of file quadrature_conical.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts [protected], [inherited]
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::QConical::QConical (const unsigned int_dim, const Order_order = INVALID_ORDER)
Constructor. Declares the order of the quadrature rule.
Definition at line 35 of file quadrature_conical.C.
                                  : QBase(d,o)
{
}
libMesh::QConical::~QConical ()
Destructor.
Definition at line 43 of file quadrature_conical.C.
{
}
Member Function Documentation
AutoPtr< QBase > libMesh::QBase::build (const std::string &name, const unsigned int_dim, const Order_order = INVALID_ORDER) [static], [inherited]
Builds a specific quadrature rule, identified through the name string. An AutoPtr<QBase> is returned to prevent a memory leak. This way the user need not remember to delete the object. Enables run-time decision of the quadrature rule. The input parameter name must be mappable through the Utility::string_to_enum<>() function.
Definition at line 40 of file quadrature_build.C.
Referenced by libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::attach_quadrature_rule().
{
  return QBase::build (Utility::string_to_enum<QuadratureType> (type),
                       _dim,
                       _order);
}
AutoPtr< QBase > libMesh::QBase::build (const QuadratureType_qt, const unsigned int_dim, const Order_order = INVALID_ORDER) [static], [inherited]
Builds a specific quadrature rule, identified through the QuadratureType. An AutoPtr<QBase> is returned to prevent a memory leak. This way the user need not remember to delete the object. Enables run-time decision of the quadrature rule.
Definition at line 51 of file quadrature_build.C.
References libMesh::err, libMesh::FIRST, libMesh::FORTYTHIRD, libMesh::out, libMesh::QCLOUGH, libMesh::QGAUSS, libMesh::QGRID, libMesh::QGRUNDMANN_MOLLER, libMesh::QJACOBI_1_0, libMesh::QJACOBI_2_0, libMesh::QMONOMIAL, libMesh::QSIMPSON, libMesh::QTRAP, libMesh::THIRD, and libMesh::TWENTYTHIRD.
{
  switch (_qt)
    {
    case QCLOUGH:
      {
#ifdef DEBUG
        if (_order > TWENTYTHIRD)
          {
            libMesh::out << "WARNING: Clough quadrature implemented" << std::endl
                         << " up to TWENTYTHIRD order." << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QClough(_dim, _order));
        return ap;
      }
    case QGAUSS:
      {
#ifdef DEBUG
        if (_order > FORTYTHIRD)
          {
            libMesh::out << "WARNING: Gauss quadrature implemented" << std::endl
                         << " up to FORTYTHIRD order." << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QGauss(_dim, _order));
        return ap;
      }
    case QJACOBI_1_0:
      {
#ifdef DEBUG
        if (_order > TWENTYTHIRD)
          {
            libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                         << " up to TWENTYTHIRD order." << std::endl;
          }
        if (_dim > 1)
          {
            libMesh::out << "WARNING: Jacobi(1,0) quadrature implemented" << std::endl
                         << " in 1D only." << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QJacobi(_dim, _order, 1, 0));
        return ap;
      }
    case QJACOBI_2_0:
      {
#ifdef DEBUG
        if (_order > TWENTYTHIRD)
          {
            libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                         << " up to TWENTYTHIRD order." << std::endl;
          }
        if (_dim > 1)
          {
            libMesh::out << "WARNING: Jacobi(2,0) quadrature implemented" << std::endl
                         << " in 1D only." << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QJacobi(_dim, _order, 2, 0));
        return ap;
      }
    case QSIMPSON:
      {
#ifdef DEBUG
        if (_order > THIRD)
          {
            libMesh::out << "WARNING: Simpson rule provides only" << std::endl
                         << " THIRD order!" << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QSimpson(_dim));
        return ap;
      }
    case QTRAP:
      {
#ifdef DEBUG
        if (_order > FIRST)
          {
            libMesh::out << "WARNING: Trapezoidal rule provides only" << std::endl
                         << " FIRST order!" << std::endl;
          }
#endif
        AutoPtr<QBase> ap(new QTrap(_dim));
        return ap;
      }
    case QGRID:
      {
        AutoPtr<QBase> ap(new QGrid(_dim, _order));
        return ap;
      }
    case QGRUNDMANN_MOLLER:
      {
        AutoPtr<QBase> ap(new QGrundmann_Moller(_dim, _order));
        return ap;
      }
    case QMONOMIAL:
      {
        AutoPtr<QBase> ap(new QMonomial(_dim, _order));
        return ap;
      }
    default:
      {
        libMesh::err << "ERROR: Bad qt=" << _qt << std::endl;
        libmesh_error();
      }
    }
  libmesh_error();
  AutoPtr<QBase> ap(NULL);
  return ap;
}
void libMesh::QConical::conical_product_pyramid (unsigned intp) [private]
Implementation of conical product rule for a Pyramid in 3D of order = _order+2*p.
Definition at line 180 of file quadrature_conical.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::get_dim(), libMesh::QBase::n_points(), libMesh::QBase::qp(), libMesh::Real, and libMesh::QBase::w().
Referenced by init_3D().
{
  // Be sure the underlying rule object was built with the same dimension as the
  // rule we are about to construct.
  libmesh_assert_equal_to (this->get_dim(), 3);
  QGauss gauss1D(1,static_cast<Order>(_order+2*p));
  QJacobi jac1D(1,static_cast<Order>(_order+2*p),2,0);
  // These rules should have the same number of points
  libmesh_assert_equal_to (gauss1D.n_points(), jac1D.n_points());
  // Save the number of points as a convenient variable
  const unsigned int np = gauss1D.n_points();
  // Resize the points and weights vectors
  _points.resize(np * np * np);
  _weights.resize(np * np * np);
  // Compute the conical product
  unsigned int q = 0;
  for (unsigned int i=0; i<np; ++i)
    for (unsigned int j=0; j<np; ++j)
      for (unsigned int k=0; k<np; ++k, ++q)
        {
          const Real xi=gauss1D.qp(i)(0);
          const Real yj=gauss1D.qp(j)(0);
          const Real zk=jac1D.qp(k)(0);
          _points[q](0) = (1.-zk) * xi;
          _points[q](1) = (1.-zk) * yj;
          _points[q](2) = zk;
          _weights[q] = gauss1D.w(i) * gauss1D.w(j) * jac1D.w(k);
        }
}
void libMesh::QConical::conical_product_tet (unsigned intp) [private]
Implementation of conical product rule for a Tet in 3D of order = _order+2*p.
Definition at line 103 of file quadrature_conical.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::get_dim(), libMesh::QBase::n_points(), libMesh::QBase::qp(), libMesh::QBase::scale(), and libMesh::QBase::w().
Referenced by init_3D().
{
  // Be sure the underlying rule object was built with the same dimension as the
  // rule we are about to construct.
  libmesh_assert_equal_to (this->get_dim(), 3);
  QGauss gauss1D(1,static_cast<Order>(_order+2*p));
  QJacobi jacA1D(1,static_cast<Order>(_order+2*p),1,0);
  QJacobi jacB1D(1,static_cast<Order>(_order+2*p),2,0);
  // The Gauss rule needs to be scaled to [0,1]
  std::pair<Real, Real> old_range(-1.0L, 1.0L);
  std::pair<Real, Real> new_range( 0.0L, 1.0L);
  gauss1D.scale(old_range,
                new_range);
  // Now construct the points and weights for the conical product rule.
  // All rules should have the same number of points
  libmesh_assert_equal_to (gauss1D.n_points(), jacA1D.n_points());
  libmesh_assert_equal_to (jacA1D.n_points(), jacB1D.n_points());
  // Save the number of points as a convenient variable
  const unsigned int np = gauss1D.n_points();
  // All rules should be between x=0 and x=1
  libmesh_assert_greater_equal (gauss1D.qp(0)(0), 0.0);
  libmesh_assert_less_equal (gauss1D.qp(np-1)(0), 1.0);
  libmesh_assert_greater_equal (jacA1D.qp(0)(0), 0.0);
  libmesh_assert_less_equal (jacA1D.qp(np-1)(0), 1.0);
  libmesh_assert_greater_equal (jacB1D.qp(0)(0), 0.0);
  libmesh_assert_less_equal (jacB1D.qp(np-1)(0), 1.0);
  // Resize the points and weights vectors
  _points.resize(np * np * np);
  _weights.resize(np * np * np);
  // Compute the conical product
  unsigned int gp = 0;
  for (unsigned int i=0; i<np; i++)
    for (unsigned int j=0; j<np; j++)
      for (unsigned int k=0; k<np; k++)
        {
          _points[gp](0) = jacB1D.qp(k)(0); //t[k];
          _points[gp](1) = jacA1D.qp(j)(0) * (1.-jacB1D.qp(k)(0)); //s[j]*(1.-t[k]);
          _points[gp](2) = gauss1D.qp(i)(0) * (1.-jacA1D.qp(j)(0)) * (1.-jacB1D.qp(k)(0)); //r[i]*(1.-s[j])*(1.-t[k]);
          _weights[gp] = gauss1D.w(i) * jacA1D.w(j) * jacB1D.w(k); //A[i]*B[j]*C[k];
          gp++;
        }
}
void libMesh::QConical::conical_product_tri (unsigned intp) [private]
Implementation of conical product rule for a Tri in 2D of order = _order+2*p.
Definition at line 52 of file quadrature_conical.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::QBase::get_dim(), libMesh::QBase::n_points(), libMesh::QBase::qp(), libMesh::QBase::scale(), and libMesh::QBase::w().
Referenced by init_2D().
{
  // Be sure the underlying rule object was built with the same dimension as the
  // rule we are about to construct.
  libmesh_assert_equal_to (this->get_dim(), 2);
  QGauss gauss1D(1,static_cast<Order>(_order+2*p));
  QJacobi jac1D(1,static_cast<Order>(_order+2*p),1,0);
  // The Gauss rule needs to be scaled to [0,1]
  std::pair<Real, Real> old_range(-1.0L, 1.0L);
  std::pair<Real, Real> new_range( 0.0L, 1.0L);
  gauss1D.scale(old_range,
                new_range);
  // Now construct the points and weights for the conical product rule.
  // Both rules should have the same number of points.
  libmesh_assert_equal_to (gauss1D.n_points(), jac1D.n_points());
  // Save the number of points as a convenient variable
  const unsigned int np = gauss1D.n_points();
  // Both rules should be between x=0 and x=1
  libmesh_assert_greater_equal (gauss1D.qp(0)(0), 0.0);
  libmesh_assert_less_equal (gauss1D.qp(np-1)(0), 1.0);
  libmesh_assert_greater_equal (jac1D.qp(0)(0), 0.0);
  libmesh_assert_less_equal (jac1D.qp(np-1)(0), 1.0);
  // Resize the points and weights vectors
  _points.resize(np * np);
  _weights.resize(np * np);
  // Compute the conical product
  unsigned int gp = 0;
  for (unsigned int i=0; i<np; i++)
    for (unsigned int j=0; j<np; j++)
      {
        _points[gp](0) = jac1D.qp(j)(0); //s[j];
        _points[gp](1) = gauss1D.qp(i)(0) * (1.-jac1D.qp(j)(0)); //r[i]*(1.-s[j]);
        _weights[gp] = gauss1D.w(i) * jac1D.w(j); //A[i]*B[j];
        gp++;
      }
}
void libMesh::ReferenceCounter::disable_print_counter_info () [static], [inherited]
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = false;
  return;
}
void libMesh::ReferenceCounter::enable_print_counter_info () [static], [inherited]
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = true;
  return;
}
unsigned int libMesh::QBase::get_dim () const [inline], [inherited]
Returns:
the dimension of the quadrature rule.
Definition at line 123 of file quadrature.h.
Referenced by libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::attach_quadrature_rule(), conical_product_pyramid(), conical_product_tet(), and conical_product_tri().
{ return _dim; }
ElemType libMesh::QBase::get_elem_type () const [inline], [inherited]
Returns:
the current element type we're set up for
Definition at line 104 of file quadrature.h.
  { return _type; }
std::string libMesh::ReferenceCounter::get_info () [static], [inherited]
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
{
#if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
  std::ostringstream oss;
  oss << '\n'
      << " ---------------------------------------------------------------------------- \n"
      << "| Reference count information |\n"
      << " ---------------------------------------------------------------------------- \n";
  for (Counts::iterator it = _counts.begin();
       it != _counts.end(); ++it)
    {
      const std::string name(it->first);
      const unsigned int creations = it->second.first;
      const unsigned int destructions = it->second.second;
      oss << "| " << name << " reference count information:\n"
          << "| Creations: " << creations << '\n'
          << "| Destructions: " << destructions << '\n';
    }
  oss << " ---------------------------------------------------------------------------- \n";
  return oss.str();
#else
  return "";
#endif
}
Order libMesh::QBase::get_order () const [inline], [inherited]
Returns:
the order of the quadrature rule.
Definition at line 169 of file quadrature.h.
Referenced by libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::attach_quadrature_rule().
{ return static_cast<Order>(_order + _p_level); }
unsigned int libMesh::QBase::get_p_level () const [inline], [inherited]
Returns:
the current p refinement level we're initialized with
Definition at line 110 of file quadrature.h.
  { return _p_level; }
const std::vector<Point>& libMesh::QBase::get_points () const [inline], [inherited]
Returns:
a std::vector containing the quadrature point locations on a reference object.
Definition at line 129 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by libMesh::QClough::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::FESubdivision::reinit().
{ return _points; }
std::vector<Point>& libMesh::QBase::get_points () [inline], [inherited]
Returns:
a std::vector containing the quadrature point locations on a reference object as a writeable reference.
Definition at line 135 of file quadrature.h.
References libMesh::QBase::_points.
{ return _points; }
const std::vector<Real>& libMesh::QBase::get_weights () const [inline], [inherited]
Returns:
a std::vector containing the quadrature weights.
Definition at line 140 of file quadrature.h.
References libMesh::QBase::_weights.
Referenced by libMesh::QClough::init_1D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::FESubdivision::reinit().
{ return _weights; }
std::vector<Real>& libMesh::QBase::get_weights () [inline], [inherited]
Returns:
a std::vector containing the quadrature weights.
Definition at line 145 of file quadrature.h.
References libMesh::QBase::_weights.
{ return _weights; }
void libMesh::ReferenceCounter::increment_constructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.first++;
}
void libMesh::ReferenceCounter::increment_destructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.second++;
}
void libMesh::QBase::init (const ElemTypetype = INVALID_ELEM, unsigned intp_level = 0) [inherited]
Initializes the data structures to contain a quadrature rule for an object of type type.
Definition at line 27 of file quadrature.C.
References libMesh::QBase::init_0D(), libMesh::QBase::init_1D(), and libMesh::QBase::init_2D().
Referenced by libMesh::QClough::init_1D(), libMesh::QTrap::init_2D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGrid::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGrid::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::QGauss(), libMesh::QJacobi::QJacobi(), libMesh::QSimpson::QSimpson(), libMesh::QTrap::QTrap(), and libMesh::FESubdivision::reinit().
{
  // check to see if we have already
  // done the work for this quadrature rule
  if (t == _type && p == _p_level)
    return;
  else
    {
      _type = t;
      _p_level = p;
    }
  switch(_dim)
    {
    case 0:
      this->init_0D(_type,_p_level);
      return;
    case 1:
      this->init_1D(_type,_p_level);
      return;
    case 2:
      this->init_2D(_type,_p_level);
      return;
    case 3:
      this->init_3D(_type,_p_level);
      return;
    default:
      libmesh_error();
    }
}
void libMesh::QBase::init_0D (const ElemTypetype = INVALID_ELEM, unsigned intp_level = 0) [protected], [virtual], [inherited]
Initializes the 0D quadrature rule by filling the points and weights vectors with the appropriate values. Generally this is just one point with weight 1.
Definition at line 71 of file quadrature.C.
References libMesh::QBase::_points, and libMesh::QBase::_weights.
Referenced by libMesh::QBase::init().
{
  _points.resize(1);
  _weights.resize(1);
  _points[0] = Point(0.);
  _weights[0] = 1.0;
}
void libMesh::QConical::init_1D (const ElemTypetype, unsignedp_level = 0) [inline], [private], [virtual]
Initializes the 1D quadrature rule by filling the points and weights vectors with the appropriate values. The order of the rule will be defined by the implementing class. It is assumed that derived quadrature rules will at least define the init_1D function, therefore it is pure virtual.
Implements libMesh::QBase.
Definition at line 65 of file quadrature_conical.h.
  {
    // See about making this non-pure virtual in the base class
    libmesh_error();
  }
void libMesh::QConical::init_2D (const ElemType_type = INVALID_ELEM, unsigned intp_level = 0) [private], [virtual]
The conical product rules are defined in 2D only for Tris.
Reimplemented from libMesh::QBase.
Definition at line 27 of file quadrature_conical_2D.C.
References conical_product_tri(), libMesh::err, libMesh::TRI3, and libMesh::TRI6.
{
  switch (type_in)
    {
    case TRI3:
    case TRI6:
      {
        this->conical_product_tri(p);
        return;
      } // end case TRI3, TRI6
      //---------------------------------------------
      // Unsupported element type
    default:
      {
        libMesh::err << "ERROR: Unsupported element type: " << type_in << std::endl;
        libmesh_error();
      }
    } // end switch (type_in)
  // We must have returned or errored-out by this point. If not,
  // throw an error now.
  libmesh_error();
  return;
}
void libMesh::QConical::init_3D (const ElemType_type = INVALID_ELEM, unsigned intp_level = 0) [private]
The conical product rules are defined in 3D only for Tets.
Definition at line 27 of file quadrature_conical_3D.C.
References conical_product_pyramid(), conical_product_tet(), libMesh::err, libMesh::PYRAMID13, libMesh::PYRAMID14, libMesh::PYRAMID5, libMesh::TET10, and libMesh::TET4.
{
  switch (type_in)
    {
    case TET4:
    case TET10:
      {
        this->conical_product_tet(p);
        return;
      } // end case TET4, TET10
    case PYRAMID5:
    case PYRAMID13:
    case PYRAMID14:
      {
        this->conical_product_pyramid(p);
        return;
      } // end case PYRAMID5
      //---------------------------------------------
      // Unsupported element type
    default:
      {
        libMesh::err << "ERROR: Unsupported element type: " << type_in << std::endl;
        libmesh_error();
      }
    } // end switch (type_in)
  // We must have returned or errored-out by this point. If not,
  // throw an error now.
  libmesh_error();
  return;
}
static unsigned int libMesh::ReferenceCounter::n_objects () [inline], [static], [inherited]
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
  { return _n_objects; }
unsigned int libMesh::QBase::n_points () const [inline], [inherited]
Returns:
the number of points associated with the quadrature rule.
Definition at line 116 of file quadrature.h.
References libMesh::QBase::_points, and libMesh::libmesh_assert().
Referenced by conical_product_pyramid(), conical_product_tet(), conical_product_tri(), libMesh::ProjectFEMSolution::operator()(), and libMesh::QBase::print_info().
  { libmesh_assert (!_points.empty());
    return libmesh_cast_int<unsigned int>(_points.size()); }
void libMesh::ReferenceCounter::print_info (std::ostream &out = libMesh::out) [static], [inherited]
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
{
  if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
}
void libMesh::QBase::print_info (std::ostream &os = libMesh::out) const [inline], [inherited]
Prints information relevant to the quadrature rule, by default to libMesh::out.
Definition at line 362 of file quadrature.h.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::libmesh_assert(), and libMesh::QBase::n_points().
Referenced by libMesh::operator<<().
{
  libmesh_assert(!_points.empty());
  libmesh_assert(!_weights.empty());
  os << "N_Q_Points=" << this->n_points() << std::endl << std::endl;
  for (unsigned int qpoint=0; qpoint<this->n_points(); qpoint++)
    {
      os << " Point " << qpoint << ":\n"
         << " "
         << _points[qpoint]
         << " Weight:\n "
         << " w=" << _weights[qpoint] << "\n" << std::endl;
    }
}
Point libMesh::QBase::qp (const unsigned inti) const [inline], [inherited]
Returns:
the $ i^{th} $ quadrature point on the reference object.
Definition at line 150 of file quadrature.h.
References libMesh::QBase::_points.
Referenced by conical_product_pyramid(), conical_product_tet(), and conical_product_tri().
  { libmesh_assert_less (i, _points.size()); return _points[i]; }
void libMesh::QBase::scale (std::pair< Real, Real >old_range, std::pair< Real, Real >new_range) [inherited]
Maps the points of a 1D interval quadrature rule (typically [-1,1]) to any other 1D interval (typically [0,1]) and scales the weights accordingly. The quadrature rule will be mapped from the entries of old_range to the entries of new_range.
Definition at line 82 of file quadrature.C.
References libMesh::QBase::_points, libMesh::QBase::_weights, libMesh::libmesh_assert_greater(), and libMesh::Real.
Referenced by conical_product_tet(), and conical_product_tri().
{
  // Make sure we are in 1D
  libmesh_assert_equal_to (_dim, 1);
  // Make sure that we have sane ranges
  libmesh_assert_greater (new_range.second, new_range.first);
  libmesh_assert_greater (old_range.second, old_range.first);
  // Make sure there are some points
  libmesh_assert_greater (_points.size(), 0);
  // We're mapping from old_range -> new_range
  for (unsigned int i=0; i<_points.size(); i++)
    {
      _points[i](0) =
        (_points[i](0) - old_range.first) *
        (new_range.second - new_range.first) /
        (old_range.second - old_range.first) +
        new_range.first;
    }
  // Compute the scale factor and scale the weights
  const Real scfact = (new_range.second - new_range.first) /
    (old_range.second - old_range.first);
  for (unsigned int i=0; i<_points.size(); i++)
    _weights[i] *= scfact;
}
virtual bool libMesh::QBase::shapes_need_reinit () [inline], [virtual], [inherited]
Returns true if the shape functions need to be recalculated.
This can happen if the number of points or their positions change.
By default this will return false.
Definition at line 198 of file quadrature.h.
{ return false; }
QuadratureType libMesh::QConical::type () const [inline], [virtual]
Returns:
the QuadratureType for this class
Implements libMesh::QBase.
Definition at line 61 of file quadrature_conical.h.
References libMesh::QCONICAL.
{ return QCONICAL; }
Real libMesh::QBase::w (const unsigned inti) const [inline], [inherited]
Returns:
the $ i^{th} $ quadrature weight.
Definition at line 156 of file quadrature.h.
References libMesh::QBase::_weights.
Referenced by conical_product_pyramid(), conical_product_tet(), and conical_product_tri().
  { libmesh_assert_less (i, _weights.size()); return _weights[i]; }
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts [static], [protected], [inherited]
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true [static], [protected], [inherited]
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex [static], [protected], [inherited]
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects [static], [protected], [inherited]
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
libMesh::err<< 'ERROR: Seems as if this quadrature rule' << std::endl << ' is not implemented for 2D.' << std::endl; libmesh_error(); }#endif virtual void init_3D (const ElemType, unsigned int =0)#ifndef DEBUG {}#else { libMesh::err << 'ERROR: Seems as if this quadrature rule' << std::endl << ' is not implemented for 3D.' << std::endl; libmesh_error(); }#endif void tensor_product_quad (const QBase& q1D); void tensor_product_hex (const QBase& q1D); void tensor_product_prism (const QBase& q1D, const QBase& q2D); const unsigned int _dim; const Order _order; ElemType _type; unsigned int _p_level; std::vector<Point> libMesh::QBase::_points [protected], [inherited]
Definition at line 332 of file quadrature.h.
Referenced by conical_product_pyramid(), conical_product_tet(), conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), libMesh::QBase::get_points(), libMesh::QGrundmann_Moller::gm_rule(), libMesh::QBase::init_0D(), libMesh::QTrap::init_1D(), libMesh::QClough::init_1D(), libMesh::QGauss::init_1D(), libMesh::QSimpson::init_1D(), libMesh::QGrid::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QTrap::init_2D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGrid::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGrid::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), libMesh::QBase::n_points(), libMesh::QBase::print_info(), libMesh::QBase::qp(), libMesh::QBase::scale(), libMesh::QMonomial::stroud_rule(), and libMesh::QMonomial::wissmann_rule().
std::vector<Real> libMesh::QBase::_weights [protected], [inherited]
The value of the quadrature weights.
Definition at line 337 of file quadrature.h.
Referenced by conical_product_pyramid(), conical_product_tet(), conical_product_tri(), libMesh::QGauss::dunavant_rule(), libMesh::QGauss::dunavant_rule2(), libMesh::QBase::get_weights(), libMesh::QGrundmann_Moller::gm_rule(), libMesh::QBase::init_0D(), libMesh::QTrap::init_1D(), libMesh::QClough::init_1D(), libMesh::QGauss::init_1D(), libMesh::QSimpson::init_1D(), libMesh::QGrid::init_1D(), libMesh::QJacobi::init_1D(), libMesh::QTrap::init_2D(), libMesh::QClough::init_2D(), libMesh::QGauss::init_2D(), libMesh::QSimpson::init_2D(), libMesh::QGrid::init_2D(), libMesh::QMonomial::init_2D(), libMesh::QTrap::init_3D(), libMesh::QGauss::init_3D(), libMesh::QSimpson::init_3D(), libMesh::QGrid::init_3D(), libMesh::QMonomial::init_3D(), libMesh::QGauss::keast_rule(), libMesh::QMonomial::kim_rule(), libMesh::QBase::print_info(), libMesh::QBase::scale(), libMesh::QMonomial::stroud_rule(), libMesh::QBase::w(), and libMesh::QMonomial::wissmann_rule().
bool libMesh::QBase::allow_rules_with_negative_weights [inherited]
Flag (default true) controlling the use of quadrature rules with negative weights. Set this to false to ONLY use (potentially) safer but more expensive rules with all positive weights.
Negative weights typically appear in Gaussian quadrature rules over three-dimensional elements. Rules with negative weights can be unsuitable for some problems. For example, it is possible for a rule with negative weights to obtain a negative result when integrating a positive function.
A particular example: if rules with negative weights are not allowed, a request for TET,THIRD (5 points) will return the TET,FIFTH (14 points) rule instead, nearly tripling the computational effort required!
Definition at line 215 of file quadrature.h.
Referenced by libMesh::QGauss::init_3D(), libMesh::QMonomial::init_3D(), and libMesh::QGrundmann_Moller::init_3D().
Author
Generated automatically by Doxygen for libMesh from the source code.