libMesh::Parallel::StandardType< Hilbert::HilbertIndices >
NAME
libMesh::Parallel::StandardType< Hilbert::HilbertIndices > -
SYNOPSIS
#include <parallel_hilbert.h>
Inherits libMesh::Parallel::DataType.
Public Member Functions
StandardType (const Hilbert::HilbertIndices *=NULL)
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
template<>class libMesh::Parallel::StandardType< Hilbert::HilbertIndices >
Definition at line 44 of file parallel_hilbert.h.
Constructor & Destructor Documentation
libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType (const Hilbert::HilbertIndices * = NULL) [inline], [explicit]
Definition at line 48 of file parallel_hilbert.h.
References libMesh::Parallel::DataType::_datatype, libMesh::libMeshPrivateData::_is_initialized, and libMesh::Parallel::DataType::DataType().
                                                   {
    // _static_type never gets freed, but it only gets committed once
    // so it's not a *huge* memory leak...
    static DataType _static_type;
    static bool _is_initialized = false;
    if (!_is_initialized)
      {
        _static_type = DataType(Parallel::StandardType<Hilbert::inttype>(), 3);
        _is_initialized = true;
      }
    _datatype = _static_type;
  }
Member Function Documentation
void libMesh::Parallel::DataType::commit () [inline], [inherited]
Definition at line 277 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::DataType::DataType().
  {
#ifdef LIBMESH_HAVE_MPI
    MPI_Type_commit (&_datatype);
#endif
  }
void libMesh::Parallel::DataType::free () [inline], [inherited]
Definition at line 284 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), libMesh::Parallel::StandardType< std::complex< T > >::~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
  {
#ifdef LIBMESH_HAVE_MPI
    MPI_Type_free (&_datatype);
#endif
  }
libMesh::Parallel::DataType::operator const data_type & () const [inline], [inherited]
Definition at line 265 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
  { return _datatype; }
libMesh::Parallel::DataType::operator data_type & () [inline], [inherited]
Definition at line 268 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
  { return _datatype; }
Member Data Documentation
data_type libMesh::Parallel::DataType::_datatype [protected], [inherited]
Definition at line 293 of file parallel.h.
Referenced by libMesh::Parallel::DataType::commit(), libMesh::Parallel::DataType::DataType(), libMesh::Parallel::DataType::free(), libMesh::Parallel::DataType::operator const data_type &(), libMesh::Parallel::DataType::operator data_type &(), libMesh::Parallel::DataType::operator=(), StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), and libMesh::Parallel::StandardType< Point >::StandardType().
Author
Generated automatically by Doxygen for libMesh from the source code.