.TH "libMesh::DirichletBoundaries" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::DirichletBoundaries \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dirichlet_boundaries\&.h>\fP
.PP
Inherits vector< DirichletBoundary * >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirichletBoundaries\fP ()"
.br
.ti -1c
.RI "\fB~DirichletBoundaries\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
We're using a class instead of a typedef to allow forward declarations and future flexibility\&. Note that std::map has no virtual destructor, so downcasting here would be dangerous\&. 
.PP
Definition at line 130 of file dirichlet_boundaries\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "libMesh::DirichletBoundaries::DirichletBoundaries ()\fC [inline]\fP"

.PP
Definition at line 133 of file dirichlet_boundaries\&.h\&.
.PP
.nf
133 {}
.fi
.SS "libMesh::DirichletBoundaries::~DirichletBoundaries ()"

.PP
Definition at line 3684 of file dof_map_constraints\&.C\&.
.PP
References end\&.
.PP
.nf
3685 {
3686   for (std::vector<DirichletBoundary *>::iterator it = begin(); it != end(); ++it)
3687     delete *it;
3688 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
