libMesh::RBConstructionBase< Base >
NAME
libMesh::RBConstructionBase< Base > -
SYNOPSIS
#include <rb_construction_base.h>
Inherits Base, and libMesh::RBParametrized.
Public Types
typedef RBConstructionBase< Base > sys_type
Public Member Functions
RBConstructionBase (EquationSystems &es, const std::string &name, const unsigned int number)
virtual ~RBConstructionBase ()
sys_type & system ()
virtual void clear ()
numeric_index_type get_n_training_samples () const
numeric_index_type get_local_n_training_samples () const
numeric_index_type get_first_local_training_index () const
numeric_index_type get_last_local_training_index () const
virtual void initialize_training_parameters (const RBParameters &mu_min, const RBParameters &mu_max, unsigned int n_training_parameters, std::map< std::string, bool > log_param_scale, bool deterministic=true)
virtual void load_training_set (std::map< std::string, std::vector< Number > > &new_training_set)
std::pair< std::string,
std::string > set_alternative_solver (AutoPtr< LinearSolver< Number > > &ls)"
void reset_alternative_solver (AutoPtr< LinearSolver< Number > > &ls, const std::pair< std::string, std::string > &orig)
void broadcast_parameters (unsigned int proc_id)
void set_training_random_seed (unsigned int seed)
void set_deterministic_training_parameter_name (const std::string &name)
const std::string & get_deterministic_training_parameter_name () const
void set_deterministic_training_parameter_repeats (unsigned int repeats)
unsigned int get_deterministic_training_parameter_repeats () const
void initialize_parameters (const RBParameters &mu_min_in, const RBParameters &mu_max_in, const std::map< std::string, std::vector< Real > > &discrete_parameter_values)
void initialize_parameters (const RBParametrized &rb_parametrized)
unsigned int get_n_params () const
unsigned int get_n_continuous_params () const
unsigned int get_n_discrete_params () const
std::set< std::string > get_parameter_names () const
const RBParameters & get_parameters () const
void set_parameters (const RBParameters &params)
const RBParameters & get_parameters_min () const
const RBParameters & get_parameters_max () const
Real get_parameter_min (const std::string &param_name) const
Real get_parameter_max (const std::string &param_name) const
void print_parameters () const
void write_parameter_data_to_files (const std::string &continuous_param_file_name, const std::string &discrete_param_file_name, const bool write_binary_data)
void read_parameter_data_from_files (const std::string &continuous_param_file_name, const std::string &discrete_param_file_name, const bool read_binary_data)
bool is_discrete_parameter (const std::string &mu_name) const
const std::map< std::string,
std::vector< Real > > & get_discrete_parameter_values () const "
void print_discrete_parameter_values () const
Static Public Member Functions
static Real get_closest_value (Real value, const std::vector< Real > &list_of_values)
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Public Attributes
bool verbose_mode
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts"
Protected Member Functions
virtual void init_data ()
RBParameters get_params_from_training_set (unsigned int index)
void set_params_from_training_set (unsigned int index)
virtual void set_params_from_training_set_and_broadcast (unsigned int index)
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Member Functions
static void get_global_max_error_pair (const Parallel::Communicator &communicator, std::pair< unsigned int, Real > &error_pair)
static void generate_training_parameters_random (const Parallel::Communicator &communicator, std::map< std::string, bool > log_param_scale, std::map< std::string, NumericVector< Number > * > &training_parameters_in, unsigned int n_training_samples_in, const RBParameters &min_parameters, const RBParameters &max_parameters, int training_parameters_random_seed=-1, bool serial_training_set=false)
static void generate_training_parameters_deterministic (const Parallel::Communicator &communicator, std::map< std::string, bool > log_param_scale, std::map< std::string, NumericVector< Number > * > &training_parameters_in, unsigned int n_training_samples_in, const RBParameters &min_parameters, const RBParameters &max_parameters, bool serial_training_set=false)
Protected Attributes
bool serial_training_set
AutoPtr< NumericVector< Number > > inner_product_storage_vector
std::string alternative_solver
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects"
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Private Attributes
bool training_parameters_initialized
std::map< std::string,
NumericVector< Number > * > training_parameters"
int training_parameters_random_seed
Detailed Description
template<class Base>class libMesh::RBConstructionBase< Base >
This class is part of the rbOOmit framework.
This is the base class for the Construction stage of the certified reduced basis (RB) method. We template the Base class so that we can derive from the appropriate libMesh System type (e.g. LinearImplicitSystem for standard reduced basis, EigenSystem for SCM) at compile time.
Author:
David J. Knezevic, 2009
Definition at line 57 of file rb_construction_base.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts [protected], [inherited]
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
template<class Base> typedef RBConstructionBase<Base> libMesh::RBConstructionBase< Base >::sys_type
The type of system.
Definition at line 77 of file rb_construction_base.h.
Constructor & Destructor Documentation
template<class Base> libMesh::RBConstructionBase< Base >::RBConstructionBase (EquationSystems &es, const std::string &name, const unsigned intnumber)
Constructor. Initializes required data structures.
template<class Base> virtual libMesh::RBConstructionBase< Base >::~RBConstructionBase () [virtual]
Destructor.
Member Function Documentation
template<class Base> void libMesh::RBConstructionBase< Base >::broadcast_parameters (unsigned intproc_id)
Broadcasts parameters on processor proc_id to all processors.
template<class Base> virtual void libMesh::RBConstructionBase< Base >::clear () [virtual]
Clear all the data structures associated with the system.
Reimplemented from libMesh::RBParametrized.
Reimplemented in libMesh::RBConstruction, libMesh::RBSCMConstruction, libMesh::RBEIMConstruction, libMesh::TransientRBConstruction, and libMesh::TransientSystem< RBConstruction >.
void libMesh::ReferenceCounter::disable_print_counter_info () [static], [inherited]
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = false;
  return;
}
void libMesh::ReferenceCounter::enable_print_counter_info () [static], [inherited]
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = true;
  return;
}
template<class Base> static void libMesh::RBConstructionBase< Base >::generate_training_parameters_deterministic (const Parallel::Communicator &communicator, std::map< std::string, bool >log_param_scale, std::map< std::string, NumericVector< Number > * > &training_parameters_in, unsigned intn_training_samples_in, const RBParameters &min_parameters, const RBParameters &max_parameters, boolserial_training_set = false) [static], [protected]
Static helper function for generating a deterministic set of parameters. Only works with 1 or 2 parameters (as defined by the lengths of min/max parameters vectors), otherwise throws an error.
template<class Base> static void libMesh::RBConstructionBase< Base >::generate_training_parameters_random (const Parallel::Communicator &communicator, std::map< std::string, bool >log_param_scale, std::map< std::string, NumericVector< Number > * > &training_parameters_in, unsigned intn_training_samples_in, const RBParameters &min_parameters, const RBParameters &max_parameters, inttraining_parameters_random_seed = -1, boolserial_training_set = false) [static], [protected]
Static helper function for generating a randomized set of parameters.
static Real libMesh::RBParametrized::get_closest_value (Realvalue, const std::vector< Real > &list_of_values) [static], [inherited]
Helper function that returns the closest entry to value from list_of_values.
template<class Base> const std::string& libMesh::RBConstructionBase< Base >::get_deterministic_training_parameter_name () const
Get the name of the parameter that we will generate deterministic training parameters for.
template<class Base> unsigned int libMesh::RBConstructionBase< Base >::get_deterministic_training_parameter_repeats () const
Get the number of times each sample of the deterministic training parameter is repeated.
const std::map< std::string, std::vector<Real> >& libMesh::RBParametrized::get_discrete_parameter_values () const [inherited]
Get a const reference to the discrete parameter values.
template<class Base> numeric_index_type libMesh::RBConstructionBase< Base >::get_first_local_training_index () const
Get the first local index of the training parameters.
template<class Base> static void libMesh::RBConstructionBase< Base >::get_global_max_error_pair (const Parallel::Communicator &communicator, std::pair< unsigned int, Real > &error_pair) [static], [protected]
Static function to return the error pair (index,error) that is corresponds to the largest error on all processors.
std::string libMesh::ReferenceCounter::get_info () [static], [inherited]
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
{
#if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
  std::ostringstream oss;
  oss << '\n'
      << " ---------------------------------------------------------------------------- \n"
      << "| Reference count information |\n"
      << " ---------------------------------------------------------------------------- \n";
  for (Counts::iterator it = _counts.begin();
       it != _counts.end(); ++it)
    {
      const std::string name(it->first);
      const unsigned int creations = it->second.first;
      const unsigned int destructions = it->second.second;
      oss << "| " << name << " reference count information:\n"
          << "| Creations: " << creations << '\n'
          << "| Destructions: " << destructions << '\n';
    }
  oss << " ---------------------------------------------------------------------------- \n";
  return oss.str();
#else
  return "";
#endif
}
template<class Base> numeric_index_type libMesh::RBConstructionBase< Base >::get_last_local_training_index () const
Get the last local index of the training parameters.
template<class Base> numeric_index_type libMesh::RBConstructionBase< Base >::get_local_n_training_samples () const
Get the total number of training samples local to this processor.
unsigned int libMesh::RBParametrized::get_n_continuous_params () const [inherited]
Get the number of continuous parameters.
unsigned int libMesh::RBParametrized::get_n_discrete_params () const [inherited]
Get the number of discrete parameters.
unsigned int libMesh::RBParametrized::get_n_params () const [inherited]
Get the number of parameters.
template<class Base> numeric_index_type libMesh::RBConstructionBase< Base >::get_n_training_samples () const
Get the total number of training samples.
Real libMesh::RBParametrized::get_parameter_max (const std::string &param_name) const [inherited]
Get maximum allowable value of parameter param_name.
Real libMesh::RBParametrized::get_parameter_min (const std::string &param_name) const [inherited]
Get minimum allowable value of parameter param_name.
std::set<std::string> libMesh::RBParametrized::get_parameter_names () const [inherited]
Get a set that stores the parameter names.
const RBParameters& libMesh::RBParametrized::get_parameters () const [inherited]
Get the current parameters.
const RBParameters& libMesh::RBParametrized::get_parameters_max () const [inherited]
Get an RBParameters object that specifies the maximum allowable value for each parameter.
const RBParameters& libMesh::RBParametrized::get_parameters_min () const [inherited]
Get an RBParameters object that specifies the minimum allowable value for each parameter.
template<class Base> RBParameters libMesh::RBConstructionBase< Base >::get_params_from_training_set (unsigned intindex) [protected]
Return the RBParameters in index index of training set.
void libMesh::ReferenceCounter::increment_constructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.first++;
}
void libMesh::ReferenceCounter::increment_destructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.second++;
}
template<class Base> virtual void libMesh::RBConstructionBase< Base >::init_data () [protected], [virtual]
Initializes the member data fields associated with the system, so that, e.g., assemble() may be used.
Reimplemented in libMesh::RBEIMConstruction, and libMesh::TransientSystem< RBConstruction >.
void libMesh::RBParametrized::initialize_parameters (const RBParameters &mu_min_in, const RBParameters &mu_max_in, const std::map< std::string, std::vector< Real > > &discrete_parameter_values) [inherited]
Initialize the parameter ranges and set current_parameters.
void libMesh::RBParametrized::initialize_parameters (const RBParametrized &rb_parametrized) [inherited]
Initialize the parameter ranges and set current_parameters.
template<class Base> virtual void libMesh::RBConstructionBase< Base >::initialize_training_parameters (const RBParameters &mu_min, const RBParameters &mu_max, unsigned intn_training_parameters, std::map< std::string, bool >log_param_scale, booldeterministic = true) [virtual]
Initialize the parameter ranges and indicate whether deterministic or random training parameters should be used and whether or not we want the parameters to be scaled logarithmically.
bool libMesh::RBParametrized::is_discrete_parameter (const std::string &mu_name) const [inherited]
Is parameter mu_name discrete?
template<class Base> virtual void libMesh::RBConstructionBase< Base >::load_training_set (std::map< std::string, std::vector< Number > > &new_training_set) [virtual]
Overwrite the training parameters with new_training_set.
static unsigned int libMesh::ReferenceCounter::n_objects () [inline], [static], [inherited]
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
  { return _n_objects; }
void libMesh::RBParametrized::print_discrete_parameter_values () const [inherited]
Print out all the discrete parameter values.
void libMesh::ReferenceCounter::print_info (std::ostream &out = libMesh::out) [static], [inherited]
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
{
  if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
}
void libMesh::RBParametrized::print_parameters () const [inherited]
Print the current parameters.
void libMesh::RBParametrized::read_parameter_data_from_files (const std::string &continuous_param_file_name, const std::string &discrete_param_file_name, const boolread_binary_data) [inherited]
Read in the parameter ranges from files.
template<class Base> void libMesh::RBConstructionBase< Base >::reset_alternative_solver (AutoPtr< LinearSolver< Number > > &ls, const std::pair< std::string, std::string > &orig)
Resets the PC (and iterative solver, if desired) in the passed-in LinearSolver object to the values specified in the pair of strings passed as the second argument. If the 'alternative_solver' string, defined below, is 'unchanged', this function does nothing.
template<class Base> std::pair<std::string,std::string> libMesh::RBConstructionBase< Base >::set_alternative_solver (AutoPtr< LinearSolver< Number > > &ls)
Changes the current PC (and iterative solver, if desired) in the passed-in LinearSolver object to an alternative solver specified by the alternative_solver string stored in this class. You might use this to e.g. switch to a sparse direct solver for the multiple RHS solves executed during the update_residual_terms function. The return strings are names of the original PC and KSP objects, you can reset these using the reset_alternative_solver() function below.
template<class Base> void libMesh::RBConstructionBase< Base >::set_deterministic_training_parameter_name (const std::string &name)
In some cases we only want to allow discrete parameter values, instead of parameters that may take any value in a specified interval. Here we provide a method to set the d Set the discrete values for parameter mu that are allowed in the training set. This must be called before the training set is generated. Set the name of the parameter that we will generate deterministic training parameters for. Defaults to 'NONE'.
template<class Base> void libMesh::RBConstructionBase< Base >::set_deterministic_training_parameter_repeats (unsigned intrepeats)
Set the number of times each sample of the deterministic training parameter is repeated.
void libMesh::RBParametrized::set_parameters (const RBParameters &params) [inherited]
Set the current parameters to params
template<class Base> void libMesh::RBConstructionBase< Base >::set_params_from_training_set (unsigned intindex) [protected]
Set parameters to the RBParameters stored in index index of the training set.
template<class Base> virtual void libMesh::RBConstructionBase< Base >::set_params_from_training_set_and_broadcast (unsigned intindex) [protected], [virtual]
Load the specified training parameter and then broadcast to all processors.
template<class Base> void libMesh::RBConstructionBase< Base >::set_training_random_seed (unsigned intseed)
Set the seed that is used to randomly generate training parameters.
template<class Base> sys_type& libMesh::RBConstructionBase< Base >::system () [inline]
Returns:
a clever pointer to the system.
Definition at line 82 of file rb_construction_base.h.
{ return *this; }
void libMesh::RBParametrized::write_parameter_data_to_files (const std::string &continuous_param_file_name, const std::string &discrete_param_file_name, const boolwrite_binary_data) [inherited]
Write out the parameter ranges to files.
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts [static], [protected], [inherited]
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true [static], [protected], [inherited]
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex [static], [protected], [inherited]
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects [static], [protected], [inherited]
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
template<class Base> std::string libMesh::RBConstructionBase< Base >::alternative_solver [protected]
Set this string to specify an alternative solver used in the set_alternative_solver() function above. Currently-supported values are: .) unchanged, to continue using the default truth solve solver .) amg, to use the BoomerAMG from Hypre (NOT for indefinite problems!) .) mumps, to use a sparse direct solver Note1: mumps and amg will only be available if PETSc has been compiled with them. Note2: RBConstruction::process_parameters_file() is responsible for reading in this value ('rb_alternative_solver') from file for RBConstruction-derived subclasses Note3: RBSCMSystem::process_parameters_file() reads this value ('scm_alternative_solver') for RBSCMSystem-derived subclasses
Definition at line 271 of file rb_construction_base.h.
template<class Base> AutoPtr< NumericVector<Number> > libMesh::RBConstructionBase< Base >::inner_product_storage_vector [protected]
We keep an extra temporary vector that is useful for performing inner products (avoids unnecessary memory allocation/deallocation).
Definition at line 257 of file rb_construction_base.h.
template<class Base> bool libMesh::RBConstructionBase< Base >::serial_training_set [protected]
This boolean flag indicates whether or not the training set should be the same on all processors. By default it is false, but in the case of the Empirical Interpolation Method (RBEIMConstruction), for example, we need the training set to be identical on all processors.
Definition at line 250 of file rb_construction_base.h.
template<class Base> std::map< std::string, NumericVector<Number>* > libMesh::RBConstructionBase< Base >::training_parameters [private]
The training samples.
Definition at line 285 of file rb_construction_base.h.
template<class Base> bool libMesh::RBConstructionBase< Base >::training_parameters_initialized [private]
Boolean flag to indicate whether or not the parameter ranges have been initialized.
Definition at line 280 of file rb_construction_base.h.
template<class Base> int libMesh::RBConstructionBase< Base >::training_parameters_random_seed [private]
If < 0, use std::time() * processor_id() to seed the random number generator for the training parameters (default). If >= 0, use the provided value * processor_id() as the random number generator seed.
Definition at line 293 of file rb_construction_base.h.
bool libMesh::RBParametrized::verbose_mode [inherited]
Public boolean to toggle verbose mode.
Definition at line 172 of file rb_parametrized.h.
Author
Generated automatically by Doxygen for libMesh from the source code.