libMesh::Parallel::StandardType< std::complex< T > >
NAME
libMesh::Parallel::StandardType< std::complex< T > > -
SYNOPSIS
#include <parallel_implementation.h>
Inherits libMesh::Parallel::DataType.
Public Member Functions
StandardType (const std::complex< T > *=NULL)
~StandardType ()
operator const data_type & () const
operator data_type & ()
void commit ()
void free ()
Protected Attributes
data_type _datatype
Detailed Description
template<typename T>class libMesh::Parallel::StandardType< std::complex< T > >
Definition at line 158 of file parallel_implementation.h.
Constructor & Destructor Documentation
template<typename T > libMesh::Parallel::StandardType< std::complex< T > >::StandardType (const std::complex< T > * = NULL) [inline], [explicit]
Definition at line 162 of file parallel_implementation.h.
                                               :
    DataType(StandardType<T>(NULL), 2) {}
template<typename T > libMesh::Parallel::StandardType< std::complex< T > >::~StandardType () [inline]
Definition at line 165 of file parallel_implementation.h.
References libMesh::Parallel::DataType::free().
{ this->free(); }
Member Function Documentation
void libMesh::Parallel::DataType::commit () [inline], [inherited]
Definition at line 277 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::DataType::DataType().
  {
#ifdef LIBMESH_HAVE_MPI
    MPI_Type_commit (&_datatype);
#endif
  }
void libMesh::Parallel::DataType::free () [inline], [inherited]
Definition at line 284 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
Referenced by libMesh::Parallel::StandardType< std::pair< T1, T2 > >::~StandardType(), ~StandardType(), libMesh::Parallel::StandardType< TypeTensor< T > >::~StandardType(), and libMesh::Parallel::StandardType< TensorValue< T > >::~StandardType().
  {
#ifdef LIBMESH_HAVE_MPI
    MPI_Type_free (&_datatype);
#endif
  }
libMesh::Parallel::DataType::operator const data_type & () const [inline], [inherited]
Definition at line 265 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
  { return _datatype; }
libMesh::Parallel::DataType::operator data_type & () [inline], [inherited]
Definition at line 268 of file parallel.h.
References libMesh::Parallel::DataType::_datatype.
  { return _datatype; }
Member Data Documentation
data_type libMesh::Parallel::DataType::_datatype [protected], [inherited]
Definition at line 293 of file parallel.h.
Referenced by libMesh::Parallel::DataType::commit(), libMesh::Parallel::DataType::DataType(), libMesh::Parallel::DataType::free(), libMesh::Parallel::DataType::operator const data_type &(), libMesh::Parallel::DataType::operator data_type &(), libMesh::Parallel::DataType::operator=(), libMesh::Parallel::StandardType< Hilbert::HilbertIndices >::StandardType(), libMesh::Parallel::StandardType< TypeVector< T > >::StandardType(), libMesh::Parallel::StandardType< std::pair< T1, T2 > >::StandardType(), libMesh::Parallel::StandardType< VectorValue< T > >::StandardType(), and libMesh::Parallel::StandardType< Point >::StandardType().
Author
Generated automatically by Doxygen for libMesh from the source code.