libMesh::MeshInput< MT >
NAME
libMesh::MeshInput< MT > -
SYNOPSIS
#include <mesh_input.h>
Public Member Functions
virtual ~MeshInput ()
virtual void read (const std::string &)=0
Protected Member Functions
MeshInput (bool is_parallel_format=false)
MeshInput (MT &, const bool is_parallel_format=false)
MT & mesh ()
void skip_comment_lines (std::istream &in, const char comment_start)
Protected Attributes
std::vector< bool > elems_of_dimension
Private Attributes
MT * _obj
const bool _is_parallel_format
Detailed Description
template<class MT>class libMesh::MeshInput< MT >
This class defines an abstract interface for Mesh input. Specific classes derived from this class actually implement reading various mesh formats.
Author:
Benjamin S. Kirk
Date:
2004
Definition at line 51 of file mesh_input.h.
Constructor & Destructor Documentation
template<class MT > libMesh::MeshInput< MT >::MeshInput (boolis_parallel_format = false) [inline], [explicit], [protected]
Default constructor. Will set the _obj to NULL, effectively rendering this object useless.
Definition at line 126 of file mesh_input.h.
                                                       :
  elems_of_dimension(),
  _obj (NULL),
  _is_parallel_format(is_parallel_format)
{
}
template<class MT> libMesh::MeshInput< MT >::MeshInput (MT &obj, const boolis_parallel_format = false) [inline], [explicit], [protected]
Constructor. Takes a writeable reference to an object. This is the constructor required to read an object.
Definition at line 137 of file mesh_input.h.
References libMesh::MeshInput< MT >::_is_parallel_format, libMesh::MeshInput< MT >::mesh(), libMesh::out, and libMesh::processor_id().
                                                                :
  elems_of_dimension(),
  _obj (&obj),
  _is_parallel_format(is_parallel_format)
{
  if (!_is_parallel_format && !this->mesh().is_serial())
    {
      if (this->mesh().processor_id() == 0)
        {
          libmesh_do_once(libMesh::out <<
                          "Warning: This MeshOutput subclass only supports meshes which have been serialized!"
                          << std::endl;);
        }
    }
}
template<class MT > libMesh::MeshInput< MT >::~MeshInput () [inline], [virtual]
Destructor.
Definition at line 157 of file mesh_input.h.
{
}
Member Function Documentation
template<class MT > MT & libMesh::MeshInput< MT >::mesh () [inline], [protected]
Returns the object as a writeable reference.
Definition at line 165 of file mesh_input.h.
Referenced by libMesh::GMVIO::_read_materials(), libMesh::GMVIO::_read_nodes(), libMesh::GMVIO::_read_one_cell(), libMesh::AbaqusIO::assign_boundary_node_ids(), libMesh::AbaqusIO::assign_sideset_ids(), libMesh::AbaqusIO::assign_subdomain_ids(), libMesh::ExodusII_IO::copy_elemental_solution(), libMesh::ExodusII_IO::copy_nodal_solution(), libMesh::GMVIO::copy_nodal_solution(), libMesh::TetGenIO::element_in(), libMesh::UNVIO::element_in(), libMesh::MeshInput< MT >::MeshInput(), libMesh::TetGenIO::node_in(), libMesh::UNVIO::node_in(), libMesh::AbaqusIO::read(), libMesh::TetGenIO::read(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO::read(), libMesh::GMVIO::read(), libMesh::CheckpointIO::read(), libMesh::XdrIO::read(), libMesh::VTKIO::read(), libMesh::LegacyXdrIO::read_ascii(), libMesh::CheckpointIO::read_bcs(), libMesh::CheckpointIO::read_connectivity(), libMesh::AbaqusIO::read_elements(), libMesh::UCDIO::read_implementation(), libMesh::UNVIO::read_implementation(), libMesh::GmshIO::read_mesh(), libMesh::LegacyXdrIO::read_mesh(), libMesh::AbaqusIO::read_nodes(), libMesh::CheckpointIO::read_nodes(), libMesh::CheckpointIO::read_nodesets(), libMesh::XdrIO::read_serialized_bcs(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::XdrIO::read_serialized_subdomain_names(), libMesh::OFFIO::read_stream(), libMesh::MatlabIO::read_stream(), libMesh::CheckpointIO::read_subdomain_names(), and libMesh::UNVIO::write_implementation().
{
  if (_obj == NULL) libmesh_error();
  return *_obj;
}
template<class MT> virtual void libMesh::MeshInput< MT >::read (const std::string &) [pure virtual]
This method implements reading a mesh from a specified file.
Implemented in libMesh::MatlabIO, libMesh::VTKIO, libMesh::XdrIO, libMesh::CheckpointIO, libMesh::LegacyXdrIO, libMesh::GMVIO, libMesh::ExodusII_IO, libMesh::GmshIO, libMesh::Nemesis_IO, libMesh::UNVIO, libMesh::TetGenIO, libMesh::UCDIO, libMesh::OFFIO, and libMesh::AbaqusIO.
template<class MT > void libMesh::MeshInput< MT >::skip_comment_lines (std::istream &in, const charcomment_start) [protected]
Reads input from in, skipping all the lines that start with the character comment_start.
Definition at line 174 of file mesh_input.h.
{
  char c, line[256];
  while (in.get(c), c==comment_start)
    in.getline (line, 255);
  // put back first character of
  // first non-comment line
  in.putback (c);
}
Member Data Documentation
template<class MT> const bool libMesh::MeshInput< MT >::_is_parallel_format [private]
Flag specifying whether this format is parallel-capable. If this is false (default) I/O is only permitted when the mesh has been serialized.
Definition at line 117 of file mesh_input.h.
Referenced by libMesh::MeshInput< MT >::MeshInput().
template<class MT> MT* libMesh::MeshInput< MT >::_obj [private]
A pointer to a non-const object object. This allows us to read the object from file.
Definition at line 110 of file mesh_input.h.
template<class MT> std::vector<bool> libMesh::MeshInput< MT >::elems_of_dimension [protected]
A vector of bools describing what dimension elements have been encountered when reading a mesh.
Definition at line 93 of file mesh_input.h.
Author
Generated automatically by Doxygen for libMesh from the source code.