.TH "libMesh::Parallel::PostWaitWork" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::Parallel::PostWaitWork \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parallel\&.h>\fP
.PP
Inherited by \fBlibMesh::Parallel::PostWaitCopyBuffer< Container, OutputIter >\fP, \fBlibMesh::Parallel::PostWaitDeleteBuffer< Container >\fP, and \fBlibMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~PostWaitWork\fP ()"
.br
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class that can be subclassed to allow other code to perform work after a MPI_Wait succeeds 
.PP
Definition at line 384 of file parallel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual libMesh::Parallel::PostWaitWork::~PostWaitWork ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 385 of file parallel\&.h\&.
.PP
.nf
385 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void libMesh::Parallel::PostWaitWork::run ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBlibMesh::Parallel::PostWaitDeleteBuffer< Container >\fP, \fBlibMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >\fP, and \fBlibMesh::Parallel::PostWaitCopyBuffer< Container, OutputIter >\fP\&.
.PP
Definition at line 387 of file parallel\&.h\&.
.PP
.nf
387 {}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
