libMesh::Solver
NAME
libMesh::Solver -
SYNOPSIS
#include <solver.h>
Inherits libMesh::ReferenceCountedObject< Solver >.
Public Types
typedef EquationSystems sys_type
Public Member Functions
~Solver ()
virtual void init ()
virtual void pre_process ()
virtual void solve ()
virtual void post_process ()
const sys_type & system () const
const MeshBase & mesh () const
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts"
Protected Member Functions
Solver (EquationSystems &es)
Solver (EquationSystems &es, const std::string &name, const unsigned int number)
sys_type & system ()
MeshBase & mesh ()
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Protected Attributes
sys_type & _system
MeshBase & _mesh
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects"
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
This is a generic class that defines a solver to be used in a simulation. A user can define a solver by deriving from this class and implementing certain functions.
Author:
Benjamin S. Kirk, 2003-2004.
Definition at line 47 of file solver.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts [protected], [inherited]
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
typedef EquationSystems libMesh::Solver::sys_type
The type of system
Definition at line 78 of file solver.h.
Constructor & Destructor Documentation
libMesh::Solver::Solver (EquationSystems &es) [inline], [explicit], [protected]
Constructor. Requires a reference to the system to be solved. The constructor is protected since it should not be instantiated by users.
Definition at line 145 of file solver.h.
                                   :
  _system (es),
  _mesh (es.get_mesh())
{
  libmesh_deprecated();
}
libMesh::Solver::Solver (EquationSystems &es, const std::string &name, const unsigned intnumber) [protected]
Constructor. Requires a reference to the EquationSystems object, a name for the system, and the system number.
libMesh::Solver::~Solver () [inline]
Destructor.
Definition at line 155 of file solver.h.
{
}
Member Function Documentation
void libMesh::ReferenceCounter::disable_print_counter_info () [static], [inherited]
Definition at line 106 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = false;
  return;
}
void libMesh::ReferenceCounter::enable_print_counter_info () [static], [inherited]
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter.
{
  _enable_print_counter = true;
  return;
}
std::string libMesh::ReferenceCounter::get_info () [static], [inherited]
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References libMesh::ReferenceCounter::_counts, and libMesh::Quality::name().
Referenced by libMesh::ReferenceCounter::print_info().
{
#if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
  std::ostringstream oss;
  oss << '\n'
      << " ---------------------------------------------------------------------------- \n"
      << "| Reference count information |\n"
      << " ---------------------------------------------------------------------------- \n";
  for (Counts::iterator it = _counts.begin();
       it != _counts.end(); ++it)
    {
      const std::string name(it->first);
      const unsigned int creations = it->second.first;
      const unsigned int destructions = it->second.second;
      oss << "| " << name << " reference count information:\n"
          << "| Creations: " << creations << '\n'
          << "| Destructions: " << destructions << '\n';
    }
  oss << " ---------------------------------------------------------------------------- \n";
  return oss.str();
#else
  return "";
#endif
}
void libMesh::ReferenceCounter::increment_constructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.first++;
}
void libMesh::ReferenceCounter::increment_destructor_count (const std::string &name) [inline], [protected], [inherited]
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References libMesh::ReferenceCounter::_counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.second++;
}
void libMesh::Solver::init () [inline], [virtual]
The initialization function. This method is used to initialize data structures befor a simulation begins.
Definition at line 162 of file solver.h.
References libMesh::EquationSystems::init(), and system().
{
  // Initialize the system.
  this->system().init ();
}
const MeshBase& libMesh::Solver::mesh () const [inline]
Returns:
a reference to the Mesh.
Definition at line 113 of file solver.h.
References _mesh.
{ return _mesh; }
MeshBase& libMesh::Solver::mesh () [inline], [protected]
Returns:
a reference to the Mesh.
Definition at line 126 of file solver.h.
References _mesh.
{ return _mesh; }
static unsigned int libMesh::ReferenceCounter::n_objects () [inline], [static], [inherited]
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References libMesh::ReferenceCounter::_n_objects.
  { return _n_objects; }
void libMesh::Solver::post_process () [inline], [virtual]
This method may be called after each solve step in order to perform any required post-processing.
Definition at line 195 of file solver.h.
Referenced by solve().
{
  // libMesh::out << "Post-processing"
  // << std::endl;
}
void libMesh::Solver::pre_process () [inline], [virtual]
This method may be called before each solve step in order to perform any required pre-processing.
Definition at line 171 of file solver.h.
Referenced by solve().
{
  // libMesh::out << "Pre-processing"
  // << std::endl;
}
void libMesh::ReferenceCounter::print_info (std::ostream &out = libMesh::out) [static], [inherited]
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References libMesh::ReferenceCounter::_enable_print_counter, and libMesh::ReferenceCounter::get_info().
{
  if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
}
void libMesh::Solver::solve () [inline], [virtual]
This method performs a solve step. What occurs in this method will depend on the type of solver. See the example programs for more details.
Definition at line 180 of file solver.h.
References post_process(), pre_process(), libMesh::EquationSystems::solve(), and system().
{
  // Perform any necessary pre-processing
  Solver::pre_process ();
  // Solve the system
  this->system().solve ();
  // Perform any necessary post-processing
  Solver::post_process ();
}
const sys_type& libMesh::Solver::system () const [inline]
Returns:
a constant reference to the system we are solving.
Definition at line 108 of file solver.h.
References _system.
Referenced by init(), and solve().
{ return _system; }
sys_type& libMesh::Solver::system () [inline], [protected]
Returns:
a writeable reference to the system we are solving.
Definition at line 121 of file solver.h.
References _system.
{ return _system; }
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts [static], [protected], [inherited]
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::get_info(), libMesh::ReferenceCounter::increment_constructor_count(), and libMesh::ReferenceCounter::increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true [static], [protected], [inherited]
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::disable_print_counter_info(), libMesh::ReferenceCounter::enable_print_counter_info(), and libMesh::ReferenceCounter::print_info().
MeshBase& libMesh::Solver::_mesh [protected]
A reference to the Mesh for the system we are solving.
Definition at line 137 of file solver.h.
Referenced by mesh().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex [static], [protected], [inherited]
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects [static], [protected], [inherited]
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by libMesh::ReferenceCounter::n_objects(), libMesh::ReferenceCounter::ReferenceCounter(), and libMesh::ReferenceCounter::~ReferenceCounter().
sys_type& libMesh::Solver::_system [protected]
A reference to the system we are solving.
Definition at line 131 of file solver.h.
Referenced by system().
Author
Generated automatically by Doxygen for libMesh from the source code.