.TH "libmesh_exceptions.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libmesh_exceptions.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibMesh::LogicError\fP"
.br
.ti -1c
.RI "class \fBlibMesh::NotImplemented\fP"
.br
.ti -1c
.RI "class \fBlibMesh::FileError\fP"
.br
.ti -1c
.RI "class \fBlibMesh::ConvergenceFailure\fP"
.br
.ti -1c
.RI "class \fBlibMesh::DynamicCastFailure\fP"
.br
.ti -1c
.RI "class \fBlibMesh::FloatingPointException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
