.TH "libMesh::MeshBase::node_iterator" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::MeshBase::node_iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mesh_base\&.h>\fP
.PP
Inherits variant_filter_iterator< MeshBase::Predicate, Node * >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename PredType , typename IterType > \fBnode_iterator\fP (const IterType &d, const IterType &e, const PredType &p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The definition of the \fBnode_iterator\fP struct\&. 
.PP
Definition at line 1021 of file mesh_base\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename PredType , typename IterType > libMesh::MeshBase::node_iterator::node_iterator (const IterType &d, const IterType &e, const PredType &p)\fC [inline]\fP"

.PP
Definition at line 1028 of file mesh_base\&.h\&.
.PP
.nf
1030                                      :
1031     variant_filter_iterator<MeshBase::Predicate,
1032     Node*>(d,e,p) {}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
