libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::Base
NAME
libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::Base -
SYNOPSIS
#include <inf_fe.h>
Static Public Member Functions
static Elem * build_elem (const Elem *inf_elem)
static ElemType get_elem_type (const ElemType type)
static unsigned int n_base_mapping_sf (const ElemType base_elem_type, const Order base_mapping_order)
Private Member Functions
Base ()
Detailed Description
template<unsigned int friend_Dim, FEFamily friend_T_radial, InfMapType friend_T_map>class libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::Base
This nested class contains most of the static methods related to the base part of an infinite element. Only static members are provided, and these should only be accessible from within InfFE.
Author:
Daniel Dreyer
Date:
2003
Definition at line 188 of file inf_fe.h.
Constructor & Destructor Documentation
template<unsigned int friend_Dim, FEFamily friend_T_radial, InfMapType friend_T_map> libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::Base::Base () [inline], [private]
Never use an object of this type.
Definition at line 195 of file inf_fe.h.
{}
Member Function Documentation
template<unsigned int Dim, FEFamily T_radial, InfMapType T_base> Elem * libMesh::InfFE< Dim, T_radial, T_base >::Base::build_elem (const Elem *inf_elem) [static]
Build the base element of an infinite element. Be careful, this method allocates memory! So be sure to delete the new element afterwards.
Definition at line 36 of file inf_fe_base_radial.C.
References libMesh::Elem::build_side(), and libMesh::AutoPtr< Tp >::release().
{
  AutoPtr<Elem> ape(inf_elem->build_side(0));
  return ape.release();
}
template<unsigned int Dim, FEFamily T_radial, InfMapType T_base> ElemType libMesh::InfFE< Dim, T_radial, T_base >::Base::get_elem_type (const ElemTypetype) [static]
Returns:
the base element associated to type. This is, for example, TRI3 for INFPRISM6.
Definition at line 46 of file inf_fe_base_radial.C.
References libMesh::EDGE2, libMesh::EDGE3, libMesh::err, libMesh::INFEDGE2, libMesh::INFHEX16, libMesh::INFHEX18, libMesh::INFHEX8, libMesh::INFPRISM12, libMesh::INFPRISM6, libMesh::INFQUAD4, libMesh::INFQUAD6, libMesh::INVALID_ELEM, libMesh::QUAD4, libMesh::QUAD8, libMesh::QUAD9, libMesh::TRI3, and libMesh::TRI6.
{
  switch (type)
    {
      // 3D infinite elements:
      // with Dim=3 -> infinite elements on their own
    case INFHEX8:
      return QUAD4;
    case INFHEX16:
      return QUAD8;
    case INFHEX18:
      return QUAD9;
    case INFPRISM6:
      return TRI3;
    case INFPRISM12:
      return TRI6;
      // 2D infinite elements:
      // with Dim=3 -> used as boundary condition,
      // with Dim=2 -> infinite elements on their own
    case INFQUAD4:
      return EDGE2;
    case INFQUAD6:
      return EDGE3;
      // 1D infinite elements:
      // with Dim=2 -> used as boundary condition,
      // with Dim=1 -> infinite elements on their own,
      // but no base element!
    case INFEDGE2:
      return INVALID_ELEM;
    default:
      {
        libMesh::err << "ERROR: Unsupported element type!: " << type
                     << std::endl;
        libmesh_error();
      }
    }
  libmesh_error();
  return INVALID_ELEM;
}
template<unsigned int Dim, FEFamily T_radial, InfMapType T_base> unsigned int libMesh::InfFE< Dim, T_radial, T_base >::Base::n_base_mapping_sf (const ElemTypebase_elem_type, const Orderbase_mapping_order) [static]
Returns:
the number of shape functions used in the mapping in the base element of type base_elem_type mapped with order base_mapping_order
Definition at line 101 of file inf_fe_base_radial.C.
References libMesh::FE< Dim, T >::n_shape_functions().
{
  if (Dim == 1)
    return 1;
  else if (Dim == 2)
    return FE<1,LAGRANGE>::n_shape_functions (base_elem_type,
                                              base_mapping_order);
  else if (Dim == 3)
    return FE<2,LAGRANGE>::n_shape_functions (base_elem_type,
                                              base_mapping_order);
  else
    {
      // whoa, cool infinite element!
      libmesh_error();
      return 0;
    }
}
Author
Generated automatically by Doxygen for libMesh from the source code.