.TH "libMesh::NonlinearImplicitSystem::ComputeVectorSubspace" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libMesh::NonlinearImplicitSystem::ComputeVectorSubspace \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nonlinear_implicit_system\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ComputeVectorSubspace\fP ()"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (std::vector< \fBNumericVector\fP< \fBNumber\fP > * > &sp, \fBsys_type\fP &s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callable abstract base class to be used as a callback to provide the solver with a basis for the system's Jacobian's nullspace (the kernel or the 'zero energy modes') or near-nullspace (the 'low energy modes')\&. A nullspace can be used to solve a degenerate problem iteratively (e\&.g\&., with a Krylov subspace method)\&. A near nullspace can be used by an Algebraic Multigrid (AMG) preconditioner to construct smoothed- aggregation-like coarse spaces\&. 
.PP
Definition at line 140 of file nonlinear_implicit_system\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual libMesh::NonlinearImplicitSystem::ComputeVectorSubspace::~ComputeVectorSubspace ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 143 of file nonlinear_implicit_system\&.h\&.
.PP
.nf
143 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void libMesh::NonlinearImplicitSystem::ComputeVectorSubspace::operator() (std::vector< \fBNumericVector\fP< \fBNumber\fP > * > &sp, \fBsys_type\fP &s)\fC [virtual]\fP"
This function will be called to compute the subspace basis (e\&.g\&., nullspace or nearnullspace)\&. It must be implemented by the user in a derived class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
