libMesh::ReferenceCounter
NAME
libMesh::ReferenceCounter -
SYNOPSIS
#include <reference_counter.h>
Inherited by libMesh::ReferenceCountedObject< T >, libMesh::ReferenceCountedObject< DiffSolver >, libMesh::ReferenceCountedObject< DofMap >, libMesh::ReferenceCountedObject< DofObject >, libMesh::ReferenceCountedObject< EigenSolver< T > >, libMesh::ReferenceCountedObject< Elem >, libMesh::ReferenceCountedObject< ElemAssembly >, libMesh::ReferenceCountedObject< EquationSystems >, libMesh::ReferenceCountedObject< FEAbstract >, libMesh::ReferenceCountedObject< LinearSolver< Number > >, libMesh::ReferenceCountedObject< LinearSolver< T > >, libMesh::ReferenceCountedObject< Node >, libMesh::ReferenceCountedObject< NonlinearSolver< Number > >, libMesh::ReferenceCountedObject< NonlinearSolver< T > >, libMesh::ReferenceCountedObject< NumericVector< T > >, libMesh::ReferenceCountedObject< PointLocatorBase >, libMesh::ReferenceCountedObject< Preconditioner< Number > >, libMesh::ReferenceCountedObject< Preconditioner< T > >, libMesh::ReferenceCountedObject< QBase >, libMesh::ReferenceCountedObject< RBAssemblyExpansion >, libMesh::ReferenceCountedObject< RBParametrized >, libMesh::ReferenceCountedObject< RBTheta >, libMesh::ReferenceCountedObject< RBThetaExpansion >, libMesh::ReferenceCountedObject< ShellMatrix< T > >, libMesh::ReferenceCountedObject< Solver >, libMesh::ReferenceCountedObject< SparseMatrix< T > >, libMesh::ReferenceCountedObject< SubdomainSelection >, libMesh::ReferenceCountedObject< System >, libMesh::ReferenceCountedObject< SystemSubset >, libMesh::ReferenceCountedObject< TimeSolver >, libMesh::ReferenceCountedObject< TreeBase >, and libMesh::ReferenceCountedObject< Value >.
Public Member Functions
~ReferenceCounter ()
Static Public Member Functions
static std::string get_info ()
static void print_info (std::ostream &out=libMesh::out)
static unsigned int n_objects ()
static void enable_print_counter_info ()
static void disable_print_counter_info ()
Protected Types
typedef std::map< std::string,
std::pair< unsigned int,
unsigned int > > Counts"
Protected Member Functions
ReferenceCounter ()
void increment_constructor_count (const std::string &name)
void increment_destructor_count (const std::string &name)
Static Protected Attributes
static Counts _counts
static Threads::atomic
< unsigned int > _n_objects"
static Threads::spin_mutex _mutex
static bool _enable_print_counter = true
Detailed Description
This is the base class for enabling reference counting. It should not be used by the user, thus it has a private constructor.
Author:
Benjamin S. Kirk, 2002-2007
Definition at line 47 of file reference_counter.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<unsigned int, unsigned int> > libMesh::ReferenceCounter::Counts [protected]
Data structure to log the information. The log is identified by the class name.
Definition at line 113 of file reference_counter.h.
Constructor & Destructor Documentation
libMesh::ReferenceCounter::ReferenceCounter () [inline], [protected]
Constructor. Protected so that you cannont instantiate a ReferenceCounter, only derive from it.
Definition at line 144 of file reference_counter.h.
References _n_objects.
{
  ++_n_objects;
}
libMesh::ReferenceCounter::~ReferenceCounter () [inline]
Destructor.
Definition at line 151 of file reference_counter.h.
References _n_objects.
{
  --_n_objects;
}
Member Function Documentation
void libMesh::ReferenceCounter::disable_print_counter_info () [static]
Definition at line 106 of file reference_counter.C.
References _enable_print_counter.
{
  _enable_print_counter = false;
  return;
}
void libMesh::ReferenceCounter::enable_print_counter_info () [static]
Methods to enable/disable the reference counter output from print_info()
Definition at line 100 of file reference_counter.C.
References _enable_print_counter.
{
  _enable_print_counter = true;
  return;
}
std::string libMesh::ReferenceCounter::get_info () [static]
Gets a string containing the reference information.
Definition at line 47 of file reference_counter.C.
References _counts, and libMesh::Quality::name().
Referenced by print_info().
{
#if defined(LIBMESH_ENABLE_REFERENCE_COUNTING) && defined(DEBUG)
  std::ostringstream oss;
  oss << '\n'
      << " ---------------------------------------------------------------------------- \n"
      << "| Reference count information |\n"
      << " ---------------------------------------------------------------------------- \n";
  for (Counts::iterator it = _counts.begin();
       it != _counts.end(); ++it)
    {
      const std::string name(it->first);
      const unsigned int creations = it->second.first;
      const unsigned int destructions = it->second.second;
      oss << "| " << name << " reference count information:\n"
          << "| Creations: " << creations << '\n'
          << "| Destructions: " << destructions << '\n';
    }
  oss << " ---------------------------------------------------------------------------- \n";
  return oss.str();
#else
  return "";
#endif
}
void libMesh::ReferenceCounter::increment_constructor_count (const std::string &name) [inline], [protected]
Increments the construction counter. Should be called in the constructor of any derived class that will be reference counted.
Definition at line 163 of file reference_counter.h.
References _counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.first++;
}
void libMesh::ReferenceCounter::increment_destructor_count (const std::string &name) [inline], [protected]
Increments the destruction counter. Should be called in the destructor of any derived class that will be reference counted.
Definition at line 176 of file reference_counter.h.
References _counts, libMesh::Quality::name(), and libMesh::Threads::spin_mtx.
Referenced by libMesh::ReferenceCountedObject< RBParametrized >::~ReferenceCountedObject().
{
  Threads::spin_mutex::scoped_lock lock(Threads::spin_mtx);
  std::pair<unsigned int, unsigned int>& p = _counts[name];
  p.second++;
}
static unsigned int libMesh::ReferenceCounter::n_objects () [inline], [static]
Prints the number of outstanding (created, but not yet destroyed) objects.
Definition at line 79 of file reference_counter.h.
References _n_objects.
  { return _n_objects; }
void libMesh::ReferenceCounter::print_info (std::ostream &out = libMesh::out) [static]
Prints the reference information, by default to libMesh::out.
Definition at line 88 of file reference_counter.C.
References _enable_print_counter, and get_info().
{
  if( _enable_print_counter ) out_stream << ReferenceCounter::get_info();
}
Member Data Documentation
ReferenceCounter::Counts libMesh::ReferenceCounter::_counts [static], [protected]
Actually holds the data.
Definition at line 118 of file reference_counter.h.
Referenced by get_info(), increment_constructor_count(), and increment_destructor_count().
bool libMesh::ReferenceCounter::_enable_print_counter = true [static], [protected]
Flag to control whether reference count information is printed when print_info is called.
Definition at line 137 of file reference_counter.h.
Referenced by disable_print_counter_info(), enable_print_counter_info(), and print_info().
Threads::spin_mutex libMesh::ReferenceCounter::_mutex [static], [protected]
Mutual exclusion object to enable thread-safe reference counting.
Definition at line 131 of file reference_counter.h.
Threads::atomic< unsigned int > libMesh::ReferenceCounter::_n_objects [static], [protected]
The number of objects. Print the reference count information when the number returns to 0.
Definition at line 126 of file reference_counter.h.
Referenced by n_objects(), ReferenceCounter(), and ~ReferenceCounter().
Author
Generated automatically by Doxygen for libMesh from the source code.