libmesh_isnan.c
NAME
libmesh_isnan.c -
SYNOPSIS
Functions
int libmesh_C_isnan_float (float a)
int libmesh_C_isnan_double (double a)
int libmesh_C_isnan_longdouble (long double a)
Function Documentation
int libmesh_C_isnan_double (doublea)
Definition at line 26 of file libmesh_isnan.c.
Referenced by libMesh::libmesh_isnan().
{ return isnan(a); }
int libmesh_C_isnan_float (floata)
Definition at line 25 of file libmesh_isnan.c.
Referenced by libMesh::libmesh_isnan().
{ return isnan(a); }
int libmesh_C_isnan_longdouble (long doublea)
Definition at line 27 of file libmesh_isnan.c.
Referenced by libMesh::libmesh_isnan().
{ return isnan(a); }
Author
Generated automatically by Doxygen for libMesh from the source code.