libMesh::Parallel::Status
NAME
libMesh::Parallel::Status -
SYNOPSIS
#include <parallel.h>
Public Member Functions
Status ()
Status (const data_type &type)
Status (const status &status)
Status (const status &status, const data_type &type)
Status (const Status &status)
Status (const Status &status, const data_type &type)
status * get ()
status const * get () const
int source () const
int tag () const
data_type & datatype ()
const data_type & datatype () const
unsigned int size (const data_type &type) const
unsigned int size () const
Private Attributes
status _status
data_type _datatype
Detailed Description
Encapsulates the MPI_Status struct. Allows the source and size of the message to be determined.
Definition at line 339 of file parallel.h.
Constructor & Destructor Documentation
libMesh::Parallel::Status::Status () [inline]
Definition at line 554 of file parallel_implementation.h.
                       :
  _status(),
  _datatype()
{}
libMesh::Parallel::Status::Status (const data_type &type) [inline], [explicit]
Definition at line 559 of file parallel_implementation.h.
                                            :
  _status(),
  _datatype(type)
{}
libMesh::Parallel::Status::Status (const status &status) [inline], [explicit]
Definition at line 564 of file parallel_implementation.h.
                                         :
  _status(stat),
  _datatype()
{}
libMesh::Parallel::Status::Status (const status &status, const data_type &type) [inline]
Definition at line 569 of file parallel_implementation.h.
                                              :
  _status(stat),
  _datatype(type)
{}
libMesh::Parallel::Status::Status (const Status &status) [inline]
Definition at line 575 of file parallel_implementation.h.
                                         :
  _status(stat._status),
  _datatype(stat._datatype)
{}
libMesh::Parallel::Status::Status (const Status &status, const data_type &type) [inline]
Definition at line 580 of file parallel_implementation.h.
                                              :
  _status(stat._status),
  _datatype(type)
{}
Member Function Documentation
data_type& libMesh::Parallel::Status::datatype () [inline]
Definition at line 364 of file parallel.h.
References _datatype.
Referenced by size().
{ return _datatype; }
const data_type& libMesh::Parallel::Status::datatype () const [inline]
Definition at line 366 of file parallel.h.
References _datatype.
{ return _datatype; }
status* libMesh::Parallel::Status::get () [inline]
Definition at line 356 of file parallel.h.
References _status.
Referenced by libMesh::Parallel::Communicator::receive(), and libMesh::Parallel::Request::wait().
{ return &_status; }
status const* libMesh::Parallel::Status::get () const [inline]
Definition at line 358 of file parallel.h.
References _status.
{ return &_status; }
unsigned int libMesh::Parallel::Status::size (const data_type &type) const [inline]
Definition at line 606 of file parallel_implementation.h.
References _status.
Referenced by libMesh::Parallel::Communicator::receive().
{
  int msg_size;
  MPI_Get_count (const_cast<MPI_Status*>(&_status), type, &msg_size);
  libmesh_assert_greater_equal (msg_size, 0);
  return msg_size;
}
unsigned int libMesh::Parallel::Status::size () const [inline]
Definition at line 621 of file parallel_implementation.h.
References datatype().
{ return this->size (this->datatype()); }
int libMesh::Parallel::Status::source () const [inline]
Definition at line 586 of file parallel_implementation.h.
References _status.
Referenced by libMesh::Nemesis_IO::read(), libMesh::System::read_serialized_blocked_dof_objects(), and libMesh::System::write_serialized_blocked_dof_objects().
{
#ifdef LIBMESH_HAVE_MPI
  return _status.MPI_SOURCE;
#else
  return 0;
#endif
}
int libMesh::Parallel::Status::tag () const [inline]
Definition at line 595 of file parallel_implementation.h.
References _status.
{
#ifdef LIBMESH_HAVE_MPI
  return _status.MPI_TAG;
#else
  libmesh_error();
  return 0;
#endif
}
Member Data Documentation
data_type libMesh::Parallel::Status::_datatype [private]
Definition at line 375 of file parallel.h.
Referenced by datatype().
status libMesh::Parallel::Status::_status [private]
Definition at line 374 of file parallel.h.
Referenced by get(), size(), source(), and tag().
Author
Generated automatically by Doxygen for libMesh from the source code.