libMesh::VariableGroup
NAME
libMesh::VariableGroup -
SYNOPSIS
#include <variable.h>
Inherits libMesh::Variable.
Public Member Functions
VariableGroup (System *sys, const std::vector< std::string > &var_names, const unsigned int var_number, const unsigned int first_scalar_num, const FEType &var_type)
VariableGroup (System *sys, const std::vector< std::string > &var_names, const unsigned int var_number, const unsigned int first_scalar_num, const FEType &var_type, const std::set< subdomain_id_type > &var_active_subdomains)
unsigned int n_variables () const
Variable variable (unsigned int v) const
Variable operator() (unsigned int v) const
const std::string & name (unsigned int v) const
unsigned int number (unsigned int v) const
unsigned int first_scalar_number (unsigned int v) const
void append (const std::string &var_name)
System * system () const
const std::string & name () const
unsigned int number () const
unsigned int first_scalar_number () const
const FEType & type () const
unsigned int n_components () const
bool active_on_subdomain (subdomain_id_type sid) const
bool implicitly_active () const
const std::set
< subdomain_id_type > & active_subdomains () const "
Protected Attributes
std::vector< std::string > _names
System * _sys
std::string _name
unsigned int _number
unsigned int _first_scalar_number
FEType _type
std::set< subdomain_id_type > _active_subdomains
Detailed Description
This class defines a logically grouped set of variables in the system. VariableGroup is appropriate for representing several unknowns in the problem that are all approximated with the same finite element approximation family and (optionally) a list of subdomains to which the variables are restricted.
Definition at line 165 of file variable.h.
Constructor & Destructor Documentation
libMesh::VariableGroup::VariableGroup (System *sys, const std::vector< std::string > &var_names, const unsigned intvar_number, const unsigned intfirst_scalar_num, const FEType &var_type) [inline]
Constructor. Omits the subdomain mapping, hence this constructor creates a variable which is active on all subdomains.
Definition at line 173 of file variable.h.
                                         :
    Variable (sys,
              "var_group",
              var_number,
              first_scalar_num,
              var_type),
    _names(var_names)
  {}
libMesh::VariableGroup::VariableGroup (System *sys, const std::vector< std::string > &var_names, const unsigned intvar_number, const unsigned intfirst_scalar_num, const FEType &var_type, const std::set< subdomain_id_type > &var_active_subdomains) [inline]
Constructor. Takes a set which contains the subdomain indices for which this variable is active.
Definition at line 191 of file variable.h.
                                                                         :
    Variable (sys,
              "var_group",
              var_number,
              first_scalar_num,
              var_type,
              var_active_subdomains),
    _names(var_names)
  {}
Member Function Documentation
bool libMesh::Variable::active_on_subdomain (subdomain_id_typesid) const [inline], [inherited]
returns true if this variable is active on subdomain sid, false otherwise. Note that we interperet the special case of an empty _active_subdomains container as active everywhere, i.e. for all subdomains.
Definition at line 129 of file variable.h.
References libMesh::Variable::_active_subdomains.
Referenced by libMesh::EquationSystems::build_solution_vector(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::EquationSystems::get_solution(), libMesh::ProjectSolution::operator()(), libMesh::ProjectFEMSolution::operator()(), libMesh::BoundaryProjectSolution::operator()(), and libMesh::DofMap::reinit().
  { return (_active_subdomains.empty() || _active_subdomains.count(sid)); }
const std::set<subdomain_id_type>& libMesh::Variable::active_subdomains () const [inline], [inherited]
Returns set of subdomain ids this variable lives on
Definition at line 143 of file variable.h.
References libMesh::Variable::_active_subdomains.
Referenced by variable(), and libMesh::System::write_header().
  { return _active_subdomains; }
void libMesh::VariableGroup::append (const std::string &var_name) [inline]
Appends a variable to the group. Really only can be used by System in a very limited window of opportunity - after the user specifies variables but before the system is initialized.
Definition at line 267 of file variable.h.
References _names.
  { _names.push_back (var_name); }
unsigned int libMesh::Variable::first_scalar_number () const [inline], [inherited]
The index of the first scalar component of this variable in the system.
Definition at line 108 of file variable.h.
References libMesh::Variable::_first_scalar_number.
Referenced by libMesh::System::n_components(), and variable().
  { return _first_scalar_number; }
unsigned int libMesh::VariableGroup::first_scalar_number (unsigned intv) const [inline]
The index of the first scalar component of this variable in the system.
Definition at line 256 of file variable.h.
References libMesh::Variable::_first_scalar_number, and n_variables().
  {
    libmesh_assert_less (v, this->n_variables());
    return _first_scalar_number+v;
  }
bool libMesh::Variable::implicitly_active () const [inline], [inherited]
returns true if this variable is active on all subdomains because it has no specified activity map. This can be used to perform more efficient computations in some places.
Definition at line 137 of file variable.h.
References libMesh::Variable::_active_subdomains.
  { return _active_subdomains.empty(); }
unsigned int libMesh::Variable::n_components () const [inline], [inherited]
The number of components of this variable.
Definition at line 120 of file variable.h.
References libMesh::Variable::_type, libMesh::FEType::family, libMesh::FEType::order, libMesh::SCALAR, and libMesh::Variable::type().
Referenced by libMesh::WrappedFunction< Output >::component(), libMesh::System::n_components(), and libMesh::WrappedFunction< Output >::operator()().
  { return type().family == SCALAR ? _type.order : 1; }
unsigned int libMesh::VariableGroup::n_variables () const [inline]
The number of variables in this VariableGroup
Definition at line 210 of file variable.h.
References _names.
Referenced by libMesh::DofMap::add_variable_group(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), first_scalar_number(), libMesh::System::get_info(), name(), number(), libMesh::DofMap::reinit(), and variable().
  { return libmesh_cast_int<unsigned int>(_names.size()); }
const std::string& libMesh::Variable::name () const [inline], [inherited]
Arbitrary, user-specified name of the variable.
Definition at line 95 of file variable.h.
References libMesh::Variable::_name.
Referenced by DMLibMeshSetSystem(), and variable().
  { return _name; }
const std::string& libMesh::VariableGroup::name (unsigned intv) const [inline]
Arbitrary, user-specified name of the variable.
Definition at line 237 of file variable.h.
References _names, and n_variables().
Referenced by libMesh::System::get_info().
  {
    libmesh_assert_less (v, this->n_variables());
    return _names[v];
  }
unsigned int libMesh::Variable::number () const [inline], [inherited]
The rank of this variable in the system.
Definition at line 101 of file variable.h.
References libMesh::Variable::_number.
Referenced by variable().
  { return _number; }
unsigned int libMesh::VariableGroup::number (unsigned intv) const [inline]
The rank of this variable in the system.
Definition at line 246 of file variable.h.
References libMesh::Variable::_number, and n_variables().
  {
    libmesh_assert_less (v, this->n_variables());
    return _number + v;
  }
Variable libMesh::VariableGroup::operator() (unsigned intv) const [inline]
Support vg(v) - returns a Variable for v.
Definition at line 231 of file variable.h.
References variable().
  { return this->variable(v); }
System* libMesh::Variable::system () const [inline], [inherited]
The System this Variable is part of.
Definition at line 87 of file variable.h.
References libMesh::Variable::_sys.
Referenced by variable().
  {
    return _sys;
  }
const FEType& libMesh::Variable::type () const [inline], [inherited]
The FEType for this variable.
Definition at line 114 of file variable.h.
References libMesh::Variable::_type.
Referenced by libMesh::WrappedFunction< Output >::component(), libMesh::DofMap::distribute_local_dofs_node_major(), libMesh::DofMap::distribute_local_dofs_var_major(), libMesh::System::get_info(), libMesh::Variable::n_components(), libMesh::WrappedFunction< Output >::operator()(), libMesh::ProjectSolution::operator()(), libMesh::ProjectFEMSolution::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::System::project_vector(), libMesh::System::read_parallel_data(), libMesh::System::read_SCALAR_dofs(), libMesh::System::read_serialized_vectors(), libMesh::DofMap::reinit(), libMesh::DofMap::SCALAR_dof_indices(), variable(), libMesh::System::write_parallel_data(), libMesh::System::write_serialized_vector(), and libMesh::System::write_serialized_vectors().
  { return _type; }
Variable libMesh::VariableGroup::variable (unsigned intv) const [inline]
Construct a Variable object for an individual member of our group.
Definition at line 217 of file variable.h.
References libMesh::Variable::active_subdomains(), libMesh::Variable::first_scalar_number(), n_variables(), libMesh::Variable::name(), libMesh::Variable::number(), libMesh::Variable::system(), libMesh::Variable::type(), and libMesh::Variable::Variable().
Referenced by operator()().
  {
    libmesh_assert_less (v, this->n_variables());
    return Variable (this->system(),
                     this->name(v),
                     this->number(v),
                     this->first_scalar_number(v),
                     this->type(),
                     this->active_subdomains());
  }
Member Data Documentation
std::set<subdomain_id_type> libMesh::Variable::_active_subdomains [protected], [inherited]
Definition at line 152 of file variable.h.
Referenced by libMesh::Variable::active_on_subdomain(), libMesh::Variable::active_subdomains(), and libMesh::Variable::implicitly_active().
unsigned int libMesh::Variable::_first_scalar_number [protected], [inherited]
Definition at line 150 of file variable.h.
Referenced by libMesh::Variable::first_scalar_number(), and first_scalar_number().
std::string libMesh::Variable::_name [protected], [inherited]
Definition at line 148 of file variable.h.
Referenced by libMesh::Variable::name().
std::vector<std::string> libMesh::VariableGroup::_names [protected]
Definition at line 271 of file variable.h.
Referenced by append(), n_variables(), and name().
unsigned int libMesh::Variable::_number [protected], [inherited]
Definition at line 149 of file variable.h.
Referenced by libMesh::Variable::number(), and number().
System* libMesh::Variable::_sys [protected], [inherited]
Definition at line 147 of file variable.h.
Referenced by libMesh::Variable::system().
FEType libMesh::Variable::_type [protected], [inherited]
Definition at line 151 of file variable.h.
Referenced by libMesh::Variable::n_components(), and libMesh::Variable::type().
Author
Generated automatically by Doxygen for libMesh from the source code.