.TH "mesh_modification.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mesh_modification.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibMesh::FunctionBase< Output >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.ti -1c
.RI "\fBlibMesh::MeshTools\fP"
.br
.ti -1c
.RI "\fBlibMesh::MeshTools::Modification\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::distort\fP (MeshBase &\fBmesh\fP, const Real factor, const bool perturb_boundary=false)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::redistribute\fP (MeshBase &\fBmesh\fP, const FunctionBase< Real > &mapfunc)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::translate\fP (MeshBase &\fBmesh\fP, const Real xt=0\&., const Real yt=0\&., const Real zt=0\&.)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::rotate\fP (MeshBase &\fBmesh\fP, const Real phi, const Real theta=0\&., const Real psi=0\&.)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::scale\fP (MeshBase &\fBmesh\fP, const Real xs, const Real ys=0\&., const Real zs=0\&.)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::all_tri\fP (MeshBase &\fBmesh\fP)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::smooth\fP (MeshBase &, unsigned int, Real)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::flatten\fP (MeshBase &\fBmesh\fP)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::change_boundary_id\fP (MeshBase &\fBmesh\fP, const boundary_id_type old_id, const boundary_id_type new_id)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Modification::change_subdomain_id\fP (MeshBase &\fBmesh\fP, const subdomain_id_type old_id, const subdomain_id_type new_id)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
