.TH "mesh_generation.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mesh_generation.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.ti -1c
.RI "\fBlibMesh::MeshTools\fP"
.br
.ti -1c
.RI "\fBlibMesh::MeshTools::Generation\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlibMesh::MeshTools::Generation::build_cube\fP (UnstructuredMesh &\fBmesh\fP, const unsigned int nx=0, const unsigned int ny=0, const unsigned int nz=0, const Real xmin=0\&., const Real xmax=1\&., const Real ymin=0\&., const Real ymax=1\&., const Real zmin=0\&., const Real zmax=1\&., const ElemType type=INVALID_ELEM, const bool gauss_lobatto_grid=false)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Generation::build_point\fP (UnstructuredMesh &\fBmesh\fP, const ElemType type=INVALID_ELEM, const bool gauss_lobatto_grid=false)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Generation::build_line\fP (UnstructuredMesh &\fBmesh\fP, const unsigned int nx, const Real xmin=0\&., const Real xmax=1\&., const ElemType type=INVALID_ELEM, const bool gauss_lobatto_grid=false)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Generation::build_square\fP (UnstructuredMesh &\fBmesh\fP, const unsigned int nx, const unsigned int ny, const Real xmin=0\&., const Real xmax=1\&., const Real ymin=0\&., const Real ymax=1\&., const ElemType type=INVALID_ELEM, const bool gauss_lobatto_grid=false)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Generation::build_sphere\fP (UnstructuredMesh &\fBmesh\fP, const Real rad=1, const unsigned int nr=2, const ElemType type=INVALID_ELEM, const unsigned int n_smooth=2, const bool flat=true)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Generation::build_extrusion\fP (UnstructuredMesh &\fBmesh\fP, const MeshBase &cross_section, const unsigned int nz, RealVectorValue extrusion_vector)"
.br
.ti -1c
.RI "void \fBlibMesh::MeshTools::Generation::build_delaunay_square\fP (UnstructuredMesh &\fBmesh\fP, const unsigned int nx, const unsigned int ny, const Real xmin, const Real xmax, const Real ymin, const Real ymax, const ElemType type, const std::vector< TriangleInterface::Hole * > *holes=NULL)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
