.TH "parallel.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parallel.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibMesh::Parallel::DataPlusInt< T >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::data_type\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::request\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::status\fP"
.br
.ti -1c
.RI "class \fBlibMesh::Parallel::MessageTag\fP"
.br
.ti -1c
.RI "class \fBlibMesh::Parallel::DataType\fP"
.br
.ti -1c
.RI "class \fBlibMesh::Parallel::StandardType< T >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::Attributes< T >\fP"
.br
.ti -1c
.RI "class \fBlibMesh::Parallel::Status\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::PostWaitWork\fP"
.br
.ti -1c
.RI "class \fBlibMesh::Parallel::Request\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::BufferType< T >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::BufferType< T * >\fP"
.br
.ti -1c
.RI "class \fBlibMesh::Parallel::Communicator\fP"
.br
.ti -1c
.RI "class \fBlibMesh::Parallel::FakeCommunicator\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::PostWaitCopyBuffer< Container, OutputIter >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::PostWaitUnpackBuffer< Container, Context, OutputIter >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::Parallel::PostWaitDeleteBuffer< Container >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.ti -1c
.RI "\fBlibMesh::Parallel\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef MPI_Datatype \fBlibMesh::Parallel::data_type\fP"
.br
.ti -1c
.RI "typedef MPI_Request \fBlibMesh::Parallel::request\fP"
.br
.ti -1c
.RI "typedef MPI_Status \fBlibMesh::Parallel::status\fP"
.br
.ti -1c
.RI "typedef MPI_Comm \fBlibMesh::Parallel::communicator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > data_type \fBlibMesh::Parallel::dataplusint_type\fP ()"
.br
.ti -1c
.RI "Status \fBlibMesh::Parallel::wait\fP (Request &r)"
.br
.ti -1c
.RI "void \fBlibMesh::Parallel::wait\fP (std::vector< Request > &r)"
.br
.ti -1c
.RI "template<typename T , typename buffertype , typename Context > void \fBlibMesh::Parallel::pack\fP (const T *object, typename std::vector< buffertype > &\fBdata\fP, const Context *context)"
.br
.ti -1c
.RI "template<typename T , typename Context > unsigned int \fBlibMesh::Parallel::packable_size\fP (const T *, const Context *)"
.br
.ti -1c
.RI "template<typename T , typename BufferIter > unsigned int \fBlibMesh::Parallel::packed_size\fP (const T *, BufferIter)"
.br
.ti -1c
.RI "template<typename T , typename BufferIter , typename Context > void \fBlibMesh::Parallel::unpack\fP (BufferIter in, T **out, Context *ctx)"
.br
.ti -1c
.RI "template<typename Context , typename buffertype , typename OutputIter > void \fBlibMesh::Parallel::unpack_range\fP (const typename std::vector< buffertype > &buffer, Context *context, OutputIter out)"
.br
.ti -1c
.RI "template<typename Context , typename buffertype , typename Iter > void \fBlibMesh::Parallel::pack_range\fP (const Context *context, Iter range_begin, const Iter range_end, typename std::vector< buffertype > &buffer)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBlibMesh::Parallel::any_source\fP"
.br
.ti -1c
.RI "const MessageTag \fBlibMesh::Parallel::any_tag\fP = MessageTag(MPI_ANY_TAG)"
.br
.ti -1c
.RI "const MessageTag \fBlibMesh::Parallel::no_tag\fP = MessageTag(0)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
