.TH "parallel_node.C" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parallel_node.C \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.ti -1c
.RI "\fBlibMesh::Parallel\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<> unsigned int \fBlibMesh::Parallel::packable_size\fP (const \fBNode\fP *node, const \fBMeshBase\fP *\fBmesh\fP)"
.br
.ti -1c
.RI "template<> unsigned int \fBlibMesh::Parallel::packed_size\fP (const \fBNode\fP *, const std::vector< \fBlargest_id_type\fP >::const_iterator in)"
.br
.ti -1c
.RI "template<> unsigned int \fBlibMesh::Parallel::packed_size\fP (const \fBNode\fP *n, const std::vector< \fBlargest_id_type\fP >::iterator in)"
.br
.ti -1c
.RI "template<> unsigned int \fBlibMesh::Parallel::packable_size\fP (const \fBNode\fP *node, const \fBParallelMesh\fP *\fBmesh\fP)"
.br
.ti -1c
.RI "template<> void \fBlibMesh::Parallel::pack\fP (const \fBNode\fP *node, std::vector< \fBlargest_id_type\fP > &\fBdata\fP, const \fBMeshBase\fP *\fBmesh\fP)"
.br
.ti -1c
.RI "template<> void \fBlibMesh::Parallel::pack\fP (const \fBNode\fP *node, std::vector< \fBlargest_id_type\fP > &\fBdata\fP, const \fBParallelMesh\fP *\fBmesh\fP)"
.br
.ti -1c
.RI "template<> void \fBlibMesh::Parallel::unpack\fP (std::vector< \fBlargest_id_type\fP >::const_iterator in, \fBNode\fP **out, \fBMeshBase\fP *\fBmesh\fP)"
.br
.ti -1c
.RI "template<> void \fBlibMesh::Parallel::unpack\fP (std::vector< \fBlargest_id_type\fP >::const_iterator in, \fBNode\fP **out, \fBParallelMesh\fP *\fBmesh\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
