.TH "petsc_macro.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
petsc_macro.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPetscCopyMode\fP { \fBPETSC_COPY_VALUES\fP, \fBPETSC_OWN_POINTER\fP, \fBPETSC_USE_POINTER\fP, \fBPETSC_COPY_VALUES\fP, \fBPETSC_OWN_POINTER\fP, \fBPETSC_USE_POINTER\fP }"
.br
.ti -1c
.RI "enum \fBPetscCopyMode\fP { \fBPETSC_COPY_VALUES\fP, \fBPETSC_OWN_POINTER\fP, \fBPETSC_USE_POINTER\fP, \fBPETSC_COPY_VALUES\fP, \fBPETSC_OWN_POINTER\fP, \fBPETSC_USE_POINTER\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "EXTERN_C_FOR_PETSC_BEGIN 
.br
EXTERN_C_FOR_PETSC_END typedef 
.br
PetscTruth \fBPetscBool\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPetscCopyMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPETSC_COPY_VALUES \fP\fP
.TP
\fB\fIPETSC_OWN_POINTER \fP\fP
.TP
\fB\fIPETSC_USE_POINTER \fP\fP
.TP
\fB\fIPETSC_COPY_VALUES \fP\fP
.TP
\fB\fIPETSC_OWN_POINTER \fP\fP
.TP
\fB\fIPETSC_USE_POINTER \fP\fP
.PP
Definition at line 122 of file petsc_macro\&.h\&.
.PP
.nf
122 { PETSC_COPY_VALUES, PETSC_OWN_POINTER, PETSC_USE_POINTER} PetscCopyMode;
.fi
.SS "enum \fBPetscCopyMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPETSC_COPY_VALUES \fP\fP
.TP
\fB\fIPETSC_OWN_POINTER \fP\fP
.TP
\fB\fIPETSC_USE_POINTER \fP\fP
.TP
\fB\fIPETSC_COPY_VALUES \fP\fP
.TP
\fB\fIPETSC_OWN_POINTER \fP\fP
.TP
\fB\fIPETSC_USE_POINTER \fP\fP
.PP
Definition at line 128 of file petsc_macro\&.h\&.
.PP
.nf
128 { PETSC_COPY_VALUES, PETSC_OWN_POINTER, PETSC_USE_POINTER} PetscCopyMode;
.fi
.SH "Variable Documentation"
.PP 
.SS "EXTERN_C_FOR_PETSC_BEGIN EXTERN_C_FOR_PETSC_END typedef PetscTruth PetscBool"

.PP
Definition at line 97 of file petsc_macro\&.h\&.
.PP
Referenced by libMesh::PetscMatrix< T >::closed(), DMCreateGlobalVector_libMesh(), DMLibMeshCreateDomainDecompositionDM(), DMLibMeshCreateFieldDecompositionDM(), DMLibMeshGetBlocks(), DMLibMeshGetSystem(), DMLibMeshGetVariables(), DMLibMeshParseDecompositionDescriptor_Private(), DMLibMeshSetSystem(), DMSetUp_libMesh(), DMView_libMesh(), and libMesh::if()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
