.TH "petsc_preconditioner.C" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
petsc_preconditioner.C \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlibMesh::PetscObjectGetComm\fP ((PetscObject) \fBpc\fP,&comm)"
.br
.ti -1c
.RI "\fBlibMesh::CHKERRABORT\fP (comm, \fBierr\fP)"
.br
.ti -1c
.RI "\fBlibMesh::for\fP (unsigned int var=0;var< \fBn_vars\fP;var++)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "template<typename T > void PetscPreconditioner< T >
.br
::set_petsc_subpreconditioner_type(PCType 
.br
type, PC &\fBpc\fP) void 
.br
PetscPreconditioner< T >
.br
 Parallel::communicator \fBlibMesh::comm\fP"
.br
.ti -1c
.RI "Parallel::Communicator \fBlibMesh::communicator\fP (comm)"
.br
.ti -1c
.RI "\fBlibMesh::ierr\fP = PCSetUp(\fBpc\fP)"
.br
.ti -1c
.RI "KSP * \fBlibMesh::subksps\fP"
.br
.ti -1c
.RI "\fBPetscInt\fP \fBlibMesh::n_local\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
