petsc_linear_solver.h
NAME
petsc_linear_solver.h -
SYNOPSIS
Classes
class libMesh::PetscMatrix< T >
class libMesh::PetscLinearSolver< T >
Namespaces
libMesh
Typedefs
typedef int PetscInt
Functions
PetscErrorCode __libmesh_petsc_preconditioner_setup (void *ctx)
PetscErrorCode __libmesh_petsc_preconditioner_apply (void *ctx, Vec x, Vec y)
PetscErrorCode __libmesh_petsc_preconditioner_setup (PC)
PetscErrorCode __libmesh_petsc_preconditioner_apply (PC, Vec x, Vec y)
Variables
EXTERN_C_FOR_PETSC_BEGIN
EXTERN_C_FOR_PETSC_END typedef
int PetscErrorCode"
Typedef Documentation
typedef int PetscInt
Definition at line 61 of file petsc_linear_solver.h.
Function Documentation
PetscErrorCode __libmesh_petsc_preconditioner_apply (void *ctx, Vecx, Vecy)
This function is called by PETSc to acctually apply the preconditioner. ctx will hold the Preconditioner.
Definition at line 66 of file petsc_linear_solver.C.
Referenced by libMesh::PetscNonlinearSolver< T >::init(), and libMesh::PetscLinearSolver< T >::init().
  {
    Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number>*>(ctx);
    PetscVector<Number> x_vec(x, preconditioner->comm());
    PetscVector<Number> y_vec(y, preconditioner->comm());
    preconditioner->apply(x_vec,y_vec);
    return 0;
  }
PetscErrorCode __libmesh_petsc_preconditioner_apply (PC, Vecx, Vecy)
Definition at line 95 of file petsc_linear_solver.C.
References CHKERRQ(), and libMesh::ierr.
  {
    void *ctx;
    PetscErrorCode ierr = PCShellGetContext(pc,&ctx);CHKERRQ(ierr);
    Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number>*>(ctx);
    PetscVector<Number> x_vec(x, preconditioner->comm());
    PetscVector<Number> y_vec(y, preconditioner->comm());
    preconditioner->apply(x_vec,y_vec);
    return 0;
  }
PetscErrorCode __libmesh_petsc_preconditioner_setup (void *ctx)
This function is called by PETSc to initialize the preconditioner. ctx will hold the Preconditioner.
Definition at line 50 of file petsc_linear_solver.C.
References libMesh::err.
Referenced by libMesh::PetscNonlinearSolver< T >::init(), and libMesh::PetscLinearSolver< T >::init().
  {
    Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number>*>(ctx);
    if(!preconditioner->initialized())
      {
        err<<"Preconditioner not initialized! Make sure you call init() before solve!"<<std::endl;
        libmesh_error();
      }
    preconditioner->setup();
    return 0;
  }
PetscErrorCode __libmesh_petsc_preconditioner_setup (PC)
Definition at line 78 of file petsc_linear_solver.C.
References CHKERRQ(), libMesh::err, and libMesh::ierr.
  {
    void *ctx;
    PetscErrorCode ierr = PCShellGetContext(pc,&ctx);CHKERRQ(ierr);
    Preconditioner<Number> * preconditioner = static_cast<Preconditioner<Number>*>(ctx);
    if(!preconditioner->initialized())
      {
        err<<"Preconditioner not initialized! Make sure you call init() before solve!"<<std::endl;
        libmesh_error();
      }
    preconditioner->setup();
    return 0;
  }
Variable Documentation
EXTERN_C_FOR_PETSC_BEGIN EXTERN_C_FOR_PETSC_END typedef int PetscErrorCode
Petsc include files.
Definition at line 60 of file petsc_linear_solver.h.
Author
Generated automatically by Doxygen for libMesh from the source code.