.TH "petsc_nonlinear_solver.C" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
petsc_nonlinear_solver.C \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPetscErrorCode\fP \fBlibMesh::__libmesh_petsc_snes_monitor\fP (SNES, \fBPetscInt\fP its, PetscReal fnorm, void *)"
.br
.ti -1c
.RI "\fBPetscErrorCode\fP \fBlibMesh::__libmesh_petsc_snes_residual\fP (SNES snes, Vec \fBx\fP, Vec r, void *ctx)"
.br
.ti -1c
.RI "\fBPetscErrorCode\fP \fBlibMesh::__libmesh_petsc_snes_jacobian\fP (SNES snes, Vec \fBx\fP, Mat *\fBjac\fP, Mat *\fBpc\fP, MatStructure *msflag, void *ctx) \fBPetscErrorCode\fP __libmesh_petsc_snes_jacobian(SNES snes"
.br
.ti -1c
.RI "\fBPetscErrorCode\fP Vec Mat Mat 
.br
void *ctx \fBlibMesh::START_LOG\fP ('jacobian()','PetscNonlinearSolver')"
.br
.ti -1c
.RI "\fBlibMesh::libmesh_assert\fP (ctx)"
.br
.ti -1c
.RI "\fBlibMesh::CHKERRABORT\fP (solver->comm()\&.get(), \fBierr\fP)"
.br
.ti -1c
.RI "PetscMatrix< Number > J_input * \fBlibMesh::pc\fP ()"
.br
.ti -1c
.RI "PetscMatrix< Number > \fBJac\fP * \fBlibMesh::jac\fP ()"
.br
.ti -1c
.RI "PetscMatrix< Number > \fBlibMesh::PC\fP (\fBpc\fP, sys\&.comm())"
.br
.ti -1c
.RI "PetscMatrix< Number > \fBlibMesh::Jac\fP (\fBjac\fP, sys\&.comm())"
.br
.ti -1c
.RI "PetscVector< Number > \fBlibMesh::X_global\fP (\fBx\fP, sys\&.comm())"
.br
.ti -1c
.RI "PC \fBlibMesh::attach_dof_map\fP (\fBsys\&.get_dof_map\fP())"
.br
.ti -1c
.RI "\fBX_global\fP \fBlibMesh::swap\fP (\fBX_sys\fP)"
.br
.ti -1c
.RI "\fBJac\fP \fBlibMesh::swap\fP (\fBJac_sys\fP)"
.br
.ti -1c
.RI "\fBsys\fP \fBlibMesh::get_dof_map\fP ()"
.br
.ti -1c
.RI "\fBlibMesh::if\fP (solver->matvec &&solver->residual_and_jacobian_object)"
.br
.ti -1c
.RI "\fBlibMesh::if\fP (solver->jacobian!=NULL)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPetscErrorCode\fP Vec Mat \fBlibMesh::jac\fP"
.br
.ti -1c
.RI "solver \fBlibMesh::_current_nonlinear_iteration_number\fP = static_cast<unsigned>(n_iterations)"
.br
.ti -1c
.RI "PetscVector< Number > & \fBlibMesh::X_sys\fP = *libmesh_cast_ptr<PetscVector<Number>*>(sys\&.solution\&.get())"
.br
.ti -1c
.RI "PetscMatrix< Number > & \fBlibMesh::Jac_sys\fP = *libmesh_cast_ptr<PetscMatrix<Number>*>(sys\&.matrix)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
