petsc_dm_nonlinear_solver.C
NAME
petsc_dm_nonlinear_solver.C -
SYNOPSIS
Namespaces
libMesh
Typedefs
typedef int PetscErrorCode
typedef int PetscInt
Functions
EXTERN_C_BEGIN PetscErrorCode DMCreate_libMesh (DM)
void libMesh::PetscDMRegister ()
Variables
PetscBool libMesh::PetscDMRegistered = PETSC_FALSE
Typedef Documentation
typedef int PetscErrorCode
Definition at line 37 of file petsc_dm_nonlinear_solver.C.
typedef int PetscInt
Definition at line 38 of file petsc_dm_nonlinear_solver.C.
Function Documentation
EXTERN_C_BEGIN PetscErrorCode DMCreate_libMesh (DM)
Definition at line 1124 of file petscdmlibmesh.C.
References DM_libMesh::blockids, DM_libMesh::blocknames, CHKERRQ(), DM_libMesh::decomposition, DM_libMesh::decomposition_type, dlm, DMCreateDomainDecomposition_libMesh(), DMCreateDomainDecompositionDM_libMesh(), DMCreateFieldDecomposition_libMesh(), DMCreateFieldDecompositionDM_libMesh(), DMCreateGlobalVector_libMesh(), DMCreateMatrix_libMesh(), DMDestroy_libMesh(), DMSetUp_libMesh(), DMView_libMesh(), libMesh::ierr, PetscFunctionBegin, PetscFunctionReturn(), DM_libMesh::varids, and DM_libMesh::varnames.
Referenced by libMesh::PetscDMRegister().
{
  PetscErrorCode ierr;
  DM_libMesh *dlm;
  PetscFunctionBegin;
  PetscValidHeaderSpecific(dm,DM_CLASSID,1);
#if PETSC_RELEASE_LESS_THAN(3,5,0)
  ierr = PetscNewLog(dm,DM_libMesh,&dlm);CHKERRQ(ierr);
#else
  ierr = PetscNewLog(dm,&dlm);CHKERRQ(ierr);
#endif
  dm->data = dlm;
  dlm->varids = new(std::map<std::string, unsigned int>);
  dlm->blockids = new(std::map<std::string, unsigned int>);
  dlm->varnames = new(std::map<unsigned int, std::string>);
  dlm->blocknames = new(std::map<unsigned int, std::string>);
  dlm->decomposition = PETSC_NULL;
  dlm->decomposition_type = DMLIBMESH_NO_DECOMPOSITION;
  dm->ops->createglobalvector = DMCreateGlobalVector_libMesh;
  dm->ops->createlocalvector = 0; // DMCreateLocalVector_libMesh;
  dm->ops->getcoloring = 0; // DMGetColoring_libMesh;
  dm->ops->creatematrix = DMCreateMatrix_libMesh;
  dm->ops->createinterpolation= 0; // DMCreateInterpolation_libMesh;
  dm->ops->refine = 0; // DMRefine_libMesh;
  dm->ops->coarsen = 0; // DMCoarsen_libMesh;
  dm->ops->getinjection = 0; // DMGetInjection_libMesh;
  dm->ops->getaggregates = 0; // DMGetAggregates_libMesh;
#if PETSC_RELEASE_LESS_THAN(3,3,1)
  dm->ops->createfielddecompositiondm = DMCreateFieldDecompositionDM_libMesh;
  dm->ops->createdomaindecompositiondm = DMCreateDomainDecompositionDM_libMesh;
#endif
  dm->ops->createfielddecomposition = DMCreateFieldDecomposition_libMesh;
  dm->ops->createdomaindecomposition = DMCreateDomainDecomposition_libMesh;
  dm->ops->destroy = DMDestroy_libMesh;
  dm->ops->view = DMView_libMesh;
  dm->ops->setfromoptions = 0; // DMSetFromOptions_libMesh;
  dm->ops->setup = DMSetUp_libMesh;
  PetscFunctionReturn(0);
}
Author
Generated automatically by Doxygen for libMesh from the source code.