std
NAME
std -
SYNOPSIS
Functions
long double max (long double a, double b)
long double min (long double a, double b)
long double max (double a, long double b)
long double min (double a, long double b)
double max (double a, float b)
double min (double a, float b)
double max (float a, double b)
double min (float a, double b)
long double max (long double a, float b)
long double min (long double a, float b)
long double max (float a, long double b)
long double min (float a, long double b)
double abs (double a)
double pow (double a, int b)
Function Documentation
double std::abs (doublea) [inline]
Definition at line 59 of file libmesh_augment_std_namespace.h.
Referenced by GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::DenseMatrix< T >::_lu_decompose(), libMesh::DistributedVector< T >::abs(), libMesh::LaspackVector< T >::abs(), libMesh::EigenSparseVector< T >::abs(), libMesh::TypeVector< T >::absolute_fuzzy_equals(), libMesh::InfElemBuilder::build_inf_elem(), libMesh::System::calculate_norm(), libMesh::FEGenericBase< T >::coarsened_dof_values(), libMesh::NumericVector< T >::compare(), libMesh::FEAbstract::compute_node_constraints(), libMesh::FEGenericBase< T >::compute_periodic_constraints(), libMesh::FEGenericBase< T >::compute_proj_constraints(), libMesh::ContinuationSystem::continuation_solve(), libMesh::MemorySolutionHistory::find_stored_entry(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::PointLocatorTree::init(), libMesh::InfFE< friend_Dim, friend_T_radial, friend_T_map >::inverse_map(), libMesh::Tet::is_child_on_side_helper(), libMesh::LocationMap< T >::key(), libMesh::DenseVector< T >::l1_norm(), libMesh::DistributedVector< T >::l1_norm(), libMesh::DenseMatrix< T >::l1_norm(), libMesh::NewtonSolver::line_search(), libMesh::DistributedVector< T >::linfty_norm(), libMesh::DenseMatrix< T >::linfty_norm(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::DofMap::max_constraint_error(), libMesh::VariationalMeshSmoother::minJ(), libMesh::VariationalMeshSmoother::minJ_BC(), libMesh::Plane::on_surface(), libMesh::Sphere::on_surface(), LIBMESH_DEFINE_HASH_POINTERS::FuzzyPointCompare::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::ProjectSolution::operator()(), libMesh::ProjectFEMSolution::operator()(), libMesh::BoundaryProjectSolution::operator()(), libMesh::TypeTensor< T >::operator==(), libMesh::EpetraVector< T >::reciprocal(), libMesh::TypeVector< T >::relative_fuzzy_equals(), libMesh::MemorySolutionHistory::retrieve(), libMesh::ContinuationSystem::set_Theta_LOCA(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::SIGN(), libMesh::Sphere::Sphere(), libMesh::MemorySolutionHistory::store(), libMesh::NumericVector< T >::subset_l1_norm(), libMesh::NumericVector< T >::subset_linfty_norm(), libMesh::ContinuationSystem::update_solution(), libMesh::TecplotIO::write_ascii(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), libMesh::GMVIO::write_binary(), libMesh::GMVIO::write_discontinuous_gmv(), libMesh::ExodusII_IO::write_element_data(), libMesh::Nemesis_IO::write_global_data(), libMesh::ExodusII_IO::write_global_data(), libMesh::ExodusII_IO::write_nodal_data(), libMesh::ExodusII_IO::write_nodal_data_discontinuous(), and libMesh::Nemesis_IO_Helper::write_nodal_solution().
{ return ::fabs(a); }
long double std::max (long doublea, doubleb) [inline]
Definition at line 27 of file libmesh_augment_std_namespace.h.
Referenced by GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::MetisPartitioner::_do_partition(), libMesh::ParallelMesh::add_elem(), libMesh::QoISet::add_indices(), libMesh::ParallelMesh::add_node(), libMesh::TreeNode< N >::bounds_point(), libMesh::System::calculate_norm(), libMesh::NumericVector< T >::compare(), libMesh::TreeNode< N >::create_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::FEType::default_quadrature_rule(), libMesh::MeshTools::Modification::distort(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_mean_stddev(), libMesh::DofMap::get_info(), libMesh::NumericVector< T >::global_relative_compare(), libMesh::QGrundmann_Moller::gm_rule(), libMesh::StatisticsVector< T >::histogram(), libMesh::Elem::hmax(), libMesh::Elem::hmin(), libMesh::LocationMap< T >::init(), libMesh::FESubdivision::init_shape_functions(), libMesh::MeshTools::BoundingBox::invalidate(), libMesh::is_between(), libMesh::ParallelMesh::libmesh_assert_valid_parallel_object_ids(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::MeshRefinement::limit_level_mismatch_at_edge(), libMesh::MeshRefinement::limit_level_mismatch_at_node(), libMesh::NewtonSolver::line_search(), libMesh::DistributedVector< T >::linfty_norm(), libMesh::NumericVector< T >::local_relative_compare(), libMesh::MeshRefinement::make_coarsening_compatible(), libMesh::DistributedVector< T >::max(), libMesh::LaspackVector< T >::max(), libMesh::EigenSparseVector< T >::max(), libMesh::DofMap::max_constraint_error(), libMesh::Elem::max_descendant_p_level(), libMesh::StatisticsVector< T >::maximum(), libMesh::DistributedVector< T >::min(), libMesh::LaspackVector< T >::min(), libMesh::EigenSparseVector< T >::min(), libMesh::Tri3::min_and_max_angle(), libMesh::ErrorVector::minimum(), libMesh::MeshTools::n_active_levels(), libMesh::CheckpointIO::n_active_levels_on_processor(), libMesh::MeshTools::n_active_local_levels(), libMesh::MeshTools::n_levels(), libMesh::MeshTools::n_local_levels(), libMesh::MeshTools::n_p_levels(), libMesh::StatisticsVector< T >::normalize(), LIBMESH_DEFINE_HASH_POINTERS::FuzzyPointCompare::operator()(), libMesh::WeightedPatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::PatchRecoveryErrorEstimator::EstimateError::operator()(), libMesh::Parallel::pack(), libMesh::StatisticsVector< T >::plot_histogram(), libMesh::Hex::quality(), libMesh::InfHex::quality(), libMesh::GmshIO::read_mesh(), libMesh::MeshBase::recalculate_n_partitions(), libMesh::DofMap::reinit(), libMesh::REINIT_ERROR(), libMesh::HPCoarsenTest::select_refinement(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::FE< Dim, T >::side_map(), libMesh::TwostepTimeSolver::solve(), libMesh::NewtonSolver::solve(), libMesh::SerialMesh::stitching_helper(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::GMVIO::write_ascii_new_impl(), libMesh::GMVIO::write_ascii_old_impl(), libMesh::TecplotIO::write_binary(), and libMesh::GMVIO::write_binary().
{ return (a>b?a:b); }
long double std::max (doublea, long doubleb) [inline]
Definition at line 32 of file libmesh_augment_std_namespace.h.
{ return (a>b?a:b); }
double std::max (doublea, floatb) [inline]
Definition at line 37 of file libmesh_augment_std_namespace.h.
{ return (a>b?a:b); }
double std::max (floata, doubleb) [inline]
Definition at line 42 of file libmesh_augment_std_namespace.h.
{ return (a>b?a:b); }
long double std::max (long doublea, floatb) [inline]
Definition at line 47 of file libmesh_augment_std_namespace.h.
{ return (a>b?a:b); }
long double std::max (floata, long doubleb) [inline]
Definition at line 52 of file libmesh_augment_std_namespace.h.
{ return (a>b?a:b); }
long double std::min (long doublea, doubleb) [inline]
Definition at line 29 of file libmesh_augment_std_namespace.h.
Referenced by GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::CentroidPartitioner::_do_partition(), libMesh::DenseMatrix< T >::_lu_decompose_lapack(), libMesh::VariationalMeshSmoother::adapt_minimum(), libMesh::VariationalMeshSmoother::adjust_adapt_data(), libMesh::TreeNode< N >::bounds_point(), libMesh::FEGenericBase< T >::compute_periodic_constraints(), libMesh::FEGenericBase< T >::compute_proj_constraints(), libMesh::InfQuad4::contains_point(), libMesh::InfPrism6::contains_point(), libMesh::InfHex8::contains_point(), libMesh::ContinuationSystem::continuation_solve(), libMesh::ExodusII_IO_Helper::create(), libMesh::Nemesis_IO_Helper::create(), libMesh::TreeNode< N >::create_bounding_box(), libMesh::MeshRefinement::create_parent_error_vector(), libMesh::Xdr::data_stream(), libMesh::MeshTools::Modification::distort(), libMesh::MeshRefinement::flag_elements_by_error_fraction(), libMesh::MeshRefinement::flag_elements_by_nelem_target(), libMesh::Nemesis_IO_Helper::get_elem_map(), libMesh::StatisticsVector< T >::histogram(), libMesh::Elem::hmin(), libMesh::LocationMap< T >::init(), libMesh::FESubdivision::init_shape_functions(), libMesh::ParmetisPartitioner::initialize(), libMesh::SparsityPattern::Build::join(), libMesh::MeshTools::libmesh_assert_valid_procids< Elem >(), libMesh::MeshTools::libmesh_assert_valid_procids< Node >(), libMesh::NewtonSolver::line_search(), libMesh::DistributedVector< T >::min(), libMesh::LaspackVector< T >::min(), libMesh::EigenSparseVector< T >::min(), libMesh::Tri3::min_and_max_angle(), libMesh::Elem::min_new_p_level_by_neighbor(), libMesh::Elem::min_p_level_by_neighbor(), libMesh::ErrorVector::minimum(), libMesh::StatisticsVector< T >::minimum(), libMesh::Threads::num_pthreads(), libMesh::SparsityPattern::Build::parallel_sync(), libMesh::Partitioner::partition(), libMesh::StatisticsVector< T >::plot_histogram(), libMesh::Hex::quality(), libMesh::InfHex::quality(), libMesh::Nemesis_IO::read(), libMesh::ExodusII_IO_Helper::read_elem_num_map(), libMesh::GmshIO::read_mesh(), libMesh::ExodusII_IO_Helper::read_node_num_map(), libMesh::XdrIO::read_serialized_bcs(), libMesh::System::read_serialized_blocked_dof_objects(), libMesh::XdrIO::read_serialized_connectivity(), libMesh::XdrIO::read_serialized_nodes(), libMesh::XdrIO::read_serialized_nodesets(), libMesh::EpetraVector< T >::reciprocal(), libMesh::Partitioner::repartition(), libMesh::Partitioner::set_node_processor_ids(), libMesh::Elem::set_p_level(), libMesh::Partitioner::set_parent_processor_ids(), libMesh::FE< Dim, T >::shape(), libMesh::NewtonSolver::solve(), libMesh::SerialMesh::stitching_helper(), libMesh::MeshTools::subdomain_bounding_box(), libMesh::EpetraMatrix< T >::update_sparsity_pattern(), libMesh::System::write_serialized_blocked_dof_objects(), and libMesh::XdrIO::write_serialized_nodes().
{ return (a<b?a:b); }
long double std::min (doublea, long doubleb) [inline]
Definition at line 34 of file libmesh_augment_std_namespace.h.
{ return (a<b?a:b); }
double std::min (doublea, floatb) [inline]
Definition at line 39 of file libmesh_augment_std_namespace.h.
{ return (a<b?a:b); }
double std::min (floata, doubleb) [inline]
Definition at line 44 of file libmesh_augment_std_namespace.h.
{ return (a<b?a:b); }
long double std::min (long doublea, floatb) [inline]
Definition at line 49 of file libmesh_augment_std_namespace.h.
{ return (a<b?a:b); }
long double std::min (floata, long doubleb) [inline]
Definition at line 54 of file libmesh_augment_std_namespace.h.
{ return (a<b?a:b); }
double std::pow (doublea, intb) [inline]
Definition at line 66 of file libmesh_augment_std_namespace.h.
Referenced by GETPOT_NAMESPACE::GetPot::_DBE_expand(), libMesh::ContinuationSystem::continuation_solve(), libMesh::FESubdivision::init_shape_functions(), libMesh::VariationalMeshSmoother::maxE(), libMesh::VariationalMeshSmoother::metr_data_gen(), libMesh::VariationalMeshSmoother::minJ(), libMesh::VariationalMeshSmoother::minJ_BC(), libMesh::FE< Dim, T >::shape(), libMesh::FE< Dim, T >::shape_deriv(), libMesh::FE< Dim, T >::shape_second_deriv(), libMesh::MeshTools::Modification::smooth(), libMesh::TwostepTimeSolver::solve(), and libMesh::VariationalMeshSmoother::vertex().
{ return std::pow(a, static_cast<double>(b)); }
Author
Generated automatically by Doxygen for libMesh from the source code.