.TH "tensor_tools.h" 3 "Tue May 6 2014" "libMesh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tensor_tools.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibMesh::TypeVector< T >\fP"
.br
.ti -1c
.RI "class \fBlibMesh::VectorValue< T >\fP"
.br
.ti -1c
.RI "class \fBlibMesh::TypeTensor< T >\fP"
.br
.ti -1c
.RI "class \fBlibMesh::TensorValue< T >\fP"
.br
.ti -1c
.RI "class \fBlibMesh::TypeNTensor< N, T >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::IncrementRank< T >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::IncrementRank< VectorValue< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::IncrementRank< TypeVector< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::IncrementRank< TypeTensor< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::IncrementRank< TensorValue< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::IncrementRank< TypeNTensor< N, T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::DecrementRank< T >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::DecrementRank< VectorValue< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::DecrementRank< TypeVector< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::DecrementRank< TensorValue< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::DecrementRank< TypeTensor< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::DecrementRank< TypeNTensor< N, T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeNumber< T >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeNumber< std::complex< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeNumber< TypeVector< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeNumber< VectorValue< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeNumber< TypeTensor< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeNumber< TensorValue< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeNumber< TypeNTensor< N, T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeReal< T >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeReal< std::complex< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeReal< TypeVector< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeReal< VectorValue< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeReal< TypeTensor< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeReal< TensorValue< T > >\fP"
.br
.ti -1c
.RI "struct \fBlibMesh::TensorTools::MakeReal< TypeNTensor< N, T > >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBlibMesh\fP"
.br
.ti -1c
.RI "\fBlibMesh::TensorTools\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , typename T2 > boostcopy::enable_if_c
.br
< ScalarTraits< T >::value 
.br
&&ScalarTraits< T2 >::value, 
.br
typename CompareTypes< T, T2 >
.br
::supertype >::type \fBlibMesh::TensorTools::inner_product\fP (const T &a, const T2 &b)"
.br
.ti -1c
.RI "template<typename T , typename T2 > CompareTypes< T, T2 >::supertype \fBlibMesh::TensorTools::inner_product\fP (const TypeVector< T > &a, const TypeVector< T2 > &b)"
.br
.ti -1c
.RI "template<typename T , typename T2 > CompareTypes< T, T2 >::supertype \fBlibMesh::TensorTools::inner_product\fP (const TypeTensor< T > &a, const TypeTensor< T2 > &b)"
.br
.ti -1c
.RI "template<unsigned int N, typename T , typename T2 > CompareTypes< T, T2 >::supertype \fBlibMesh::TensorTools::inner_product\fP (const TypeNTensor< N, T > &a, const TypeNTensor< N, T2 > &b)"
.br
.ti -1c
.RI "template<typename T > T \fBlibMesh::TensorTools::norm_sq\fP (T a)"
.br
.ti -1c
.RI "template<typename T > T \fBlibMesh::TensorTools::norm_sq\fP (std::complex< T > a)"
.br
.ti -1c
.RI "template<typename T > Real \fBlibMesh::TensorTools::norm_sq\fP (const TypeVector< T > &a)"
.br
.ti -1c
.RI "template<typename T > Real \fBlibMesh::TensorTools::norm_sq\fP (const VectorValue< T > &a)"
.br
.ti -1c
.RI "Number \fBlibMesh::TensorTools::curl_from_grad\fP (const VectorValue< Number > &)"
.br
.ti -1c
.RI "VectorValue< Number > \fBlibMesh::TensorTools::curl_from_grad\fP (const TensorValue< Number > &grad)"
.br
.RI "\fIComputes the curl of a vector given the gradient of that vector\&. \fP"
.ti -1c
.RI "TensorValue< Number > \fBlibMesh::TensorTools::curl_from_grad\fP (const TypeNTensor< 3, Number > &)"
.br
.ti -1c
.RI "Number \fBlibMesh::TensorTools::div_from_grad\fP (const VectorValue< Number > &grad)"
.br
.RI "\fIDummy\&. Divgerence of a scalar not defined, but is needed for \fBExactSolution\fP to compile\&. \fP"
.ti -1c
.RI "Number \fBlibMesh::TensorTools::div_from_grad\fP (const TensorValue< Number > &grad)"
.br
.RI "\fIComputes the divergence of a vector given the gradient of that vector\&. \fP"
.ti -1c
.RI "VectorValue< Number > \fBlibMesh::TensorTools::div_from_grad\fP (const TypeNTensor< 3, Number > &)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libMesh from the source code\&.
